### PR TITLE
Fix SPI TFT for STM32F1/F4

### LINKED ISSUE #26504: [BUG] B1 se plus  bugfix-2.1.x have white screen.
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I downloaded bugfix2.1.x from the website, applied it to the latest configuration file for B1 se plus, 
installed it on an SD card, but when I boot up, I get a white screen. 

I tried connecting with Pronterface to the computer, and that works fine. 
M503 can read, and M115 displays the firmware version, indicating a successful firmware installation. 
However, the white screen issue leaves me unsure of what to do :(

### Bug Timeline

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to Reproduce

1.Download bugfix2.1.x from Marlin Github and open it.
2.Download B1 se plus .h and adv.h from the Marlin Github configuration files.
3.Overwrite the bugfix2.1.x with B1 se plus .h and adv.h, then build.
4.Place firmware.bin on the SD card, boot up, and encounter a white screen.

### Version of Marlin Firmware

bugfix2.1.x 

### Printer model

B1 se plus

### Electronics

_No response_

### LCD/Controller

BTT TFT35 SPI V1.1

### Other add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

the file same from here Marlin Configuration
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/13593348/Configuration.zip)

my LCD
BTT TFT35 SPI V1.1
IMAG1134

### LINKED ISSUE #26530: [BUG] SKR2 with TFT BTT_TFT35_SPI_V1_0 create white screen
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

SKR2 with TFT BTT_TFT35_SPI_V1_0 create white screen

### Bug Timeline

new. With 2.1.2.1 it was not in. when i try later Marlin-bugfix-2.1.x i found it

### Expected behavior

screen working

### Actual behavior

white screen

### Steps to Reproduce

just install the compiled firmware

### Version of Marlin Firmware

[Marlin-bugfix-2.1.x](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.1.x?fbclid=IwAR2PI8qYb667l36XJqcCG2xihP70zv6yTDb6Z25aoNruAJnB7fhQudWQeYY)

### Printer model

biqu b1 se plus

### Electronics

stock

### LCD/Controller

_No response_

### Other add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/13676405/Configuration_adv.zip)

It is strange because it should have been fixed:  Fix SPI TFT for STM32F1/F4 #26052 

Sorry i am new in git hub.... maybe it is solved and i got the wrong file.... not the really last one 2.X

### PR DESCRIPTION
**Pull request by jmz52**
### Description

Fix SPI TFT for STM32F4 issue introduced in https://github.com/MarlinFirmware/Marlin/pull/25784

Also fixed an issue with macro pins check for SPI pins when pins are defined as  reference to analog pins instead of numbers
```
variant.h:
#define PA7  A7
```

### Requirements

STM32F4 board and TFT display with SPI interface

### Benefits

STM32F4 boards (SKR v2 and MKS Robin Nano v3.x) can again be used with SPI TFT  displays.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I cherry picked these changes into https://github.com/MarlinFirmware/Marlin/pull/26041 and the `BOARD_BTT_SKR_V2_0_REV_B` + `MKS_TS35_V2_0` combination works, but `BOARD_BTT_SKR_V2_0_REV_B` + `BTT_TFT35_SPI_V1_0` does not.

I'll do some more testing today to see if it's an issue of incorrectly defined pins or something is still broken.

**Comment by thisiskeithb** [comment]
`BTT_TFT35_SPI_V1_0` pinout seems fine. Something is still broken for this screen on STM32F4.

File: Marlin/src/HAL/STM32/tft/tft_spi.cpp [hunk 1]
```diff
@@ -43,8 +43,8 @@ void TFT_SPI::init() {
   if ((spiInstance = (SPI_TypeDef *)pinmap_peripheral(digitalPinToPinName(TFT_SCK_PIN),  PinMap_SPI_SCLK)) == NP) return;
   if (spiInstance != (SPI_TypeDef *)pinmap_peripheral(digitalPinToPinName(TFT_MOSI_PIN), PinMap_SPI_MOSI)) return;
 
-  #if PIN_EXISTS(TFT_MISO) && TFT_MISO_PIN != TFT_MOSI_PIN
-    if (spiInstance != (SPI_TypeDef *)pinmap_peripheral(digitalPinToPinName(TFT_MISO_PIN), PinMap_SPI_MISO)) return;
+  #if PIN_EXISTS(TFT_MISO)
+    if ((TFT_MISO_PIN != TFT_MOSI_PIN) && (spiInstance != (SPI_TypeDef *)pinmap_peripheral(digitalPinToPinName(TFT_MISO_PIN), PinMap_SPI_MISO))) return;
```
Comment (thinkyhead) [inline Marlin/src/HAL/STM32/tft/tft_spi.cpp:52]: Is there a special benefit to comparing these pins in code instead of in the preprocessor?

Comment (jmz52) [reply Marlin/src/HAL/STM32/tft/tft_spi.cpp:52]: Some SPI pins are defined as reference to analog pins instead of numbers like `#define PA7  A7`
I've run into problem on F401 development board when these definitions could not be resolved to numbers in preprocessor and caused incorrect code behavior.

Comment (jmz52) [reply Marlin/src/HAL/STM32/tft/tft_spi.cpp:52]: A7 is declared as `static const uint8_t` in framework-arduinoststm32\cores\arduino\pins_arduino.h:
```
#define PIN_A7       (PIN_A6 + 1)
static const uint8_t A7 = PIN_A7;
```

**Comment by jmz52** [comment]
@thisiskeithb, `MKS_TS35_V2_0` and `BTT_TFT35_SPI_V1_0` have the same ST7796 TFT driver.
If `MKS_TS35_V2_0` work with `BOARD_BTT_SKR_V2_0_REV_B` then `BTT_TFT35_SPI_V1_0` should work too.

Lerdge TFT display is known to report custom ID, so forcing exact driver might help to bypass identification part
`#define TFT_DRIVER ST7796`

Other that this it should be either pins definition, cable orientation issue or forgotten TFT reset pin (if there is one on this display)
TFT initialization code is pretty much back to 'pre H7' state, so at the very least you should see random color pixels on the screen.

**Comment by thisiskeithb** [comment]
> Lerdge TFT display is known to report custom ID, so forcing exact driver might help to bypass identification part
`#define TFT_DRIVER ST7796`

That was the fix!

...which is interesting since this should be set already:

https://github.com/MarlinFirmware/Marlin/blob/57d26f7e4f614ee4e05e7e97fdc7109d8cfdc702/Marlin/src/inc/Conditionals_LCD.h#L1641-L1642

edit: I see some GUI glitches in both the `BTT_TFT35_SPI_V1_0` & `MKS_TS35_V2_0` like red or blue rectangles/blocks that span the full width of the screen and flashes/glitching of various icons, so it's not quite working as it used to:

image image

To confirm it wasn't an issue with the hardware I'm testing on my desk, I also flashed my Biqu B1 SE Plus which has the same `BTT_TFT35_SPI_V1_0` TFT & `BOARD_BTT_SKR_V2_0_REV_B` motherboard and it also has the same issues.

**Comment by jmz52** [comment]
`TFT_DEFAULT_DRIVER` is used if the id read from the controller is 0x0000 or 0xFFFF.
If id is reported but unknown then `TFT_DEFAULT_DRIVER` is ignored and no TFT initialization is performed.

`TFT_DRIVER` bypass TFT identification completely and force the specific driver.

**Comment by thisiskeithb** [comment]
> `TFT_DEFAULT_DRIVER` is used if the id read from the controller is 0x0000 or 0xFFFF.
> If id is reported but unknown then `TFT_DEFAULT_DRIVER` is ignored and no TFT initialization is performed.

> `TFT_DRIVER` bypass TFT identification completely and force the specific driver.

Adding `#define TFT_DRIVER ST7796` wasn't required before, but should it be set now `Conditionals_LCD.h`?

**Comment by jmz52** [comment]
@thisiskeithb, I was not able to reproduce these glitches on my MKS Robin Nano v3.1, so I'll need your help to find the root cause.
Here is my understanding of the current state of the code, please correct me if I am wrong.
- SKR v3 works with both MKS and BTT screens and can autodetect driver on both of them, no visual glitches
- SKR v2 worked on pre-H7 code both MKS and BTT screens and could autodetect driver on both of them, and there were no visual glitches
- SKR v2 can autodetect MKS screen but not the BTT screen on H7 code with this fix applied. visual glitches on both MKS and BTT screens

If this is correct, that the first and easiest to validate step should be fixing autodetection of BTT display. Visual glitches might be caused by the same SPI issues that are failing autodetection. I need you to run autodetection on SKR v3 board and check for ID that is actually reported by the ST7796 controller (to make sure that it does report valid ID and not 0x0000 or 0xFFFF where default drivers steps in)

**Comment by thisiskeithb** [comment]
> I'll need your help to find the root cause

I will retest each of these commits/scenarios this week. Keep in mind that I'll need to apply pin changes from https://github.com/MarlinFirmware/Marlin/pull/26041 since https://github.com/MarlinFirmware/Marlin/pull/25784 was merged with compile errors for these boards/displays and that `HAS_SPI_TFT` macro is not universal for these displays due to different pinouts.

> I need you to run autodetection on SKR v3 board and check for ID that is actually reported by the ST7796 controller (to make sure that it does report valid ID and not 0x0000 or 0xFFFF where default drivers steps in)

How do I get the ID reported from the ST7796 controller?

**Comment by jmz52** [comment]
> How do I get the ID reported from the ST7796 controller?

You need to add SERIAL_ECHOLN are the end of `TFT_SPI::ReadID()` function and check console output.
https://github.com/MarlinFirmware/Marlin/blob/2.1.2.1/Marlin/src/HAL/STM32/tft/tft_spi.cpp#L175

**Comment by thisiskeithb** [comment]
> You need to add SERIAL_ECHOLN are the end of `TFT_SPI::ReadID()` function and check console output.

Adding something as simple as `SERIAL_ECHOLN("Testing");` doesn't dump anything to serial, so I'm guessing that it happens too early in the boot process? I'm not sure how to get the TFT ID for you.

> - SKR v2 worked on pre-H7 code both MKS and BTT screens and could autodetect driver on both of them, and there were no visual glitches

Correct. Using Marlin as of c483fe7 (right before 3ea87ad was merged) and adding pin changes from #26041, I do not need to add `#define TFT_DRIVER ST7796` to my config, so auto detection appears to be working correctly(?) on `BOARD_BTT_SKR_V2_0_REV_B` and both `BTT_TFT35_SPI_V1_0` & `MKS_TS35_V2_0` TFTs. There are also no visual glitches like I'm seeing with current `bugfix-2.1.x`/this PR.

> - SKR v2 can autodetect MKS screen but not the BTT screen on H7 code with this fix applied. visual glitches on both MKS and BTT screens

Correct. Note: I had to add pin changes from #26041 as well.

> - SKR v3 works with both MKS and BTT screens and can autodetect driver on both of them, no visual glitches

Note quite. `BOARD_BTT_SKR_V3_0`/`BOARD_BTT_SKR_V3_0_EZ` with pin changes from #26041, can autodetect both TFTs. Testing with the latest `bugfix-2.1.x` (bcf61cc) and code from this (#26052) PR. Note: `MKS_TS35_V2_0` glitches red/green/blue blocks spanning the entire TFT width during any UI sounds (like initializing EEPROM settings)/`M300` and there's random lines of red if you scroll through parts of the UI too fast. `BTT_TFT35_SPI_V1_0` seems to be fine now.

Just to make sure it wasn't hardware, I tested on multiple `BOARD_BTT_SKR_V3_0`/`BOARD_BTT_SKR_V3_0_EZ`/`BOARD_BTT_SKR_V2_0_REV_B` boards (including my Biqu B1 SE Plus) as well as multiple `BTT_TFT35_SPI_V1_0` & `MKS_TS35_V2_0` TFTs. All issues were reproducible across each hardware combos.

**Comment by jmz52** [comment]
That is a bit unexpected, SERIAL_ECHOLN is what I am using for debugging TFT code.
Are us using onboard USB on external USB/UART converter (like FT232 or CH340) connected to onboard UART?
Are "start" and reset reason messages shown in console?

There is another way to check for ID - disable TFT_DEFAULT_DRIVER for BTT_TFT35_SPI_V1_0 and check if SKR3 still can autodetect the TFT controller. If it does, then the ID reported is exactly the 0x7796 - Marlin has only one ID for this controller in tft_ids.h:
`#define ST7796          0x7796`

> Note: MKS_TS35_V2_0 glitches red/green/blue blocks spanning the entire TFT width during any UI sounds (like initializing EEPROM settings)/M300 and there's random lines of red if you scroll through parts of the UI too fast. BTT_TFT35_SPI_V1_0 seems to be fine now.

Please check if problem with MKS_TS35_V2_0 persist if  `BEEPER_PIN` is removed from pins file. And if the glithec are still present with `BEEPER_PIN` intact, but with disabled touch screen when everything is controller via encoder.

MKS screen shares HW SPI with touch controller, while BTT uses dedicated pins for touch and software spi to read data from it.
This difference might be the reason why there are no glitches on BTT screen.

**Comment by thisiskeithb** [comment]
> Please check if problem with MKS_TS35_V2_0 persist if `BEEPER_PIN` is removed from pins file.

Testing this PR on `BOARD_BTT_SKR_V2_0_REV_B` + `MKS_TS35_V2_0` (and of course, pin changes from #26041), glitches go away with the `BEEPER_PIN` disabled.

> And if the glithec are still present with BEEPER_PIN intact, but with disabled touch screen when everything is controller via encoder.

With `BEEPER_PIN` enabled and `TOUCH_SCREEN` disabled with `BOARD_BTT_SKR_V2_0_REV_B` + `MKS_TS35_V2_0`, glitches are still there and sometimes the UI goes into submenus on its own when sending / playing tones. I also seem to have stumbled upon a new bug. The lower part of the UI is now completely missing on most screens with `TOUCH_SCREEN` disabled:

image

image

I have one `MKS_TS35_V2_0` with an encoder and one without, so disabling `TOUCH_SCREEN` wouldn't make sense for the one without, but the UI should still display correctly either way.

> There is another way to check for ID - disable TFT_DEFAULT_DRIVER for BTT_TFT35_SPI_V1_0 and check if SKR3 still can autodetect the TFT controller. 

Disabling `TFT_DEFAULT_DRIVER` for `BOARD_BTT_SKR_V3_0_EZ` + `BTT_TFT35_SPI_V1_0` works. The TFT is auto-detected and seems to work as expected.

> Are us using onboard USB on external USB/UART converter (like FT232 or CH340) connected to onboard UART?

Onboard USB.

> Are "start" and reset reason messages shown in console?

No.

**Comment by jmz52** [comment]
> I have one MKS_TS35_V2_0 with an encoder and one without, so disabling TOUCH_SCREEN wouldn't make sense for the one without, but the UI should still display correctly either way.

Invisible answer selection (Init EEPROM) was just fixed in #26077

Edit screen ("nozzle") was designed to hide "-" "v" and "+" icons when touch screen is disabled.
These elements can't be interacted with and provide no additional information.
The "slider is intended to be reduced to "progress bar" - no draggable element, but still shows where in range of possible values the current value is.

**Comment by phcay** [comment]
I have an MKS Robin Nano v3.0 with an MKS TS35V2 w/encoder.

And indeed, in the bugfix-2.1.x branch, from the "SPI TFT / Touchscreen for STM32H7 (#25784)", I have a white screen from the boot. I can control the Robin Nano with USB, but the screen is unusable.
Using the parent commit "Fix ProUI _remain_time" it works again.

Then I found this PR. So I tested your tft_spi.cpp with the latest "[cron] Bump distribution date (2023-07-06)", and for my configuration it works.

Thanks for this work, and also for "Rework TFT Color UI layout #26077"

**Comment by thisiskeithb** [comment]
I just discovered that I get a solid white screen with `MKS_TS35_V2_0` on `BOARD_MKS_ROBIN_NANO_V2` (STM32F1-based), so maybe F1 is also affected by similar F4 bugs.

I'd have to do some git bisecting to find out when it was broken though.

**Comment by jmz52** [comment]
@thisiskeithb, what code you were using when you've got white sreen on MKS Robin Nano v2 - bugfix or code from this patch?

**Comment by thisiskeithb** [comment]
> what code you were using when you've got white sreen on MKS Robin Nano v2 - bugfix or code from this patch?

Current `bugfix-2.1.x`. I'll do some more testing this weekend and see if F1 is affected the same way F4 is or if this is an entirely new bug.

Speaking of this PR, I just rebased it on current bugfix since several TFT-related PRs have gone in that will make testing easier.

**Comment by jmz52** [comment]
F1 and F4 shares most of the code, so I would expect the root cause to be the same - `TFT_SPI::transmit()`
Could you please test this PR on F1 with and without forced `TFT_DRIVER`?

**Comment by phcay** [comment]
I also have an MKS Robin Nano v2.0 with an MKS TS35V2 with encoder in a drawer.
So I did some tests with the same sources as I did with the MKS Robin Nano v3.0 (bugfix-2.1.x "[cron] Bump distribution date (2023-07-06)". It's not connected to a printer and it's powered only via USB, but that should be enough to test that.
I did not impose TFT_DRIVER, and I checked that it was also the case in pins_MKS_ROBIN_NANO_common.h and pins_MKS_ROBIN_NANO_V2.h.
Attention, to remove any ambiguity, do not touch the tft_spi.cpp of the STM32F1, only that of the STM32 must be replaced (the same as for the NANO_V3).

NanoV2+TS35V2 without patch tft_spi.cpp: **White blank screen**
NanoV2+TS35V2 with tft_spi.cpp patch: **Screen works**
NanoV2+TS35V2 [maple] without patch tft_spi.cpp: **Screen works**
NanoV2+TS35V2 [maple] with tft_spi.cpp patch: **Screen works**

**Comment by phcay** [comment]
To isolate which fixes impact my MKS motherboards, I independently tested the 2 main changes in this PR:

Moved MISO and MOSI pin comparison conditions from preprocessor to compiler.
Restoration of part of the code of the TFT_SPI::transmit(uint16_t data) function for non STM32H7xx.

I checked the pin assignment for the tft_spi, the touchscreen and the encoder button, they are identical between the NanoV2 (STM32F103) and the NanoV3 (STM32F407).

Note that on the MKS_NanoV2 and MKS_NanoV3, the MISO and MOSI pins are of the same type (PA), so switching the preprocessor conditions to the compiler should not change the operation for these 2 cards (apart from a small flash consumption of 16 bytes), but that does not mean that it does not correct for cards where they would be of different type.
```
TFT_MISO_PIN: PA6
TFT_MOSI_PIN: PA7
```
NanoV2+TS35V2 [tft_spi.cpp - original]: White blank screen
NanoV2+TS35V2 [tft_spi.cpp - PR26052]: Screen works
NanoV2+TS35V2 [tft_spi.cpp - only condition preproc 2 compiler fix]: **White blank screen**
NanoV2+TS35V2 [tft_spi.cpp - only TFT_SPI::transmit(uint16_t data) fix]: **Screen works**

I did not perform the tests on the NanoV3, because it is in use. I can do some tests later, but a priori, it should be the same.

So it is indeed TFT_SPI::transmit(uint16_t data) which corrects the operation for the NanoV2. Indeed, following the implementation in the tft_spi.cpp for the STM32H7xx after 06/30/2023, the resulting code for non STM32H7xx has been changed.
The code of this PR26052 makes it possible to restore the code resulting from this function for non STM32H7xx as it was on 06/30/2023.

functional code:
```cpp
   __HAL_SPI_ENABLE(&SPIx);
   SPIx.Instance->DR = data;
   while (!__HAL_SPI_GET_FLAG(&SPIx, SPI_FLAG_TXE)) {} // <===
   while ( __HAL_SPI_GET_FLAG(&SPIx, SPI_FLAG_BSY)) {}
```
instead of this non-working code:
```cpp
     __HAL_SPI_ENABLE(&SPIx);
     SPIx.Instance->DR = data;
     while (__HAL_SPI_GET_FLAG(&SPIx, SPI_FLAG_BSY)) {}
     __HAL_SPI_DISABLE(&SPIx); // <===
```
I therefore tested whether it was the absence of the wait for the appearance of the `SPI_FLAG_TXE` flag or the presence of the `__HAL_SPI_DISABLE(&SPIx)` which was the problem, so I tested these 2 elements independently.

The `SPI_FLAG_TXE` present (or not) does not change anything on the NanoV2.
On the other hand, **the presence of `__HAL_SPI_DISABLE(&SPIx)` causes the White blank screen** on the NanoV2.

So jmz52's proposal to move `__HAL_SPI_DISABLE(&SPIx)` only for STM32H7xx instead of being common already seems like a good solution to me. As for waiting for the transmission flag, it may have been set to make other configurations work, but for mine, it has no impact at first glance.

P.S.: sorry if there are strange words, but I don't speak English, it's an auto translation.

**Comment by Foxies-CSTL** [comment]
Just to complete the tests:
NanoV3.1+TS35RV2 [tft_spi.cpp - original]: White blank screen
NanoV3.1+TS35RV2 [tft_spi.cpp - PR26052]: Screen works

**Comment by jmz52** [comment]
@thisiskeithb, please retest autodetection and visual glitches on updated code.
If problems still exist, try to uncomment this line in HAL/STM32/tft/tft_spi.cpp and check if it has any effect on autodetection or visual glitches.
```
//pin_PullConfig(get_GPIO_Port(STM_PORT(digitalPinToPinName(TFT_SCK_PIN))), STM_LL_GPIO_PIN(digitalPinToPinName(TFT_SCK_PIN)), GPIO_PULLDOWN);
```

Color UI compilation was broken in #25939, fix to tft_string.cpp included in this code.

**Comment by thisiskeithb** [comment]
https://github.com/MarlinFirmware/Marlin/pull/26052/commits/75af24f2bbbdf649e9a84b7f9e29f02c3aa22294 brings in the latest bugfix code to make this PR easier to test current builds.

Testing this PR as-is:
- SKR 3 (STM32H7), both MKS & BTT SPI TFTs work, no visual glitches.
- SKR 2 (STM32F4), the MKS SPI TFT works, no visual glitches. The BTT SPI TFT only shows a white screen/does not work.

Uncommenting `pin_PullConfig(get_GPIO_Port(STM_PORT(digitalPinToPinName(TFT_SCK_PIN))), STM_LL_GPIO_PIN(digitalPinToPinName(TFT_SCK_PIN)), GPIO_PULLDOWN);` in `HAL/STM32/tft/tft_spi.cpp`: Same white screen issue on the SKR 2 + BTT SPI TFT.

Adding `#define TFT_DRIVER ST7796` to the config (and disabling `pin_PullConfig(get_GPIO_Port(STM_PORT(digitalPinToPinName(TFT_SCK_PIN))), STM_LL_GPIO_PIN(digitalPinToPinName(TFT_SCK_PIN)), GPIO_PULLDOWN);`) fixes the white screen issue and there were no visual glitches.

**Comment by jmz52** [comment]
In `TFT_SPI::readID()` method please replace SPI prescaler settings from
`SPIx.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_64;`
to
`
SPIx.Init.BaudRatePrescaler = SPIx.Instance == SPI1 ? SPI_BAUDRATEPRESCALER_8 : SPI_BAUDRATEPRESCALER_4;
`
and retest BTT SPI with `pin_PullConfig` line disabled and enabled.


Do you have an external USB-UART converter that can be used to connect onboard UART connector (FT232R or similar)?
It might be needed for further debugging.
USB serial connection is reset on each MCU reboot, so it might loose some of the information send to console.
External USB-UART converter is more convenient and reliable for debugging.

**Comment by thisiskeithb** [comment]
> In `TFT_SPI::readID()` method please replace SPI prescaler settings from
> `SPIx.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_64;`
> to
> `SPIx.Init.BaudRatePrescaler = SPIx.Instance == SPI1 ? SPI_BAUDRATEPRESCALER_8 : SPI_BAUDRATEPRESCALER_4;`
> and retest BTT SPI with `pin_PullConfig` line disabled and enabled.

I still get a white screen on an SKR 2 + BTT SPI TFT and toggling the `pin_PullConfig()` line doesn't change anything.

> Do you have an external USB-UART converter that can be used to connect onboard UART connector (FT232R or similar)?

~~I think so? It's a generic "FT232RL USB to TTL Serial Converter" I bought for another project, but haven't used it.~~

I just confirmed this works (ignore the TMC errors since this SKR 2 board doesn't have any drivers plugged in):

```
>  External Reset
> Marlin bugfix-2.1.x
> echo: Last Updated: 2023-08-02 | Author: (thisiskeithb, BIQU B1 SE Plus)
> echo: Compiled: Aug  3 2023
> echo: Free Memory: 60287  PlannerBufferBytes: 3584
> EEPROM loaded from slot 22.
> echo:V88 stored settings retrieved (743 bytes; crc 44283)
> //action:notification Stored settings retrieved
> //action:prompt_end
> Testing X connection... Error: All LOW
> Testing Y connection... Error: All LOW
> Testing Z connection... Error: All LOW
> Testing Z2 connection... Error: All LOW
> Testing E connection... Error: All LOW
> echo:SD card ok
```

**Comment by jmz52** [comment]
I've added debug code that will dump identification data to console.
```
TFT_SPI::getID()
  raw data : 4294967295
  readID(0x04) : 0xFFFF
  raw data : 3918719
  readID(0xD3) : 0x7796
```
Please run this code on SKR2 and SKR3 to check IDs reported by MKS TS35 and BTT SPI TFT on both boards

**Comment by thisiskeithb** [comment]
#### SKR 2 with BTT SPI TFT
```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3642943
  readID(0xD3) : 0x6F2C
  Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

#### SKR 2 with MKS SPI TFT
```
TFT_SPI::getID()
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

#### SKR 3 with BTT SPI TFT
```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3918623
  readID(0xD3) : 0x7796
  Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

#### SKR 3 with MKS SPI TFT
```
TFT_SPI::getID()
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

**Comment by jmz52** [comment]
Well, that is not good at all.
According to ST7796S datasheet data read from RDID4(Read ID4) a.k.a. 0xD3 register should be following:
```
1x dummy read (single SPI clock tick or single uint8/uint16 from FSMC)
8x bits - 0x00
8x bits - 0x77
8x bits - 0x96
```
STM32F1/F4 can't read 25 bits from hardware SPI, so 4 full bytes are read instead.
MISO line is pulled up, so last 7 bits should be set to 1.
TFT CS is set to HIGH after 4 bytes transfer, so 7 extra SPI clock ticks are ignored by TFT controller.

So the valid identification data read from SPI should be
```
0 0000 0000 0111 0111 1001 0110 1111 111 - 3918719
```
And this is exactly the value I am getting from MKS TS35 on MKS Robin Nano 3.1

On SKR boards the situation is not that bright
MKS TS35 display does not report anything, so default driver is used
BTT TFT reports its ID, but the data are corrupted
```
0 0000 0000 0111 0111 1001 0110 1111 111   - 3918719 (reference i.e. MKS Robin Nano 3.1)
0 0000 0000 0111 0111 1001 0110 0011 111   - 3918623 / SKR3 with BTT TFT
  0000 0000 0011 0111 1001 0110 0011 111 1 - 3642943 / SKR2 with BTT TFT
0 0000 0000 0.11 0111 1001 0110 0011 111 1 - 3642943 / SKR2 the lost bit
```
SKR3 has all important bits set right, but the first two bits from final dummy read are set to 0 instead of 1
SKR2 data is 1 bit off and 1 important bit is incorrectly set to 0. It looks like one bit was lost i.e. send between two SPI clock ticks and was ignored by STM32

I am going to look at schematics for SKR2 and SKR3 to check if there is a difference in SPI interface in EXP1/EXP2

In the mean time, can you collect `raw data` from `TFT_SPI::readID()` using pre-H7 code ?
I am beginning to worry if TFT IDs were ever reported correctly on SKR2 or if their absence was masked by `TFT_DEFAULT_DRIVER`

**Comment by thisiskeithb** [comment]
I'm not sure it matters, but I retested this PR since you committed https://github.com/MarlinFirmware/Marlin/pull/26052/commits/6ae35fe6edd7412670c12fe4689e650cd964cf74 after my first round of results:

#### SKR 2 with BTT SPI TFT
```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3609087
  readID(0xD3) : 0x6E23
```

#### SKR 2 with MKS SPI TFT
```
TFT_SPI::getID()
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

#### SKR 3 with BTT SPI TFT
```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3918623
  readID(0xD3) : 0x7796
```

#### SKR 3 with MKS SPI TFT
```
TFT_SPI::getID()
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

**Comment by thisiskeithb** [comment]
> In the mean time, can you collect raw data from TFT_SPI::readID() using pre-H7 code ?

I went back to https://github.com/MarlinFirmware/Marlin/commit/c483fe76c7c750d1ee08a6d5fdfe363f1beb4e03, which is right before https://github.com/MarlinFirmware/Marlin/commit/3ea87ad54c1e445a1c8cfef1489809edae5decb3. I had to also pull in `pins_BTT_SKR_V2_0_common.h` updates from https://github.com/MarlinFirmware/Marlin/pull/26041:

#### SKR 2 with BTT SPI TFT
*(TFT is white/does not work)*
```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3640321
  readID(0xD3) : 0x6F18
```

#### SKR 2 with MKS SPI TFT
```
TFT_SPI::getID()
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

Since the BTT SPI TFT wouldn’t work with https://github.com/MarlinFirmware/Marlin/commit/c483fe76c7c750d1ee08a6d5fdfe363f1beb4e03 (even though it did before), I tried to test `2.1.2.1` and apply the debug commits, but they wouldn’t merge cleanly. There’s been a lot of bugs/fixes with TFT code, so maybe I missed something trying to pull in commits / patches from various places.

**Comment by jmz52** [comment]
For `2.1.2.1` the only debug code needed is the single line in `TFT_SPI::readID()` that prints `raw data : ` , it can be manually added rat the end of the method.
```
SERIAL_ECHOLNPGM("  raw data : ", data);
return data >> 7;
```

For pre-H7 code, please check reported 'raw data' and IDs in following scenarios using code compiled for `BTT_TFT35_SPI_V1_0`
1.  SKR2 with BTT TFT, reboot board several times and check if 'raw data' are the same on each boot
2. disconnect TFT, but keep EXP1/EXP2 cables connected to the SKR2 board
3. disconnect EXP1/EXP2 cables
4. connect MKS TS35 (using correct cables orientation for this screen), this will add idle peripheral devices to SPI bus
5. same as # 1 but using different set of EXP1/EXP2 cables if available
6. same as # 1 but with `BEEPER_PIN` set to -1

**Comment by thisiskeithb** [comment]
> SERIAL_ECHOLNPGM("  raw data : ", data);

I had to use `SERIAL_ECHOLNPGM("  raw data : ", Data);` since all the "lowercase" PRs/commits/fixes were merged after `2.1.2.1`.

---

Using an SKR 2 with BTT SPI TFT firmware and `2.1.2.1`:

> 1.  SKR2 with BTT TFT, reboot board several times and check if 'raw data' are the same on each boot

```
raw data : 905969663
raw data : 3640321
```
TFT is white/doesn't work

A few reboots later and:
```
raw data : 905969663
raw data : 3918592
```
TFT works

Another reboot later:
```
raw data : 905969663
raw data : 3642880
```
TFT is white/doesn't work

---

> 2. disconnect TFT, but keep EXP1/EXP2 cables connected to the SKR2 board

```
raw data : 4294967295
raw data : 4294967295
```
This does not change after 10+ reboots

---

> 3. disconnect EXP1/EXP2 cables

```
raw data : 4294967295
raw data : 4294967295
```
This does not change after 10+ reboots

---

> 4. connect MKS TS35 (using correct cables orientation for this screen), this will add idle peripheral devices to SPI bus

```
raw data : 4294967295
raw data : 4294967295
```
This does not change after 10+ reboots. Note: I am still using the SKR 2 + BTT SPI TFT firmware for this test.

---

> 5. same as # 1 but using different set of EXP1/EXP2 cables if available

```
raw data : 905969663
raw data : 3918592
```
I swapped out 480mm cables for some that are 300mm. Values don't change / TFT works, but will randomly remain white after pressing reset.

---

> 6. same as # 1 but with `BEEPER_PIN` set to -1

```
raw data : 905969663
raw data : 3918592
```
Using the same 300mm cables still attached, values don't change / TFT works, but will randomly remain white after pressing reset.

---

I’ll look for some shorter cables / see if I can find some shielding tape to help with bench testing since that seems to help. In fact, the B1 SE Plus with SKR 2 + BTT SPI TFT has short, shielded EXP cables, but that machine is not easy to hook up extra cables internally for debugging.

Edit: I found some 200mm EXP cables and wrapped them with some shielding/faraday tape and there is no change/improvement.

File: Marlin/src/HAL/STM32/tft/tft_spi.cpp (hunk 1 above)
Comment (thinkyhead) [reply Marlin/src/HAL/STM32/tft/tft_spi.cpp:52]: > Some SPI pins are defined as reference to analog pins

Ah, that's weird since they're digital when used with SPI. Oh well!

**Comment by thinkyhead** [comment]
Are we still looking at reverting all the changes before #25784 and starting over with the STM32 changes in a way that leaves STM32F4 functionaluty intact? Perhaps we can just try to redo #25784 and its followups in a way that only STM32H7 is affected and nothing else is touched.

It might be worth a look at how Klipper manages its STM32 kernel and differences between them. It seems like it has a pretty clean set of implementations.

**Comment by thisiskeithb** [comment]
> Are we still looking at reverting all the changes before https://github.com/MarlinFirmware/Marlin/pull/25784 and starting over with the STM32 changes in a way that leaves STM32F4 functionaluty intact?

Manually defining the TFT driver type with `#define TFT_DRIVER ST7796` when `BTT_TFT35_SPI_V1_0` is enabled seems to work (despite not needing to do this pre-H7 code), so that could be a temporary workaround for now.

**Comment by jmz52** [comment]
>Are we still looking at reverting all the changes before https://github.com/MarlinFirmware/Marlin/pull/25784 and starting over with the STM32 changes in a way that leaves STM32F4 functionality intact?

H7 and F1/F4 changes are already separated in this PR.

There are only two lines or code that differ from original F1/F4 code:
- pull-down for `TFT_SCK_PIN` is disabled, so it can be used on boards with onboard pull-up resistors on SPI
- SPI BaudRatePrescaler is increased from 4 (SPI2 and SPI3) or 8 (SPI1) to 64 during TFT identification procedure

Both these lines were reverted to original state during tests above and neither of them have any effect on SKR2 issues.

**Comment by vovodroid** [comment]
Hi, what is status of this issue?

I needed to revert both https://github.com/MarlinFirmware/Marlin/commit/fef772ef29e502c8fd2f53e10de383dbcb3529fe and  https://github.com/MarlinFirmware/Marlin/commit/3ea87ad54c1e445a1c8cfef1489809edae5decb3 to use latest bugfix branch on original Biqu S1 SE with SKR 2.

**Comment by thisiskeithb** [comment]
> Hi, what is status of this issue?

This PR is still pending.

See my comment above for the current fix/workaround still needed for an SKR 2: https://github.com/MarlinFirmware/Marlin/pull/26052#issuecomment-1667186530

**Comment by vovodroid** [comment]
> Manually defining the TFT driver type with `#define TFT_DRIVER ST7796` when `BTT_TFT35_SPI_V1_0` is enabled seems to work

Yes, I tried in Configuration.h

```
#define BTT_TFT35_SPI_V1_0
#define TFT_DRIVER ST7796
//#define TFT_GENERIC
```
without success. Should it be defined in another way?
Anyway it's worth to  keep branch functional.

**Comment by jmz52** [comment]
@vovodroid, this code works on hardware I have - MKS Robin Nano 3.1 and black F407VE, both with MKS TS35.
SKR2 and BTT SPI TFT have same MCU (STM32F407VE) and TFT Controller (ST7796), but identification process failures.
Forced TFT_DRIVER skips TFT identification completely, making SKR2 work with both BTT and MKS screens (on this branch's code)

One of the problem with diagnostics is that it is not clear if identification process worked on pre-H7 code or if fall-back to default driver was in place.
If you have USB-UART adapter and can run tests on your board, this will help me to understand the changes between pre-H7 and current state of this branch.

**Comment by vovodroid** [comment]
> If you have USB-UART adapter and can run tests on your board,

Do you mean connecting printer via serial port like for regular debug logs? How to view debugs on boot?


> Forced TFT_DRIVER skips TFT identification completely, making SKR2 work with both BTT and MKS screens (on this branch's code)

I didn't try your branch, but bugfix-2.1.x. Is your fix included in main branch?

**Comment by vovodroid** [comment]
I mean these two commits:

image

Does your branch contains new fixes to be checked on SKR 2 with

```
#define BTT_TFT35_SPI_V1_0
#define TFT_DRIVER ST7796
```
?

**Comment by thisiskeithb** [comment]
> I didn't try your branch, but bugfix-2.1.x. Is your fix included in main branch?

No, but I just merged the latest `bugfix-2.1.x` into this PR so it's now up to date.

> Do you mean connecting printer via serial port like for regular debug logs? How to view debugs on boot?

Something like an FT232RL USB to TTL serial converter connected to the TFT port works best to collect all serial data.

**Comment by vovodroid** [comment]
> I just merged the latest `bugfix-2.1.x` into this PR so it's now up to date.

Ok, I'll test it. Is `#define TFT_DRIVER ST7796` still needed?

> Something like an FT232RL USB to TTL serial converter

Like this one?
image

Should it be connected to Arduino? I can only connect board to PC or Android via OTG adapter. Will it work for boot loging?

**Comment by thisiskeithb** [comment]
> Is #define TFT_DRIVER ST7796 still needed?

In the code/PR's current state, it is required for the SKR 2 now. This was not the case before STM32H7 SPI support was added.

> Like this one?

Yes.

> Should it be connected to Arduino? I can only connect board to PC or Android via OTG adapter. Will it work for boot loging?

You can connect to the FT232RL with VSCode via USB.

**Comment by vovodroid** [comment]
> You can connect to the FT232RL with VSCode via USB.

How I connect this adapter to USB? Where do the six pins connect?


Well, I tried this branch with `#define TFT_DRIVER ST7796`. In general it works on SKR 2, but it seems that screen is lagging, some of items randomly is not drawn, and appears later or when knob is rotating. There screens after entering to "Settings" menu:

image

image

image

Is it performance issue?

**Comment by ellensp** [comment]
"How I connect this adapter to USB? Where do the six pins connect?"  its a serial device,it is plugged into a serial port such as the tft or the wifi port. (tft port is easiest)  Use 3 pins TX to board RX, RX to board TX and GND to GND

Make sure to set the jumper to 3.3v signal levels

You then enable the serial port in marlin. and you can send debug messages to it  (or gcode) or log anything with  serail terminal program...

**Comment by vovodroid** [comment]
> log anything with serail terminal program...

Does connecting to standard USB with PC or tablet do the same thing?

**Comment by ellensp** [comment]
yes, but it gives you an independent port, so can still connect and control it with standard control programs via standard usb port

**Comment by thisiskeithb** [comment]
> Does connecting to standard USB with PC or tablet do the same thing?

It's similar, but the board will disconnect USB on reboot and you may not catch all serial messages (particularly debug ones like those used in this PR with `DEBUG_TFT_IO` enabled.)

**Comment by vovodroid** [comment]
Well, if it's needed I can purchase such adapter on Ali, but please provide me instruction how to setup it on SKR 2.
Where do six pins go on the main board?

**Comment by thinkyhead** [comment]
> Manually defining the TFT driver type with `#define TFT_DRIVER ST7796` when `BTT_TFT35_SPI_V1_0` is enabled seems to work (despite not needing to do this pre-H7 code), so that could be a temporary workaround for now.

~~It looks like this was intended with `TFT_DEFAULT_DRIVER` being set to `ST7796` for `BTT_TFT35_SPI_V1_0` (so maybe there was a known issue with the driver ID being flaky), but I don't see where `TFT_DEFAULT_DRIVER` is being picked up and used. I'll add a commit that sets `TFT_DRIVER` to `TFT_DEFAULT_DRIVER` instead of `AUTO` when `TFT_DEFAULT_DRIVER` is defined and see if that covers it. Configs will then have to leave `TFT_DRIVER` undefined instead of using `AUTO`.~~

EDIT: I see that `TFT_DEFAULT_DRIVER` is the fallback if the ID could not be acquired from the display. It keeps trying if `getID` returns 0x0000 or 0xFFFF but doesn't keep trying if some unusual ID is returned. It simply leaves the display uninitialized. So I added another commit, which will continue up to the fallback if the ID returned by the display is unrecognized. That at least fixes the issue where the SKR 2 was stopping before getting to the fallback.

**Comment by thisiskeithb** [comment]
As of the latest commits (33cd243), I still get a blank/white screen with `BTT_TFT35_SPI_V1_0` on an SKR 2 unless I add `#define TFT_DRIVER ST7796` to the config.

**Comment by thisiskeithb** [comment]
I rebased a local copy of this PR on current `bugfix-2.1.x` (with `#define TFT_DRIVER ST7796` in the config) and now I'm back to having random red blocky parts in the UI like I had back in https://github.com/MarlinFirmware/Marlin/pull/26052#issuecomment-1622401066 on an SKR 2 with the BTT TFT35 SPI.

**Comment by jmz52** [comment]
@thisiskeithb, can you please check the [lts-2.1.1](https://github.com/MarlinFirmware/Marlin/tree/lts-2.1.1) code - does it work for SKR 2 / BTT TFT35 SPI without `#define TFT_DRIVER ST7796`?

**Comment by thisiskeithb** [comment]
> can you please check the [lts-2.1.1](https://github.com/MarlinFirmware/Marlin/tree/lts-2.1.1) code - does it work for SKR 2 / BTT TFT35 SPI without `#define TFT_DRIVER ST7796`?

`2.1.1` works for an SKR 2 / BTT TFT35 SPI without `#define TFT_DRIVER ST7796`.

**Comment by jmz52** [comment]
Please add readID debug output `TFT_SPI::getID()` in `2.1.1` and check if driver was identified correctly or if fall-back to default driver took place.

**Comment by thisiskeithb** [comment]
> Please add readID debug output `TFT_SPI::getID()` in `2.1.1` and check if driver was identified correctly or if fall-back to default driver took place.

```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3918592
  readID(0x04) : 0x7796
  Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

**Comment by jmz52** [comment]
This is kind of strange - TFT ID was read correctly from the second register (0x7796), but there is still a fall-back to default message.
And register IDs of the first and second reads are the same.
Is this a text issue, or valid ID really was ignored for some reason?

**Comment by thisiskeithb** [comment]
>  Is this a text issue, or valid ID really was ignored for some reason?

I have no idea, but I'm happy to run more tests on older tags if that helps at all.

Something in #25784 changed how this BTT TFT35 SPI works on STM32F4 and `#define TFT_DRIVER ST7796` is now required.

**Comment by jmz52** [comment]
Please test if SKR2 can identify BTT TFT35 SPI on [tft-spi-debug](https://github.com/jmz52/Marlin/tree/tft-spi-debug) branch
It contains latest bugfix with tft spi code from 2.1.1 i.e. no H7 support

**Comment by thisiskeithb** [comment]
> Please test if SKR2 can identify BTT TFT35 SPI on [tft-spi-debug](https://github.com/jmz52/Marlin/tree/tft-spi-debug) branch

TFT works fine without needing to add `#define TFT_DRIVER ST7796` to the config:

```
readID(0x04) : 0xFFFF
readID(0xD3) : 0x7796
```

**Comment by jmz52** [comment]
Good, now we can gradually change code to find out that was the breaking point
Please retest the [tft-spi-debug](https://github.com/jmz52/Marlin/tree/tft-spi-debug) branch on SKR2

**Comment by thisiskeithb** [comment]
> Please retest the [tft-spi-debug](https://github.com/jmz52/Marlin/tree/tft-spi-debug) branch on SKR2

"Update TFT_SPI::transmit()" / 2b2a2f8f54a83cf11177bc80173ee3efa61145c7 works:
```
readID(0x04) : 0xFFFF
readID(0xD3) : 0x7796
```

**Comment by jmz52** [comment]
`TFT_SPI::transmit()` seems to be in order. Please retest code with updated `TFT_SPI::readID()`

**Comment by thisiskeithb** [comment]
> Please retest code with updated `TFT_SPI::readID()`

"Update TFT_SPI::readID()" / 293fa83f08aab7fe987c6c71c1058f02c0b2ddae works:
```
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3918623
  readID(0xD3) : 0x7796
```

**Comment by jmz52** [comment]
Weird, `init()`, `transmit()` and `readID()` functions were about the same as the code from this PR, but the TFT ID was read correctly.

Please retest updated code in [tft-spi-debug](https://github.com/jmz52/Marlin/tree/tft-spi-debug) branch - `tft_spi.cpp` is the same as in this PR.

**Comment by thisiskeithb** [comment]
> Please retest updated code in [tft-spi-debug](https://github.com/jmz52/Marlin/tree/tft-spi-debug) branch - `tft_spi.cpp` is the same as in this PR.

"Revert "STM32H7 code"" / d3a8d09f53ab542034475900e7429674f47ff39f works:

```
raw data : 905969663
readID(0x04) : 0xFFFF
raw data : 3918592
readID(0xD3) : 0x7796
```

**Comment by jmz52** [comment]
Sorry, forgot to push updated code.
Please retest again.

**Comment by thisiskeithb** [comment]
> Sorry, forgot to push updated code. Please retest again.

"STM32H7 code again" / bad0289098186ee9359dd0f4593d21246f14201c works:

```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3918623
  readID(0xD3) : 0x7796
```

**Comment by jmz52** [comment]
And what IDs are reported by code in [this PR](https://github.com/jmz52/Marlin/tree/stm32f4-tft-spi-fix) ?

**Comment by thisiskeithb** [comment]
> And what IDs are reported by code in [this PR](https://github.com/jmz52/Marlin/tree/stm32f4-tft-spi-fix) ?

Using code from this PR (#26052) + merging in latest `bugfix-2.1.x` since it was ~ a month behind:

```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3918623
  readID(0xD3) : 0x7796
```

This is now back to working without `#define TFT_DRIVER ST7796`, but the UI has blocks of red like https://github.com/MarlinFirmware/Marlin/pull/26052#issuecomment-1622401066 and scrolling through menus is super buggy with menu items missing/reappearing on scroll and blocks of red across the entire width.

edit: ...and #26445 broke touchscreen support.

**Comment by jmz52** [comment]
Not sure if this is related at all, but after reverting https://github.com/MarlinFirmware/Marlin/pull/26445 I've run into a problem with reading screen id (0x7FDE instead of 0x7796)
`tft_spi.cpp` code from https://github.com/MarlinFirmware/Marlin/commit/293fa83f08aab7fe987c6c71c1058f02c0b2ddae works fine, so I still have a chance to find out what causing this identification issue.

**Comment by jmz52** [comment]
Sadly that identification issue was caused by a silly mistake - SPI was not slowed down before reading IDs and the data were corrupted.
Anyway please test this updated version and let me know if TFT identification was successful and if there are any visual glitches present.

SPI is intentionally configured to be extremely slow, so touch screen might not be responsive event after if you reverse said PR.
If visual glitches are still present, please check if `TFT_SHARED_IO` options from `Configuration.h` has any effect on them.

**Comment by thisiskeithb** [comment]
"Update tft_spi.cpp" / https://github.com/MarlinFirmware/Marlin/pull/26052/commits/ec5a964a1c09392eaca890d9a2088d941b6c43be "works", but I get a warning now:

```prolog
Marlin/src/HAL/STM32/tft/tft_spi.cpp: In static member function 'static uint32_t TFT_SPI::readID(uint16_t)':
Marlin/src/HAL/STM32/tft/tft_spi.cpp:198:14: warning: unused variable 'BaudRatePrescaler' [-Wunused-variable]
  198 |     uint32_t BaudRatePrescaler = SPIx.Init.BaudRatePrescaler;
      |              ^~~~~~~~~~~~~~~~~
```

Here's the serial output:
```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3918623
  readID(0xD3) : 0x7796
```

I say "works" because the screen is *really* slow now and takes a long time to redraw on boot or going through the menus. It reminds me of loading images on dial up 😄 I took a video, but it's taking forever to sync to the cloud.

**Comment by jmz52** [comment]
Are there any visual glitches?

**Comment by thisiskeithb** [comment]
> Are there any visual glitches?

Yes. The entire UI is extremely slow and loads top to bottom like a wipe transition on boot / every menu action.

**Comment by jmz52** [comment]
Slow UI drawing is intentional - long time ago I had visual glitches that only happened on very slow SPI baudrates.
If all color and items are displayed correctly, please uncomment the
`    //SPIx.Init.BaudRatePrescaler = BaudRatePrescaler;`
line in  [tft_spi.cpp](https://github.com/jmz52/Marlin/blob/ec5a964a1c09392eaca890d9a2088d941b6c43be/Marlin/src/HAL/STM32/tft/tft_spi.cpp#L232) and retest.

**Comment by thisiskeithb** [comment]
> Slow UI drawing is intentional - long time ago I had visual glitches that only happened on very slow SPI baudrates. If all color and items are displayed correctly, please uncomment the ` //SPIx.Init.BaudRatePrescaler = BaudRatePrescaler;` line in [tft_spi.cpp](https://github.com/jmz52/Marlin/blob/ec5a964a1c09392eaca890d9a2088d941b6c43be/Marlin/src/HAL/STM32/tft/tft_spi.cpp#L232) and retest.

Ahh, ok. I uncommented that line and the UI is back to being speedy again. There's also no red / blocky UI parts like I was seeing.

And here's the serial output if it helps at all:
```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3918623
  readID(0xD3) : 0x7796
```

**Comment by thisiskeithb** [comment]
I just rebased this PR on current `bugfix-2.1.x` to clean up the commit history and make it easier to revert specific/recent bugfix commits (like PR #26445 that broke touch) for testing.

**Comment by jmz52** [comment]
> There's also no red / blocky UI parts like I was seeing.

Speaking of which, please make sure you are using `#define TFT_THEME BLUE_MARLIN` for testing.
Missing a byte when filling screen with black my not be noticeable, but blue background will not let that slip undetected.

Please test SKR2 with MKS TS35 and SKR3 with both displays and check for reported IDs and visual glitches.

**Comment by thisiskeithb** [comment]
> Speaking of which, please make sure you are using `#define TFT_THEME BLUE_MARLIN` for testing.
> Missing a byte when filling screen with black my not be noticeable, but blue background will not let that slip undetected.

Now parts of the UI are light blue instead of red on SKR 2 + BTT TFT35 SPI and menus are not highlighting correctly. Looks like `#define TFT_THEME BLACK_MARLIN` was hiding that issue.

Testing with an SKR 3 + BTT TFT35 SPI, the UI looks fine without any light blue/blocky parts or going multi-color when the speaker beeps.

Serial output for both SKR 2 & SKR 3 with BTT TFT35 SPI for good measure:
```
TFT_SPI::getID()
  raw data : 905969663
  readID(0x04) : 0xFFFF
  raw data : 3918623
  readID(0xD3) : 0x7796
```

---

Testing with an SKR 2 and SKR 3 + MKS TS35, the UI looks mostly fine, but the screen scrambles/goes multi-color whenever there's a sound played like when the speaker beeps after an EEPROM reset. I had this issue in previous testing, so I'm not sure if that was ever fixed. I am also getting a `Fallback to TFT_DEFAULT_DRIVER` message via serial with both motherboard + TS35 combos:

```
TFT_SPI::getID()
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  raw data : 4294967295
  readID(0xD3) : 0xFFFF
  Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

**Comment by jmz52** [comment]
And here I thought we've made some progress on F4 code fix...
Please check `lts-2.1.1` again with blue background and both BTT and MKS displays - TFT IDs, visual glitches and side effects from speaker.

**Comment by thisiskeithb** [comment]
> Please check lts-2.1.1 again with blue background and both BTT and MKS displays - TFT IDs, visual glitches and side effects from speaker.

The MKS TS35 wasn't supported on the SKR 2 in 2.1.1 since the SKR 2 pins file used the `HAS_SPI_TFT` macro which did not properly define pins for the MKS TFT, but I can backport the pins file changes to hopefully get that going.

> TFT IDs

This may be more difficult since I'm not sure what needs to be changed to backport that code for testing.

*This is a quite a mess* and I think we should just revert all of these SPI TFT changes (except pins files) so SPI TFTs work on F1 and F4 again. We can delay H7 support until it's been properly tested and doesn't break F1 & F4 in the process.

... and hopefully touch will work again soon once a fix is found in #26455.

**Comment by jmz52** [comment]
> I think we should just revert all of these SPI TFT changes (except pins files) so SPI TFTs work on F1 and F4 again.

That's what I am trying to do. Tricky part is that there were number of changes on tft code after H7 commit.

I've reverted [tft-spi-debug](https://github.com/jmz52/Marlin/tree/tft-spi-debug) to F4 only code.
Please test in on BTT and MKS displays - blue background, TFT IDs, visual glitches and side effects from speaker.

**Comment by thisiskeithb** [comment]
> I've reverted [tft-spi-debug](https://github.com/jmz52/Marlin/tree/tft-spi-debug) to F4 only code.
> Please test in on BTT and MKS displays - blue background, TFT IDs, visual glitches and side effects from speaker.

### SKR 2 with `BTT_TFT35_SPI_V1_0`

Display works as expected. No blocky UI or glitches while scrolling through the menus or playing tones.

Serial output:
```
raw data : 905969663
readID(0x04) : 0xFFFF
raw data : 3918592
readID(0xD3) : 0x7796
```

Adding `#define TFT_DRIVER ST7796` is not required since the TFT works as expected.

---

### SKR 2 with `MKS_TS35_V2_0`

Display does not work as expected. The UI goes blocky/mutli-color/glitches while playing tones. Scrolling through the menus seems to be OK.

Serial output:
```
raw data : 4294967295
readID(0xD3) : 0xFFFF
raw data : 4294967295
readID(0xD3) : 0xFFFF
Fallback to TFT_DEFAULT_DRIVER : 0x7796
```

Adding `#define TFT_DRIVER ST7796` is not required since the fallback `TFT_DEFAULT_DRIVER` is being used.

**Comment by jmz52** [comment]
It looks like the issue with SKR2 & TS35 is not new, but we had to chance to face it as pins required for TS35 were not defined.

Could you redefine pins in [2.1.2.1](https://github.com/MarlinFirmware/Marlin/tree/2.1.2.1) to test if SKR2/TS35 really had these issues on pre-H7 code?
If you could, please also test if enabling `TFT_SHARED_SPI` option has any affect on these glitches.

**Comment by thisiskeithb** [comment]
Rebased on current `bugfix-2.1.x` that includes recent touch screen fixes.

**Comment by thisiskeithb** [comment]
> Could you redefine pins in [2.1.2.1](https://github.com/MarlinFirmware/Marlin/tree/2.1.2.1) to test if SKR2/TS35 really had these issues on pre-H7 code?
> If you could, please also test if enabling `TFT_SHARED_SPI` option has any affect on these glitches.

Using an SKR 2 with `MKS_TS35_V2_0` on `2.1.2.1` with SKR 2 `HAS_SPI_TFT` pin changes backported, same exact symptoms as reported in https://github.com/MarlinFirmware/Marlin/pull/26052#issuecomment-1834466150:
- The UI goes blocky/mutli-color/glitches while playing tones.
- Scrolling through the menus seems to be OK.
- `TFT_SHARED_SPI` does not change this behavior.

**Comment by jmz52** [comment]
I've connected MKS TS35 to Black_F407 dev board using SKR2 pinout and jumper wires.
TFT screen was detected correctly and there were not visual glitches
```
TFT_SPI::getID()
  raw data : 3918719
  readID(0xD3) : 0x7796
```

Can you please provide me your SKR2 TS35 configuration files for bugfix-2.1.x, so I may test it on my HW?

**Comment by thisiskeithb** [comment]
> Can you please provide me your SKR2 TS35 configuration files for bugfix-2.1.x, so I may test it on my HW?

There's not much required, but here's the minimal config: [bugfix-2.1.x-mks-ts35-skr-v2-minimal-config.zip](https://github.com/MarlinFirmware/Marlin/files/13549854/bugfix-2.1.x-mks-ts35-skr-v2-minimal-config.zip)

<details><summary>And diff view for faster viewing:</summary>
<p>

```diff
diff --git a/Marlin/Configuration.h b/Marlin/Configuration.h
index 4d0351b..72f1a19 100644
--- a/Marlin/Configuration.h
+++ b/Marlin/Configuration.h
@@ -68,7 +68,7 @@
 
 // Choose the name from boards.h that matches your setup
 #ifndef MOTHERBOARD
-  #define MOTHERBOARD BOARD_RAMPS_14_EFB
+  #define MOTHERBOARD BOARD_BTT_SKR_V2_0_REV_B
 #endif
 
 /**
@@ -79,7 +79,7 @@
  *
  * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
  */
-#define SERIAL_PORT 0
+#define SERIAL_PORT -1 // USB
 
 /**
  * Serial Port Baud Rate
@@ -92,7 +92,7 @@
  *
  * :[2400, 9600, 19200, 38400, 57600, 115200, 250000, 500000, 1000000]
  */
-#define BAUDRATE 250000
+#define BAUDRATE 115200
 
 //#define BAUD_RATE_GCODE     // Enable G-code M575 to set the baud rate
 
@@ -101,7 +101,7 @@
  * Currently Ethernet (-2) is only supported on Teensy 4.1 boards.
  * :[-2, -1, 0, 1, 2, 3, 4, 5, 6, 7]
  */
-//#define SERIAL_PORT_2 -1
+#define SERIAL_PORT_2 1 // TFT port repurposed for FT232RL USB to TTL serial converter
 //#define BAUDRATE_2 250000   // :[2400, 9600, 19200, 38400, 57600, 115200, 250000, 500000, 1000000] Enable to override BAUDRATE
 
 /**
@@ -2712,7 +2712,7 @@
 // If you have a speaker that can produce tones, enable it here.
 // By default Marlin assumes you have a buzzer with a fixed frequency.
 //
-//#define SPEAKER
+#define SPEAKER
 
 //
 // The duration and frequency for the UI feedback sound.
@@ -3219,7 +3219,7 @@
 // Usually paired with MKS Robin Nano V2 & V3
 // https://github.com/makerbase-mks/MKS-TFT-Hardware/tree/master/MKS%20TS35
 //
-//#define MKS_TS35_V2_0
+#define MKS_TS35_V2_0
 
 //
 // 320x240, 2.4", FSMC Display From MKS
@@ -3323,7 +3323,7 @@
  *   root of your SD card, together with the compiled firmware.
  */
 //#define TFT_CLASSIC_UI
-//#define TFT_COLOR_UI
+#define TFT_COLOR_UI
 //#define TFT_LVGL_UI
 
 #if ENABLED(TFT_COLOR_UI)
@@ -3343,7 +3343,7 @@
    * BLACK_MARLIN - Theme with 'black' background
    * ANET_BLACK   - Theme used for Anet ET4/5
    */
-  #define TFT_THEME BLACK_MARLIN
+  #define TFT_THEME BLUE_MARLIN
 
   //#define TFT_SHARED_IO   // I/O is shared between TFT display and other devices. Disable async data transfer.
 
@@ -3380,7 +3380,7 @@
 //
 // Touch Screen Settings
 //
-//#define TOUCH_SCREEN
+#define TOUCH_SCREEN
 #if ENABLED(TOUCH_SCREEN)
   #define BUTTON_DELAY_EDIT      50 // (ms) Button repeat delay for edit screens
   #define BUTTON_DELAY_MENU     250 // (ms) Button repeat delay for menus
@@ -3401,7 +3401,7 @@
   #endif
 
   #if ENABLED(TFT_COLOR_UI)
-    //#define SINGLE_TOUCH_NAVIGATION
+    #define SINGLE_TOUCH_NAVIGATION
   #endif
 #endif
```

</p>
</details>

**Comment by jmz52** [comment]
The tones that causes visual glitches - how they are played?
Are they regular UI feedback or from M300 gcode?

**Comment by thisiskeithb** [comment]
> Are they regular UI feedback or from M300 gcode?

Both methods trigger the display corruption.

**Comment by doshiyo103** [comment]
Hi,
I am using Marlin-stm32f4-tft-spi-fix to develop firmware. 
On the B1 SE Plus, there is a significant delay in the display, 
and there are residual images during menu operations. 
Could you please check and investigate?

**Comment by jmz52** [comment]
@doshiyo103 , TFT IO was intentionally slowed for troubleshooting.

You need to uncomment following line in Marlin/src/HAL/STM32/tft/tft_spi.cpp
`//SPIx.Init.BaudRatePrescaler = BaudRatePrescaler;`

**Comment by doshiyo103** [comment]
Hi,Thank you for your response.
I'm sorry, I'm a user who doesn't understand code at all. 
Are you suggesting that deleting this commented line is sufficient? 
Currently, I've tried deleting the comment, then rebuilding and reinstalling, 
but the delay issue persists, and the machine seems to be restarting randomly.

I apologize for my lack of familiarity with code, 
and I may need to ask for your understanding. Thank you for your help.

 ``` 
uint32_t TFT_SPI::readID(const uint16_t inReg) {
  uint32_t data = 0;
  #if PIN_EXISTS(TFT_MISO)
    uint32_t BaudRatePrescaler = SPIx.Init.BaudRatePrescaler;
    SPIx.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_64;

    dataTransferBegin(DATASIZE_8BIT);
    writeReg(inReg);

    if (SPIx.Init.Direction == SPI_DIRECTION_1LINE) SPI_1LINE_RX(&SPIx);

    #ifdef STM32H7xx
      for (uint32_t i = 0; i < 4; i++) {
        MODIFY_REG(SPIx.Instance->CR2, SPI_CR2_TSIZE, 1);
        __HAL_SPI_ENABLE(&SPIx);
        SET_BIT(SPIx.Instance->CR1, SPI_CR1_CSTART);

        if (SPIx.Init.Direction == SPI_DIRECTION_2LINES) SPIx.Instance->TXDR = 0;
        while (!__HAL_SPI_GET_FLAG(&SPIx, SPI_FLAG_EOT));
        data = (data << 8) | SPIx.Instance->RXDR;
        __HAL_SPI_DISABLE(&SPIx);
        __HAL_SPI_CLEAR_EOTFLAG(&SPIx);
        __HAL_SPI_CLEAR_TXTFFLAG(&SPIx);
      }
    #else
      __HAL_SPI_ENABLE(&SPIx);
      for (uint32_t i = 0; i < 4; i++) {
        if (SPIx.Init.Direction == SPI_DIRECTION_2LINES) {
          while (!__HAL_SPI_GET_FLAG(&SPIx, SPI_FLAG_TXE));
          SPIx.Instance->DR = 0;
        }
        while (!__HAL_SPI_GET_FLAG(&SPIx, SPI_FLAG_RXNE));
        data = (data << 8) | SPIx.Instance->DR;
      }
    #endif

    dataTransferEnd();
    //SPIx.Init.BaudRatePrescaler = BaudRatePrescaler;     <----just delete?
  #endif

  DEBUG_ECHOLNPGM("  raw data : ", data);
  return data >> 7;
 ```

**Comment by thisiskeithb** [comment]
@doshiyo103: I’d recommend using an older version of Marlin or waiting until this PR is merged and issue is fixed in bugfix.

**Comment by vovodroid** [comment]
@doshiyo103, you can revert commits fef772ef29e502c8fd2f53e10de383dbcb3529fe and 3ea87ad54c1e445a1c8cfef1489809edae5decb3 in bugfix-2.1.x (that's how I run it on B1 SE: SKR2+ SPI TFT)

**Comment by doshiyo103** [comment]
@thisiskeithb ,Hi,Thank you for your response.
I can wait for this fix,and really thank you did good job for Marlin!

@vovodroid ,Hi,Thank you for your response.
I really want to try the solution you mentioned, but this is my first time using GitHub, 
so I'm not quite sure about the meaning of 'revert commits #fef772e and #3ea87ad in bugfix-2.1.x.' 
Could you please tell me how to do it? 

Thank you very much for your assistance. 
I'm happy to hear that this method might allow me to use the firmware!

**Comment by vovodroid** [comment]
> meaning of 'revert commits #fef772e and #3ea87ad in bugfix-2.1.x.'

It means remove changes from branch as if they didn't exist. It's not matter of Github, but Git itself. You should clone Marlin repository to your computer and discard (revert) these commits with Git or any Git-Gui shell (I use Gitextension on Windows).

**Comment by doshiyo103** [comment]
@vovodroid ,
HI,I think I did it. I downloaded GitExtensions to operate, 
successfully reverted the two commits you mentioned, then rebuilt. 
Now the startup is normal, and there is no delay in operation. 

Thank you very much for your assistance!!!! 
However, I still look forward to everything being resolved smoothly, bringing a better experience to everyone. 
Thanks to everyone, you're great!!

**Comment by thisiskeithb** [comment]
`DEBUG_TFT_IO` is now disabled by default in 2483e3c and I wasn't sure if `SPIx.Init.BaudRatePrescaler = BaudRatePrescaler;` should stick around, so I made it a conditional of `DEBUG_TFT_IO` so screens will run at full speed unless `DEBUG_TFT_IO` is enabled.

@jmz52: This PR is also now up to date with current bugfix, but is there anything else to do? The MKS TS35 issue has existed long before these SPI TFT updates based on testing we've done here.

**Comment by firepower9966** [comment]
Any Updates ? when PR goes to commit, what the usual time frame?

**Comment by thisiskeithb** [comment]
> when PR goes to commit, what the usual time frame?

PRs get merged when they are ready. This PR took an especially long time since jmz52 doesn't have the exact hardware on hand and had to remote test through me since I have all the hardware.

There's still more work to be done to improve SPI TFT support on STM32F1 & STM32F4, but that'll be in a future PR.

@jmz52: Please let me know if there's additional testing/hardware configs that I should run code on.

**Comment by firepower9966** [comment]
I can also test I have Mks Nano Robin V3.1 and MKS TS35 V2.0 with MKS TMC2209 uart mode and MKSWifi with ESP3D 2.1.2 firmware.
How can i test PR?

**Comment by firepower9966** [comment]
I manual   edited the commits into my bugfix-2.1.x that gave me white screen , and now it test OK.
I will also test later with latest bug fix, but need to fine tune configs first as this is a new printer build.

**Comment by firepower9966** [comment]
Thank You for you help to get it to work , very happy .

**Review by firepower9966 — APPROVED** [review]
I manual edited the commits into my bugfix-2.1.x that gave me white screen , and now it test OK.

updated
Test ok with latest bugfix-2.1.x dated 1/1/24

**Comment by Conan877** [comment]
I am willing to buy MKS Robin Nano V3.1 + MKS TS35 V2 today, but I haven't found it yet. Has this problem been solved?

**Comment by thisiskeithb** [comment]
> Has this problem been solved?

Yes, this PR has been merged.

image
