### PR TITLE
FTMotion: Fix TMC2208 timing bug (attempt)

### LINKED ISSUE #28248: [BUG] FTM. Complete stoppage of the extruder at a random moment in time.
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Overall, the FTM works very well – I don't hear any squeaking from the stepper motors, and the extruder motor doesn't squeak or click either. I get excellent quality corners without lumps or under-extrusion.
But there is one problem: at some point (it could be 2 minutes or 20 minutes after printing starts, or in the latter case, an hour and a half after printing starts), the extruder stops.

Movement along the X and Y axes continues quickly and accurately along the product, but the extruder's stepper motor remains stationary.

I can see this because the large gears of the extruder protrude beyond the gearbox housing.

And it's not a clogged nozzle or a blockage due to filament hardening in the heatbreak — if I stop printing and start the same file again, everything will be fine for a while, but then it will stop completely again.

### Bug Timeline

_No response_

### Expected behavior

I expect it to print until the end.

### Actual behavior

The extruder stepper motor stops at random times, sometimes after a considerable interval.

### Steps to Reproduce

1. Set the FTM settings according to my configuration files.
2. Start printing something long.

### Version of Marlin Firmware

FIRMWARE_NAME:Marlin bugfix-2.1.x (Dec 20 2025 20:02:37)

### Printer model

voxelab aquila

### Electronics

Creality 2.4.7 motherboard

### LCD/Controller

DWIN (Ender 3v2 display unit)

### Other add-ons

_No response_

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Configs:
[cfgs.zip](https://github.com/user-attachments/files/24286636/cfgs.zip)

Extruder.
Image

Last print, no complaints, just the extruder stopping after an hour and a half.
Image

### PR DESCRIPTION
**Pull request by dbuezas**
### Description

TMC2208 Direction-Flip Delay

Some TMC2208 / TMC2208_STANDALONE setups may require a short delay after a DIR change
to avoid timing-sensitive glitches, especially when using stealthChop.

When enabled for an axis, FT Motion will "pause" that axis for > 750µs after a detected
direction flip by holding its trajectory coordinate constant for a multiple of FTM_TS
frames. For the default FTM_FS = 1000, it is a single 1ms frame.
Other axes keep moving normally, and the wait is cancelled if the axis flips again.

NOTE: Typically only needed if you actually use stealthChop on that axis.

### Configurations

FTM + 2208 drivers in stealthchop

### Related Issues

Hopefully fixes #28248

### CODE REVIEW

**Comment by yrabbit** [comment]
The situation with TMC2225 (TMC2208) has been corrected. My settings for FTM, Creality 4.2.7 board:

``` C
#define X_DRIVER_TYPE  TMC2208_STANDALONE
#define Y_DRIVER_TYPE  TMC2208_STANDALONE
#define Z_DRIVER_TYPE  TMC2208_STANDALONE
#define E0_DRIVER_TYPE TMC2208_STANDALONE

#define FTM_IS_DEFAULT_MOTION 
#define NO_STANDARD_MOTION 

#define FTM_DEFAULT_SHAPER_X      ftMotionShaper_ZVD
#define FTM_SHAPING_DEFAULT_FREQ_X   40.0f

#define FTM_DEFAULT_SHAPER_Y      ftMotionShaper_ZVD
#define FTM_SHAPING_DEFAULT_FREQ_Y   40.0f

#define FTM_DEFAULT_SHAPER_Z      ftMotionShaper_NONE
#define FTM_SHAPING_DEFAULT_FREQ_Z   21.0f

#define FTM_SHAPER_E
#define FTM_DEFAULT_SHAPER_E      ftMotionShaper_NONE
#define FTM_SHAPING_DEFAULT_FREQ_E   21.0f 

#define FTM_SMOOTHING
#define FTM_SMOOTHING_TIME_E        0.06f

#define FTM_POLYS 
#define FTM_TRAJECTORY_TYPE POLY5 

#define FTM_BUFFER_SIZE             2048
#define FTM_FS  
```

Before the fixes related to TMC2225 (TMC2208), the extruder would stop:

https://github.com/user-attachments/assets/c638be50-e50c-46d6-a85a-4614ad816ce5

After corrections in this PR, stoppages due to TMC2225 (TMC2208) are no longer observed.

**Comment by narno2202** [comment]
@dbuezas , I missed @yrabbit success. In my mind this should be mandatory if a faulty driver is present: TMC2208 or TMC5160.

You could remove the related code in `Configuration_adv.h` and do if you want in `drivers.h`
```c
#define _OR_ADTX(N,T)   || AXIS_DRIVER_TYPE_X##N(T)
#define HAS_X_DRIVER(T) (0 RREPEAT2(NUM_X_STEPPERS, _OR_ADTX, T))
#define _OR_ADTY(N,T)   || AXIS_DRIVER_TYPE_Y##N(T)
#define HAS_Y_DRIVER(T) (0 RREPEAT2(NUM_Y_STEPPERS, _OR_ADTY, T))
#define _OR_ADTZ(N,T)   || AXIS_DRIVER_TYPE_Z##N(T)
#define HAS_Z_DRIVER(T) (0 RREPEAT2(NUM_Z_STEPPERS, _OR_ADTZ, T))
```

then at the end  of this file
```c
#if ENABLED(FT_MOTION)
  #if HAS_X_DRIVER(TMC2208) || HAS_X_DRIVER(TMC2208_STANDALONE) || HAS_X_DRIVER(TMC5160) || HAS_X_DRIVER(TMC5160_STANDALONE)
      #define APPLY_TIMING_HACK_ON_X
    #endif
    #if HAS_Y_DRIVER(TMC2208) || HAS_Y_DRIVER(TMC2208_STANDALONE) || HAS_Y_DRIVER(TMC5160) || HAS_Y_DRIVER(TMC5160_STANDALONE)
      #define APPLY_TIMING_HACK_ON_Y
    #endif
    #if HAS_Z_DRIVER(TMC2208) || HAS_Z_DRIVER(TMC2208_STANDALONE) || HAS_Z_DRIVER(TMC5160) || HAS_Z_DRIVER(TMC5160_STANDALONE)
      #define APPLY_TIMING_HACK_ON_Z
    #endif
    #if HAS_E_DRIVER(TMC2208) || HAS_E_DRIVER(TMC2208_STANDALONE) || HAS_E_DRIVER(TMC5160) || HAS_E_DRIVER(TMC5160_STANDALONE)
      #define APPLY_TIMING_HACK_ON_E
    #endif
#endif // FT_MOTION
```

**Comment by dbuezas** [comment]
The issue only appears on stealthchop only, so better be configurable to avoid it applying on machines set to spreadcycle

**Comment by narno2202** [comment]
At least for standalone drivers (stealthchop by default and not modifiable).

**Comment by dbuezas** [comment]
Well, for non standalone too if the user set them as stealthchop, and I don't think the 5160s are affected.
Anyway this is experimental, we don't yet know if it works well

**Comment by oliof** [comment]
> Well, for non standalone too if the user set them as stealthchop, and I don't think the 5160s are affected. Anyway this is experimental, we don't yet know if it works well

Most standalone drivers are set to stealthchop, you usually need to solder a pair of pads to enable spreadcycle if stepsticks. With onboard drivers, all bets are off.

File: Marlin/Configuration_adv.h [hunk 1]
```diff
@@ -1238,6 +1238,32 @@
...
+   * to avoid the driver to turn off, especially when using stealthChop (which is the default
+   * for standalone configuration).
+   *
+   * When enabled for an axis, FT Motion will "pause" that axis for > 750µs after a detected
+   * direction flip by holding its trajectory coordinate constant for a multiple of FTM_TS
+   * frames. For the default FTM_FS = 1000, it is a single 1ms frame.
+   * Other axes keep moving normally, and the wait is cancelled if the axis flips again.
+   *
+   */
+  #if AXIS_DRIVER_TYPE_X(TMC2208) || AXIS_DRIVER_TYPE_X(TMC2208_STANDALONE)
```
Comment (thinkyhead) [inline Marlin/Configuration_adv.h]: How does TMC2209 / TMC2225 differ so that it doesn't stall?

Comment (dbuezas) [reply Marlin/Configuration_adv.h]: You'll have to ask tmc. It's a known bug of the 2208

Comment (thinkyhead) [reply Marlin/Configuration_adv.h]: I'm studying the documentation on exactly how TMC drivers expect these signals to be structured, and I recommend everyone else touching this code please join me in this enjoyable reading of datasheets and technical papers!

Comment (dbuezas) [reply Marlin/Configuration_adv.h]: It's unfortunately not specified in the datasheet, it's not an timing explicit timing requirement. 
The approach here comes from the workaround in klipper pointed by @nuck-TH, other workaround alternatives by @narno2202 and discussions in #28248

Comment (thinkyhead) [reply Marlin/Configuration_adv.h]: Do we currently skip changing DIR when an axis's movement distance is 0 (and its previous move distance was negative)? That won't likely fix anything, but it would remove some extraneous DIR pulses.

Comment (dbuezas) [reply Marlin/Configuration_adv.h]: The dir pin is only touched before an actual step, right before it and not otherwise

Comment (thinkyhead) [reply Marlin/Configuration_adv.h]: And I see that there is an explicit `DIR_WAIT_AFTER` in `Stepper::ftMotion_stepper` for any change of DIR before the next step. For TMC2208 it's just 100 ns. Enough time to settle, so the DIR signal itself is safe on that side.

However, there is no `DIR_WAIT_BEFORE` there in `ftMotion_stepper` to ensure the DIR signal is not coming too soon _after_ a STEP. All that would be required would be to store the time when the last STEP was done and make a specialized FT Motion version of `DIR_WAIT_BEFORE` that only waits 100 ns minus the time elapsed since then.

Not to oversimplify the problem, but this is the first naive approach I would try.

Comment (Nuck-TH) [reply Marlin/Configuration_adv.h]: This waits are busywaits _inside an ISR_. They are _relatively_ fine for ensuring signal timings, but not for 2208 problem mitigation, because busywaiting whopping 750us inside ISR is absolutely unacceptable.

Comment (thinkyhead) [reply Marlin/Configuration_adv.h]: Adding delay by modifying the next command time may have the same effect. Ideally you want to look ahead, see that a DIR change is pending on the next command, and shift the time of the next command forward at that point.

**Comment by narno2202** [comment]
@thinkyhead, I tried to catch the DIR changes in `ftMotion_stepper()` (DIR_STEP and STEP - DIR) and add a delay of 800ns (searching gave 650ns) before and after DIR pulse but no success..  @dbuezas  and @thinkyhead , what about catching the DIR changes in `stepping.h`, exit the `do .. while loop in Stepper.isr()` if necessary and change interval value to set the next stepper ISR (`HAL_timer_set_compare(MF_TIMER_STEP, next_isr_ticks)`)?

**Comment by dbuezas** [comment]
I don't think it is a timing of the dir pin issue given all the experiments and the klipper workaround, i.e not a logic timing problem. Instead, it seems to be an oversensitive overcurrent protection when there's two contiguous steps in different directions. 
IMO if it was pin timing issue it wouldn't require a monstrous wait of almost a ms.

**Comment by dbuezas** [comment]
@narno2202 , the user reported this PR to have fixed his issue, and it has no issues with lost steps or interrupting other axes already.

**Comment by thinkyhead** [comment]
> two contiguous steps in different directions

So, in other words, you could do the DIR change at any point in-between the two STEP signals, but if there is too little time between the different-direction STEP signals the driver will go into STST.

Our basic motion assumes TMC2209 requires 100 ns for DIR signals to settle. And it assumes that if a STEP signal also needs time to settle, and then some additional time for the "instantaneous" step to physically complete. If the DIR change arrives in the middle of the step, either before it has settled or while the step is in-progress, presumably that will also cause STST.

Timing of signals could depend on the driver design, because theoretically in response to the STEP signal the driver could make a latched copy of the DIR state instead of using the source DIR state. It would still need to have a settled DIR signal to do that, so there's just no eliminating that 100 ns post-delay.

At the extreme, you could imagine two STEP signals in opposite directions causing a current-spike when there is some momentum in the axis, and then the detection of the spike is what causes the driver to choke.

I'm speculating a bit here. What would be most useful would be to see a healthy pulse train side-by-side with the kinds of pulse-trains that cause STST, and just make sure we adhere to all the required intervals, even when inserting babysteps into the signal train.

---

The solution here seems good to me. Direction changes are far less frequent occurrences than steps, so even though this adds some overhead on every direction change, it should not end up slowing anything significantly.

**Comment by dbuezas** [comment]
Warning, the extra changes before merging it broke the algorithm.

File: Marlin/src/module/ft_motion.cpp [hunk 2]
```diff
@@ -612,7 +620,38 @@ void FTMotion::fill_stepper_plan_buffer() {
...
     }
     else {
+
+      #if HAS_FTM_DIR_CHANGE_HOLD
+
+        // When a flip is detected (and the axis is in stealthChop or is standalone),
+        // hold that axis' trajectory coordinate constant for at least 750µs.
+
+        #define DIR_FLIP_HOLD_S 0.000'750f
+        static constexpr uint32_t dir_flip_hold_frames = DIR_FLIP_HOLD_S / (FTM_TS + 1);
```
Comment (dbuezas) [inline Marlin/src/module/ft_motion.cpp:630]: For the record: the parenthesis introduced here is wrong

Comment (Nuck-TH) [reply Marlin/src/module/ft_motion.cpp:630]: @thinkyhead fyi

Comment (dbuezas) [reply Marlin/src/module/ft_motion.cpp:630]: Is fixed in bugfix
