### PR TITLE
Fail SD mounting with no SPI re-init

### LINKED ISSUE #19223: [BUG] Endstop switches not being read properly when connected to OctoPi
### Bug Description

When connected to an OctoPi, my X and Y endstop switches are always being reported as "open." This causes the printer to try and move beyond its minimum bounds. This does not happen when the Pi is disconnected. I have filed an issue with both OctoPi and OctoPrint, and both have indicated that this appears to be a firmware problem.

If I connect the Pi when the printer is already homed, I can send `M119` and see the following:

```
Send: M119
Recv: Reporting endstop status
Recv: x_min: open
Recv: y_min: TRIGGERED
Recv: z_min: open
```

### My Configurations

My configurations are exactly as provided in the example configs for my printer model (ender 3 v2): https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20V2

### Steps to Reproduce

On an Ender3 v2 with the example configurations, attempt to home the printer with OctoPi connected.

**Expected behavior:** [What you expect to happen]

The printer should stop at the endstops

**Actual behavior:** [What actually happens]

The printer continues to try and move the carriage beyond the minimum bounds.

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

sd2card.init uses SPI_SD_INIT_RATE, not SPI_SPEED. The removed line set the spi speed to wrong velocity and the SD stop working. Even if correct, that spiInit dont need stay there, as is the calling code the responsability to put spi in the right state before the use.

### Benefits

Fixes #19223

It removes the false "SD Init Fail" when booting a printer without a SD card.

### Related Issues

#19223

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> It removes the false "SD Init Fail" when booting a printer without a SD card.

Thanks! This also addresses the comments left on https://github.com/MarlinFirmware/Marlin/pull/19064

**Comment by rhapsodyv** [comment]
Doing more research, I found that spiInit is totally wrong, as it assume that the SD is SPI... but a lot of SD uses SDIO with no spi involved ...

The bug it fixes, is because that SPI init defaults to SPI 1, that are the same pins as used for creality_v4 end stops:

```cpp
// endstops on Creality v4
#define X_STOP_PIN                          PA5
#define Y_STOP_PIN                          PA6
#define Z_STOP_PIN                          PA7

// spi default pins
#ifndef SCK_PIN
  #define SCK_PIN  PA5
#endif
#ifndef MISO_PIN
  #define MISO_PIN PA6
#endif
#ifndef MOSI_PIN
  #define MOSI_PIN PA7
#endif
#ifndef SS_PIN
  #define SS_PIN   PA4
#endif
```

**Comment by mikemerryguy** [comment]
line 386 I changed from (cardreader.cpp)
else if (marlin_state != MF_INITIALIZING) 
to 
else if (marlin_state == MF_INITIALIZING) 
and now I get my ready message vs SD INIT FAIL on boot with no SD
with SD I can print from SD
without I can attach SD as normal and print as normal.

File: Marlin/src/sd/cardreader.cpp [hunk 1]
```diff
@@ -383,10 +383,9 @@ void CardReader::mount() {
 
   if (flag.mounted)
     cdroot();
-  else {
-    spiInit(SPI_SPEED); // Return to base SPI speed
+  else if (marlin_state != MF_INITIALIZING)
```
Comment (mikemerryguy) [inline Marlin/src/sd/cardreader.cpp:386]: line 386 change != to == 
fixed SD INIT FAIL on boot with no SD card for me.

**Comment by thisiskeithb** [comment]
@mikemerryguy: Which board/LCD/SDCARD_CONNECTION setting?

I tested this on a few printers:

With a BTT002 on a MK3S with a `REPRAP_DISCOUNT_SMART_CONTROLLER` (no motherboard-based SD card reader), no errors displayed on boot when no SD card is present in the LCD-based SD card slot.

With an SKR Mini E3 V2 on an Ender-3 with a `CR10_STOCKDISPLAY` (no LCD-based SD card reader), "SD Init Fail" is displayed on boot when no SD card is present in the motherboard-based SD card slot.

With an SKR Mini E3 V1.2 on an Ender-3 with a `CR10_STOCKDISPLAY` (no LCD-based SD card reader), "SD Init Fail" is displayed on boot when no SD card is present in the motherboard-based SD card slot.

With an SKR 1.4 on an Biqu B1 with a `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` and `SDCARD_CONNECTION` set to `ONBOARD`, "SD Init Fail" is displayed on boot when no SD card is present in the motherboard-based SD card slot.

With an SKR 1.4 on an Biqu B1 with a `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` and `SDCARD_CONNECTION` set to `LCD`, no errors are displayed on boot when no SD card is present in either the motherboard or LCD-based SD card slot.

**Review by mikemerryguy — COMMENTED** [review]
> @mikemerryguy: Which board/LCD/SDCARD_CONNECTION setting?
> 
> I tested this on a few printers:
> 
> With a BTT002 on a MK3S with a `REPRAP_DISCOUNT_SMART_CONTROLLER` (no motherboard-based SD card reader), no errors displayed on boot when no SD card is present in the LCD-based SD card slot.
> 
> With an SKR Mini E3 V2 on an Ender-3 with a `CR10_STOCKDISPLAY` (no LCD-based SD card reader), "SD Init Fail" is displayed on boot when no SD card is present in the motherboard-based SD card slot.
> 
> With an SKR 1.4 on an Biqu B1 with a `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` and `SDCARD_CONNECTION` set to `ONBOARD`, "SD Init Fail" is displayed on boot when no SD card is present in the motherboard-based SD card slot.
> 
> With an SKR 1.4 on an Biqu B1 with a `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` and `SDCARD_CONNECTION` set to `LCD`, no errors are displayed on boot when no SD card is present in either the motherboard or LCD-based SD card slot.

I am using Skr mini e3 1.2 with CR10 stock display settings on an ENDER 3 

as per facebook I think the issue is deeper in marlin_state or MF_INITIZLIZING but it DID work for my setup!

**Comment by rhapsodyv** [comment]
Changing to ` == MF_INITIZLIZING` will only hide the problem... If you are getting `SD Init Fail` with "!=" and not with "==" is because the sd init code has being called after the what marlin define as "boot sequence".

When I send that PR, I was just focused in solving the spiInit problem, that was conflicting with creality board and was totally wrong there.

But, as you and @thisiskeithb are reporting, maybe the entire "if not mount, show fail" is wrong...

I will review the sd init code.

**Comment by mikemerryguy** [comment]
@rhapsodyv Yes, I do think its deeper, I just was reporting it worked for now, and as I said, hopefully we get it sorted, I did not dig deeper, I am ehhhh basic programming level haha made some stuff, but never deep into a firmware!!! 
Thanks for looking into it!

**Comment by rhapsodyv** [comment]
What is happening is:

In the marlin boot marlin_state is MF_INITIZLIZING, it call card.mount(). If fail, it will not show any message.

After all boot sequence, marlin_state became MF_RUNNING. So, all calls to card.mount() now on will show the message.

The issue is, that in the marlin main loop, it always calls: card.manage_mediaI(). This function compares the current card insertion state with the last state from the previews calls.

The problem is: some boards don't have the SD_DETECT_PIN. So, the marlin code always consider that the SD was inserted and try mount it *every time*.

It appears to be in the boot sequence, but isn't. The card.mount is called every second (or so), and will try mount and give fail message *always* if the board don't have SD_DETECT_PIN.

So, my suggestion is: only show that `ui.set_status_P(GET_TEXT(MSG_SD_INIT_FAIL), -1);` if the board have SD_DETECT_PIN... 
Without that, it will always and forever show that "SD Init Fail", until you insert a SD...

**Comment by rhapsodyv** [comment]
@mikemerryguy take a look in this PR #19236

**Comment by mikemerryguy** [comment]
@rhapsodyv 
@thisiskeithb 
what you think?
it compiled!!!
didn't test yet!!!

if (flag.mounted)
    cdroot();
  else if (marlin_state != MF_INITIALIZING) 
    #if defined (SD_DETECT_PIN)
      ui.set_status_P(GET_TEXT(MSG_SD_INIT_FAIL), -1);
    #endif


fix from  #19236 works perfect, thanks guys!

**Comment by th3dstudio** [comment]
Can confirm this fixes the endstop with no SD card inserted issue on the V4.2.7 boards.
