### PR TITLE
Fixes G29_with_retry behavior

### LINKED ISSUE #11044: G29_RETRY_AND_RECOVER off by one
### Description
When using the `G29_RETRY_AND_RECOVER` feature, the retry loop is incorrectly set up. 

### Steps to Reproduce

1. Enable G29_RETRY_AND_RECOVER
2. Set G29_MAX_RETRIES
3. Bypass probe signal
4. Run G29

**Expected behavior:**
Failed bed probes are retried `G29_MAX_RETRIES` times, before failing.

**Actual behavior:**
Failed bed probes are retried `G29_MAX_RETRIES - 1` times, with one extra `G29_RECOVER_COMMANDS` followed immediately by `G29_FAILURE_COMMANDS`.

#### Additional Information
The relevant code is in [GcodeSuite::G29_with_retry()](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/gcode/gcode.cpp#L139):
```
for (uint8_t i = G29_MAX_RETRIES; i--;) {
      G29();
      if (planner.leveling_active) break;
      #ifdef G29_ACTION_ON_RECOVER
        SERIAL_ECHOLNPGM("//action:" G29_ACTION_ON_RECOVER);
      #endif
      #ifdef G29_RECOVER_COMMANDS
        process_subcommands_now_P(PSTR(G29_RECOVER_COMMANDS));
      #endif
}
```

### PR DESCRIPTION
**Pull request by hexane360**
### Description
As currently implemented, `G29_RETRY_AND_RECOVER` is situated outside all `G29()` code, and attempts reprobe attempts whenever leveling is disabled after running `G29()`. However, there are several reasons `G29()` can leave without enabling bed leveling that have nothing to do with a failed probe (axes not homed, dry run, report, etc.). There are two ways to solve this: to turn `G29()` into a `bool` that indicates whether a probe has failed, or to handle reprobe attempts inside `G29()`. This PR is the second approach, currently for ABL only. Implementing it for UBL shouldn't be too hard, but UBL currently doesn't handle failed probes at all. It might help to encapsulate `probe_pt()` in a helper function that handles retry logic to achieve DRY.

I've thoroughly this code with and without `G29_RETRY_AND_RECOVER`. 

### Benefits
1. `G29_MAX_RETRIES` is now the number of *re*tries, not just tries. It also persists across multiple different probes in the same G29 commands, which is intuitive as well as idiomatic with the original Lulzbot implementation.
2. Extraneous `G29_RECOVER_COMMANDS` are not run without an accompanying call to `G29()`
3. Full G29 functionality is restored

### Related Issues
Fixes #11044.

### CODE REVIEW

File: Marlin/src/inc/SanityCheck.h [hunk 1]
```diff
@@ -930,6 +930,17 @@ static_assert(X_MAX_LENGTH >= X_BED_SIZE && Y_MAX_LENGTH >= Y_BED_SIZE,
...
 #endif
 
+#if ENABLED(G29_RETRY_AND_RECOVER)
+  #if !HAS_LEVELING
+    #error "G29_RETRY_AND_RECOVER requires automatic bed leveling"
+  #elif !ENABLED(OLDSCHOOL_ABL)
+    #error "G29_RETRY_AND_RECOVER currently only supports ABL"
+  #endif
+  #ifndef G29_MAX_RETRIES
+    #define G29_MAX_RETRIES 0
```
Comment (thinkyhead) [inline Marlin/src/inc/SanityCheck.h]: This define should go into the code file that uses it, since only one file does.

File: Marlin/src/inc/SanityCheck.h [hunk 2]
```diff
@@ -930,6 +930,17 @@ static_assert(X_MAX_LENGTH >= X_BED_SIZE && Y_MAX_LENGTH >= Y_BED_SIZE,
   #error "MESH_EDIT_GFX_OVERLAY requires AUTO_BED_LEVELING_UBL and a Graphical LCD."
 #endif
 
+#if ENABLED(G29_RETRY_AND_RECOVER)
+  #if !HAS_LEVELING
+    #error "G29_RETRY_AND_RECOVER requires automatic bed leveling"
```
Comment (thinkyhead) [inline Marlin/src/inc/SanityCheck.h]: This option will simply be ignored when leveling is disabled. It's more convenient to ignore it, so users may disable leveling for testing purposes without also having to disable `G29_RETRY_AND_RECOVER` before they can recompile.

File: Marlin/src/inc/SanityCheck.h [hunk 3]
```diff
@@ -930,6 +930,17 @@ static_assert(X_MAX_LENGTH >= X_BED_SIZE && Y_MAX_LENGTH >= Y_BED_SIZE,
...
+  #elif !ENABLED(OLDSCHOOL_ABL)
+    #error "G29_RETRY_AND_RECOVER currently only supports ABL"
```
Comment (thinkyhead) [inline Marlin/src/inc/SanityCheck.h]: This is ok, though.

File: Marlin/src/gcode/bedlevel/abl/G29.cpp [hunk 4]
```diff
@@ -683,7 +687,18 @@ void GcodeSuite::G29() {
...
+          
+          #if ENABLED(G29_RETRY_AND_RECOVER)
+            while (isnan(measured_z) && retries--) { //retry probe
+              #ifdef G29_ACTION_ON_RECOVER
+                SERIAL_ECHOLNPGM("//action:" G29_ACTION_ON_RECOVER);
+              #endif
+              #ifdef G29_RECOVER_COMMANDS
+                process_subcommands_now_P(PSTR(G29_RECOVER_COMMANDS));
+              #endif
+              measured_z = probe_pt(xProbe, yProbe, raise_after, verbose_level);
```
Comment (thinkyhead) [inline Marlin/src/gcode/bedlevel/abl/G29.cpp]: Here we must be careful. If the probe failed, driving the nozzle into the bed, this might drive it even further into the bed. I suppose this might also be possible with the previous implementation too….

**Comment by thinkyhead** [comment]
This kind of alters the meaning of the retry option. It's meant to retry the entire leveling procedure, not just each individual probe. So, I would prefer the other idea: When the feature is enabled, have `G29` return a `bool` indicating that the failure is fatal and should not be re-tried…
```cpp
    for (uint8_t i = G29_MAX_RETRIES; i--;) {
      if (G29() || planner.leveling_active) break;
```
Or, the return status might indicate simply that it should not be retried, either because it _was_ a fatal error or it was successful…
```cpp
    for (uint8_t i = G29_MAX_RETRIES; i--;) {
      if (G29()) break;
```

File: Marlin/src/gcode/bedlevel/abl/G29.cpp (hunk 4 above)
Comment (hexane360) [reply Marlin/src/gcode/bedlevel/abl/G29.cpp]: I don't think this is a huge concern. As called by G29, `probe_pt` currently raises by `Z_CLEARANCE_BETWEEN_PROBES` whether or not the probe was successful. The nozzle would have to have been driven down by more than this for it to remain touching the bed. If this is a concern, the best way to fix this for all use cases would be to have probe_pt completely undo any failed probes before returning (this would improve the behavior even when not using this feature).

**Comment by hexane360** [comment]
This does alter the retry option as it exists in HEAD, but the retry option in HEAD is severely broken. In the [Marlin currently distributed by Lulzbot](devel.lulzbot.com/TAZ/Olive/software/firmware/Marlin_Oliveoil_Tilapia_v1.0.2.22_60d344d/Marlin/Marlin_main.cpp) (who made the original `G29_RETRY_AND_RECOVER` PR), the retry option functions on a per-probe basis, with retries reset at the beginning of each level command. I could understand either way, but I don't think this feature has widespread enough adoption that we're stuck with the current behavior. [Lulzbot's current repo](https://code.alephobjects.com/rMARLIN53d2e26aedc9438220b1cb9ad78f7d1fdf2d6c5f) seems to use a mix of the two approaches.

**Comment by marcio-ao** [comment]
@hexane360: My original implementation would retry individual probes, but I identified a problem with that approach. The recover procedure can be something dramatic like attempting to level the X axis by skipping steps against the endstops and rehome; if something like that is done, I doubt the previous probes would still be valid and it makes sense to re-run the entire G29.

**Comment by marcio-ao** [comment]
> This does alter the retry option as it exists in HEAD, but the retry option in HEAD is severely broken. In the Marlin currently distributed by Lulzbot (who made the original G29_RETRY_AND_RECOVER PR)

You're looking at our old FW. The new firmware is in the 'devel' branch. We continue to implement the old behavior on previously released products to not confuse users, but on new printers like the Mini 2 we re-run the entire G29. This will be our preferred approach going forward.

**Comment by marcio-ao** [comment]
> However, there are several reasons G29() can leave without enabling bed leveling that have nothing to do with a failed probe (axes not homed, dry run, report, etc.)

@hexane360: True this. My implementation was done in a way to minimize changes to Marlin, since I never really know whether my changes will make it upstream, so I try to keep changes to a minimum and very localized at first as this makes it easier for me to carry the modifications if they are not incorporated upstream. This means that certain cases are handled incorrectly, as you correctly identified. I think having "G29()" return a bool to distinguish between a failed probe or something else makes sense to me and would improve the behavior of the retry and recover.

I don't think repeating individual probes is the way to go, however.

**Comment by hexane360** [comment]
I've changed the fix per the suggestions above. G29 is still routed through `G29_with_retry()`, but ABL's G29 now has `bool` returns (hidden by the preprocessor without `G29_RETRY_and_RECOVER`). Everything except a failed probe returns `true`, allowing `G29_with_retry` to only retry failed probes.

Modifying UBL's `G29()` will take a bit more doing, as the probing code is buried inside helper functions. I'm not really comfortable taking a stab at it because I'd have no way to test it.

I haven't had a chance to test this yet, but I should be able to tomorrow.

**Comment by thinkyhead** [comment]
Looks good. I like it. Kind of reminds me of my own macro-lovin' code style.

**Comment by thinkyhead** [comment]
One change: Classically, it's more common to return `true` as the error instead of `false`, and we've been moving more code in that direction. So I've just added a commit that inverts the return value.

**Comment by marcio-ao** [comment]
@hexane360: I don't really understand the need for the G29_RETURN macro. Is it really a performance gain to avoid returning a single boolean?

**Comment by hexane360** [comment]
@marcio-ao: It was more to make the change as unobtrusive as possible, by keeping the function exactly the same without `G29_RETRY_AND_RECOVER`. Especially because I expect very few people to use this feature. It also gives a clear indication in the code that the return values are only used by `G29_RETRY_AND_RECOVER`, and maintains symmetry with UBL and MBL's `G29()` implementations.

However, I can definitely see the perspective that it's more complicated a solution than is strictly necessary.

**Comment by marcio-ao** [comment]
@hexane360: Okay. And since @thinkyhead already chimed in that he likes macros, I guess I have to go along with it! :D

**Comment by thinkyhead** [comment]
Every byte counts. If the code is smaller by having a `void` return type, then it's good to save the bytes.

**Comment by marcio-ao** [comment]
> Every byte counts. If the code is smaller by having a void return type, then it's good to save the bytes.

If this were a global variable, I might be inclined to agree. But we're talking about a stack based variable here, so the overhead only exists momentarily (plus I suspect the compiler would optimize it away the return value if it wasn't used).

**Comment by thinkyhead** [comment]
I was referring to the size of the flashed binary.
