### PR TITLE
🩹 Fix ESP3D WiFi Support

### LINKED ISSUE #26786: [BUG] No ESP3D_WIFISUPPORT on ESP32 in 2.1.2.2 and bugfix-2.1.x
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Some change in `Configuration_adv.h`, in new version now no chance to enable `WEBSUPPORT`, `OTASUPPORT` on tinybee (`ESP3D_WIFISUPPORT`)
only change is `#if EITHER(WIFISUPPORT, ESP3D_WIFISUPPORT)` to now: `#if ENABLED(WIFISUPPORT)`
Code works fine but without webserver.
How to enable `WEBSUPPORT`, `OTASUPPORT` without errors?

In `2.1.2.2`:
```c
//#define WIFISUPPORT         // Marlin embedded WiFi management. Not needed for simple WiFi serial port.
#define ESP3D_WIFISUPPORT   // ESP3D Library WiFi management (https://github.com/luc-github/ESP3DLib)

/**
 * Extras for an ESP32-based motherboard with WIFISUPPORT
 * These options don't apply to add-on WiFi modules based on ESP32 WiFi101.
 */
#if ENABLED(WIFISUPPORT)
  #define WEBSUPPORT          // Start a webserver (which may include auto-discovery) using SPIFFS
  #define OTASUPPORT          // Support over-the-air firmware updates
  #define WIFI_CUSTOM_COMMAND // Accept feature config commands (e.g., WiFi ESP3D) from the host
  //AUTHENTICATION_FEATURE: protect pages by login password.
  #define AUTHENTICATION_FEATURE
  /**
   * To set a default WiFi SSID / Password, create a file called Configuration_Secure.h with
   * the following defines, customized for your network. This specific file is excluded via
   * .gitignore to prevent it from accidentally leaking to the public.
   *
   *   #define WIFI_SSID "WiFi SSID"
   *   #define WIFI_PWD  "WiFi Password"
   */
  //#include "Configuration_Secure.h" // External file with WiFi SSID / Password
#endif
```

in `2.1.2.1`:
```c
//#define WIFISUPPORT         // Marlin embedded WiFi management
#define ESP3D_WIFISUPPORT   // ESP3D Library WiFi management (https://github.com/luc-github/ESP3DLib)

#if EITHER(WIFISUPPORT, ESP3D_WIFISUPPORT)
  #define WEBSUPPORT          // Start a webserver (which may include auto-discovery)
  #define OTASUPPORT          // Support over-the-air firmware updates
  #define WIFI_CUSTOM_COMMAND // Accept feature config commands (e.g., WiFi ESP3D) from the host
  //AUTHENTICATION_FEATURE: protect pages by login password.
  #define AUTHENTICATION_FEATURE
  /**
   * To set a default WiFi SSID / Password, create a file called Configuration_Secure.h with
   * the following defines, customized for your network. This specific file is excluded via
   * .gitignore to prevent it from accidentally leaking to the public.
   *
   *   #define WIFI_SSID "WiFi SSID"
   *   #define WIFI_PWD  "WiFi Password"
   */
  //#include "Configuration_Secure.h" // External file with WiFi SSID / Password
#endif
```

### Bug Timeline

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

`2.1.2.2`

### Printer model

Creality Ender-3 Pro

### Electronics

mks-tinybee

### LCD/Controller

`CR10_STOCKDISPLAY`

### Other add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/14236649/Marlin.zip)

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

#26097 broke WiFi support for ESP3D on ESP32-based boards, so this PR brings back that functionality. See #26786 & https://github.com/luc-github/ESP3DLib/issues/75 for more information.

CC: @luc-github

### Requirements

ESP32-based motherboard with WiFi / ESP3DLib

### Benefits

WiFi will work on these boards again.

### Related Issues

- #26097
- https://github.com/luc-github/ESP3DLib/issues/75
- #26786

### CODE REVIEW

**Comment by EmVee381** [comment]
it works for me, thx. why is it not in branch??

**Comment by thisiskeithb** [comment]
> it works for me, thx. why is it not in branch??

Because this PR has not been merged yet.

**Comment by EmVee381** [comment]
> > it works for me, thx. why is it not in branch??
> 
> Because this PR has not been merged yet.

yes, but why ? :) i don't understand that, i am new in this, i see there are no conflicts message for two weeks. thx

**Comment by thisiskeithb** [comment]
> yes, but why ?

There are nearly 100 PRs in the queue and these things take time.

File: Marlin/src/inc/SanityCheck.h [hunk 1]
```diff
@@ -3929,11 +3929,11 @@ static_assert(_PLUS_TEST(3), "DEFAULT_MAX_ACCELERATION values must be positive."
...
   #endif
-#elif ENABLED(WIFI_CUSTOM_COMMAND)
+#elif ENABLED(WIFI_CUSTOM_COMMAND) && NONE(ESP3D_WIFISUPPORT, WIFISUPPORT)
   #error "WIFI_CUSTOM_COMMAND requires an ESP32 motherboard and WIFISUPPORT."
-#elif ENABLED(OTASUPPORT)
+#elif ENABLED(OTASUPPORT) && NONE(ESP3D_WIFISUPPORT, WIFISUPPORT)
   #error "OTASUPPORT requires an ESP32 motherboard and WIFISUPPORT."
-#elif defined(WIFI_SSID) || defined(WIFI_PWD)
+#elif (defined(WIFI_SSID) || defined(WIFI_PWD)) && NONE(ESP3D_WIFISUPPORT, WIFISUPPORT)
   #error "WIFI_SSID and WIFI_PWD only apply to ESP32 motherboard with WIFISUPPORT."
```
Comment (sjasonsmith) [inline Marlin/src/inc/SanityCheck.h:3937]: If these settings are indeed valid for ESP3D_WIFISUPPORT, then I think the comments should be updated to reflect `WIFISUPPORT or ESP3D_WIFISUPPORT`

File: Marlin/Configuration_adv.h [hunk 2]
```diff
@@ -4342,7 +4342,7 @@
  * Extras for an ESP32-based motherboard with WIFISUPPORT
  * These options don't apply to add-on WiFi modules based on ESP32 WiFi101.
  */
-#if ENABLED(WIFISUPPORT)
+#if ANY(WIFISUPPORT, ESP3D_WIFISUPPORT)
```
Comment (sjasonsmith) [inline Marlin/Configuration_adv.h:4345]: I am not familiar with Marlin's WiFi supoprt. Is the ESP32 WiFi101 mentioned in the comment related to WIFISUPPORT or ESP3D_WIFISUPPORT at all, or are those yet a third way to use WiFi?

Without knowing any better, a novice like me may assume that ESP32 WiFi101 is related to ESP3D_WIFISUPPORT. That is likely a bad assumption, meaning we could stand to improve the comments to make that harder to misinterpret.

Consider this optional and I welcome your thoughts on this.

Comment (thisiskeithb) [reply Marlin/Configuration_adv.h:4345]: WiFi101 is a discontinued Arduino shield that apparently needed some kind of special code changes to Marlin other than needing just a serial port enabled like most WiFi addons.

It's a constant source of confusion for users (See https://github.com/MarlinFirmware/Marlin/issues/26624), but my aim with this PR is to simply get ESP3D support on ESP-based motherboards working again.
