### PR TITLE
Fix for the Mini12864 and SD card access on the BTT SKR Mini E3 V3

### LINKED ISSUE #27103: [BUG] Mini 12864 on SKR Mini E3 V3 display issue
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I've attached a BGTHREETECH MINI 12864 V2.0 display board and knob to my BIGTREETECH SKR MINI E3 V3.0 control board via a SKR Mini Screen Adapter and the display operates normally until the SD card is accessed.  Once the menu to view the card is selected the display stops responding.  The SPI clock also stops being generated.  While this is happening I can issue a M21 command from the serial console and the card is detected and the files are listed, along with the brief reappearance of the SPI clock, but once it's done the display remains stuck.  Removing the SD card causes the LCD to reset and resume normal operation.

I've tried both the controller's onboard SD card slot and the SD card slot on the display and they both work, but they also both cause the display to stall.  The display's SD card slot was enabled by modifying the boards pins to use an extra I/O header for the SD chip select and card detect and setting the chip select line on the onboard SD card to high/disabled. It appears that accessing the SD card causes the display loop to jam for some reason.

If the printer is booted with an SD card inserted the Marlin logo appears and then the display locks up.  I can still talk to the controller via the serial connection.  The 'media inserted' text does display when a card is inserted into a slot and the screen keeps functioning normally, it's just when the directory is listed it stalls.

### Bug Timeline

New bug

### Expected behavior

The display should show a list of files and allow one to be selected.  On boot the normal status screen should appear.

### Actual behavior

The display gets stuck displaying it's last image until the SD card is removed.

### Steps to Reproduce

1. Boot with no SD card inserted.
2. Insert a SD card into either the onboard SD card slot or the display's SD card slot, depending on configuration.
3. Observe that the 'media detected' text appears at the bottom of the status display.
4. Enter the menu and try to list the files on the card via the display and control wheel.

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

it's a mix of a Solidoodle 2 Pro and Enter 3 parts

### Electronics

BTT SKR MINI E3 V3.0

### LCD/Controller

BTT MINI 12864 V2.0

### Other add-ons

SKR MINI SCREEN ADAPTER

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Repetier Host

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Configuration and pin dump attached. 
[config.zip](https://github.com/MarlinFirmware/Marlin/files/15368797/config.zip)

The board changes for the LCD SD card are:  
//The following block selects the onboard SD card.  Comment it out.
/*
#if SD_CONNECTION_IS(ONBOARD)
  #define SD_DETECT_PIN                     PC3
#elif SD_CONNECTION_IS(LCD) && (ALL(TOUCH_UI_FTDI_EVE, LCD_FYSETC_TFT81050) || IS_TFTGLCD_PANEL)
  #define SD_DETECT_PIN              EXP1_01_PIN
  #define SD_SS_PIN                  EXP1_05_PIN
#elif SD_CONNECTION_IS(CUSTOM_CABLE)
  #error "SD CUSTOM_CABLE is not compatible with SKR Mini E3."
#endif

#define ONBOARD_SPI_DEVICE                     1  // SPI1 -> used only by HAL/STM32F1...
#define ONBOARD_SD_CS_PIN                   PA4   // Chip select for "System" SD card
*/
//This points at the LCD SD cards new pins
#define SD_DETECT_PIN              PD5
#define ONBOARD_SD_CS_PIN          PD4

//The following line was added to the SPI setup for STM32
OUT_WRITE(EXP1_05_PIN, HIGH);

---

Pinout through the adapter and showing the two new connections:
screen adapter

### PR DESCRIPTION
**Pull request by RzTen1**
### Description

This fixes the issue if the Mini12864 screen going blank when an SD card is inserted. This changes the SPI code to add a slight wait state before activating the chip select as the SD card operates in mode 0 and the display operates in mode 3.  Normally the change happens too fast for the screen to pick up and won't clear until the display is reset on SD card removal.

This enables the use of the onboard SD card slot.  The SD card slot on the display can also be used as long as two additional wires for SD chip select and SD insertion detection are added and the pins defined.  This pull does not make the changes required for that.

### Requirements

A BTT Mini12864 v2.0, FYSETC Mini 12864 v2.1, or equivalent display.
A BTT SKR Mini E3 V3 motherboard.
A BTT SKR Mini Screen Adapter.

### Benefits

This allows the display to function when a SD card is inserted into the onboard SD card slot.

### Configurations

The following must be set:

```c
#define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V3_0
#define FYSETC_MINI_12864_2_1
#define SKR_MINI_SCREEN_ADAPTER
//the following are needed for the screen backlight
#define NEOPIXEL_LED
#define NEOPIXEL_TYPE NEO_RGB 
#define NEOPIXEL_PIXELS 3
#define NEOPIXEL_BRIGHTNESS 200
```

### Related Issues
- #27103

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Thanks for this PR!

There are some quirks with these Mini 12864 displays on some other STM32G0 boards like the Manta M4P (without adapter board) as well as the STM32F4-based BTT002, so I'll see if similar changes work for those configs.

> The SD card slot on the display can also be used as long as two additional wires for SD chip select and SD insertion detection are added and the pins defined. This pull does not make the changes required for that.

I can check this as well.

File: Marlin/src/HAL/STM32/dogm/u8g_com_stm32duino_swspi.cpp [hunk 1]
```diff
@@ -0,0 +1,139 @@
+/**
+ * Marlin 3D Printer Firmware
+ * Copyright (c) 2020 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
```
Comment (thisiskeithb) [inline Marlin/src/HAL/STM32/dogm/u8g_com_stm32duino_swspi.cpp]: This should be `(c) 2024`

Comment (RzTen1) [reply Marlin/src/HAL/STM32/dogm/u8g_com_stm32duino_swspi.cpp]: I've updated the date.

**Comment by RzTen1** [comment]
> Thanks for this PR!
> 
> There are some quirks with these Mini 12864 displays on some other STM32G0 boards like the Manta M4P (without adapter board) as well as the STM32F4-based BTT002, so I'll see if similar changes work for those configs.
> 
> > The SD card slot on the display can also be used as long as two additional wires for SD chip select and SD insertion detection are added and the pins defined. This pull does not make the changes required for that.
> 
> I can check this as well.

Welcome and thanks!  I suspect that this may apply to other boards with the similar processors but I've only got the one.  I think the STM32F might need more work.  When I was poking through there it looked like code for software SPI hadn't been written yet.  I played around with the hardware SPI mode briefly on mine and I think the issue there is similar, it's just too fast, but I wasn't able to get the clock divider working.  Every time I requested a lower frequency the scope kept reporting that the SPI bus was running over 4Mhz.  Software SPI never appears to exceed 1Mhz.  Approximately anyway, the intermittent nature of the clock signal made locking onto it a real pain.

**Comment by RzTen1** [comment]
Actually this may be a bit premature. It looks like the screen is still stalling out on some SD card reads. I'm able to clear the screen by hitting the button, but I have to do it after every card read when it's printing. Let me dig into it a bit more. It's still better than it was but I wouldn't call it fixed.

**Comment by RzTen1** [comment]
Well, I feel silly.  I had assumed forcing the LCD into software SPI mode put everything into software SPI mode, it does not.  My issue was due to the SD card enabling hardware SPI, which breaks software SPI as it won't let it drive the pins while hardware's grabbed it.  I've added a tweak to the HAL for the STM32 so that if the LCD is in software mode everything else is as well.  My tests are all working now so we should be good to go.

File: Marlin/src/HAL/STM32/u8g/LCD_defines.h [hunk 2]
```diff
@@ -25,8 +25,13 @@
  * STM32 LCD-specific defines
  */
 
-uint8_t u8g_com_std_sw_spi_fn(u8g_t *u8g, uint8_t msg, uint8_t arg_val, void *arg_ptr);         // See U8glib-HAL
-uint8_t u8g_com_stm32duino_hw_spi_fn(u8g_t *u8g, uint8_t msg, uint8_t arg_val, void *arg_ptr);  // See U8glib-HAL
+#if ALL(HAS_MARLINUI_U8GLIB, FORCE_SOFT_SPI)
```
Comment (thisiskeithb) [inline Marlin/src/HAL/STM32/u8g/LCD_defines.h:28]: I don't think this is ever true due to file include order.

One of the problematic hardware configurations I have (and was hoping this PR would help) is on a BIQU Hurakan with a `BTT_MINI_12864` & , `BOARD_BTT_MANTA_M4P_V2_1` (STM32G0). Both `HAS_MARLINUI_U8GLIB` & `FORCE_SOFT_SPI` are set elsewhere, but they don't appear to be true at the same time ahead of this (`LCD_defines.h`) file.

I threw in some warnings as a check:

image

In either case, it doesn't fix the SPI issues I'm having with this LCD/hardware combination, but I thought I'd mention it.

Comment (thisiskeithb) [inline Marlin/src/HAL/STM32/u8g/LCD_defines.h]: Does this work as intended?

One of the problematic hardware configurations I have (and was hoping this PR would help) is on a BIQU Hurakan with a `BTT_MINI_12864` & `BOARD_BTT_MANTA_M4P_V2_1` (STM32G0), so I gave this PR a try.

Both `HAS_MARLINUI_U8GLIB` & `FORCE_SOFT_SPI` are set elsewhere, but both are true...and not... ahead of this (`LCD_defines.h`) file due to file include order(?).

I threw in some errors as a check:

image

Both of my errors show up in the terminal.

In either case, it doesn't fix the SPI issues I'm having with this LCD/hardware combination (bummer!), but I thought I'd mention it.

Comment (RzTen1) [reply Marlin/src/HAL/STM32/u8g/LCD_defines.h]: Yeah, that's my fault. I was being overly paranoid and added that at the last minute and didn't notice it wasn't matching.  I just removed that entire #if block, we shouldn't need it anyway as the only libraries it's overriding are the ones for the display anyway.  Does that look any better for that board and display combo now?

Comment (RzTen1) [reply Marlin/src/HAL/STM32/u8g/LCD_defines.h]: Also just to double check: you should be getting a screen with random dots at least on powerup if everything is wired correctly.  On my BTT display the plugs were upside down and the arrow that normally points at pin 1 points at pin 10 instead.  I had to wiggle the plugs off and put them back on backwards before it'd work.  The FYSEC display I have had them facing the right direction out of the box.

Comment (thisiskeithb) [reply Marlin/src/HAL/STM32/u8g/LCD_defines.h]: > Does that look any better for that board and display combo now?

There's no change in the M4P/Mini 12864 display behavior with this PR, so it's probably something else.

> Also just to double check: you should be getting a screen with random dots at least on powerup if everything is wired correctly. 

Yep, no issues there since the Manta M4P has two EXP connectors.

> On my BTT display the plugs were upside down and the arrow that normally points at pin 1 points at pin 10 instead. I had to wiggle the plugs off and put them back on backwards before it'd work. The FYSEC display I have had them facing the right direction out of the box.

No one can agree on what is Pin 1, so it's common to rotate EXP cables 180° when using mixed & matched hardware. Most of my EXP cables have the tabs cut off because of it 😄

Comment (RzTen1) [reply Marlin/src/HAL/STM32/u8g/LCD_defines.h]: Just wondering: does the SD card slot work on your display?

Comment (thisiskeithb) [reply Marlin/src/HAL/STM32/u8g/LCD_defines.h]: > does the SD card slot work on your display?

Sort of.

The screen doesn't update and requires the encoder to be pressed to "refresh" the screen. This initially happens after displaying the Marlin & custom boot logos and status screen doesn't show / appears frozen, but clicking the encoder refreshes the screen. Inserting an SD card into the LCD's SD card reader shows "Media Inserted" on the status screen, but the screen will lock up if I try to access the SD card until I remove it. Once the SD card is removed, the screen "works" again.

Setting `SDCARD_CONNECTION` to `ONBOARD` doesn't work at all. In fact, the motherboard reboots when you insert an SD card to the onboard SD slot.

Note: The Manta series of boards were designed with Klipper in mind originally, but Marlin support was ported to them, so some quirks are not unexpected. Speaking of Klipper, inserting an SD card into the onboard SD slot does not cause the motherboard to reboot, but Klipper doesn't use the onboard SD slot for anything, so 🤷

Comment (RzTen1) [reply Marlin/src/HAL/STM32/u8g/LCD_defines.h]: That's exactly what mine was doing when the SD card was stuck in hardware SPI mode.  Would you mind adding '#define SOFTWARE_SPI' into your pins or configuration file to see if that makes a difference?  That one line change to the HAL file should have kicked it out of hardware mode but maybe it's not getting set for some reason. It's also possible you pulled it before I added that as I did that change kind of late, in which case just updating HAL_SPI.cpp should fix it but it's still possible you have a new issue.

Comment (thisiskeithb) [reply Marlin/src/HAL/STM32/u8g/LCD_defines.h]: Behavior is the same, so I'll stop hijacking your PR 😄

I'll open a proper bug report for this at some point, but not many people are running Marlin on this hardware combination for it to be an issue apparently.

**Comment by thinkyhead** [comment]
This would be a good opportunity to make some tweaks to clarify the difference between `SOFTWARE_SPI` and `FORCE_SOFT_SPI`, as sometimes a pins file will define one or the other, and it isn't clear which one should be used. It may be that we should always use `FORCE_SOFT_SPI`, since `SOFTWARE_SPI` is also defined by `HAL/**/spi_pins.h` for cases where the defined SPI pins don't correspond to the hardware SPI pins, or where the pins are shared between a DOGLCD and an SD card.

The question is, does Marlin (almost) always look for `ANY(SOFTWARE_SPI , FORCE_SOFT_SPI)`, or does it make a distinction sometimes? If there is a consistent distinction, then one of these defines might benefit from being renamed for more clarity. If there isn't a real distinction, then maybe `FORCE_SOFT_SPI` should just cause `SOFTWARE_SPI` to be defined.

Anyway, there's an LCD Pins Refactoring PR in progress which would be tripped up by making any big change to these defines in the pins files, so any big cleanup of this area can wait till after that gets merged.

**Comment by MCFFHAB** [comment]
I am having a problem with this commit - please see #27221 - To resolve my problem outlined on #27221 I reverted the commit for "SW SPI Mode 3 for U8G on STM32 (#27111)" and now all works well.  I did apply all other commits that were introduced at the same time: "U8G_SPI_USE_MODE_3 for *_MINI_12864", "USE_SOFTWARE_SPI => SDFAT_USE_SOFTWARE_SPI", "Misc. SPI cleanup".  All of these did not create a problem.
