### PR TITLE
Fix MKS Nano V1.2 FSMC Display

### LINKED ISSUE #18899: [BUG?] FSMC_GRAPHICAL_TFT on BOARD_MKS_ROBIN_NANO: Backlight pin redefined
Board: MKS Robin Nano 1.2 (environment mks_robin_nano35)

When compiling the current bugfix version (2465f2fd746169bca31ec43a956211bed15839c6) with #define TFT_LVGL_UI_FSMC, everything works. When I don't define TFT_LVGL_UI_FSMC but FSMC_GRAPHICAL_TFT, I get constant compiler warnings during compilation, like this:

```
Marlin/src/gcode/bedlevel/../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO.h:229:0: warning: "LCD_BACKLIGHT_PIN" redefined
 #define LCD_BACKLIGHT_PIN -1
 
Marlin/src/gcode/bedlevel/../../inc/../pins/stm32f1/pins_MKS_ROBIN_NANO.h:211:0: note: this is the location of the previous definition
 #define LCD_BACKLIGHT_PIN PD13
```

After restarting the printer it hangs at the "Booting..." screen. A serial connection can not be established.

I'm using a vanilla Configuration.h and pins_MKS_ROBIN_NANO.h, with just a few things changed in Configuration.h:

```
#define SERIAL_PORT 3
#define BAUDRATE 115200
#define MOTHERBOARD BOARD_MKS_ROBIN_NANO
#define FSMC_GRAPHICAL_TFT
```

The warnings will go away when I comment out the #if HAS_SPI_LCD section in pins_MKS_ROBIN_NANO.h, but it still hangs at the "Booting..." screen.

So why does it assume I have an SPI display? I didn't #define it anywhere. 

I'd call that a bug, because I'd expect to be able to choose between FSMC_GRAPHICAL_TFT and TFT_LVGL_UI_FSMC on the Robin Nano 1.2, not be forced to use TFT_LVGL_UI_FSMC. I mean it's a nice addition, but right now it's missing some menus I need.

I guess that this problem is also the reason why the screen won't work anymore with my non-vanilla bugfix-2.0.x (with pins file modified for UART etc.), starting with this commit: https://github.com/MarlinFirmware/Marlin/commit/38ce5966e19094fb499ce7d647961c0594c5f811

Before that commit I could simply comment out the #if HAS_SPI_LCD section to get rid of the warnings and it would work. The compiler warning spam started with my merge on June 25th, I guess it was caused by this commit (but I didn't try to pinpoint it):
https://github.com/MarlinFirmware/Marlin/commit/d20d4591321aa467c062f0050355d2aca84e03ad

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

- Fix compiling warnings and the FSMC display for MKS Nano v1.2
- Add 3x upscale support for NON-DMA TFT
- Fix the 0x8066 init code
- Removed non supported displays that were add to nano board by mistake
- Re-enabled DMA for FSMC_GRAPHICAL_TFT for nano v1.2

### Benefits

Fix #18899

### CODE REVIEW

File: Marlin/src/lcd/dogm/u8g_dev_tft_320x240_upscale_from_128x64.cpp [hunk 1]
```diff
@@ -650,7 +650,7 @@ uint8_t u8g_dev_tft_320x240_upscale_from_128x64_fn(u8g_t *u8g, u8g_dev_t *dev, u
           lcd_id = 0;
           return 0;
         default:
-          setWindow = (lcd_id & 0xFF000000) ? setWindow_st7789v : setWindow_ili9328;
+          setWindow = (lcd_id && 0xFF000000) ? setWindow_st7789v : setWindow_ili9328;
```
Comment (GMagician) [inline Marlin/src/lcd/dogm/u8g_dev_tft_320x240_upscale_from_128x64.cpp]: Sure it's right? `something && 0xFF000000` is same thing than testing just `something` since 0xFF000000 is always true

Comment (GMagician) [reply Marlin/src/lcd/dogm/u8g_dev_tft_320x240_upscale_from_128x64.cpp]: If warning is about sign/unsigned maybe a (lcd_id & 0xFF000000U) may fix

Comment (rhapsodyv) [reply Marlin/src/lcd/dogm/u8g_dev_tft_320x240_upscale_from_128x64.cpp]: The original marlin code uses &&. A few days ago, @thinkyhead saw that `&&` and changed to `&`. We all thought it won't be a problem.
But seems some displays are working because that if were __always true__ .. heheh.. So, now, for a test, I just put back the *original code*...
If it work for the user, I will try to find the LCD_ID of his display to properly handle it the switch.

Comment (GMagician) [reply Marlin/src/lcd/dogm/u8g_dev_tft_320x240_upscale_from_128x64.cpp]: If it works this way then you may simply write:
`setWindow = lcd_id ? setWindow_st7789v : setWindow_ili9328;`
or
`setWindow = (lcd_id != 0) ? setWindow_st7789v : setWindow_ili9328;`
if some warning appears

Comment (rhapsodyv) [reply Marlin/src/lcd/dogm/u8g_dev_tft_320x240_upscale_from_128x64.cpp]: Thanks. But I know how to do a `if`. As I said: I just put back the original code.

Comment (GMagician) [reply Marlin/src/lcd/dogm/u8g_dev_tft_320x240_upscale_from_128x64.cpp]: I'm sorry was not to offend you, just that what I proposed remove any doubt about the code. Everyone reading such code may think that && is wrong and change it with a &, as @thinkyhead did

Comment (rhapsodyv) [reply Marlin/src/lcd/dogm/u8g_dev_tft_320x240_upscale_from_128x64.cpp]: No problem. That won’t be the final code. It’s just for the user test. I went back to the original code to be easy to reasoning about the problem, as he said that worked before.

All points the we must remove the if... because if the “always true branch” is correct, we can keep only that path... 

Don’t worry. That abomination won’t be merged that way.

**Comment by thisiskeithb** [comment]
Per our discussion on Discord, I'm getting a half black/half white (fuzzy) screen and the board isn't usable with `FSMC_GRAPHICAL_TFT`:

image

[Link to Tevo Nereus config with fixes from this PR](https://github.com/thisiskeithb/Marlin/tree/testing/tevo-nereus-fsmc).

**Comment by rhapsodyv** [comment]
I found the problem. FSMC_UPSCALE 3x was never implemented for a NON-DMA display, line Nano v1.2. I will work on that.

**Comment by Miraculix200** [comment]
> 
> 
> I found the problem. FSMC_UPSCALE 3x was never implemented for a NON-DMA display, line Nano v1.2. I will work on that.

This is what I use in my currently working config (before the commits in the past few days)
  #define LCD_USE_DMA_FSMC
  #define FSMC_DMA_DEV DMA2
  #define FSMC_DMA_CHANNEL DMA_CH5

https://github.com/Miraculix200/Marlin-SapphirePro-2209-UART/blob/289425c9abb01d1fd082c85a7974b58552a8aced/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_NANO.h#L198

Don't remember where I got that from.

**Comment by Miraculix200** [comment]
Ok, getting there. With LCD_RESET_PIN commented out and these lines added I get a working display. Though the touchscreen seems to freak out. It acts as if it is getting randomly touched.

#define LCD_USE_DMA_FSMC
#define FSMC_DMA_DEV DMA2
#define FSMC_DMA_CHANNEL DMA_CH5

I'll try again with these changes reverted, with commit 280bded  merged

**Comment by rhapsodyv** [comment]
> Ok, getting there. With LCD_RESET_PIN commented out and these lines added I get a working display. Though the touchscreen seems to freak out. It acts as if it is getting randomly touched.
> 
> #define LCD_USE_DMA_FSMC
> #define FSMC_DMA_DEV DMA2
> #define FSMC_DMA_CHANNEL DMA_CH5
> 
> I'll try again with these changes reverted, with commit [280bded](https://github.com/MarlinFirmware/Marlin/commit/280bdeddc5d3a3f44a0f247e36650b9e7ef5b881) merged


Now we found!  MKS removed that DMA settings from they nano board. And the NON-DMA never was implemented for FSMC_UPSCALE 3x.
The two things together, blew up.

**Comment by Miraculix200** [comment]
> I'll try again with these changes reverted, with commit [280bded](https://github.com/MarlinFirmware/Marlin/commit/280bdeddc5d3a3f44a0f247e36650b9e7ef5b881) merged

Reverting the DMA #defines I made doesn't produce a working display with 280bded

**Comment by thisiskeithb** [comment]
The latest changes in this PR  plus:

```cpp
#define LCD_USE_DMA_FSMC                        // Use DMA transfers to send data to the TFT
#define FSMC_DMA_DEV                      DMA2
#define FSMC_DMA_CHANNEL               DMA_CH5 
```
Produces:

image

**Comment by Miraculix200** [comment]
> Produces:

Could be caused by LCD_RESET_PIN not being commented out?

**Comment by Miraculix200** [comment]
R0038791
This is what I get with LCD_RESET_PIN defined (and the DMA defines included)

**Comment by Miraculix200** [comment]
Well.... with LCD_RESET_PIN defined I get a green display. But it works.

With LCD_RESET_PIN commented out I get a normal looking display, but the touch screen is freaking out, acting as if it is getting touched on the enter button twice per second or so. When I use the down arrow while it's in the menu screen, I can stop it for a while. But then it starts again

**Comment by Miraculix200** [comment]
The green display seems to be slightly flickering. As if it was the wrong update frequency? Or maybe it's just more visible because it's green. 

Also, when turning the printer on I first get a green bar above the enter button. Without any text displayed, only the touch buttons. After a while the info screen appears.

**Comment by rhapsodyv** [comment]
> The green display seems to be slightly flickering. As if it was the wrong update frequency? Or maybe it's just more visible because it's green.
> 
> Also, when turning the printer on I first get a green bar above the enter button. Without any text displayed, only the touch buttons. After a while the info screen appears.

Do you have TFT 3.5 or 2.8/2.4?

**Comment by thisiskeithb** [comment]
> Do you have TFT 3.5 or 2.8/2.4?

Pretty sure the Nano 1.2 only comes with the TFT35.

**Comment by Miraculix200** [comment]
> Do you have TFT 3.5 or 2.8/2.4?

3.5

**Comment by Miraculix200** [comment]
I have to add that I've been using it with LCD_RESET_PIN commented out in the past months. 

Maybe the touch screen freaking out with LCD_RESET_PIN commented out is not related to this display issue, but to the recent changes that have been made to touch buttons.

**Comment by rhapsodyv** [comment]
> I have to add that I've been using it with LCD_RESET_PIN commented out in the past months.
> 
> Maybe the touch screen freaking out with LCD_RESET_PIN commented out is not related to this display issue, but to the recent changes that have been made to touch buttons.

with the lasts commits, are you able to connect to the serial? If so, can you send me LCD ID that is show there?

**Comment by rhapsodyv** [comment]
@Miraculix200  I isolated the FSMC configs as were before. Can you test the last commit?

**Comment by thisiskeithb** [comment]
It works now!

image

**Comment by thisiskeithb** [comment]
I don't know why the original Nano V1.2 pins file has `MKS_MINI_12864` pins defined since the Nano v1.2 only has a single 32-pin "flat flexible"/ribbon ZIF connector for the included (tethered) LCD & it has zero EXP connectors/pins: [MKS%20Robin%20Nano%20V1.1_001%20PIN.pdf](https://github.com/makerbase-mks/MKS-Robin-Nano/blob/master/hardware/MKS%20Robin%20Nano%20V1.1_001/MKS%20Robin%20Nano%20V1.1_001%20PIN.pdf)

**Comment by rhapsodyv** [comment]
@thisiskeithb I removed the non supported displays and enabled back the DMA. Can you test again?

I think we finished.

**Comment by thisiskeithb** [comment]
> I removed the non supported displays and enabled back the DMA. Can you test again?
> 
> I think we finished.

Everything still works. Great work!

**Comment by Miraculix200** [comment]
Works for me too. Well done. 

I'd suggest to remove the SPI section in pins_MKS_ROBIN_NANO.h, because there is no possibility to connect an SPI display to Robin Nano version 1.x. And version 2.0 has its own pins file.

**Comment by thinkyhead** [comment]
> suggest to remove the SPI section

Do you refer to `TFT_LVGL_UI_SPI` ?

**Comment by rhapsodyv** [comment]
> > suggest to remove the SPI section
> 
> Do you refer to `TFT_LVGL_UI_SPI` ?

No. I already removed.

We are talking about that LCD: MKS_MINI_12864

**Review by rhapsodyv — COMMENTED** [review]
Ok, that can be removed too.

**Comment by rhapsodyv** [comment]
Nano only have FSMC. LVGL and FSMC_GRAPHICAL interface.

**Comment by neoxm3** [comment]
@rhapsodyv   for me the latest commit is not working.,..

FLSUN Q5 with mks robin nano v1.2 + tft mks 3.5 , i have in the configuration file:
- #define MOTHERBOARD BOARD_MKS_ROBIN_NANO
- #define FSMC_GRAPHICAL_TFT

and this is the result (atached image)
IMG_20200809_193307

**Comment by rhapsodyv** [comment]
@neoxm3 are you using the last bugfix?

**Comment by neoxm3** [comment]
@rhapsodyv  yes, downloaded today... I tryed to comment the lcd reset pin, but no difference

**Comment by rhapsodyv** [comment]
TFT 2.4/2.8/3.5? 

If is less than 3.5, you need to set `FSMC_UPSCALE 2`

**Comment by rhapsodyv** [comment]
In fact, you need to configura all this:
```
  #ifndef FSMC_UPSCALE
    #define FSMC_UPSCALE                    3
  #endif
  #ifndef LCD_FULL_PIXEL_WIDTH
    #define LCD_FULL_PIXEL_WIDTH            480
  #endif
  #ifndef LCD_PIXEL_OFFSET_X
    #define LCD_PIXEL_OFFSET_X              48
  #endif
  #ifndef LCD_FULL_PIXEL_HEIGHT
    #define LCD_FULL_PIXEL_HEIGHT           320
  #endif
  #ifndef LCD_PIXEL_OFFSET_Y
    #define LCD_PIXEL_OFFSET_Y              32
  #endif
```

as defaults are set to 3.5 display

**Comment by neoxm3** [comment]
I am going to try, i didnt dismounted the lcd but now seeing it more slowly,  i am not secure that this is a 3.5 tft... It is more like 3 - 2.8,, thanks for the clue!

**Comment by neoxm3** [comment]
omg! solved! very thanks @rhapsodyv 
with this options:

 #ifndef FSMC_UPSCALE
    #define FSMC_UPSCALE                    2
  #endif
  #ifndef LCD_FULL_PIXEL_WIDTH
    #define LCD_FULL_PIXEL_WIDTH            320  //480
  #endif
  #ifndef LCD_PIXEL_OFFSET_X
    #define LCD_PIXEL_OFFSET_X              48
  #endif
  #ifndef LCD_FULL_PIXEL_HEIGHT
    #define LCD_FULL_PIXEL_HEIGHT           240   //320
  #endif
  #ifndef LCD_PIXEL_OFFSET_Y
    #define LCD_PIXEL_OFFSET_Y              32
  #endif

now, my only problem is that i have the  tft inverted... :P
i can flip the screen with:
 #define LCD_SCREEN_ROT_180

but the touch buttons are not flipped... :P and remains in top

**Comment by rhapsodyv** [comment]
You can put it direct to you Configuration.h
```
#define FSMC_UPSCALE 2
#define LCD_FULL_PIXEL_WIDTH 320 
#define LCD_PIXEL_OFFSET_X 48
#define LCD_FULL_PIXEL_HEIGHT 240
#define LCD_PIXEL_OFFSET_Y 32
```
For rotation, try:
```
#define GRAPHICAL_TFT_ROTATE_180
```

**Comment by neoxm3** [comment]
> 
> 
> You can put it direct to you Configuration.h
> 
> ```
> #define FSMC_UPSCALE 2
> #define LCD_FULL_PIXEL_WIDTH 320 
> #define LCD_PIXEL_OFFSET_X 48
> #define LCD_FULL_PIXEL_HEIGHT 240
> #define LCD_PIXEL_OFFSET_Y 32
> ```
> 
> For rotation, try:
> 
> ```
> #define GRAPHICAL_TFT_ROTATE_180
> ```

#define GRAPHICAL_TFT_ROTATE_180 (only this) doesnt rotate the screen in my case.

#define LCD_SCREEN_ROT_180 yes but not the touch buttons.

thanks!

**Comment by rhapsodyv** [comment]
You need better `XPT2046_*` calibration values. Try swapping the signal from `XPT2046_X_CALIBRATION` and `XPT2046_Y_CALIBRATION`

**Comment by meteozond** [comment]
@rhapsodyv could touchscreen (not display) be mirrored with XPT2046_X_CALIBRATION settings?
