### PR TITLE
Fix printing pauses with FTM_DIR_CHANGE_HOLD

### LINKED ISSUE #28274: [BUG] A brief pause after 12 minutes of printing, with the X, Y, and E axes stopping and an unusual sound.
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The printer stops for a split second in the middle of printing a straight line on the very first layer 12 minutes after starting printing. After the pause, printing continues without any layer shift. The pause is accompanied by a sound, probably from one of the motors (it has been established that the LCD speaker has nothing to do with the sound).

The pause always occurs at the 12th minute of printing and then every 10 minutes thereafter, i.e. at the 22nd minute, the 32nd minute, and so on.

This is only observed when using UBL. When UBL is disabled (in the file with the G29 D command, not in the firmware), printing proceeds completely without pauses or sounds for the entire 3 hours.

### Bug Timeline

_No response_

### Expected behavior

I assume printing using bed levelling

### Actual behavior

Unhealthy pause

### Steps to Reproduce

Print attached file.

[test-ears.gcode.zip](https://github.com/user-attachments/files/24559228/test-ears.gcode.zip)

### Version of Marlin Firmware

Marlin bugfix-2.1.x (Jan 12 2026 09:35:29) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:2MHz/1000 KINEMATICS:Cartesian EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Printer model

Voxelab Aquila

### Electronics

Motherboard Creality 4.2.7

### LCD/Controller

dwin

### Other add-ons

_No response_

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[cfgs-new-issue.zip](https://github.com/user-attachments/files/24559252/cfgs-new-issue.zip)

### PR DESCRIPTION
**Pull request by dbuezas**
Fixes #28274
Also brings back the defines to configuration_adv.h since this timing fix shouldn't be applied for spreadcycle (and we can't know the driver mode in standalone mode, since it may be configured via jumperpads)

### CODE REVIEW

**Comment by Nuck-TH** [comment]
why last_target_traj.e is conditioned to only update when timing fix enabled?

**Comment by dbuezas** [comment]
You're right.

File: Marlin/Configuration_adv.h [hunk 1]
```diff
@@ -1238,6 +1238,29 @@
...
+   *
+   * Enable on axes that use stealthchop and if you notice that motor turns off during print,
+   * typically only necessary on E.
+   *
+   * TMC2208 / TMC2208_STANDALONE drivers may require a short delay after a DIR change
+   * to prevent a standstill error when using stealthChop (the standalone default).
+   * When enabled, FT Motion will hold that axis still for > 750µs after a DIR change.
+   */
+  #if AXIS_DRIVER_TYPE_X(TMC2208) || AXIS_DRIVER_TYPE_X(TMC2208_STANDALONE)
+    //#define FTM_DIR_CHANGE_HOLD_X 1
```
Comment (thinkyhead) [inline Marlin/Configuration_adv.h]: I really don't like exposing these and putting the onus on the user to figure out what is safe. We should ensure that the basic default is overly-conservative so that users are not given the first impression that FTM is just broken.

Comment (dbuezas) [reply Marlin/Configuration_adv.h]: That's what the new comment was for, not all 2208 need the fix that deviates from ideal trajectory.

Comment (dbuezas) [reply Marlin/Configuration_adv.h]: Oh, I see you just made the default to enabled, 👍
