### PR TITLE
Tramming wizard usability improvements

### LINKED ISSUE #22201: [BUG] Assisted tramming wizard "Left-Front" bug
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

** Assisted Tramming Wizard ** BL Touch V3.1** LCD function to display measurement deviations has a bug. Have been trying multiple firmware versions for quite some time, bug fixes and none bugfixes all have the same problem. When sending probe to "Left-Front" on LCD screen and probing for the measurement, it does not report back the measurement deviation to the LCD screen. Instead, it displays 0 until I switch to a different corner and before taking that new measurement, seeing the last measurement in the LCD screen, then switch back to re-probe, and back and forth etc. to level that specific corner "Front-Left". Have no problems with any of the other corners just always that corner. Also have to spin my adjustment knob in the opposite direction in comparison to the others to level according to the last deviation reported for 'Front-Left'.

### Bug Timeline

No, this has always been happening 

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

2.0.x

### Printer model

ender 5

### Electronics

_No response_

### Add-ons

BL Touch V3.1

### Your Slicer

Cura

### Host Software

_No response_

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

This makes two changes to ASSISTED_TRAMMING_WIZARD:
1. Allow any point to be probed first and become the reference point. Previously you had to start with the first point in the list.
2. Do not show "Last value" if the point has not yet been probed. Previously you would see non-zero values here before probing the point, because "reference - 0.0" resulted in a non-zero number.

On a mega2560, these changes increase RAM usage by 5 bytes and FLASH usage by 92 bytes.

### Requirements

ASSISTED_TRAMMING_WIZARD

### Benefits

Somewhat more intuitive usage.

### Configurations

These are for a very non-stock MakerGear M2 with these features enabled:
[Modified_M2.zip](https://github.com/MarlinFirmware/Marlin/files/7071381/Modified_M2.zip)

### Related Issues

#22201

### CODE REVIEW

File: Marlin/src/lcd/menu/menu_tramming.cpp [hunk 1]
```diff
@@ -94,6 +98,11 @@ void goto_tramming_wizard() {
   set_all_unhomed();
   queue.inject_P(TERN(CAN_SET_LEVELING_AFTER_G28, PSTR("G28L0"), G28_STR));
 
+  // Initialize measured values to NAN so we will know if they have been measured.
+  // LOOP_L_N(i, G35_PROBE_COUNT) z_measured[i] = (float)NAN;
```
Comment (sjasonsmith) [inline Marlin/src/lcd/menu/menu_tramming.cpp]:
```suggestion
  // Initialize points to invalid so we will know if they have been measured.
```

File: Marlin/src/lcd/menu/menu_tramming.cpp [hunk 2]
```diff
@@ -39,8 +39,10 @@
 //#define DEBUG_OUT 1
 #include "../../core/debug_out.h"
 
-float z_measured[G35_PROBE_COUNT] = { 0 };
+static float z_measured[G35_PROBE_COUNT];
+static bool z_isvalid[G35_PROBE_COUNT];
```
Comment (sjasonsmith) [inline Marlin/src/lcd/menu/menu_tramming.cpp:43]: My initial implementation initialized z_measured to NAN, but I found that the isnan() calls are **very** expensive. Using separate flag variables reduced FLASH usage by 38 bytes, although it did increase RAM usage by a few bytes.

If 3 bytes of RAM is more important than 38 bytes of FLASH, we could easily revert the commit where I made the switch.

File: Marlin/src/lcd/menu/menu_tramming.cpp [hunk 3]
```diff
@@ -94,6 +98,10 @@ void goto_tramming_wizard() {
   set_all_unhomed();
   queue.inject_P(TERN(CAN_SET_LEVELING_AFTER_G28, PSTR("G28L0"), G28_STR));
 
+  // Initialize points to invalid so we will know if they have been measured.
+  LOOP_L_N(i, G35_PROBE_COUNT) z_isvalid[i] = false;
```
Comment (thinkyhead) [inline Marlin/src/lcd/menu/menu_tramming.cpp]: `ZERO(z_isvalid)` would also be fine here, but I'm not sure whether it results in smaller code. Probably the compiler knows to convert `memset` into a small loop in some cases.

File: Marlin/src/lcd/menu/menu_tramming.cpp (hunk 2 above)
Comment (thinkyhead) [reply Marlin/src/lcd/menu/menu_tramming.cpp:43]: It's okay if `isnan()` is slow. It is surprising that it would cost 38 bytes more than adding an array and accompanying logic. According to my initial review of the code here, the array is initialized to `false` but I don't see anyplace where elements are being set to `true`.

File: Marlin/src/lcd/menu/menu_tramming.cpp (hunk 3 above)
Comment (thinkyhead) [reply Marlin/src/lcd/menu/menu_tramming.cpp]: As mentioned above, there doesn't seem to be any place where `z_isvalid[...]` is being set to `true`. Has this new code actually been tested?

**Comment by thinkyhead** [comment]
Tweaked the code to set `z_isvalid[tram_index]` to `true` when a probe measurement succeeds. Got rid of the global `tram_index` since it is a passed argument.

**Comment by thinkyhead** [comment]
The text of `MSG_LAST_VALUE_SP` "Last value" might be misleading or ambiguous. It will always show "0" for the reference point, and the difference (i.e., error) for others. Maybe "Last offset" or "Last error" would be better.

**Comment by sjasonsmith** [comment]
I thought I had tested the final product, but after reading your comments I must have either not tested it or messed up when I rebased it to remove my printer config.

I can probably test it out again tonight. I’m on my phone so it’s not easy for me to see what all you changed.

Personally I would prefer to receive your feedback and be able to investigate and fix issues myself. Once you’ve changed a bunch of stuff it is no longer “my code” that I’ve invested time in writing/testing.

**Comment by thinkyhead** [comment]
Your code is still preserved, as this has not been rebased. If you need guidance on cherry-picking commits or on checking out earlier commits feel free to hit me up on Discord.

**Comment by sjasonsmith** [comment]
It looks like I just got so caught up in comparing sizes that I simply did not test the latest revision.

**Comment by thinkyhead** [comment]
Oops, I pushed the wrong commit to `bugfix-2.0.x` while merging changes, so this is not actually merged. If you start another PR from the same branch (`PR/Tramming_Wizard_Origin`) then this can be continued on the new PR.

**Comment by thinkyhead** [comment]
PR #22671 is good to go…

**Comment by sjasonsmith** [comment]
Additional size comparisons after adding the missing flag set:

Using NAN instead of separate flags still increases size by ~36 bytes.

Switching to bit flags instead of byte flags decreases RAM by (points - 1) bytes, but increases FLASH by about 50 bytes.

I'll go ahead and test and will open a new PR if additional changes are needed.
