### PR TITLE
Fix mismatched conditional and default override include order

### LINKED ISSUE #20582: [BUG] FTDI EVE fails to build with AUTO_BED_LEVELING_BILINEAR
BOARD_FYSETC_S6_V2_0
LCD_FYSETC_TFT81050
S6_TFT_PINMAP

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5747102/Marlin.zip)

Linking .pio/build/FYSETC_S6/firmware.elf
/home/lino/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: .pio/build/FYSETC_S6/src/src/lcd/extui/lib/ftdi_eve_touch_ui/marlin_events.cpp.o: in function `ExtUI::onMeshUpdate(signed char, signed char, float)':
/home/lino/Drucker/fysetc_s6/Firmware/Marlin_2.0.8/Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/marlin_events.cpp:144: undefined reference to `BedMeshScreen::onMeshUpdate(signed char, signed char, float)'
/home/lino/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: .pio/build/FYSETC_S6/src/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/screens.cpp.o:(.rodata._ZN9ScreenRef13functionTableE+0x340): undefined reference to `BedMeshScreen::onEntry()'
/home/lino/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: .pio/build/FYSETC_S6/src/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/screens.cpp.o:(.rodata._ZN9ScreenRef13functionTableE+0x350): undefined reference to `BedMeshScreen::onRedraw(draw_mode_t)'
/home/lino/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: .pio/build/FYSETC_S6/src/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/screens.cpp.o:(.rodata._ZN9ScreenRef13functionTableE+0x354): undefined reference to `BedMeshScreen::onTouchStart(unsigned char)'
/home/lino/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: .pio/build/FYSETC_S6/src/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/screens.cpp.o:(.rodata._ZN9ScreenRef13functionTableE+0x35c): undefined reference to `BedMeshScreen::onTouchEnd(unsigned char)'
collect2: error: ld returned 1 exit status
*** [.pio/build/FYSETC_S6/firmware.elf] Error 1
================================================================================== [FAILED] Took 42.47 seconds ==================================================================================

Environment    Status    Duration
-------------  --------  ------------
FYSETC_S6      FAILED    00:00:42.472
============================================================================= 1 failed, 0 succeeded in 00:00:42.472 =============================================================================
The terminal process "pio 'run', '--environment', 'FYSETC_S6'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

### PR DESCRIPTION
**Pull request by InsanityAutomation**
When SD_SPI_SPEED  was set in config adv, conditionals lcd had already set it, so duplicate define messages bounded. When using Bilinear instead of UBL, touchscreen had calls to undefined functions.

### CODE REVIEW

File: Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/bed_mesh_screen.cpp [hunk 1]
```diff
@@ -21,7 +21,7 @@
 
 #include "../config.h"
 
-#if BOTH(TOUCH_UI_FTDI_EVE, AUTO_BED_LEVELING_UBL)
+#if BOTH(TOUCH_UI_FTDI_EVE, HAS_MESH)
```
Comment (sjasonsmith) [inline Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/bed_mesh_screen.cpp:24]: I already posted a PR which resolved this build issue in a different way: #20608.

I don't have compatible hardware, so I don't know which approach is correct. I would appreciate @InsanityAutomation's input on this.

Comment (thinkyhead) [reply Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/bed_mesh_screen.cpp:24]: If it compiles with the other mesh-based leveling systems, then it is compatible. I've made a couple of other tweaks to that end.

Comment (sjasonsmith) [reply Marlin/src/lcd/extui/lib/ftdi_eve_touch_ui/screens/bed_mesh_screen.cpp:24]: OK, I closed my other PR then.
