### PR TITLE
Use 'adv vref' from HAL instead of constant voltage

### LINKED ISSUE #26010: [BUG] Incorrect temperature scaling of AD595 on 3.3 volt boards like BTT SKR 3
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The temperature reading from an AD595 thermocouple amplifier connected to a K type thermocouple (Temperature sensor type -1) reads high by (5 / 3.3 * actual temperature) on a controller board with a 3.3 volt ADC reference. For instance, 25C will display as 38C. This sensor works perfectly on a 5 volt board.

The problem is located in `temperature.cpp` line 1974 in `2.1.2.1` or line 2145 of `bugfix-2.1.x`:

https://github.com/MarlinFirmware/Marlin/blob/1fbeac7b5255634bb5aca209a3d3dcb6b5e43193/Marlin/src/module/temperature.cpp#L2145

The "5.0" is the ADC reference voltage for a 5 volt board like the Arduino MEGA 2560. When replaced with a board like the BTT SKR 3 which uses a 3.3 volt ADC reference, the temperature reads incorrectly.

To fix the problem I changed the line to this:
```cpp
#define TEMP_AD595(RAW)  ((RAW) * 3.3 * 100.0 / float(HAL_ADC_RANGE) / (OVERSAMPLENR) * (TEMP_SENSOR_AD595_GAIN) + TEMP_SENSOR_AD595_OFFSET)
```
The ideal fix isto have a parameter that defines the ADC reference voltage for each board instead of having to hard code it in temperature.cpp

### Bug Timeline

Discovered by replacing Arduino MEGA 2560 with BTT SKR 3

### Expected behavior

A temperature of 25.0C should display reasonably close to 25.0C 

### Actual behavior

25.0C displays as 37.6C.

### Steps to Reproduce

Connect a AD595 with thermocouple (Temperature sensor type -1) to input E0. 
For a temperature of 25.0C the display will show 37.6C. If you multiply 37.6 * (3.3/5) you get 24.8 which is close to 25.0 with only 10 bits of ADC resolution.

Instead of connecting an actual thermocoupe to E0, you can simulate it by applying 0.250 V to E0 thermister input.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11844388/Configuration.zip)

### Version of Marlin Firmware

`2.1.2.1` but exists in all versions of Marlin

### Printer model

Custom Prusa i3 mk2 style

### Electronics

 BTT SKR 3 board

### Add-ons

AD595 thermocouple amplifier and E3D K type probe

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

A similar problem exists for anyone using an AD8495 on a 5 volt board because the 3.3 volt reference is hard coded on the line below the AD595.

https://github.com/MarlinFirmware/Marlin/blob/1fbeac7b5255634bb5aca209a3d3dcb6b5e43193/Marlin/src/module/temperature.cpp#L2146

The "6.6" is actually 2 * 3.3 volts. I was done that way because the AD8495 output is only 5mv/C compared to 10mv/C on the AD595. Like the issue I described above, the ADC reference voltage should be defined in the board data instead of being hard coded.

### PR DESCRIPTION
**Pull request by GMagician**
This may solve #26010 but someone that knows how AD* devices work should take a look at this PR

### CODE REVIEW

**Comment by thinkyhead** [comment]
According to the datasheets, you cannot even use an [AD595](https://www.analog.com/media/en/technical-documentation/data-sheets/AD594_595.pdf) with a 3.3V supply voltage. For a 3.3V ADC you must use [AD8495](https://www.analog.com/media/en/technical-documentation/data-sheets/ad8494_8495_8496_8497.pdf) instead. Maybe we should add a warning about that to `Warnings.cpp`.

File: Marlin/src/module/temperature.cpp [hunk 1]
```diff
@@ -2142,8 +2142,10 @@ void Temperature::task() {
   UNUSED(ms);
 }
 
-#define TEMP_AD595(RAW)  ((RAW) * 5.0 * 100.0 / float(HAL_ADC_RANGE) / (OVERSAMPLENR) * (TEMP_SENSOR_AD595_GAIN) + TEMP_SENSOR_AD595_OFFSET)
-#define TEMP_AD8495(RAW) ((RAW) * 6.6 * 100.0 / float(HAL_ADC_RANGE) / (OVERSAMPLENR) * (TEMP_SENSOR_AD8495_GAIN) + TEMP_SENSOR_AD8495_OFFSET)
+// For a 5V input the AD595 returns a value scaled with 10mV per °C. (Minimum input voltage is 5V.)
+#define TEMP_AD595(RAW)  ((RAW) * (ADC_VREF_MV) / 10.0f / float(HAL_ADC_RANGE) / (OVERSAMPLENR) * (TEMP_SENSOR_AD595_GAIN) + TEMP_SENSOR_AD595_OFFSET)
```
Comment (GMagician) [inline Marlin/src/module/temperature.cpp]: Instead of changing adc_ref to mV (involve a lot of source files) you may use 0.010f that is clearly 10mV

Comment (thinkyhead) [reply Marlin/src/module/temperature.cpp]: I changed the define to use mV units so that the values are integers and can therefore emit a `#warning` instead of being required to use `static_assert`.
