### PR TITLE
Fix #19170 - Mesh Bed Level on Color UI

### LINKED ISSUE #19170: [BUG] COLOR_UI With Mesh Bed Leveling
### Bug Description

In the procedure of mesh bed leveling, next when in Display appear "Click to Begin" ,Nothing happens if touched.
In general the touch screen works very well, only on that screen it doesn't work.
Since there are no buttons or anything, you can't even go back, and you have to take them.

### My Configurations

https://github.com/andreibobirica/Marlin/tree/2.0.x

### Steps to Reproduce

Click on Bed Leveling with Mesh Bed Leveling and COLOR_UI (no classic_ui)
Wait for homing
Wait for CLICK TO BEGIN to appear
Touch the screen, nothing is happening.

**Expected behavior:**
Step 5: Initiate a move to the next point
**Actual behavior:** 
Nothing

#### Additional Information
I tried to fix the bug but couldn't.
In menu_bed_leveling.cpp this procedure goes all the way to the stage
Step 4: Display "Click to Begin", wait for click
But no clicks are recorded afterwards.

Through octoprint and serial debugging I tried to figure out which functions were not working, and while on that screen the ui.use_click () function can be called and is working, the use_click function is executed if pressed on the screen.
However, nothing happens immediately afterwards.
I'm afraid all "click to begin" integrations are broken.

To solve this problem, I have temporarily removed the wait.
And I immediately moved on to step 5:
   //
   // Step 4: Display "Click to Begin", wait for click
   // Move to the first probe position
   //
   void _lcd_level_bed_homing_done () {
     if (ui.should_draw ()) MenuItem_static :: draw (1, GET_TEXT (MSG_LEVEL_BED_WAITING));
     / * if (ui.use_click ()) {
       manual_probe_index = 0;
       _lcd_level_goto_next_point ();
     } * /
     _lcd_level_goto_next_point ();
   }

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

The color UI needs a control to handle clicks. 

### Benefits

Fix #19170.

### Related Issues

#19170

### CODE REVIEW

**Review by appliedmike — COMMENTED** [review]
Thanks for you work,
When I apply this change I get TFT_WIDTH & TFT_HEIGHT not declared
Board : mks_robin_nano35
Screen : MKS TFT35 v1.0
using TFT_480x320
any clues to where I'm going wrong?, Apologies if this isn't correct place to ask

**Comment by rhapsodyv** [comment]
> Thanks for you work,
> When I apply this change I get TFT_WIDTH & TFT_HEIGHT not declared
> Board : mks_robin_nano35
> Screen : MKS TFT35 v1.0
> using TFT_480x320
> any clues to where I'm going wrong?, Apologies if this isn't correct place to ask

You are using bugfix?

I tested with nano v2. I could missed something.

**Comment by appliedmike** [comment]
Guilty ☹ , I’m using your marlin UI that provides additional axis move screen  (Excellent work!!)  so I was avoiding bugfix until it was includedAhh also I’m on Robin Nano 1.2 (so non spi) I tried to get TFT_LVGL_UI_FSMC to work, but get a memory overflow issue on compile  so remain on TFT_480x320 ☹  Sent from Mail for Windows 10 From: Victor OliveiraSent: Saturday, 26 September 2020 7:18 AMTo: MarlinFirmware/MarlinCc: appliedmike; CommentSubject: Re: [MarlinFirmware/Marlin] Fix #19170 - Mesh Bed Level on Color UI (#19514) Thanks for you work,When I apply this change I get TFT_WIDTH & TFT_HEIGHT not declaredBoard : mks_robin_nano35Screen : MKS TFT35 v1.0using TFT_480x320any clues to where I'm going wrong?, Apologies if this isn't correct place to askYou are using bugfix?I tested with nano v2. I could missed something.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by appliedmike** [comment]
Guilty ☹ , I’m using your marlin UI that provides additional axis move screen  (Excellent work!!)  so I was avoiding bugfix until it was included
Ahh also I’m on Robin Nano 1.2 (so non spi) 
I tried to get TFT_LVGL_UI_FSMC to work, but get a memory overflow issue on compile  so remain on TFT_480x320 ☹

**Comment by rhapsodyv** [comment]
Thanks for your feedback! For nano v1 it was broken! I fixed it now!

File: Marlin/src/lcd/menu/menu_bed_leveling.cpp [hunk 1]
```diff
@@ -159,7 +164,11 @@
   //         Move to the first probe position
   //
   void _lcd_level_bed_homing_done() {
-    if (ui.should_draw()) MenuItem_static::draw(1, GET_TEXT(MSG_LEVEL_BED_WAITING));
+    if (ui.should_draw()) {
+      MenuItem_static::draw(1, GET_TEXT(MSG_LEVEL_BED_WAITING));
+      // Color UI needs a control to detect a touch
+      TERN_(HAS_GRAPHICAL_TFT, touch.add_control(CLICK, 0, 0, TFT_WIDTH, TFT_HEIGHT));
```
Comment (thinkyhead) [inline Marlin/src/lcd/menu/menu_bed_leveling.cpp:170]: Note that `should_draw` will be `true` when the touch is received, so briefly there will be a second touch control added to the display. I see that touch controls are removed when the LCD is cleared, but not otherwise, so be sure to always use standard methods to erase the screen.
