### PR TITLE
[bf20ng] Resolve vsnprintf undefined on Due compile issue

### LINKED ISSUE #7687: [BUG] [Bugfix 2.0.x] Can't compile for DUE with u8glib
### Compile Error
======================
**1. When I compile with:**

  #define MOTHERBOARD BOARD_RAMPS_FD_V1
... 
  #define DOGLCD      // Full graphics display

I get a warning:
sketch/src/gcode/control/M111.cpp: In static member function 'static void GcodeSuite::M111()':
/Users/xxxxxx/Library/Arduino15/packages/arduino/hardware/sam/1.6.11/cores/arduino/avr/pgmspace.h:103:61: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 #define pgm_read_word(addr) (*(const unsigned short *)(addr))
                                                             ^
sketch/src/gcode/control/M111.cpp:55:31: note: in expansion of macro 'pgm_read_word'
         serialprintPGM((char*)pgm_read_word(&debug_strings[i]));

=====================
**2. When add:**
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

I get an error:
sketch/src/lcd/ultralcd.cpp: In function 'void lcd_status_printf_P(uint8_t, const char*, ...)':
sketch/src/lcd/ultralcd.cpp:4615:61: error: 'vsnprintf_P' was not declared in this scope
   vsnprintf_P(lcd_status_message, 3 * (LCD_WIDTH), fmt, args);

=====================
**3. When I add to HAL_Due.h, line 77:**

#ifndef vsnprintf_P
  #define vsnprintf_P vsnprintf
#endif 

I get no compilation error , LCD doesn't work, clear, a lot of warnings like:
/Users/xxxxxx/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_t6963.c:128:26: warning: assignment from incompatible pointer type [enabled by default]
   u8g_input_data_port[7] =  portInputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D7]));.

=====================
**4. When I try the same with "MK4duo Firmware" LCD works.**

### PR DESCRIPTION
**Pull request by fiveangle**
Resolves #7687 compile errors due to vsprintf not defined for Due HAL but does not resolve LCD not working.

These compile warnings are probably very relevant but I'm unsure how to resolve:

```
n file included from /Users/speedster/Library/Arduino15/packages/arduino/hardware/sam/1.6.11/cores/arduino/Arduino.h:31:0,
                 from /var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_170758/sketch/src/gcode/control/../../inc/../HAL/HAL_DUE/HAL_Due.h:38,
                 from /var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_170758/sketch/src/gcode/control/../../inc/../HAL/HAL.h:84,
                 from /var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_170758/sketch/src/gcode/control/../../inc/MarlinConfig.h:32,
                 from /var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_170758/sketch/src/gcode/control/../gcode.h:243,
                 from /var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_170758/sketch/src/gcode/control/M111.cpp:23:
/var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_170758/sketch/src/gcode/control/M111.cpp: In static member function 'static void GcodeSuite::M111()':
/Users/speedster/Library/Arduino15/packages/arduino/hardware/sam/1.6.11/cores/arduino/avr/pgmspace.h:103:61: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 #define pgm_read_word(addr) (*(const unsigned short *)(addr))
                                                             ^
/var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_170758/sketch/src/gcode/control/M111.cpp:55:31: note: in expansion of macro 'pgm_read_word'
         serialprintPGM((char*)pgm_read_word(&debug_strings[i]));
                               ^
```
and...
```
/Users/speedster/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_fast_parallel.c: In function 'u8g_com_arduino_fast_parallel_init':
/Users/speedster/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_fast_parallel.c:104:20: warning: assignment from incompatible pointer type [enabled by default]
   u8g_data_port[0] =  portOutputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D0]));
                    ^
/Users/speedster/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_fast_parallel.c:106:20: warning: assignment from incompatible pointer type [enabled by default]
   u8g_data_port[1] =  portOutputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D1]));
                    ^
/Users/speedster/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_fast_parallel.c:108:20: warning: assignment from incompatible pointer type [enabled by default]
   u8g_data_port[2] =  portOutputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D2]));
                    ^
/Users/speedster/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_fast_parallel.c:110:20: warning: assignment from incompatible pointer type [enabled by default]
   u8g_data_port[3] =  portOutputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D3]));
                    ^
/Users/speedster/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_fast_parallel.c:113:20: warning: assignment from incompatible pointer type [enabled by default]
   u8g_data_port[4] =  portOutputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D4]));
                    ^
/Users/speedster/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_fast_parallel.c:115:20: warning: assignment from incompatible pointer type [enabled by default]
   u8g_data_port[5] =  portOutputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D5]));
                    ^
/Users/speedster/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_fast_parallel.c:117:20: warning: assignment from incompatible pointer type [enabled by default]
   u8g_data_port[6] =  portOutputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D6]));
                    ^
/Users/speedster/Documents/Arduino/libraries/U8glib/src/clib/u8g_com_arduino_fast_parallel.c:119:20: warning: assignment from incompatible pointer type [enabled by default]
   u8g_data_port[7] =  portOutputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D7]));
                    ^
```

and more...

### CODE REVIEW

**Comment by thinkyhead** [comment]
Can the `vsnprintf` work with `PSTR("...")` input? If not, we might need to roll our own `vsnprintf_P` that does an intermediate string copy.

**Comment by thinkyhead** [comment]
Ah, I see…

> `PROGMEM` is part of the `pgmspace.h` library that is available in the AVR architecture only. So you first need to include the library at the top your sketch, like this…

In the `HAL_LPC1768/arduino.h` file we have this:
```cpp
#define PROGMEM
#define PSTR(v) (v)
#define PGM_P const char *
```
So it looks like `pgm_read_word`, etc., could also be made into macros that simply return the contents of memory.

**Comment by thinkyhead** [comment]
`HAL_Due.h` contains this…
```cpp
// Fix bug in pgm_read_ptr
#undef pgm_read_ptr
#define pgm_read_ptr(addr) (*(addr))
```
So, maybe this would work…?
```cpp
inline uint16_t pgm_read_word(const void *addr) { return *((uint16_t*)addr); }
```

**Comment by thinkyhead** [comment]
I see, `HAL_Teensy.h` does this:
```cpp
#undef pgm_read_word
#define pgm_read_word(addr) (*(addr))
```
I like the `inline` function better, since it makes sure to get the correctly sized value.

**Comment by thinkyhead** [comment]
>
```
/Users/speedster/Library/Arduino15/packages/arduino/hardware/sam/1.6.11/cores/arduino/avr/pgmspace.h:103:61: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 #define pgm_read_word(addr) (*(const unsigned short *)(addr))
                                                             ^
/var/folders/q1/g9l9mqmn319fh27k43yqpy440000gr/T/arduino_build_170758/sketch/src/gcode/control/M111.cpp:55:31: note: in expansion of macro 'pgm_read_word'
         serialprintPGM((char*)pgm_read_word(&debug_strings[i]));
```

This is an error in `M111`. It should be using `pgm_read_ptr` and not assuming a 16-bit pointer with `pgm_read_word` — patched.

**Comment by bobc** [comment]
On 32 bit, pgm_read_ptr needs to read a 32 bit. On AVR pgm_read_ptr reads a
16 bit.

Otherwise, all the pgm_read_xxx functions on 32 bit are simply memory
accesses.

**Comment by thinkyhead** [comment]
@bobc I wonder if we need to enforce the proper size, because the address pointer given to `pgm_read_ptr` could be anything from a `char*` to a `float*` (and it should flag this, if possible). I think this would ensure that the compiler will bark if it's not a pointer to a pointer:
```cpp
#define pgm_read_ptr(addr) (*((void**)(addr)))
. . .
const char *char_ptr = "some chars";
const char **some_ptr = &char_ptr;
char *got_ptr = pgm_read_ptr(some_ptr); // ok!
char *bad_ptr = pgm_read_ptr(char_ptr); // bad conversion warning
```

**Comment by thinkyhead** [comment]
I see a few other places in the code where `pgm_read_word` needs to be replaced by `pgm_read_ptr`, and I'll add those patches shortly.

File: Marlin/src/HAL/HAL_DUE/HAL_Due.h [hunk 1]
```diff
@@ -74,6 +74,10 @@
   #define strncpy_P(dest, src, num) strncpy((dest), (src), (num))
 #endif
 
+#ifndef vsnprintf_P
+  #define vsnprintf_P vsnprintf
+#endif
```
Comment (thinkyhead) [inline Marlin/src/HAL/HAL_DUE/HAL_Due.h:79]: Probably the `#ifndef` will never be needed, but I'll take it for now!
