### PR TITLE
Fix stepper timing

### LINKED ISSUE #28167: [BUG] Incorrect feedrates on fast MPU's
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

On teensy 4.1 steps/s is capped at around 70,000.
This is still prevalent on MPU with slower clocks but the error is less significant due to multistepping kicking in earlier.

### Bug Timeline

Bug noticed when moving from teensy 3.6 to 4.1

### Expected behavior

Requesting a move that required 76,800 steps per second.
30mm/s*2560steps/mm = 76,800 steps/s

### Actual behavior

 Gave me a move that went at ~66,000 steps per second.

### Steps to Reproduce

Use a teensy 4.1 and any config that can achieve speeds greater than 50,000 steps per second.
Drop in feedrate monitoring code or use an ocilloscope to monitor step output. 
Send a single move at a large speed.
Notice that we are not hitting the right steps per second.

### Version of Marlin Firmware

2.0.9.7

### Electronics

Testbench, MPU only

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Configs only have the steps per unit and mm per second change to be able to achieve >50,00 steps per second

We actually fixed this on our machines by timing the Stepper::isr() with the GPT and removing that time from next_isr_ticks. The feedrate error is now below 2%. This was not a robust fix for other MPU's but I felt it was worth mentioning here.

[Configs.zip](//github.com/user-attachments/files/23490775/Configs.zip)

Below is the code added to idle() in MarlinCore.cpp used to monitor feedrate (as well as other things). Also validated by Oscilloscope.

```cpp
static millis_t next_pos_report_ms = millis();
static uint64_t timeReportLast = micros();

if (ELAPSED(millis(), next_pos_report_ms)) {

  #if PRINTER_VERSION == PRINTER_VERSION_TEST
    next_pos_report_ms = millis() + 1000UL;
  #else
    next_pos_report_ms = millis() + 200UL;
  #endif
  static char str[12];

  static float timeelapsed;
  static xyze_pos_t velocity, lastnpos, npos, lpos;

  LOOP_NUM_AXES(a)
    npos[a] = planner.get_axis_position_mm((AxisEnum)a);

  timeelapsed = static_cast<float>(micros() - timeReportLast) / 6e7; // mm/us to mm/m
  timeReportLast = micros();
  velocity = (npos - lastnpos) / timeelapsed;
  lastnpos = npos;

  lpos = npos.asLogical();

  // Logical position reporting
  SERIAL_CHAR('a', '|');
  LOOP_NUM_AXES(a) {
    SERIAL_ECHO(dtostrf(lpos[a], 1, 3, str));
    SERIAL_CHAR(',');
  }
  // Native position reporting
  LOOP_NUM_AXES(a) {
    SERIAL_ECHO(dtostrf(npos[a], 1, 3, str));
    SERIAL_CHAR(',');
  }
  // Axis velocity reporting
  LOOP_NUM_AXES(a) {
    SERIAL_ECHO(dtostrf(velocity[a], 1, 2, str));
    if (a < NUM_AXES - 1) // no comma at end
      SERIAL_CHAR(',');
  }
  SERIAL_ECHOLN(
      C(','), int(planner.moves_free()) // planning buffer (things that will be done)
    , C(','), BLOCK_BUFFER_SIZE - 1 // planning buffer max
    , C(','), int(BUFSIZE - queue.ring_buffer.length) // command buffer (things to do)
    , C(','), BUFSIZE // command buffer max
  );
}
```

### PR DESCRIPTION
**Pull request by nanctil**
### Description

[Potential solution for #28167](https://github.com/MarlinFirmware/Marlin/pull/28168)
Removed the time spent in the ISR from the calculated period to the next Stepper ISR.

### Requirements

Fix should work on all boards AFAIK. Tested on Teensy_41.

### Benefits

Fixes the inaccuracy in the stepping period due to the ISR potentially taking up a significant portion of that time. More prevalent on faster MPU's at faster step rates.

### Configurations

[Configs.zip](https://github.com/user-attachments/files/23506224/Configs.zip)

Optionally, I also included in a copy of MarlinCore.cpp with added serial output that includes the current mm/m (and other things for debugging).

### Related Issues

[BUG] Incorrect feedrates on fast MPU's #28167

### CODE REVIEW

File: Marlin/src/module/stepper.cpp [hunk 1]
```diff
@@ -1728,7 +1728,7 @@ void Stepper::isr() {
   // sure that the time has not arrived yet - Warrantied by the scheduler
 
   // Set the next ISR to fire at the proper time
-  HAL_timer_set_compare(MF_TIMER_STEP, next_isr_ticks);
+  HAL_timer_set_compare(MF_TIMER_STEP, next_isr_ticks-time_spent);
```
Comment (thinkyhead) [inline Marlin/src/module/stepper.cpp]: I would insert spaces around the minus sign here, but at the moment the PR is locked for maintainers. You can check a box on the PR which will allow us to edit it ourselves.
