### PR TITLE
Use DELAY_NS for non-const SW SPI delay in DUE. (#22320)

### LINKED ISSUE #22320: [BUG] DUE compilation error HAL_SPI.cpp non const spiDelayCyclesX4
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When compiling Marlin from both the 2.0.x and the bugfix-2-0-x branch the compilation fails with the following error:

<details><summary>Log Output</summary>

```
In file included from sketch/src/inc/MarlinConfig.h:49:0,
                 from sketch/src/MarlinCore.h:24,
                 from sketch/src/MarlinCore.cpp:31:
sketch/src/inc/SanityCheck.h:423:4: warning: #warning "MAX*_SS_PIN, MAX*_SS2_PIN, MAX*_CS_PIN, and MAX*_CS2_PIN are deprecated and will be removed in a future version. Please use TEMP_0_CS_PIN/TEMP_1_CS_PIN instead." [-Wcpp]
   #warning "MAX*_SS_PIN, MAX*_SS2_PIN, MAX*_CS_PIN, and MAX*_CS2_PIN are deprecated and will be removed in a future version. Please use TEMP_0_CS_PIN/TEMP_1_CS_PIN instead."
    ^
In file included from sketch/src/module/printcounter.h:25:0,
                 from sketch/src/MarlinCore.cpp:53:
sketch/src/module/../libs/duration_t.h:111:36: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
     #pragma GCC diagnostic ignored "-Wformat-overflow"
                                    ^
In file included from sketch/src/HAL/DUE/../../inc/MarlinConfig.h:49:0,
                 from sketch/src/HAL/DUE/HAL.cpp:27:
sketch/src/HAL/DUE/../../inc/SanityCheck.h:423:4: warning: #warning "MAX*_SS_PIN, MAX*_SS2_PIN, MAX*_CS_PIN, and MAX*_CS2_PIN are deprecated and will be removed in a future version. Please use TEMP_0_CS_PIN/TEMP_1_CS_PIN instead." [-Wcpp]
   #warning "MAX*_SS_PIN, MAX*_SS2_PIN, MAX*_CS_PIN, and MAX*_CS2_PIN are deprecated and will be removed in a future version. Please use TEMP_0_CS_PIN/TEMP_1_CS_PIN instead."
    ^
In file included from sketch/src/HAL/DUE/../../inc/MarlinConfig.h:49:0,
                 from sketch/src/HAL/DUE/HAL_SPI.cpp:40:
sketch/src/HAL/DUE/../../inc/SanityCheck.h:423:4: warning: #warning "MAX*_SS_PIN, MAX*_SS2_PIN, MAX*_CS_PIN, and MAX*_CS2_PIN are deprecated and will be removed in a future version. Please use TEMP_0_CS_PIN/TEMP_1_CS_PIN instead." [-Wcpp]
   #warning "MAX*_SS_PIN, MAX*_SS2_PIN, MAX*_CS_PIN, and MAX*_CS2_PIN are deprecated and will be removed in a future version. Please use TEMP_0_CS_PIN/TEMP_1_CS_PIN instead."
    ^
In file included from sketch/src/HAL/DUE/HAL_SPI.cpp:41:0:
sketch/src/HAL/DUE/HAL_SPI.cpp: In function 'uint8_t spiTransferX(uint8_t)':
sketch/src/HAL/DUE/../shared/Delay.h:93:83: error: the value of 'spiDelayCyclesX4' is not usable in a constant expression
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                   ^
sketch/src/HAL/DUE/HAL_SPI.cpp:252:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
sketch/src/HAL/DUE/HAL_SPI.cpp:243:19: note: 'uint32_t spiDelayCyclesX4' is not const
   static uint32_t spiDelayCyclesX4 = 4 * (F_CPU) / 1000000; // 4µs => 125khz
                   ^
In file included from sketch/src/HAL/DUE/HAL_SPI.cpp:41:0:
sketch/src/HAL/DUE/../shared/Delay.h:93:83: note: in template argument for type 'bool' 
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                   ^
sketch/src/HAL/DUE/HAL_SPI.cpp:252:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
sketch/src/HAL/DUE/../shared/Delay.h:93:83: error: the value of 'spiDelayCyclesX4' is not usable in a constant expression
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                   ^
sketch/src/HAL/DUE/HAL_SPI.cpp:252:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
sketch/src/HAL/DUE/HAL_SPI.cpp:243:19: note: 'uint32_t spiDelayCyclesX4' is not const
   static uint32_t spiDelayCyclesX4 = 4 * (F_CPU) / 1000000; // 4µs => 125khz
                   ^
In file included from sketch/src/HAL/DUE/HAL_SPI.cpp:41:0:
sketch/src/HAL/DUE/../shared/Delay.h:93:83: note: in template argument for type 'int' 
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                   ^
sketch/src/HAL/DUE/HAL_SPI.cpp:252:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
sketch/src/HAL/DUE/../shared/Delay.h:93:95: error: invalid type in declaration before '(' token
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                               ^
sketch/src/HAL/DUE/HAL_SPI.cpp:252:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
sketch/src/HAL/DUE/../shared/Delay.h:93:83: error: the value of 'spiDelayCyclesX4' is not usable in a constant expression
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                   ^
sketch/src/HAL/DUE/HAL_SPI.cpp:257:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
sketch/src/HAL/DUE/HAL_SPI.cpp:243:19: note: 'uint32_t spiDelayCyclesX4' is not const
   static uint32_t spiDelayCyclesX4 = 4 * (F_CPU) / 1000000; // 4µs => 125khz
                   ^
In file included from sketch/src/HAL/DUE/HAL_SPI.cpp:41:0:
sketch/src/HAL/DUE/../shared/Delay.h:93:83: note: in template argument for type 'bool' 
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                   ^
sketch/src/HAL/DUE/HAL_SPI.cpp:257:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
sketch/src/HAL/DUE/../shared/Delay.h:93:83: error: the value of 'spiDelayCyclesX4' is not usable in a constant expression
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                   ^
sketch/src/HAL/DUE/HAL_SPI.cpp:257:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
sketch/src/HAL/DUE/HAL_SPI.cpp:243:19: note: 'uint32_t spiDelayCyclesX4' is not const
   static uint32_t spiDelayCyclesX4 = 4 * (F_CPU) / 1000000; // 4µs => 125khz
                   ^
In file included from sketch/src/HAL/DUE/HAL_SPI.cpp:41:0:
sketch/src/HAL/DUE/../shared/Delay.h:93:83: note: in template argument for type 'int' 
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                   ^
sketch/src/HAL/DUE/HAL_SPI.cpp:257:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
sketch/src/HAL/DUE/../shared/Delay.h:93:95: error: invalid type in declaration before '(' token
   #define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
                                                                                               ^
sketch/src/HAL/DUE/HAL_SPI.cpp:257:7: note: in expansion of macro 'DELAY_CYCLES'
       DELAY_CYCLES(spiDelayCyclesX4);
       ^
exit status 1
Fehler beim Kompilieren für das Board Arduino Due (Programming Port).
```
</details>

After digging into the code I found out that the problem is the usage of the MACRO 
#define DELAY_CYCLES(X) do { SmartDelay<IS_CONSTEXPR(X), IS_CONSTEXPR(X) ? X : 0> _smrtdly_X(X); } while(0)
in the file Delay.h in conjunction with the bad definition of 
static uint32_t spiDelayCyclesX4 = 4 * (F_CPU) / 1000000; // 4µs => 125khz
in HAL_SPI.cpp

Changing the variable definition to static const uint32_t spiDelayCyclesX4 = 4 * (F_CPU) / 1000000; // 4µs => 125khz does solve above error but gives a new one because spiDelayCyclesX4 is tryed to by overridden in void spiInit(uint8_t spiRate) in the default case of switch/case instuction.
Commenting this line out 
spiDelayCyclesX4 = ((F_CPU) / 1000000) >> (6 - spiRate) << 2; // spiRate of 2 gives the maximum error with current CPU

makes the build finally go through successfully.

### Bug Timeline

New

### Expected behavior

Build shall work flawless for Arduino DUE board

### Actual behavior

Build is breaking, see description above

### Steps to Reproduce

1. Select Arduino DUE board in the board-configurator
2. Start build

### Version of Marlin Firmware

2.0.x, bugfix-2.0.x

### Printer model

CoreXY

### Electronics

Arduino DUE with RAMPS

### Add-ons

_No response_

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by slowbro**
### Description

In DUE's HAL_SPI, a non-const integer is used with DELAY_CYCLES which causes an error on compilation. Instead of using cycles, use nanoseconds as used elsewhere in the file.

### Requirements

See #22320 for configs to reproduce.

### Benefits

Fixes bug in DUE SW SPI.

### Configurations

See #22320

### Related Issues

Resolves #22320

### CODE REVIEW

File: Marlin/src/HAL/DUE/HAL_SPI.cpp [hunk 1]
```diff
@@ -510,7 +510,7 @@
         spiRxBlock = (pfnSpiRxBlock)spiRxBlockX;
         break;
       default:
-        spiDelayCyclesX4 = ((F_CPU) / 1000000) >> (6 - spiRate) << 2; // spiRate of 2 gives the maximum error with current CPU
+        spiDelayNS = (((F_CPU) / 1000000) >> (6 - spiRate) << 2) * 100; // spiRate of 2 gives the maximum error with current CPU
```
Comment (thinkyhead) [inline Marlin/src/HAL/DUE/HAL_SPI.cpp]: If this is now nanoseconds, then presumably it should no longer involve `(F_CPU / 1000000)` but should use the nanosecond equivalent of the original calculation.

Comment (thinkyhead) [reply Marlin/src/HAL/DUE/HAL_SPI.cpp]: Note that (F_CPU / 1000000) cycles == 1µs, aka 1000 nanoseconds.

Comment (thinkyhead) [reply Marlin/src/HAL/DUE/HAL_SPI.cpp]: …thus:
```cpp
spiDelayNS = 4000 >> (6 - spiRate);  // spiRate of 2 gives the maximum error with current CPU
```
…or…
```cpp
spiDelayNS = 4000 / _BV(6 - spiRate);  // spiRate of 2 gives the maximum error with current CPU
```

Comment (slowbro) [reply Marlin/src/HAL/DUE/HAL_SPI.cpp]: Ah, I see. I suppose I could just `* 1000` then, not sure how I got 100; that would make the 400 above invalid, as well. Though I'm sure there's a much nicer bitmath way of doing it. I'll look at the other HALs.

Comment (slowbro) [reply Marlin/src/HAL/DUE/HAL_SPI.cpp]: Ah, ok. Thanks!!

Comment (thinkyhead) [reply Marlin/src/HAL/DUE/HAL_SPI.cpp]: Simple enough to follow, since:
```cpp
#define DELAY_NS(x) DELAY_CYCLES((x) * ((F_CPU) / 1000000UL) / 1000UL)          // floor
```
