### PR TITLE
Fixes #13482 compiling error DEBUG_EEPROM_READWRITE

### LINKED ISSUE #13482: [BUG] compiling error with DEBUG_EEPROM_READWRITE
### Description

PR https://github.com/MarlinFirmware/Marlin/commit/380c771988ff415d48cc06df74b6c86967087016#diff-095d5ce4ba7d3ee64f2dc65b6f0d0ebc

With defined `DEBUG_EEPROM_READWRITE` becomes compile error.

```
Marlin\src\module\configuration_store.cpp:411:25: error: 'eeprom_index' was not declared in this scope
int &test_index = eeprom_index;
^
```

### Steps to Reproduce

1. actives `#define DEBUG_EEPROM_READWRITE`
2. compile
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/3002576/Marlin.zip)

### PR DESCRIPTION
**Pull request by Ludy87**
See: https://github.com/MarlinFirmware/Marlin/issues/13482

### CODE REVIEW

File: Marlin/src/module/configuration_store.cpp [hunk 1]
```diff
@@ -397,7 +397,9 @@ void MarlinSettings::postprocess() {
     #define EEPROM_SKIP(VAR) (eeprom_index += sizeof(VAR))
   #endif
 
-  #define EEPROM_START()          int eeprom_index = EEPROM_OFFSET; persistentStore.access_start()
+  int eeprom_index = EEPROM_OFFSET;
+
+  #define EEPROM_START()          persistentStore.access_start()
```
Comment (thinkyhead) [inline Marlin/src/module/configuration_store.cpp]: This will break EEPROM read/write when done more than once between reboots. `EEPROM_START` must set the `eeprom_index` value back to the start value, otherwise nothing else will reset it. The `eeprom_index` value is meant to be a local, and should not be changed into a global.

**Comment by thinkyhead** [comment]
Thanks for pointing out the error. The applied fix works around the issue.

**Comment by Ludy87** [comment]
thx @thinkyhead

**Comment by pinchies** [comment]
Thanks @Ludy87 & @thinkyhead
