### PR TITLE
separate led structures

### LINKED ISSUE #27810: [BUG] Cannot successfully build when using separate NEO_RGB and NEO_RGBW Neopixel LEDs
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I have two sets of LEDs connected to my printer mainboard, a BTT SKR 3 EZ (i.e. STM32H723VG_btt build target). The first set is the LEDs on the screen (BTT Mini12864 V2), which are NEO_RGB as enforced by SanityCheck.h. The second set is an LED lightbar I designed connected to the mainboard's RGB port, which are NEO_RGBW; specifically, Inolux IN-PI55QATPRPGPBPW-40 LEDs. Attempting to define NEOPIXEL_TYPE as NEO_RGB, NEOPIXEL2_TYPE as NEO_RGBW and enabling NEOPIXEL2_SEPARATE throws up an error during compilation with ABM+VS Code (see below). Disabling NEOPIXEL2_SEPARATE compiles successfully, as does defining NEOPIXEL2_TYPE as NEO_RGB with NEOPIXEL2_SEPARATE enabled. I tested this on the latest bugfix commit b23f86f83f6ff5f2e8fcedc4203ca081cbc58596 but it has been an issue for at least the past two months, according to the git blame of my Configuration.h.

### Bug Timeline

Previous bug report was closed: https://github.com/MarlinFirmware/Marlin/issues/24765

### Expected behavior

Compilation to succeed and the ability to separately control NEO_RGB and NEO_RGBW LEDs

### Actual behavior

```
...
Compiling .pio\build\STM32H723VG_btt\src\src\feature\z_stepper_align.cpp.o
Compiling .pio\build\STM32H723VG_btt\src\src\gcode\bedlevel\G26.cpp.o
Compiling .pio\build\STM32H723VG_btt\src\src\gcode\bedlevel\G42.cpp.o
In file included from Marlin\src\feature\leds\../../inc/MarlinConfigPre-1-axes.h:40,
                 from Marlin\src\feature\leds\../../inc/Conditionals-1-axes.h:32,
                 from Marlin\src\feature\leds\../../inc/MarlinConfigPre.h:27,
                 from Marlin\src\feature\leds\../../inc/MarlinConfigPre-5-post.h:24,
                 from Marlin\src\feature\leds\../../inc/MarlinConfigPre-6-type.h:24,
                 from Marlin\src\feature\leds\../../inc/MarlinConfig.h:28,
                 from Marlin\src\feature\leds\leds.cpp:27:
Marlin\src\feature\leds\leds.cpp: In static member function 'static void LEDLights2::set_color(const LEDColor&)':
Marlin\src\feature\leds\leds.cpp:283:97: error: 'const LEDColor' {aka 'const struct LEDColor'} has no member named 'w'
  283 |                             : neo2.Color(incol.r, incol.g, incol.b OPTARG(HAS_WHITE_LED2, incol.w));
      |                                                                                                 ^
c:\git\marlinworkzone\marlin\src\core\macros.h:215:20: note: in definition of macro 'EMIT'
  215 | #define EMIT(V...) V
      |                    ^
c:\git\marlinworkzone\marlin\src\core\macros.h:217:56: note: in expansion of macro '_OPTARG'
  217 | #define TERN_(O,A)          _TERN(_ENA_1(O),OMIT,EMIT)(A) // OPTION ? 'A' : '<nul>'
      |                                                        ^
c:\git\marlinworkzone\marlin\src\core\macros.h:223:29: note: in expansion of macro 'TERN_'
  223 | #define OPTARG(O,A...)      TERN_(O,DEFER(_OPTARG)(A))
      |                             ^~~~~
Marlin\src\feature\leds\leds.cpp:283:68: note: in expansion of macro 'OPTARG'
  283 |                             : neo2.Color(incol.r, incol.g, incol.b OPTARG(HAS_WHITE_LED2, incol.w));
      |                                                                    ^~~~~~
Compiling .pio\build\STM32H723VG_btt\src\src\gcode\bedlevel\M420.cpp.o
Compiling .pio\build\STM32H723VG_btt\src\src\gcode\bedlevel\ubl\G29.cpp.o
Compiling .pio\build\STM32H723VG_btt\src\src\gcode\bedlevel\ubl\M421.cpp.o
*** [.pio\build\STM32H723VG_btt\src\src\feature\leds\leds.cpp.o] Error 1
```

### Steps to Reproduce

In Configuration.h: 
```
#define BTT_MINI_12864
#define NEOPIXEL_TYPE           NEO_RGB 
#define NEOPIXEL2_TYPE          NEO_RGBW
#define NEOPIXEL2_SEPARATE
```

Then attempt to build for STM32H723VG_btt.

### Version of Marlin Firmware

Bugfix 2.1.x commit b23f86f83f6ff5f2e8fcedc4203ca081cbc58596

### Printer model

Creality Ender 3 Pro

### Electronics

BTT SKR 3 EZ mainboard

### LCD/Controller

BTT Mini12864 V2 screen

### Other add-ons

Custom Neopixel LED lightbar, using Inolux IN-PI55QATPRPGPBPW-40 RGBW LEDs

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[configs.zip](https://github.com/user-attachments/files/19826742/configs.zip)

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Some combinations of LED strips broke compiling the code 

In particular 

```CPP
  #define NEOPIXEL_TYPE          NEO_GRB
  #define NEOPIXEL2_TYPE          NEO_GRBW
  #define NEOPIXEL2_SEPARATE
```
Currently errors with 

```
Marlin\src\feature\leds\leds.cpp:283:97: error: 'const LEDColor' {aka 'const struct LEDColor'} has no member named 'w'
  283 |                             : neo2.Color(incol.r, incol.g, incol.b OPTARG(HAS_WHITE_LED2, incol.w));
```

The cause is that both led strings use a common struct LEDColor
But LEDColor dynamically changes at compile time to include white support or not.  It also only looked at NEOPIXEL_TYPE for a white led.

I separated the two led strings to use their own unique LEDColor that allows either to have a white led.  

### Requirements

  #define NEOPIXEL_TYPE          NEO_GRB
  #define NEOPIXEL2_TYPE          NEO_GRBW
  #define NEOPIXEL2_SEPARATE

### Benefits

Builds and works as expected

### Configurations

Example config for a RAMPS with two LED strips 

```
  #define NEOPIXEL_TYPE          NEO_GRB
  #define NEOPIXEL_PIN                4 // LED driving pin
  #define NEOPIXEL2_TYPE          NEO_GRBW
  #define NEOPIXEL2_PIN               5
  #define NEOPIXEL2_SEPARATE

```
[Example Configuration.zip](https://github.com/user-attachments/files/21012684/Example.Configuration.zip)

### Related Issues

<li>MarlinFirmware/Marlin/issues/27810</li>

### CODE REVIEW

**Comment by ellensp** [comment]
Although I have tested this lots, there are so many LED options it is possible I missed or broke something.

Check thoroughly

**Comment by thinkyhead** [comment]
To do this more comprehensively we should make a template struct that either has or does not have a white component, and then define the types for each LED peripheral from the appropriate template. The updated struct would include a new method "White()" that sets the white color with RGB or with the white LED (or *all* sometimes?) according to whether the template parameter indicating RGBW is true.

**Comment by MarathonMAN1** [comment]
Also be able to commit Neopixel LED2 to an RGB screen would be helpful. Taking up the main LED's that are event oriented leave LED2 with very minimal control. Seems like a template based for each LED or Neopixels is a move in the right direction.

**Comment by thisiskeithb** [comment]
> Also be able to commit Neopixel LED2 to an RGB screen would be helpful. Taking up the main LED's that are event oriented leave LED2 with very minimal control. Seems like a template based for each LED or Neopixels is a move in the right direction.

I would like to tackle some improvements, but here's the related Feature Request for now:

- https://github.com/MarlinFirmware/Marlin/issues/25236

File: Marlin/src/gcode/feature/leds/M150.cpp [hunk 1]
```diff
@@ -80,24 +80,46 @@ void GcodeSuite::M150() {
...
+
+  const uint8_t valR = seenR ? (parser.has_value() ? parser.value_byte() : 255) : (old_color >> 16) & 0xFF;
+  const uint8_t valU = seenU ? (parser.has_value() ? parser.value_byte() : 255) : (old_color >>  8) & 0xFF;
+  const uint8_t valB = seenB ? (parser.has_value() ? parser.value_byte() : 255) :  old_color        & 0xFF;
+  #if HAS_WHITE_LED || HAS_WHITE_LED2
+    const uint8_t valW = seenW ? (parser.has_value() ? parser.value_byte() : 255) : (old_color >> 24) & 0xFF;
+  #endif
+  #if ENABLED(NEOPIXEL_LED)
+    const uint8_t valP = seenP ? (parser.has_value() ? parser.value_byte() : 255) : brightness;
+  #endif
```
Comment (thinkyhead) [inline Marlin/src/gcode/feature/leds/M150.cpp]: Important: The `seen()` method pre-loads the value for the specified parameter, overwriting the previously fetched parameter value. So you can't use `seen`, `seen`, `seen`, `value`, `value`, `value`. It has to be `seen`, `value`, `seen`, `value`, `seen`, `value`.
