### PR TITLE
"Fix all serial issues" pending PR

### LINKED ISSUE #20906: [BUG] Latest bugfix commit breaks emergency parser
### Bug Description

I just updated my bugfix branch to the very latest commit (7bbdbcfb6db4c6d35e4aaffca06073dd2bfc6719) and I tried compiling the firmware and immediately got this error

```
Marlin/src/HAL/STM32/MarlinSerial.cpp: In member function 'void MarlinSerial::_rx_complete_irq(serial_t*)':
Marlin/src/HAL/STM32/MarlinSerial.cpp:84:31: error: 'emergency_state' was not declared in this scope; did you mean 'emergency_parser'?
   84 |       emergency_parser.update(emergency_state, c);
      |                               ^~~~~~~~~~~~~~~
      |                               emergency_parser
Compiling .pio/build/BIGTREE_SKR_PRO/src/src/core/utility.cpp.o
*** [.pio/build/BIGTREE_SKR_PRO/src/src/HAL/STM32/MarlinSerial.cpp.o] Error 1
```
I do have emergency paraser enabled.. 

### Configuration Files

Here's a link to my branch: https://github.com/NovaViper/Marlin/tree/xavier-stable2.0.x/Marlin
Aswell as the run: https://github.com/NovaViper/Marlin/runs/1785661931

### Steps to Reproduce

1. Get the 7bbdbcf commit
2. Enable Emergency parser 
3. Compile for an SKR_Pro board
4. The error occurs

**Expected behavior:**

It should compile like normal and throw out the error

**Actual behavior:**

It throws out that error mentioned above

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

### LINKED ISSUE #20921: [BUG] Temperature no longer reported to OctoPrint
### Bug Description

Somewhere between yesterday morning and the most recent merges within 24 hours, OctoPrint can no longer read temperatures from my SKR Pro 1.0. It worked when I used Bugfix 2.0 from yesterday morning sometime (-8 PST) but when I used the latest bugfix this morning the issue cropped up. It causes OctoPrint to disconnect due to multiple timeouts.

### Configuration Files
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5895797/Configs.zip)

### Steps to Reproduce

Use the current bugfix 2.0 and connect to SKR 1.0 with Octoprint. It appears to connect OK but no temperature data is reported. This causes OctoPrint to throw an error about multiple timeout retires exceeded.

**Expected behavior:**

Temperatures would display

**Actual behavior:**

No temperature is displayed and the host disconnects.

#### Additional Information

I will do my best to provide any additional details as needed. I am not a developer so please be gentle. Thanks for your wonderful work and contributions to 3D printing and Open Source!

### LINKED ISSUE #20946: [BUG] ADVANCED_OK returns additional info
Board is a SKR Mini E3 v2.0

Configs:
https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20Pro/BigTreeTech%20SKR%20Mini%20E3%202.0

Enable ADVANCED_OK and compile.

Build is from bugfix-2.0.x on Jan 28 2021.

Output from USB Serial:
```
Send: N609 G1 X81.579 Y150.534 E0.02365*91
Recv: ok WN\x856m0g9p P0 B1
Send: N610 G1 X81.579 Y153.156 E0.08224*94
Recv: ok WN\x856m1h0g P0 B3
Send: N611 G1 X82.334 Y153.156 E0.02365*93
Recv: ok WN\x856m1h1h P0 B3
Send: N612 G1 X82.334 Y147.117 E0.18936*89
Recv: ok WN\x856m1h2i P0 B3
Send: N613 G1 X83.088 Y146.469 E0.03118*94
Recv: ok WN\x856m1h3j P0 B3
Send: N614 G1 X83.088 Y153.156 E0.20968*90
Recv: ok WN\x856m1h4k P0 B3
```

I'm not sure what the `WN\x856m1h3j` etc parts are.... Probably a bug...

### LINKED ISSUE #20957: [Possible BUG] Serial comunication closes/drops
### Bug Description

With last bugfix-2.0.x when connected to the board with OctoPi after executing one command or wait some seconds the comunication closes.

### Configuration Files

This happens with both my printers.

[Ender 3.zip](https://github.com/MarlinFirmware/Marlin/files/5900951/Ender.3.zip)
[AM8.zip](https://github.com/MarlinFirmware/Marlin/files/5900953/AM8.zip)

### Steps to Reproduce

1. Connect using octoprint
2. After connection observe that there is no temperature messages
3. If I execute one command command or wait some seconds the connection closes/drops.

### PR DESCRIPTION
**Pull request by X-Ryl669**
### Description

Fix a building issue with STM32 platform and emergency parser as reported by @DrumClock

### Requirements

STM32 board with emergency parser enabled

### Benefits

Fix build, so it does not break anymore

### Configurations

I don't have those. Please have a look [here](https://github.com/DrumClock/Marlin/tree/GTR-4E)

### Related Issues

None created.

### CODE REVIEW

**Comment by rhapsodyv** [comment]
Maybe you should add all fixes for serial here, as a follow-up for the recent changes. What you think? 

Seems that multi serial, emergency parser and auto report are having issues with the last changes...

**Comment by X-Ryl669** [comment]
Ok, let's do that!

**Comment by CRCinAU** [comment]
Agreed - it seems there's a lot broken right now, and the problem is there's various fixes scattered everywhere making it really difficult to track what's going on...

**Comment by GMagician** [comment]
@X-Ryl669 you may go on with this fix. I posted #20945 to fix invalid uint8_t printed as char since I noted that mostly Marlin cast them to int when it wants a number. Unfortunatelly G29 T was not fixed and double unlucky SAMD51 uses signed chars.

In code there are some parts that need uint8_t sent as real ascii value (not number) then I think we solved all issues

**Comment by X-Ryl669** [comment]
I tend to follow your opinion here. The majority of platforms previously had "print(unsigned char, base = 0)" and not "print(unsigned char, base = DEC)". So if some code use `print((uint8_t)i)` to actually mean formatting the number, then this code should be fixed. 

It also means that the bug was present previously (on AVR, the only platform that used `print(uint8_t,DEC)`) but it was not reported.

**Comment by GMagician** [comment]
> I tend to follow your opinion here. The majority of platforms previously had "print(unsigned char, base = 0)" and not "print(unsigned afixed.
> It also means that the bug was present previously (on AVR, the only platform that used `print(uint8_t,DEC)`) but it was not reported.

Also samd is as avr,weird no one found that previously. I fixed that anyway

**Comment by CRCinAU** [comment]
Likely related with possible fix posted:
https://github.com/MarlinFirmware/Marlin/issues/20946

**Comment by GMagician** [comment]
> Likely related with possible fix posted:
> #20946

That seems something different

**Comment by logiclrd** [comment]
@GMagician It _is_ different, but this PR is sneaking in a fix for that issue at the same time.

image

**Comment by logiclrd** [comment]
rhapsodyv wrote:

> Maybe you should add all fixes for serial here, as a follow-up for the recent changes. What you think?

I'm assuming that's what that's about.

As a curious bystander, I'd like to propose de-obfuscating that overload of `print`. From where I'm standing, it doesn't seem to actually improve the performance or behaviour of the code at all, and it significantly decreases readability and maintainability. All the other overloads are one-liners, sure, but that overload is actually _doing something_. I think that one in particular ought to be returned to the pre-refactor form:
```
  void print(long n, int base = DEC)
  {
    if (base == 0) write(n);
    else if (base == DEC) {
      if (n < 0) { print('-'); n = -n; }
      printNumber(n, DEC);
    }
    else
      printNumber(n, base);
  }
```
Note that there is also another behavioural difference, in that the refactored form will now emit negative signs for bases other than 10 as well.

**Comment by X-Ryl669** [comment]
Ok, this should be fixed. Thanks @logiclrd for spotting a bug.

File: Marlin/src/core/serial_base.h [hunk 1]
```diff
@@ -82,9 +82,18 @@ struct SerialBase {
...
-  void print(long c, int base = DEC)                      { if (!base) write(c); else { write((const uint8_t*)"-", c < 0); printNumber(c < 0 ? -c : c, base); } }
   void print(unsigned long c, int base = DEC)             { printNumber(c, base); }
   void print(double c, int digits = 2)                    { printFloat(c, digits); }
+  void print(long c, int base = DEC)                      {
+    if (!base) {
+      write(c);
+      return;
+    }
+    if (base == DEC && c < 0) {
+      write((uint8_t)'-'); c = -c;
```
Comment (GMagician) [inline Marlin/src/core/serial_base.h:93]: write('-') ;is more than enough

Comment (GMagician) [reply Marlin/src/core/serial_base.h:93]: or at worst (char)'-'

**Comment by X-Ryl669** [comment]
@logiclrd I've removed all the (different) print implementations for all platforms to have a single one. As strange as it seems, the different implementation where not behaving the same (as @GMagician spotted for printing unsigned char, that's not the same for AVR and ARM). So I had to made choices and honestly I've missed some code or over-optimized some other code as your spotted, introducing my own bugs here. The patch removed close to a thousand line of code and added additional features in exchange.

In the end, I think it's better that there is a single print implementation for all Marlin, since, once the "bug tsunami" is gone, there will be no more strange bug that happens on some platform but not on other due to these difference of platform. 
I'm sorry for inconvenience meanwhile.

File: Marlin/src/core/serial_base.h (hunk 1 above)
Comment (X-Ryl669) [reply Marlin/src/core/serial_base.h:93]: Yep probably but on x86, it'll trigger a "conversion from signed to unsigned" warning if not cast.

**Comment by GMagician** [comment]
> @logiclrd I've removed all the (different) print implementations for all platforms to have a single one. As strange as it seems, the different implementation where not behaving the same (as @GMagician spotted for printing unsigned char, that's not the same for AVR and ARM). So I had to made choices and honestly I've missed some code or over-optimized some other code as your spotted, introducing my own bugs here.

Current implementation works correctly (when merged with my PR #20945). All the misunderstanding born because of some bug in Marlin (fixed by my pr) where some uint8_t where expected to print as numbers. This was unlucky correct on AVR and SAMD51 and for some STM32 (the ones with compiler option to turn chars to signed), but as I checked into code I saw that usually uint8_t are casted to int16_t when a number is needed (exists some part where uint8_t and chars are expected to be printed as a byte, so you have to keep them with base=0).

I think this PR and mine can and should be merged as soon as possible (yours because of divide by 0 and reboot and mine to complete the fix)

File: Marlin/src/core/serial_base.h (hunk 1 above)
Comment (X-Ryl669) [reply Marlin/src/core/serial_base.h:93]: BTW, there is a latent bug in `c = -c` for `LONG_MIN` which does not exist (since `-LONG_MIN > LONG_MAX`) and can not be represented in a signed long... This was present in Marlin previously, so I don't know if I should fix it or not.

**Comment by GMagician** [comment]
...well another solution might be that you incorporate my PR into this, even if they are really two different issues

**Comment by X-Ryl669** [comment]
I'll do that. This PR is a collect all serial issue.

**Comment by GMagician** [comment]
> 
> 
> I'll do that. This PR is a collect all serial issue.

Give me a shot when you do it so I properly close mine

File: Marlin/src/core/serial_base.h (hunk 1 above)
Comment (X-Ryl669) [reply Marlin/src/core/serial_base.h:93]: This only happens for platform without 2-complement representation for negative number. I think all platform are 2-complement so it's ok.

Comment (GMagician) [reply Marlin/src/core/serial_base.h:93]: it should be wrong then where it0s already used a char in other part of the code (G29 T and other parts)

Comment (logiclrd) [reply Marlin/src/core/serial_base.h:93]: Wait, isn't that backwards? 2's-complement numbers _do_ have the problem. If someone calls `print((uint16_t)0x8000)`, then it'll try to compute a 16-bit equivalent of -(-32768), which doesn't exist.

Comment (logiclrd) [reply Marlin/src/core/serial_base.h:93]: Er, well, it's `long`, so substitute `(uint32_t)0x80000000` and `-(-2147483648)`.

Comment (logiclrd) [reply Marlin/src/core/serial_base.h:93]: I just copy/pasted the new implementation to a stand-alone test project running on my x86 desktop, with `printNumber` implemented as simply `cout << n`, and when I passed in 0x80000000, the output it generated was `--2147483648`.

Comment (logiclrd) [reply Marlin/src/core/serial_base.h:93]: Haha, I just also copy/pasted in the definition of `printNumber`, and it prints `0x80000000` as `-56303/413/`. :-D

Comment (logiclrd) [reply Marlin/src/core/serial_base.h:93]: Here's one possible mitigation which works on my desktop and doesn't seem to depend on a particular binary representation of the number, handling negatives as check one layer down in `printNumber` instead:
```
void printNumber(unsigned long n, const uint8_t base)
{
  if (!base) {
    write((uint8_t)n);
    return;
  }
  if (n) {
    unsigned char buf[8 * sizeof(long)]; // Enough space for base 2
    int8_t i = 0;
    signed long sn = (signed long)n;
    if ((sn < 0) && (base == DEC)) {
      write((uint8_t)'-');
      // Handle the first digit specially. In an earlier version of this code, we would simply set n to -n, but
      // there might exist a value of n for which we can't represent -n directly.
      buf[i++] = -(sn % base);
      n = (unsigned long)(sn / -base);
    }
    while (n) {
      buf[i++] = n % base;
      n /= base;
    }
    while (i--) write((char)(buf[i] + (buf[i] < 10 ? '0' : 'A' - 10)));
  }
  else write('0');
}
```
With this change, the handling of negatives inside `print` is no longer needed.

Testing:
```
  for (int base = 2; base <= 16; base++)
  {
    print(0x80000000, base);
    write('\n');
  }
```

```
10000000000000000000000000000000
12112122212110202102
2000000000000000
13344223434043
553032005532
104134211162
20000000000
5478773672
-2147483648
A02220282
4BB2308A8
282BA4AAB
1652CA932
C87E66B8
80000000
```

I have confirmed these values. I also tested the sequence 0x7FFFFFF0 through 0x8000000F in each of these bases and didn't see any anomalies.

Comment (X-Ryl669) [reply Marlin/src/core/serial_base.h:93]: @logiclrd Thanks for the example code. Indeed, the initial serial code print had issues. The new code still have them as well (I've copy and pasted here the old code). You're right but IMHO, it's a 2 step process. First, we make a single version of the print function in all the code base, then we fix it. Your code will happen in a second step, for now, I'd like to keep bug-for-bug equivalent code... *if I can say so*, to ensure I'm not introducing too many differences in one shot.

Comment (X-Ryl669) [reply Marlin/src/core/serial_base.h:93]: Please let me know your opinion.

Comment (X-Ryl669) [reply Marlin/src/core/serial_base.h:93]: Ideally, I'd like to remove all special case print with base == 0, since when you do call print with base = 0, you should have called write instead (it's only for char and unsigned char). This means replacing in the code base all call to `SERIAL_ECHO(uint8)` when what was really meant is `SERIAL_CHAR()`. That way, once you read in the code a SERIAL_ECHO, it **always** mean printing a number as decimal (or at worst, in another base), but not outputing an ASCII char.

Comment (X-Ryl669) [reply Marlin/src/core/serial_base.h:93]: Once this is done, we'll be able to simplify the print functions not to have so many overload/case. In your code, you're computing a modulo and that's expensive (although, the only base we are interested in is 10 and 16 in reality). If you compute modulo 16 **and** you have 2 complement number, then the modulo is not required.

Comment (logiclrd) [reply Marlin/src/core/serial_base.h:93]: I'm

Comment (logiclrd) [reply Marlin/src/core/serial_base.h:93]: I'm not convinced that that level of optimization is really necessary. What proportion of the available CPU cycles is actually used by formatting integers? We could make it blindingly fast with a separate path per base and careful bit arithmetic, but is that solving any problem?

I'm only a bystander, a user of the software and not a developer of it, but I am a developer professionally and can say wholeheartedly that I am 100% on board with refactoring and reworking as entirely independent steps. :-)

I might say that if different parts of the code have different interpretations of `SERIAL_ECHO` then perhaps they should _all_ have to change -- make `SERIAL_WRITE_NUMBER` and `SERIAL_WRITE_CHAR` and get rid of `SERIAL_ECHO` entirely, and every call site changes to a macro that is truly explicit about what it is doing.

**Comment by X-Ryl669** [comment]
Due to the high quantity of issue reported in the last hours, I'm not sure it's a good idea to delay merging this code. I'll probably ask to merge this ASAP since it fixes top priority issues first, and I'll reopen another PR for the less priority version.

**Comment by ellensp** [comment]
If you think it ready you might want to remove the draft tag

File: Marlin/src/core/serial_base.h (hunk 1 above)
Comment (X-Ryl669) [reply Marlin/src/core/serial_base.h:93]: Yep. I'm inline with your opinion. Yet, it's a **huge** work due to the number of SERIAL_ECHO in the code. Will do it step by step.

**Comment by X-Ryl669** [comment]
@CRCinAU , @rhapsodyv, @GMagician  Thank you for redirecting the issues here. It's really appreciated!

**Comment by X-Ryl669** [comment]
@thinkyhead Can you please merge this ASAP to stop the flood of (related) issues this is solving ?

File: Marlin/src/core/serial_base.h (hunk 1 above)
Comment (thinkyhead) [reply Marlin/src/core/serial_base.h:93]: Our assumption has always been that an 8-bit number (`byte`, `char`, `uint8_t`, etc.) *may* be printed as a single character by the serial methods, so you will see many places where an 8-bit value is cast to an integer in order to get the desired numerical output.

File: Marlin/src/feature/bedlevel/ubl/ubl.cpp [hunk 2]
```diff
@@ -150,7 +150,7 @@
     SERIAL_ECHO_SP(7);
     LOOP_L_N(i, GRID_MAX_POINTS_X) {
       if (i < 10) SERIAL_CHAR(' ');
-      SERIAL_ECHO((int)i); //PLEASE LEAVE THIS COMMENT, THIS CODE IS HARD TO FIND, I'LL REVERT IT LATER ON
+      SERIAL_ECHO((int)i);
```
Comment (X-Ryl669) [inline Marlin/src/feature/bedlevel/ubl/ubl.cpp:153]: Yes, it is for now. I'm sorry, but those are hard to find in the code. The next step is to revert the print(uint8) to actually print the number (not the ASCII value). 

When this is done, I'll remove the cast as it'll not be required anymore, so I need some easy to find message to find them (I don't want to search for all `(int)` cast in the code.

For this to work, all the other place where SERIAL_ECHO(uint8) is used instead of SERIAL_CHAR will have to be converted to the later.
When this is done, I'll have a clearer usage of the right serial macro.

Comment (X-Ryl669) [reply Marlin/src/feature/bedlevel/ubl/ubl.cpp:153]: I've spread the exact same message in multiple places, so if you revert one, you'll have to revert all. I'd prefer you don't revert any.

**Comment by thinkyhead** [comment]
If later you want to deal with the issue of integer casting of 8-bit values to make serial printing happy, you can use this regular expression to search the code and find all the instances:
```
(SERIAL|DEBUG)_[A-Z_]+\([^)\n]+int
```

**Comment by X-Ryl669** [comment]
Thanks!

**Comment by X-Ryl669** [comment]
@logiclrd  I've tested your version of printNumber. Unfortunately, it does not work with unsigned value higher than 2³¹ (it prints a negative value in that case). I'll probably replace with [this](https://godbolt.org/z/e8WMbo) that seems to work with both sign and it's easier to understand IMHO.

This works because when computing `-n` in a 2 complement system, the CPU inverts the bits and add 1. So `-0x8000` gives `0x7FFF + 1` => `0x8000` which is exactly the good value when understood as unsigned. I don't know if it was thought this way when invented, but in our case, it really help simplifying the code.

**Comment by logiclrd** [comment]
Huh, okay, yeah, I thought basically that decimal numbers just always needed to be treated as signed, but if the function needs to handle both signed and unsigned numbers, then it isn't possible to do that with a single overload. Having both signed and unsigned overloads makes the most sense, and it is definitely convenient that the specific case where `n = -n` doesn't actually work still does the right thing with this design. I might suggest adding a comment calling out that behaviour for future maintainers. Thanks for looking into this more deeply :-)
