### PR TITLE
[1.1.x] Fix M303 thermal protection #8103

### LINKED ISSUE #8103: Marlin 115 tried to burn my house down during PID tuning
### Bug Report
- Description: I started a PID tune from Octoprint's terminal.  My thermistor went out during the PID tune (or maybe before I started it, not sure on this detail).  Heater turned on and just never shut off until I intervened.

- Expected behaviour: Firmware should detect mintemp before/during PID tuning and shut the heat off (it was reading -14C at the time).
- Actual behaviour: Smoking PLA and scorched hotend parts.
- Steps to reproduce:
  - Install TH3D115 hex binary firmware (th3dstudio.com) on CR-10
  - Install Octopi 0.14 and Octoprint 1.3.5
  - Disable the thermistor
  - Issue M303 from octoprint

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/1418930/config.zip)

### PR DESCRIPTION
**Pull request by RowanMeara**
The temperature sanity checking logic was not applied during M303
(pid autotuning) because instead of setting a target temperature, PID_autotune
directly manipulated the pwm values.  When PIDTEMP/PIDTEMPBED is
enabled, PWM values rather than the target temperature determine whether
the heater is on.  I changed the temperature sanity checking logic to look directly at the PWM values
when pid is enabled.

I tested M303 with the changes and they fix #8103 .

Edit: I also added calls to disable the heaters if PID_autotune errors out.

### CODE REVIEW

**Comment by AnHardt** [comment]
A good solution!

**Comment by ghost** [comment]
Very Good job .... 👍 
Make the same for 2.0 please 😄

**Comment by GMagician** [comment]
Hello, sorry for int(er)mission, I checked the pid code and I think we can save up to 2K changing some things, but not sure if this is correct or not
1) at the end of function there is
       if (!wait_for_heatup) disable_all_heaters();
but above there is a while cycle that exits when variable is 'false' then we can just call function with no if.
2) Everywhere in function, when exit and also "disable heaters' are required, instead of 'return' set 'wait_for_heatup' to false and (p)ut remaining code to else {...}

What do you think?
Compiling original code differences are:
184582 bytes (70.4% Full) vs 182470 bytes (69.6% Full)
with this fix maybe we can save more bytes (heater off is c(a)lled more times)

**Comment by Roxy-3D** [comment]
> Hello, sorry for intermission, I checked the pid code and I think we can save up to 2K changing some things, but not sure if this is correct or not

I wonder if there is some 'dead code' that is being eliminated by the compiler when you make those changes?   Can you cut and paste your code here for people to discuss?   It would be helpful if you can show in the comments what changed so people can discuss things easier.

**Comment by GMagician** [comment]
Honestly test was made on 2.0.x-bugfix branch with platformio, sadly with arduino there is no such optimization...
only replacing with 'break' gives me some free memory
default configuration gives me 
52246 -> 52236 bytes

[temperature.zip](https://github.com/MarlinFirmware/Marlin/files/1424600/temperature.zip)

**Comment by GMagician** [comment]
This is really fun..I made same test again, on 2.0 with platformio, just to be sure I'm not crazy

I confirm:
Original code:
  Program:  184582 bytes (70.4% Full)
  Data:       6486 bytes (79.2% Full)
With variables set to false
  Program:  182470 bytes (69.6% Full)
  Data:       6486 bytes (79.2% Full)
With break (as 1.1 sent before)
  Program:  183734 bytes (70.1% Full)
  Data:       6486 bytes (79.2% Full)

o_O

**Comment by fiveangle** [comment]
Aside from trimming potentially dead code, I've noticed Arduino and PlatformIO swapping places a handful of bytes +/- with nearly every change —no rhyme or reason. When I'm struggling to fit into a 128k board, I'll try both and use whichever comes out smaller :)

**Comment by RowanMeara** [comment]
I implemented the changes that @GMagician suggested which ended up saving me 62 bytes (116,272->116,210) on my arduino mega.

File: Marlin/temperature.cpp [hunk 1]
```diff
@@ -384,21 +384,21 @@ uint8_t Temperature::soft_pwm_amount[HOTENDS],
       #define MAX_OVERSHOOT_PID_AUTOTUNE 20
       if (input > temp + MAX_OVERSHOOT_PID_AUTOTUNE) {
         SERIAL_PROTOCOLLNPGM(MSG_PID_TEMP_TOO_HIGH);
-        return;
+        break;
       }
       // Every 2 seconds...
-      if (ELAPSED(ms, temp_ms + 2000UL)) {
+      if (ELAPSED(ms, temp_ms)) {
```
Comment (thinkyhead) [inline Marlin/temperature.cpp]: Savvy!
