### PR TITLE
fix pins postprocessing for Z_MULTI_ENDSTOPS

### LINKED ISSUE #27014: [BUG] Dual Z Stepper with dual endstop don't work
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hello,
I have configured Marlin 2.1.2.2.
With 2 Z stepper motors and 2 endstops.

The steppers drive manually, but the homing function only works in X and Y. Nothing happens when homing Z.

The endstops respond with M119.

If you move the Z axis manually and press one of the two Z endstops, both steppers stop. But only one stepper should remain standing.

The problem can be found more often on the Internet.

### Bug Timeline

Marlin 2.1.2.2

### Expected behavior

Each stepper should stop with the corresponding limit switch and the homing function in Z and the homing function of all 3 axes should work

### Actual behavior

Z Homing is not possible. 
When you press a Z endstop, both steppers stop

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

2.1.2.2

### Printer model

_No response_

### Electronics

BTT SKR V1.3

### LCD/Controller

BTT TFT 35

### Other add-ons

_No response_

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/15101161/Config.zip)

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Marlin/src/pins/pins_postprocess.h for Z_MULTI_ENDSTOPS  doesn't work as desired

The Idea of pins_postprocess is to automatically juggle existing pins around as the features requires it.
In this case the feature is Z_MULTI_ENDSTOPS

Z Stop works:
(works) Use Z_MIN_PIN or Z_MAX_PIN when defined.
(works) If Z_STOP_PIN is defined automatically converted to  Z_MIN_PIN or Z_MAX_PIN depending on your homing direction as needed

Z2 Stop does not work as it should:
(works) Use Z2_MIN_PIN or Z2_MAX_PIN when defined.
(works) If Z2_STOP_PIN exists it is automatically converted to Z2_MIN_PIN or Z2_MAX_PIN depending on your homing direction 
(faulty) If Z2_STOP_PIN does not exist and a unused Z_MIN_PIN or Z_MAX_PIN is defined use that as  Z2_STOP_PIN
Currently it can define Z2_STOP_PIN as Z_STOP_PIN even when this is in conflict
(faulty) error if there are no options left. No error in current code.

Z3 Stop does not work as it should:
(works) Use Z3_MIN_PIN or Z3_MAX_PIN when defined.
(works) If Z3_STOP_PIN exists it is automatically converted to Z3_MIN_PIN or Z3_MAX_PIN depending on your homing direction 
(faulty) There is no standard pin to reuse as this pin, so error if there are no options left
Currently Z4_STOP_PIN will be defined as Z_STOP_PIN even when this is in conflict

Z4 Stop does not work as it should:
(works) Use Z4_MIN_PIN or Z4_MAX_PIN when defined.
(works) If Z4_STOP_PIN exists it is automatically converted to Z4_MIN_PIN or Z4_MAX_PIN depending on your homing direction 
(faulty) There is no standard pin to reuse as this pin, so error if there are no options left
Currently Z4_STOP_PIN will be defined as Z_STOP_PIN even when this is in conflict

Updated to correct all of these 

Added some sanity checks for commonly miss configured X2_STOP, X3_STOP and X4_STOP pins.

### Requirements

Z_MULTI_ENDSTOPS

### Benefits

Marlin auto selects correct stop pins

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/27014#issuecomment-2133507095

### CODE REVIEW

**Comment by ellensp** [comment]
@thinkyhead  When you come to review this please go over this with a fine tooth comb,  Programmed very late at night on almost no sleep

CI error is unrelated to this PR

**Comment by thinkyhead** [comment]
Thanks for catching this one. The architecture of this thing can be tedious with so many scattered elements, but I'm sure we'll get it all wrangled in time. Perhaps "Armlin" would be a good codename for a 32-bit-only codebase with a more sensible high-level architecture.

File: Marlin/src/pins/pins_postprocess.h [hunk 1]
```diff
@@ -564,19 +564,29 @@
...
-        #error"Cannot auto allocate Z2_STOP_PIN. Define Z2_STOP_PIN in Configuration_adv.h"
+        #error "Cannot auto allocate Z2_STOP_PIN. Define Z2_STOP_PIN in Configuration_adv.h"
       #endif
     #endif
-
     #if NUM_Z_STEPPERS >= 3
       #if ((Z_HOME_TO_MIN && !defined(Z3_MIN_PIN)) || (Z_HOME_TO_MAX && !defined(Z3_MAX_PIN))) && !defined(Z3_STOP_PIN)
-        #error"Cannot auto allocate Z3_STOP_PIN. Define Z3_STOP_PIN in Configuration_adv.h"
+        #if Z_HOME_TO_MIN && defined(Z_MAX_PIN)
+          #define Z3_STOP_PIN Z_MAX_PIN
```
Comment (ellensp) [inline Marlin/src/pins/pins_postprocess.h:573]: This can be in conflict. If the user has not defined Z2_STOP_PIN, then Z_MAX_PIN is already allocated to  Z2_STOP_PIN and cannot be used for Z3_STOP_PIN.

File: Marlin/src/pins/pins_postprocess.h [hunk 2]
```diff
@@ -564,19 +564,29 @@
...
+        #elif Z_HOME_TO_MAX && defined(Z_MIN_PIN)
+          #define Z3_STOP_PIN Z_MIN_PIN
```
Comment (ellensp) [inline Marlin/src/pins/pins_postprocess.h:575]: This can be in conflict. If the user has not defined Z2_STOP_PIN, then Z_MIN_PIN is already allocated to  Z2_STOP_PIN and cannot be used for Z3_STOP_PIN.

File: Marlin/src/pins/pins_postprocess.h [hunk 3]
```diff
@@ -564,19 +564,29 @@
...
+        #endif
       #endif
     #endif
-
     #if NUM_Z_STEPPERS >= 4
-      #if ((Z_HOME_TO_MIM && !defined(Z4_MIN_PIN)) || (Z_HOME_TO_MAX && !defined(Z4_MAX_PIN))) && !defined(Z4_STOP_PIN)
-        #error"Cannot auto allocate Z4_STOP_PIN. Define Z4_STOP_PIN in Configuration_adv.h"
+      #if ((Z_HOME_TO_MIN && !defined(Z4_MIN_PIN)) || (Z_HOME_TO_MAX && !defined(Z4_MAX_PIN))) && !defined(Z4_STOP_PIN)
+        #if Z_HOME_TO_MIN && defined(Z_MAX_PIN)
+          #define Z4_STOP_PIN Z_MAX_PIN
```
Comment (ellensp) [inline Marlin/src/pins/pins_postprocess.h:584]: This can be in conflict. If the user has not defined Z2_STOP_PIN, then Z_MAX_PIN is already allocated to  Z2_STOP_PIN and cannot be used for Z4_STOP_PIN
If the user has not defined Z3_STOP_PIN, then Z_MAX_PIN is already allocated to  Z3_STOP_PIN and cannot be used for Z4_STOP_PIN
This results in Z2_STOP_PIN and Z3_STOP_PIN and Z4_STOP_PIN  being set to Z_MAX_PIN

File: Marlin/src/pins/pins_postprocess.h [hunk 4]
```diff
@@ -564,19 +564,29 @@
...
+        #elif Z_HOME_TO_MAX && defined(Z_MIN_PIN)
+          #define Z4_STOP_PIN Z_MIN_PIN
```
Comment (ellensp) [inline Marlin/src/pins/pins_postprocess.h:586]: This can be in conflict. If the user has not defined Z2_STOP_PIN, then Z_MIN_PIN is already allocated to  Z2_STOP_PIN and cannot be used for Z4_STOP_PIN. 
If the user has not defined Z3_STOP_PIN, then Z_MIN_PIN is already allocated to  Z3_STOP_PIN and cannot be used for Z4_STOP_PIN. 
This results in Z2_STOP_PIN and Z3_STOP_PIN and Z4_STOP_PIN being set to Z_MIN_PIN

**Comment by ellensp** [comment]
"assume a shared pin"

Why would you assume a shared pin when you enabled Z_MULTI_ENDSTOPS? This is the opposite of what Z_MULTI_ENDSTOPS is for.

I do not think this is a desirable outcome when you set Z_MULTI_ENDSTOPS

**Comment by thinkyhead** [comment]
Yeah, it's a strange idea. I don't know what the original rationale was for that choice, but I didn't want to change it right away without looking further. I expect we'll go back to asserting separate endstop pin defines, but maybe we'll tweak the error to explain the use cases. … I'll review the history now and then apply whatever is most sensible.

**Comment by thinkyhead** [comment]
Couldn't find any specific misuse cases, but reading the history was good for a few chuckles.
