### PR TITLE
🩹 Fix MCU check for STM32H7-based BTT Octopus Pro V1

### LINKED ISSUE #26830: [BUG] Broken env_validate.h check for BTT Octopus Pro V1
WhatsApp Image 2024-03-02 at 13 19 15_9b197ccb
WhatsApp Image 2024-03-02 at 13 19 15_46a9da15

>> Compilation fails. Using the old Octopus Pro 1.0 definitions results in an STM32F4 error, and using the Octopus Pro Max EZ definitions compiles but crashes the firmware.
> 
> You don't reuse any of the Octopus Pro 1.0 / STM32F4 definitions with the referenced PR.
> 
> Use the files from [the PR's source fork](https://github.com/thisiskeithb/Marlin/tree/pr/add_octopus_pro_1_1_stm32H723zet6) ([.ZIP download](https://github.com/thisiskeithb/Marlin/archive/refs/heads/pr/add_octopus_pro_1_1_stm32H723zet6.zip)) or wait until it is merged.
> 
> Using a minimal config, this compiles fine.
> 
> <details><summary>Minimal Config:</summary>
> <p>
> 
> ```diff
> diff --git a/Marlin/Configuration.h b/Marlin/Configuration.h
> index b21eba7..2c7199f 100644
> --- a/Marlin/Configuration.h
> +++ b/Marlin/Configuration.h
> @@ -67,7 +67,7 @@
>  
>  // Choose the name from boards.h that matches your setup
>  #ifndef MOTHERBOARD
> -  #define MOTHERBOARD BOARD_RAMPS_14_EFB
> +  #define MOTHERBOARD BOARD_BTT_OCTOPUS_PRO_V1_1
>  #endif
>  
>  /**
> @@ -78,7 +78,7 @@
>   *
>   * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
>   */
> -#define SERIAL_PORT 0
> +#define SERIAL_PORT -1
>  
>  /**
>   * Serial Port Baud Rate
> diff --git a/platformio.ini b/platformio.ini
> index e3bdb6f..f54fee7 100644
> --- a/platformio.ini
> +++ b/platformio.ini
> @@ -13,7 +13,7 @@
>  [platformio]
>  src_dir      = Marlin
>  boards_dir   = buildroot/share/PlatformIO/boards
> -default_envs = mega2560
> +default_envs = STM32H723ZE_btt
>  include_dir  = Marlin
>  extra_configs =
>      Marlin/config.ini
> ```
> 
> </p>
> </details>
> 
> Compile log using the above minimal config:
> 
> <details><summary>STM32H723ZE_btt  SUCCESS:</summary>
> <p>
> 
> ```prolog
> Archiving .pio/build/STM32H723ZE_btt/libFrameworkArduino.a
> Indexing .pio/build/STM32H723ZE_btt/libFrameworkArduino.a
> Linking .pio/build/STM32H723ZE_btt/firmware.elf
> Checking size .pio/build/STM32H723ZE_btt/firmware.elf
> Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
> RAM:   [          ]   2.0% (used 11544 bytes from 577536 bytes)
> Flash: [==        ]  20.0% (used 104916 bytes from 524288 bytes)
> Building .pio/build/STM32H723ZE_btt/firmware.bin
> ====================================== [SUCCESS] Took 40.74 seconds ======================================
> 
> Environment      Status    Duration
> ---------------  --------  ------------
> STM32H723ZE_btt  SUCCESS   00:00:40.735
> ======================================= 1 succeeded in 00:00:40.735 =======================================
>  *  Terminal will be reused by tasks, press any key to close it. 
> ```
> 
> </p>
> </details>

_Originally posted by @thisiskeithb in https://github.com/MarlinFirmware/Marlin/issues/26044#issuecomment-1618362922_

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Due to our use of [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) in the pins files, there needs to be an additional target check in `pins_BTT_OCTOPUS_V1_common.h` for the `env_validate.h` include since Octopus Pro V1 ships with both STM32F4 & STM32H7 MCUs.

_Note: I tried another method by removing the `env_validate.h` includes in both the Octopus board common files and defining them in individual pins files, but there are still nested pin includes that that end up failing due to mismatched MCUs._

### Requirements

STM32H7-based BTT Octopus Pro V1

### Benefits

STM32H7-based BTT Octopus Pro V1 configs will build

### Related Issues

- #26830

### CODE REVIEW

File: Marlin/src/pins/stm32f4/pins_BTT_OCTOPUS_V1_common.h [hunk 1]
```diff
@@ -21,7 +21,11 @@
  */
 #pragma once
 
-#include "env_validate.h"
+#if NOT_TARGET(STM32H7)
```
Comment (sjasonsmith) [inline Marlin/src/pins/stm32f4/pins_BTT_OCTOPUS_V1_common.h:26]:
```suggestion
// The Octopus Pro V1 has shipped with both STM32F4 and STM32H7 MCUs.
// Ensure the correct env_validate.h file is included based on the build environment used.
#if NOT_TARGET(STM32H7)
```
