### PR TITLE
Fix wait_for_user in the Color UI

### LINKED ISSUE #19627: Pause before deploy/stow not working with new UI style
### Bug Description
When I enable pause before deploy/stow feature by uncommenting #define PAUSE_BEFORE_DEPLOY_STOW - i can't confirm bed leveling sensor deployment on the screen, there is just no way to do it - when i click on deployment message - nothing happens.

### My Configurations
I have Flsun Q5 with MKS Robin Nano 1.2 board with 320x240 Graphical TFT screen. Marlin 2.0.7 release.
**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[alexeyzel_config.zip](https://github.com/MarlinFirmware/Marlin/files/5329328/alexeyzel_config.zip)

### Steps to Reproduce

1. Uncomment #define PAUSE_BEFORE_DEPLOY_STOW and enable UBL, compile firmware and upload it to printer
2. Turn the printer on and send "G28" command
3. Send "G29 P1" command

**Expected behavior:** [What you expect to happen]

Clickable message should appear at the center of the screen "Deploy Z-Probe", after manual probe deployment i should be able to confirm probe deployment by taping on the screen and bed leveling process should continue.

**Actual behavior:** [What actually happens]

"Deploy Z-Probe" message appears in the status bar and it is not clickable, there is no way to confirm probe deployment.

120597729_3495352840527053_6358815970162577230_n

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

Some marlin operations just wait for a encoder click, without any specific screen.

This PR makes the color ui handle it.

### Benefits

Fix #19627 

### Related Issues

#19627

### CODE REVIEW

File: Marlin/src/lcd/tft/touch.cpp [hunk 1]
```diff
@@ -80,6 +83,15 @@ void Touch::idle() {
   now = millis();
 
   if (get_point(&_x, &_y)) {
+    #if HAS_RESUME_CONTINUE
+      // UI is waiting for a click anywhere?
+      if (wait_for_user) {
```
Comment (thinkyhead) [inline Marlin/src/lcd/tft/touch.cpp:88]: When will C++ give us `extern::wait_for_user` ?

**Comment by Foxies-CSTL** [comment]
Hi,
My config: QQS-Pro with Hispeed Board (aka clone Mks Robin_mini), 4xTMC2208, Mks_Robin_TFT_V2 and 
Marlin BugFix 20201012 with 320x240 Marlin UI select.

I test this PR #19694 and the result is:
AutoCalibration Delta by menu.
A simple press on the screen is necessary to validate the deployment of the probe but there is no validation screen like the EEPROM reset screen (picture).
The validation of the acknowledgment of the storage of the probe by pressing the screen (one touch) also works.

But there is still a problem when launching a calibration (UBL) to build a cold mesh or a bed calibration procedure (G29 P1). Confirmation of the probe deployment acknowledgment by pressing the screen (one touch) freezes my screen and a reset is necessary.

I have also tried the probe test (M48) and it works fine.

Here is my feedback.
Probe_stow2
Probe_stow
Probe_deploy-after
Probe_acquitement

**Comment by rhapsodyv** [comment]
@Foxies-CSTL can you open a issue for your specific case, with your configs?
