### PR TITLE
[2.0.x] Make MBL work more like PROBE_MANUALLY

### LINKED ISSUE #7491: Mesh Level stuck in LOOP
### Bug Report
- Description: Marlin 1.1.4 Mesh Level restarts after completing. Cannot exit loop
- Expected behaviour: Once Mesh level is completed, it should return to the menu. It does not, I just restart Mesh leveling again
- Actual behaviour: Mesh leveling begins again after finishing. Cannot break out of loop
- Steps to reproduce: Start Mesh leveling. You can't end it
 Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/1220196/Configuration.zip)

### LINKED ISSUE #7912: [Marlin 1.1.5] Lcd bed leveling executes 2 times in a row
Hi,

With Marlin 1.1.5 on a Prusa I3 clone, sometimes when I do a manual bed leveling via the lcd screen, the bed leveling process executes a second time just after the first one. 

In this case, the lcd displays "leveling done" only at the end of the first one.

Is it a known issue or Am I just doing something wrong ?

Don't hesitate if I can upload files or info.

Thanks

### PR DESCRIPTION
**Pull request by thinkyhead**
See also #8574

Fix #7912 and Fix #7491 by making MBL's `LCD_BED_LEVELING` work in the same manner as `PROBE_MANUALLY`.

### CODE REVIEW

File: Marlin/src/gcode/bedlevel/mbl/G29.cpp [hunk 1]
```diff
@@ -102,7 +90,7 @@ void GcodeSuite::G29() {
     case MeshStart:
       mbl.reset();
       mbl_probe_index = 0;
-      enqueue_and_echo_commands_P(PSTR("G28\nG29 S2"));
+      enqueue_and_echo_commands_P(lcd_wait_for_move ? PSTR("G29 S2") : PSTR("G28\nG29 S2"));
```
Comment (fiveangle) [inline Marlin/src/gcode/bedlevel/mbl/G29.cpp:93]: MBL does not require LCD, so this breaks printers w/o one

Also, this desperately needs a travis test as it comes up like every couple hundred commits 😝 

```
Marlin/src/gcode/bedlevel/mbl/G29.cpp: In static member function 'static void GcodeSuite::G29()':
Marlin/src/gcode/bedlevel/mbl/G29.cpp:93:35: error: 'lcd_wait_for_move' was not declared in this scope
enqueue_and_echo_commands_P(lcd_wait_for_move ? PSTR("G29 S2") : PSTR("G28\nG29 S2"));
```

**Comment by Roxy-3D** [comment]
> Also, this desperately needs a travis test as it comes up like every hundred commits :stuck_out_tongue_closed_eyes:

I wonder if we could have two sets of Travis tests...   And if so...  We would put this test into the 'More Complete' set?

**Comment by fiveangle** [comment]
I think testing with and w/o these should be part of basic tests wherever supported:

- Panel (display + controller)
- SD

The above example illustrates this.

But I agree with you that a more comphrensive set of tests would be nice.  I think one that iterates through every example config would catch a lot of regressions that usually take weeks to be worked through in the tracker.

I looked at doing this back in spring but didn't find an easy (e.g. 5 min I spent ;) solution.  It's relatively easy to break up the existing tests to parallelize them, but that doesn't really help much when the setup time on the Precise travis instance is between 4 and 10 minutes: it just spins travis resources w/o really lowering the test time.

**Comment by Roxy-3D** [comment]
I wouldn't even be opposed to making the extended Travis tests User Name related or perhaps even Pull Request number related.   If once every 25 pull requests, we do an extended Travis Test...   Nothing will go unnoticed for that long.
