### PR TITLE
Option to use FT_MOTION for homing / probing

### LINKED ISSUE #27899: [BUG] FT_MOTION and Biqu Microprobe
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Please, help and feedback wanted.
For now, with a Biqu Microprobe in current bugfix,  `FT_MOTION` is disabled for Z homing and probing (not intellectually satisfying), but it's the simplest way to go.
The Microprobe could be wired at a 5 pin BLTouch connector or at 3 pin connector (servo or BLTouch depending on the board) and a 2 pin Z Min. The probe must also be wired on a port with a strong pull-up which is always (?) the case of a Z Min endstop connector but not  on a 5 pin BLTouch (some users reported failure with this wiring on forums for homing and probing with classic motion system).
As my probe is wired on Z min endstop, I've found a solution for my config (adding a little delay in `endstop.resync()`) but feedback is needed. Only thisiskeithb reported failure with this solution on a Biqu Hurakan (probe wired to a 5 pin connector).
This is the link to the repository for testing: https://github.com/narno2202/Marlin/tree/FTM_Microprobe_Fix.
Just use your config files with `FT_MOTION` enabled in `Configuration_adv.h`. If `FT_MOTION` is not your default motion system, do a `M493 S1` before homing and/or probing and please report success or failure with your config.
If some users have ideas to achieve the same result with either wiring, this would be great.

### Bug Timeline

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

Repo synced to current_bugfix

### Printer model

_No response_

### Electronics

_No response_

### LCD/Controller

_No response_

### Other add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by narno2202**
### Description
For now, with a Biqu Microprobe in current bugfix, `FT_MOTION` is disabled for Z homing and probing.

The Microprobe could be wired at a 5 pin BLTouch connector or at 3 pin connector (servo or BLTouch depending on the board) and a 2 pin Z Min. The probe must also be wired on a port with a strong pull-up which is always (?) the case of a Z Min endstop connector but not on a 5 pin BLTouch (some users reported failure with this wiring on forums for homing and probing with classic motion system).
The failure with `FT_MOTION` is probably a mix between hardware and timing. The probe is auto triggered immediately after the clearance move at the beginning of the homing move.
This PR enables endstop testing only when the homing move has begun while keeping `FT_MOTION` enabled. 
Tested with a Biqu Microprobe and a BLTouch, worked with or without homing bump.
Not tested on a 5 pin connector as I don't have a motherboard with this type of connector.

### Requirements
`FT_MOTION` enabled with any kind of probe

### Benefits
Fix homing and probing issues when` FT_MOTION` is enabled with various probes

### CODE REVIEW

**Comment by thisiskeithb** [comment]
This still needs more testing:

- https://github.com/MarlinFirmware/Marlin/issues/27899

**Comment by narno2202** [comment]
Still waiting for feedback. With a PR I imagine a code review and useful information.

File: Marlin/src/module/endstops.cpp [hunk 1]
```diff
@@ -960,7 +964,10 @@ void Endstops::update() {
           if ( TERN1(Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN, z_probe_enabled) // When Z_MIN is the probe, the probe must be enabled
             && TERN1(USE_Z_MIN_PROBE, !z_probe_enabled)                   // When Z_MIN isn't the probe, Z MIN is ignored while probing
           ) {
-            PROCESS_ENDSTOP_Z(MIN);
+            #if ENABLED(FT_MOTION)
+              if (z_homing_probing_active || !ftMotion.cfg.active)
+            #endif
+              PROCESS_ENDSTOP_Z(MIN);
```
Comment (classicrocker883) [inline Marlin/src/module/endstops.cpp]: extra tab here

**Comment by thinkyhead** [comment]
I like the simplicity of this solution. I see no potential issues with it as it is.

**Comment by thisiskeithb** [comment]
> I see no potential issues with it as it is.

The version I tried from the linked issue did not work, so it'd be nice to get this latest code tested + have more hardware combinations tested before merging.

**Comment by thisiskeithb** [comment]
Rebased this PR on the latest `bugfix-2.1.x` and I still have the same problem with failing Z homing as reported in the [linked issue](https://github.com/MarlinFirmware/Marlin/issues/27899#issuecomment-3016211877):

> Tested on a Biqu Hurakan with Manta M4P as well as an Ender-3 with an SKR V3.

> With FT Motion enabled: I still have the same issue as reported originally where the Z probe is triggered as soon as Z homing begins.

**Comment by narno2202** [comment]
Back from holidays. I apologize, I'm so stupid. I see your comments and I realize that I mixed 2 `Configuration.h` files. For sure,  everything is working in my configuration because  `DELAY_BEFORE_PROBING` is enabled.

Looking deeper in the probing failure, the Biqu Microprobe is self triggered by `planner.synchronize()`  in `do_homing_move()`  function in` motion.cpp`. If I add  `safe_delay()` in `do_homing move()` with `DELAY_BEFORE_PROBING` disabled , Z homing is successful.

I merge current bugfix in my repo with the new `FT_MOTION` code by @dbuezas (possibly improving electronic interference). Z homing still fails without adding a delay. I have an SKR 1.4 turbo at home, Z homing is also successful with a delay. In this case the probe is wired on a 3-pin BLTouch port and on 2-pin probe port, Z min endstop is not used.
So with the last `FT_MOTION` code and a delay, Z homing is successful on my Monster8 V1, probe wired on Z Min Endstop and on a SKR 1.4 Turbo, probe wired on a 2-pin probe port.
 
@thisiskeithb , can you please test this , you just have to enable `DELAY_BEFORE_PROBING` with the default value (in my case).
Once again, I apologize.

**Comment by thinkyhead** [comment]
We can add a strong warning that a minimum `DELAY_BEFORE_PROBING` is needed for probing when FT Motion is enabled, assuming that nothing else is required.

**Comment by narno2202** [comment]
If @thisiskeithb confirm success with his boards, I am in favor of automatically enabling `DELAY_BEFORE_PROBING` when `FT_MOTION` is defined and a probe is present or eventually add safe_delay in `Endstops::enable_z_probe` and in `Probe::probe_down_to_z` definitions (but `QUIET_PROBING` is still present in these 2 functions, the first proposal is probably simplier).

**Comment by dbuezas** [comment]
Is it understood why a delay is needed or is this a mitigation?

**Comment by narno2202** [comment]
Since the beginning, I have imagined both a timing and a hardware problem. The latter is probably related to the microprobe hardware. Your changes are solving potential EMI but have no real impact on a timing issue. The delay solution was already working for my configuration with the probe wired to Z min Endstop (MKS Monster8 V1), and now, again for my 2 testing configurations (Z min Endstop on MKS Monster8 V1 and  probe port on )SKR 1.4 turbo), it's working.

**Comment by dbuezas** [comment]
Browsing around I see one race condition:

The FTM loop checks like this:
```
if (stepper.abort_current_block) {
    if (stepperCmdBuffHasData) return;          // Wait until motion buffers are emptied
    discard_planner_block_protected();
    reset();
    stepper.abort_current_block = false;  // Abort finished.
  }
```
so halting is delayed by up to 1ms (`FTM_TS`). Maybe unnecessary but should be that problematic. The issue I see is that reset does `stepperCmdBuff_produceIdx = stepperCmdBuff_consumeIdx = 0;`, which is not an atomic operation, and we are not inside an atomic section the so the following can happen:

1. endstop_triggered() calls quick_stop() inside an atomic section
1. quick_stop() does `abort_current_block = true`
2. atomic section ends
3. the ftm loop sees abort_current_block and `stepperCmdBuff_consumeIdx = 0;` is executed first, but stepperCmdBuff_produceIdx is not updated yet
4. stepper interrupt takes over
5. it does `ftMotion.stepperCmdBuffHasData = (ftMotion.stepperCmdBuff_produceIdx != ftMotion.stepperCmdBuff_consumeIdx);`, which is suddently true
6. isr checks for abort_current_block and exits
7. ftm loop continues discarding the block and setting `stepper.abort_current_block = false`
8. the stepper isr thinks there's still data (because `ftMotion.stepperCmdBuff_produceIdx != ftMotion.stepperCmdBuff_consumeIdx` and abort_current_block is false so it keeps moving


I don't see how this can escalate further, but it doesn't look intended.

One could try:
```
if (stepper.abort_current_block) {
    ATOMIC_SECTION_START();
    // DONT WAIT until motion buffers are emptied
    discard_planner_block_protected();
    reset(); // <-- this empties the command buffer
    stepper.abort_current_block = false;  // Abort finished.
    ATOMIC_SECTION_END();
  }
```

**Comment by narno2202** [comment]
I test it but no change without delay.
When `abort_current_block` is true, no step commands are processed in `Stepper::ftMotion_stepper()`. If `stepperCmdBuffHasData` is true, ftMotion::loop() ends, `abort_current_block` stays false, and `ftMotion_stepper()` returns without processing any steps. This loop ends when `stepperCmdBuffHasData` is false.

**Comment by dbuezas** [comment]
I noticed one thing which i believe to be related: upon restarting the machine, if i do `g1 x10` in relative coords, the pulse train is missing the last chunk with the deceleration phase, and not all 10mm are travelled. If I then do `g1 x-10`, then motion starts doing the missing last part of the last block (including deceleration), and only then it starts moving to the left.

So it looks like something thinks motion was finished before it actually is, and it disables the stepper ist while there are still pending steps

**Comment by narno2202** [comment]
I've tested with the last code modification, without delay still Z homing failure and I didn't notice @dbuezas's  remark.

**Comment by dbuezas** [comment]
Yes I think there's a problem somewhere else too, but race conditions are always bad anyway.
By the way (and not really within the scope of your PR), I wonder if we could simplify the abort block logic by just immediately clearing all buffers inside an atomic block, instead of setting a flag that then is checked in a bunch of different places. This would also make the isr a bit more efficient because (one less if)

**Comment by narno2202** [comment]
I think that we can remove `if (stepperCmdBuffHasData) return;` in FTMotion::loop() and `if (abort_current_block) return;` in `Stepper::ftMotion_stepper()`. As we clear all the ft_motion data, no steps are generated or processed and the motion stops as planned. I tested these changes and everything seems ok (homing is still fine on Z axis with a delay) .

**Comment by dbuezas** [comment]
YES, exactly! :)

**Comment by thinkyhead** [comment]
The warning only specifies a "longer delay" but not a minimum value. What minimum delay should we recommend, if any?

**Comment by narno2202** [comment]
The default value (200ms) always works fine with my 2 configurations. My preference is in favor of an automatic and transparent setting for the end user when `FT_MOTION` is enabled.

**Comment by thisiskeithb** [comment]
> My preference is in favor of an automatic and transparent setting for the end user when FT_MOTION is enabled

We already have several other conditional checks when a MicroProbe is enabled, so it's fine to add another for this delay.

**Comment by narno2202** [comment]
I totally agree. @thisiskeithb have you the opportunity to test `DELAY_BEFORE_PROBING` after @dbuezas code merge?

**Comment by thisiskeithb** [comment]
> I totally agree. @thisiskeithb have you the opportunity to test `DELAY_BEFORE_PROBING` after @dbuezas code merge?

Not yet, but working on it. There isn't a rush to get this PR merged since MicroProbe + FT Motion homing behavior works for everyone as-is in ~current~ a recently tested version of bugfix.

**Comment by thisiskeithb** [comment]
I pulled down a copy of this PR, rebased it on current `bugfix-2.1.x` (5af8425), applied my Hurakan configs, and...

Z homing continues to fail with FT Motion enabled, even with delays of 200-500ms.

Using latest `bugfix-2.1.x` with my Hurakan configs and FT Motion enabled, Z homing works fine.

**Comment by thisiskeithb** [comment]
I found the 500ms reference in the [MicroProbe manual](https://github.com/bigtreetech/MicroProbe/blob/master/MicroProbe%20V2%20User%20Manual_20240330.pdf):

image

Curiously, that long of a delay isn't normally required for proper Z homing under Marlin.

**Comment by narno2202** [comment]
For sure, in latest bugfix-2.1.x, `FT_MOTION` is inactive for Z homing. So adding a delay works in some config. Can you test with the probe wired on Z min endstop or Z stop pin ?
My config: 
1 MKS Monster8 V1 : BLTouch 3 pins port and Z min endstop
2 SKR 1.4 Turbo : Servos 3 pins port and  2 pins probe port

Just for information, for a BLTouch the delay is 750ms after probe deploy in `BLTouch.cpp` . BLTouch still works when delay is 0 with or without `FT_MOTION` enabled.

**Comment by narno2202** [comment]
Looking at the Manta 4P and SKR mini E3 V3 datasheets, the probe port is wired to the PC14 pin, which is also shared with an oscillator. This is not the case with other motherboards or other pins (Z stop pin). Could this play a role in Biqu Microprobe failure on the Manta4P board wired to the 5 pin connector?

**Comment by thisiskeithb** [comment]
> Looking at the Manta 4P and SKR mini E3 V3 datasheets

I'm using an SKR V3 EZ, not SKR Mini E3 V3. Yes, these names are silly 🙂

**Comment by narno2202** [comment]
On the SKR V3 EZ, PC14 pin is also shared with an oscillator but I realize that the probe port is on the PC13 pin. Can you try wiring on the Z-stop port ?

On my side, I cannot do more because my 2 configurations work correctly by adding a delay. If you confirm the correct operation of the probe on the Z-stop pin, the probe is probably only compatible with FT_MOTION for all motherboards if connected to a Z-min-endstop or Z-stop pin; otherwise, it could be self-triggered.

**Comment by thinkyhead** [comment]
I've added the option `FTM_HOME_AND_PROBE` which you will need to enable to test FT Motion with homing and/or probing. That will get us past this issue and allow for testing that the other changes (e.g., from #28075) are robust.
