### PR TITLE
MAX31865 enhancements

### LINKED ISSUE #22526: [BUG] MINTEMP on SKR 1.3 with MAX31865
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

MAX31865 is not working   Marlin-bugfix-2.0.x 2021-08-05 
SKR1.3 +TFT35 
Case 1 
conf.h :
```cpp
#define SERIAL_PORT -1
#define SERIAL_PORT_2 0 
#define MOTHERBOARD BOARD_BTT_SKR_V1_3 
#define TEMP_SENSOR_0 -5
#define MAX31865_SENSOR_OHMS_0      100   // (Ω) Typically 100 or 1000 (PT100 or PT1000)
#define MAX31865_CALIBRATION_OHMS_0 430   // (Ω) Typically 430 for Adafruit PT100; 4300 for Adafruit PT1000

#define SDSUPPORT
//#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```
conf_adv.h
```cpp
  //#define SDCARD_CONNECTION LCD
```
MAX31865.h:
`SPI_MODE1 `

pins_BTT_SKR_common:
```cpp
#define TEMP_0_CS_PIN   P0_16
// #ifndef TEMP_0_PIN
//   #define TEMP_0_PIN                    P0_24_A1  // A1 (T1) - (68) - TEMP_0_PIN
// #endif

   #define SDCARD_CONNECTION            ONBOARD
```
MAX31865 connected to:
```
SDI  P0.18
CS    P0.16
CLK  P0.15
SDO P0.17 
VCC and GND 
```
Compilation - no errors  
file .bin >> sd card>> SKR>> restart >> no printer attached  on TFT35 

Case 2 >>
```cpp
#define TEMP_SENSOR_0  1 
//#define TEMP_0_CS_PIN   P0_16
 #ifndef TEMP_0_PIN
   #define TEMP_0_PIN                    P0_24_A1  // A1 (T1) - (68) - TEMP_0_PIN
 #endif
```
Compilation - no errors  
file .bin >> sd card>> SKR>> restart >> READY 
 
case 3 :
after some changes .... MINTEMP triggered HEATER_ID: E0

Some suggestions? 

### Expected behavior

MAX 31865 work  with SKR 1.3

### Actual behavior

no communication / freeze of mainboard

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

SKR 1.3 

### Electronics

SKR 1.3

### PR DESCRIPTION
**Pull request by jinhong-**
### Description
- Fix SPI mode typo
- Use software SPI library for software SPI mode
- Added timings/delays for sck and cs signals to match SPI speed

### Requirements

Software SPI now uses the `<SoftwareSPI.h>` dependency. Not quite sure which board is or is not compatible, but i assume it should be compatible with all

### Benefits

Using the software SPI library, SPI clock speed can now be regulated, hopefully this means more compatibility with boards of different speeds. So far this PR will work with SKR E3 Turbo

### Configurations

No additional configurations apart from the original settings to enable MAX31865

### Related Issues

Might Fix #22526

### CODE REVIEW

File: Marlin/src/libs/MAX31865.cpp [hunk 1]
```diff
@@ -81,6 +81,7 @@ SPISettings MAX31865::spiConfig = SPISettings(
     _mosi = spi_mosi;
     _miso = spi_miso;
     _sclk = spi_clk;
+    _spi_speed = swSpiInit(SPI_QUARTER_SPEED, SD_SCK_PIN, SD_MOSI_PIN);
```
Comment (slowbro) [inline Marlin/src/libs/MAX31865.cpp]: I think this should use `spi_mosi`, `spi_sck` since the SD Card pins will not always be used, so one could use arbitrary free pins for temp sensors. In this case, those are provided in the constructor. It looks like the actual/provided pins are used elsewhere; unsure if this is just a requirement for the setup routine or not.

Also, this disregards the speed selected in spiConfig above; can `_spi_speed` be integrated into or replace `spiConfig` above, as well as the `SPI_QUARTER_SPEED`?

File: Marlin/src/libs/MAX31865.cpp [hunk 2]
```diff
@@ -150,17 +152,16 @@ void MAX31865::begin(max31865_numwires_t wires, float zero, float ref) {
   Rzero = zero;
   Rref = ref;
 
-  OUT_WRITE(_cs, HIGH);
+  SET_OUTPUT(_cs);
+  write(_cs, HIGH);
```
Comment (slowbro) [inline Marlin/src/libs/MAX31865.cpp]: This change should be reverted. The macro `OUT_WRITE()` acheives both of these. In this case, the local `write()` is unneccesary.

File: Marlin/src/libs/MAX31865.cpp [hunk 3]
```diff
@@ -92,6 +93,7 @@ SPISettings MAX31865::spiConfig = SPISettings(
   MAX31865::MAX31865(int8_t spi_cs) {
     _cs = spi_cs;
     _sclk = _miso = _mosi = -1;
+    _spi_speed = swSpiInit(SPI_QUARTER_SPEED, SD_SCK_PIN, SD_MOSI_PIN);
```
Comment (slowbro) [inline Marlin/src/libs/MAX31865.cpp]: See above.

File: Marlin/src/libs/MAX31865.cpp [hunk 4]
```diff
@@ -458,19 +459,23 @@ void MAX31865::writeRegister8(uint8_t addr, uint8_t data) {
...
     SPI.endTransaction();
 
-  WRITE(_cs, HIGH);
+  write(_cs, HIGH);
 }
 
+void MAX31865::write(pin_t pin, bool value){
+  for (uint8_t i = 0; i < _spi_speed; i++)
+    WRITE(pin, value);
+}
```
Comment (slowbro) [inline Marlin/src/libs/MAX31865.cpp]: Does the SoftwareSPI library have a means of doing this, instead of calling `WRITE()` `_spi_speed` times? Perhaps also, instead of calling write in a loop, a `safe_delay()` call could be used here.

**Review by slowbro — CHANGES_REQUESTED** [review]

**Comment by jinhong-** [comment]
> Thank you for doing this! Much better than manual bitbang.

No worries! To be honest this is my first time submitting to a "firmware"-ish code base. I do mostly software programming. Not hardware/firmware. Real-time programming is quite distant from my field of expertise 😄

File: Marlin/src/libs/MAX31865.cpp (hunk 1 above)
Comment (jinhong-) [reply Marlin/src/libs/MAX31865.cpp]: Let me change this. This is definitely a bug. I copied and pasted the code from elsewhere and i forgot to change the pins

File: Marlin/src/libs/MAX31865.cpp (hunk 2 above)
Comment (jinhong-) [reply Marlin/src/libs/MAX31865.cpp]: I created a wrapper write function that writes signals to the pin according to the SPI speed. Not sure if this is an important step but I've had pretty good results in terms of stability of my max31865 with my SKR E3 turbo board

File: Marlin/src/libs/MAX31865.cpp (hunk 1 above)
Comment (jinhong-) [reply Marlin/src/libs/MAX31865.cpp]: >Also, this disregards the speed selected in spiConfig above; can _spi_speed be integrated into or replace spiConfig above, as well as the SPI_QUARTER_SPEED?

To be honest I am not too sure myself. From what I can tell, spiConfig has no accessible fields or functions to allow me to read the configuration that was passed in. I would assume the next best thing is to simply declare a separate private field which can be shared. What are your thoughts?

**Comment by jinhong-** [comment]
@slowbro i refactored the codes and removed the write function. Will test it later with my printer again to see if it works well

File: Marlin/src/libs/MAX31865.cpp (hunk 2 above)
Comment (thinkyhead) [reply Marlin/src/libs/MAX31865.cpp]: @slowbro — Note that FastIO macros like `WRITE` and `OUT_WRITE` require the first argument to be known at compile-time. They cannot take a variable, only a pin name or equivalent preprocessor define. If the pin is a variable, then the code must use `pinMode`, `digital_write`, etc.

File: Marlin/src/libs/MAX31865.cpp (hunk 4 above)
Comment (thinkyhead) [reply Marlin/src/libs/MAX31865.cpp]: Note that FastIO macros like `WRITE` and `OUT_WRITE` require the first argument to be known at compile-time. They cannot take a variable, only a pin name or equivalent preprocessor define. If the pin is a variable, then the code must use `pinMode`, `digital_write`, etc.

**Comment by thinkyhead** [comment]
Everything looks good to me. I look forward to hearing how well it actually works!

File: Marlin/src/libs/MAX31865.cpp (hunk 4 above)
Comment (jinhong-) [reply Marlin/src/libs/MAX31865.cpp]: @thinkyhead does this mean that calling `WRITE` this way does not actually do anything?

**Comment by jinhong-** [comment]
I've flashed my printer with new refactors and so far it works. Occasionally I get under/over voltage errors which requires me to do strange things to fix it. I suspect this is hardware related than software. Ordered an original adafruit max31865 to rule that out

File: Marlin/src/libs/MAX31865.cpp (hunk 4 above)
Comment (thinkyhead) [reply Marlin/src/libs/MAX31865.cpp]: Some of the HAL FastIO implementations simply call `digitalWrite` but others use direct port manipulation in a way that requires the pin to be a `#define`.

**Comment by Gotos** [comment]
Hi there!
Just FYI: This seems to have broken the build for my Teensylu clone board. For me, Arduino complained about not being able to find SoftwareSPI.h. Googling around for that file didn't really help me. This all happened despite me not even using a MAX31865 and thus not having it set up in configuration.h.

What did help was switching to Platform.IO (and if I had know how easy that is and how much quicker it compiles everything, I would have done so earlier anyway).
I'm not sure if I just did something wrong, but as this is working for me now, I mainly post this in case anyone else has the same problem and stumbles over this or in case this is actually considered a bug.

**Comment by ellensp** [comment]
This breaks MAX31865 on all platforms
Where does this <SoftwareSPI.h>  come from? 
It not in arduino ide or platfomio

**Comment by thinkyhead** [comment]
Sorry about that. I am too trusting of outside experts.

Does `#include <SPI.h>` fulfill the requirements? What about `#include "private_spi.h"`?

What configuration can I use to invoke compilation with `HAS_MAX31865 && !LIB_USR_MAX31865` for debugging?

**Comment by thinkyhead** [comment]
@jinhong — Not all platforms have a `<SoftwareSPI.h>` header available. These changes will have to be reverted until it can be determined which platforms are able to accommodate these changes, and which platforms must use the direct pin manipulation technique.

**Comment by jinhong-** [comment]
@thinkyhead sorry about that. I think a solution could be to use `#if defined` statements to switch between the implementations for now. I am no expert but for sure I am not able to get the original implementation to work with SKR e3 turbo. My best guess is that the SKR board uses a higher clocked processor at 120mhz, which is too fast for the SPI connection with a MAX31865 board

**Comment by thinkyhead** [comment]
I think the general issue is that the bit-banging SPI code has no delays in it, so it is bound to fail on any fast MCU. If the bit-banging code has to remain then it should be fixed, maybe based on the software SPI code from the library, which presumably has the correct delays.

**Comment by thinkyhead** [comment]
@Gotos, @ellensp — Please check whether #22682 takes care of the issue without breaking anything.

**Comment by Gotos** [comment]
Looks good, I just successfully compiled it in the Arduino IDE. Thanks!
