### PR TITLE
fixes #20961 Compile error in host_response_handler

### LINKED ISSUE #20961: [BUG] Can't compile with SDSUPPORT disabled
### Bug Description

Impossible to success a compilation when #define SDSUPPORT is disabled.

106402276-07122b00-6429-11eb-9b94-af680cf736e7

### Configuration Files

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/5901201/Configurations.zip)

### PR DESCRIPTION
**Pull request by ellensp**
### Description

host_response_handler() will not compile if SDSUPPORT is disabled 
Uses the following without checking for SDSUPPORT and M24_STR is only defined when using SDSUPPORT
```
          extern const char M24_STR[];
          queue.inject_P(M24_STR);
```
Added a check for SDSUPPORT

### Requirements

ADVANCED_PAUSE_FEATURE and HOST_PROMPT_SUPPORT with SDSUPPORT disabled

### Benefits

Compiles as expected 

### Configurations

[https://github.com/MarlinFirmware/Marlin/files/5901201/Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/5901201/Configurations.zip)

### Related Issues

Issue #20961

### CODE REVIEW

File: Marlin/src/feature/host_actions.cpp [hunk 1]
```diff
@@ -182,7 +182,7 @@ void host_action(PGM_P const pstr, const bool eol) {
         break;
       case PROMPT_PAUSE_RESUME:
         msg = PSTR("LCD_PAUSE_RESUME");
-        #if ENABLED(ADVANCED_PAUSE_FEATURE)
+        #if BOTH(ADVANCED_PAUSE_FEATURE,SDSUPPORT)
```
Comment (qwewer0) [inline Marlin/src/feature/host_actions.cpp]: A space is missing. 😛

Comment (discip) [reply Marlin/src/feature/host_actions.cpp:185]: That fixed my problem.
Thanks a ton. 👍

**Comment by discip** [comment]
That fixed my problem.
Thanks a ton. 👍

File: Marlin/src/feature/host_actions.cpp (hunk 1 above)
Comment (ellensp) [reply Marlin/src/feature/host_actions.cpp]: Ill get right on that, its the most important thing in the world to have just the correct amount of spaces. (apparently)
