### PR TITLE
Better support for "infinite" axes: Enable G92.9 (directly set current position) for rotational axes

### LINKED ISSUE #26220: [BUG] 8 Axis on Octopus, no longer compiles
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

8 axis example config no longer builds

### Bug Timeline

Since https://github.com/MarlinFirmware/Marlin/pull/25761

### Expected behavior

It should build

### Actual behavior

it errors with:
```
Marlin/src/HAL/STM32/../../inc/../core/types.h:982:68: error: expected unqualified-id before numeric constant
  982 |       bool LOGICAL_AXIS_LIST(E:1, A:1, B:1, C:1, _I:1, _J:1, _K:1, _U:1, _V:1, _W:1);
      |                                                                    ^~

```

### Steps to Reproduce

1. use Configs https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/examples/linear_axes/Octopus%208%20LINEAR_AXES
2. build
3. see the error

### Version of Marlin Firmware

Bugfix-2.1.x

### Electronics

Octopus

### Additional information & file uploads
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12494655/Configuration.zip)

### LINKED ISSUE #26335: 5 axis with rotation fails to compile.
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

```CPP
Marlin/src/module/motion.cpp:1164:83: error: 'const xyze_pos_t {aka const struct XYZEval<float>}' has no member named 'k'
           distance_sqr = ROTATIONAL_AXIS_GANG(sq(diff.i), + sq(diff.j), + sq(diff.k), + sq(diff.u), + sq(diff.v), + sq(diff.w));
                                                                                   ^
```

### Expected behavior

It should build

### Actual behavior

It has a compile error.

### Steps to Reproduce

1. Download https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/linear_axes/RAMPS%205%20LINEAR_AXES
2. replace default Config files with these configs
3. add   #define AXIS4_ROTATES to Configuration.h 
4. build

### Version of Marlin Firmware

Bugfix-2.1.x

### Electronics

RAMPS

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12874674/Configuration.zip)

Error comes from types.h, it has this code 

```CPP
#if HAS_ROTATIONAL_AXES
  #define ROTATIONAL_AXIS_GANG(V...) GANG_N(ROTATIONAL_AXES, V)
#endif

```

But this define is not called as HAS_ROTATIONAL_AXES is not set yet

#If HAS_ROTATIONAL_AXES is also used in Configuration_adv.h 
But is also not working as it is not set yet.

HAS_ROTATIONAL_AXES is set in inc/Conditionals_post.h to late.

### related
https://github.com/MarlinFirmware/Marlin/issues/26220
https://reprap.org/forum/read.php?146,893571,893596#msg-893596

### PR DESCRIPTION
**Pull request by DerAndere1**
### Description

- In principle, rotational axes can be infinite. But with Marlin, the user needs reset the current position of that axis to 0 regularly to prevent overflow of the position variables. The best configuration for an "infinite" rotational axis can be found below.
- Suppose we had rotational A axis and `//#define NO_WORKSPACE_OFFSETS`. In this scenario there was no way for the user to prevent overflow of the position variables. With this PR, `G92.9 A0` can be used to directly zero the positions of the rotational axes (A axis in this example).
- This PR Includes a hotfix (simplified) for rotational axes until a decision on PR https://github.com/MarlinFirmware/Marlin/pull/24334 is made 

### Requirements

Best to be used with an axis that can rotate infinitely. 
```
#define AXIS4_ROTATES
#define I_MIN_POS -9999999
#define I_MAX_POS  9999999
//#define MIN_SOFTWARE_ENDSTOP_I
//#define MAX_SOFTWARE_ENDSTOP_I
```

For rotational axes without a homing switch, this is required in addition:
```
#define I_HOME_DIR 0
#define MANUAL_I_HOME_POS 0 
```

For full testing, use a display with MarlinUI and also this:
```
#define INCH_MODE_SUPPORT
//#define NO_WORKSPACE_OFFSETS
#define CNC_COORDINATE_SYSTEMS
```

### Benefits

allow rotational axes to rotate without end

### Configurations
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/12329349/Config.zip)

### Related Issues
- Fix https://github.com/MarlinFirmware/Marlin/issues/26220
- Fix https://github.com/MarlinFirmware/Marlin/issues/26335
- https://github.com/MarlinFirmware/Marlin/issues/24901
- https://github.com/MarlinFirmware/Marlin/issues/24196
- https://github.com/MarlinFirmware/Marlin/pull/24334

### CODE REVIEW

File: Marlin/src/lcd/marlinui.cpp [hunk 1]
```diff
@@ -850,6 +854,16 @@ void MarlinUI::init() {
       if (axis != NO_AXIS_ENUM && ELAPSED(millis(), start_time) && !planner.is_full()) {
 
         const feedRate_t fr_mm_s = (axis < LOGICAL_AXES) ? manual_feedrate_mm_s[axis] : XY_PROBE_FEEDRATE_MM_S;
```
Comment (thinkyhead) [inline Marlin/src/lcd/marlinui.cpp]: Ideally the manual feed rate for rotational axes will _already_ be expressed in degrees-per-second. And then, rotational axes will not be affected by the mode being "inches" or "mm" because the axes are rotational. This is distinct from an axis that is part of a kinematic system (SCARA) where we convert mm to degrees behind the scenes.

File: Marlin/src/module/planner.cpp [hunk 2]
```diff
@@ -2008,8 +2008,8 @@ bool Planner::_populate_block(
   #endif
 
   SECONDARY_AXIS_CODE(
-    dm.i = (dist.i > 0), dm.j = (dist.j > 0), dm.k = (dist.k > 0),
-    dm.u = (dist.u > 0), dm.v = (dist.v > 0), dm.w = (dist.w > 0)
+    dm.i = (dist._i > 0), dm.j = (dist._j > 0), dm.k = (dist._k > 0),
+    dm.u = (dist._u > 0), dm.v = (dist._v > 0), dm.w = (dist._w > 0)
```
Comment (thinkyhead) [inline Marlin/src/module/planner.cpp]: The `AxisBits` struct members with underscores are just placeholders to fill out the `union` and are not intended to be acknowledged or used in code.

**Comment by thinkyhead** [comment]
The general problem remains that G-code commands only supply a single feed rate in terms of current units per second, but not all axes have a meaningful conversion from degrees to linear units. So a move that only involves a rotational axis and no others should be able to get its feed rate in terms of degrees-per-second (or radians-per-second if the machine is in Radians Mode). And on the LCD display an axis rotational position should be shown in degrees/radians too, or in some unit that is more pertinent to the application. It's challenging to devise a general approach to this.

**Comment by DerAndere1** [comment]
Indeed, I would say that  https://github.com/MarlinFirmware/Marlin/pull/24334 is the more complete solution regarding the feedrate for linear moves vs. rotation. I have not tested that PR in a while but it was working at some point. With PR 24334 merged, _this_ PR would be simplified to just add G92.9 for machines with rotational axes.

**Comment by thinkyhead** [comment]
> Indeed, I would say that https://github.com/MarlinFirmware/Marlin/pull/24334 is the more complete solution regarding the feedrate for linear moves vs. rotation. I have not tested that PR in a while but it was working at some point. With PR 24334 merged, this PR would be simplified to just add G92.9 for machines with rotational axes.

I agree that PR has the completeness advantage, but this PR can still be merged first and then we can take another look at #24334 and decide how best to apply it. With #24334 I was mainly stuck on how janky our support for rotational axes is in the planner, and I wonder if we could come up with a superior design.

This PR is largely non-disruptive and should only affect code size when there's one or more rotational axes and/or inches units support is turned on.
