### PR TITLE
Fix samd51 i2c eeprom issues

### LINKED ISSUE #17813: [BUG] i2c eeprom hangs on samd51
#17651 removed `eeprom_init` call from byte read/write functions but not to block counterpart (why removed partially?).
This PR causes in SAMD51 a hang when accessing i2s eeprom.

### PR DESCRIPTION
**Pull request by GMagician**
When i2c eeprom is enabled samd51 simply hangs on startup. Now it's fixed

Fix #17813

### CODE REVIEW

File: Marlin/src/HAL/SAMD51/eeprom_wired.cpp [hunk 1]
```diff
@@ -22,7 +22,7 @@
 
 #include "../../inc/MarlinConfig.h"
 
-#if USE_WIRED_EEPROM && DISABLED(QSPI_EEPROM)
```
Comment (GMagician) [inline Marlin/src/HAL/SAMD51/eeprom_wired.cpp]: Semantically speaking qspi is an hard wired eeprom, similar to any i2c eprom added on shields, but this is mounted directly on the board PCB, but yes this is really pedantry
