### PR TITLE
Fix ftmotion unstable step rate

### LINKED ISSUE #27344: [BUG] FT_MOTION produces strange sound
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

There is different, strange motion sound with FTM enabled (without IS). See also https://github.com/MarlinFirmware/Marlin/pull/26848#issuecomment-2171996308

Default:

https://github.com/user-attachments/assets/a528021b-1606-408a-b5ac-2508e3c0eff3

FTM:

https://github.com/user-attachments/assets/298ebe31-ec99-4332-a445-c81fecf39f6e

Spectrogram:
image

BTT 3.0, TMC 2209

I'll try to take oscillograms later.

### Bug Timeline

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

bugfix-2.1.x 2024-08-07

### Printer model

_No response_

### Electronics

_No response_

### LCD/Controller

_No response_

### Other add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/user-attachments/files/16569641/Marlin.zip)

### PR DESCRIPTION
**Pull request by dbuezas**
### Description

FTMotion is very noisy, and a logic analyser shows very clearly how it fails to generate a constant pulse rate:
image

It's expected that it generates two rate bands since it can only produce rates which are an integer fraction of FTM_STEPPER_FS, but it shouldn't generate half a dozen.

There were 3 main problems:

1. Bresenham error is reset between slices (i.e trajectory points). This changes the phase of the pulse train on every FTM_TS seconds (default setting is 1 millisecond). This is somewhat hidden by stepping only when the error crosses FTM_CTS_COMPARE_VAL (so it steps at half a denominator), but that still makes uneven rates.
2. The bresenham nominator (delta) is calculated as `traj[idx]*steps_per_mm - steps`, so any error accumulated in one slice is compensated by going faster in the next one. The correct way is to rely on a persistent (static) fractional error variable.
3. The bresenham nominator (delta) is calculated per slice (1 ms) as an integer, so at low speeds it has awful resolution. This accumulates error across the whole slice (goes too slow) which is then also corrected in the next one by going too fast. For example, if at slow speeds, an axis travels at 2.5 steps per slice, it will do only 2 in the first one, and then it will do 3 in the next one and so on.

This PR fixes them like this:
1. Keep bresenham error vector across slices (static variable)
2. Calculate delta as `(traj[idx] - traj[idx-1]) * steps_per_mm`, this way rates are consistent across slices. Step error doesn't accumulate since it is kept across slices. ~~The only disadvantage is that after any move we may be ±1 step away from the target, but that only happens once per direction change so it doesn't accumulate.~~ **FIXED**
3. Use a scaler for the  bresenham nominator and denominator to increase resolution (1<<10)

As a bonus I also:
1. Renamed variables and functions to be more representative. This also makes many comments unnecessary. I would have let them as they were, but I was having a hard time understanding the code.
2. Also refactored the macros in the function that generates the stepper commands, which were very hard to follow. They should be slightly more efficient too since there's no function call indirections anymore.

### Result

image
image

Rates are constant (only the expected 2 bands) and steppers are silent.

Note: The fact that each band jumps a tiny bit is just quantisation error in my logic analyzer. It goes away if I use higher acquisition rate. All pulse trains show very good consistency on each of the (maximum) two bands.

### Requirements

Enable FTMotioon

### Benefits

Silent steppers that don't resonate and cause layer shifts

### Configurations

#define FT_MOTION

### Related Issues

Solves [#ft_motion](https://github.com/MarlinFirmware/Marlin/issues/27344)

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Cc: @narno2202

**Comment by thinkyhead** [comment]
It makes sense to me! I will put this on the BIQU BX for testing tomorrow and see what happens.

File: Marlin/src/module/ft_motion.cpp [hunk 1]
```diff
@@ -644,109 +646,98 @@ void FTMotion::makeVector() {
...
+    do {                                                    \
+      if (step_error_q10.A >= denom_q10) {                  \
+        step_error_q10.A -= denom_q10;                      \
+        cmd |= _BV(FT_BIT_DIR_##A) | _BV(FT_BIT_STEP_##A);  \
+      }                                                     \
+      if (step_error_q10.A <= -denom_q10) {                 \
+        step_error_q10.A += denom_q10;                      \
+        cmd |= _BV(FT_BIT_STEP_##A); /* neg dir implicit */ \
+      }                                                     \
+    } while (0);
```
Comment (thinkyhead) [inline Marlin/src/module/ft_motion.cpp:725]: I presume this has been tested, but it seems like this should be doing something more like the following, because it is used within a loop of `FTM_STEPS_PER_UNIT_TIME`:
```cpp
  constexpr int32_t one_q10 = _BV(10);
  #define RUN_AXIS(A)                                       \
    do {                                                    \
      if (step_error_q10.A >= one_q10) {                    \
        step_error_q10.A -= one_q10;                        \
        cmd |= _BV(FT_BIT_DIR_##A) | _BV(FT_BIT_STEP_##A);  \
      }                                                     \
      if (step_error_q10.A <= -one_q10) {                   \
        step_error_q10.A += one_q10;                        \
        cmd |= _BV(FT_BIT_STEP_##A); /* neg dir implicit */ \
      }                                                     \
    } while (0);
```
Does that make sense?

File: Marlin/src/module/ft_motion.cpp [hunk 2]
```diff
@@ -644,109 +646,98 @@ void FTMotion::makeVector() {
...
+    // Reference the next stepper command in the circular buffer
+    ft_command_t& cmd = stepperCmdBuff[stepperCmdBuff_produceIdx];
+
+    // Init the command to no STEP (Reverse DIR)
     cmd = 0;
 
-    // Accumulate the errors for all axes
-    err_P += delta;
+    // Accumulate the "error" for all axes according the fixed-point distance
+    step_error_q10 += delta_q10;
```
Comment (thinkyhead) [inline Marlin/src/module/ft_motion.cpp:735]: …and in that case this line would be placed above the loop since it covers the whole UNIT_TIME covered by each individual call to `generateStepsFromTrajectory`.

**Comment by dbuezas** [comment]
Thanks for looking into it Scott!  

I see you liked the function renames but not the flag renames.  I still find myself needing to go back to read the comments and check usage each time I go come across one of the flags.  

M wish is that the flags indicating the state of each step are named in the same way as their buffers and functions, to reduce mental indirection when reading the code.  

I understand this makes reviewing the diff harder, but imho it improves readability of the resulting code quite a bit (particularly when reading it for the first time) 

The processing flow is:  
```
block -> trajectory -> postprocessed_trajectory -> stepper_steps vector
```

The states the flags define are:
- A block may or may not be active and ready to be converted into trajectory
- Trajectory (referred to as traj, vector, batch or window) may be empty, full but not post processed, or postprocessed and ready to be converted into steps  
- Converting to stepper steps is referred to as interp  

---

| Current name | Current description | Flag renaming suggestions |
|---|---|---|
| Flag: `blockProcRdy`<br><br>Buffer: `block`<br>Fn: `loadBlockData` | // Set when new block data is loaded from stepper module into FTM, ...<br>// ... and reset when block is completely converted to FTM trajectory. | Flag: `isBlockInProgress`, `isBlockActive`, `isBlockLoaded`, `isBlockReadyForTrajectory`, `isBlockOpen` |
| Flag `batchRdy`<br><br>Buffer: `traj`<br>Fn: `generateTrajectoryPointsFromBlock` | // Indicates a batch of the fixed time trajectory...<br>// ... has been generated, is now available in the upper -<br>// batch of traj.x[], y, z ... e vectors, and is ready to be<br>// post processed, if applicable, then interpolated. Reset when the<br>// data has been shifted out. | Flag: `isTrajBufferFull`, `isTrajReadyForPostprocess`, `isTrajGenerated`, `doesTrajNeedPostprocess`, `isTrajReadyForMod` |
| Flag: `batchRdyForInterp`<br>Buffer: `trajMod`<br>Fn: `generateStepsFromTrajectory` | // The batch has been post processed (if applicable) and is ready to be converted to step commands. | Flag: `isTrajBufferPostProcessed`,  `isTrajModReadyForSteps`, `isTrajPostProcessed` |
| Flag: none<br>Buffer: `stepperCmdBuff` |  | We could call it `stepperSteps` but this didn't confuse me anyway |

---

What confuses me (particularly on first read) about the current naming:

* `blockProcRdy`: Readily processed or ready to be processed?
* `batchRdy`: What's a batch? traj batch, trajMod batch or stepper command batch?
* `batchRdyForInterp`: What batch, and how's interp :P ?

I think these renames even make some comments obvious. For example in this function I really don't know what i going on:

```cpp
if (blockProcRdy) {
    if (!batchRdy) makeVector(); // Caution: Do not consolidate checks on blockProcRdy/batchRdy, as they are written by makeVector().
    // When makeVector is finished: either blockProcRdy has been set false (because the block is
    // done being processed) or batchRdy is set true, or both.

    // Check if the block has been completely converted:
    if (!blockProcRdy) {
      discard_planner_block_protected();

      // Check if the block needs to be runout:
      if (!batchRdy && !planner.has_blocks_queued()) {
        runoutBlock();
        makeVector(); // Do an additional makeVector call to guarantee batchRdy set this loop.
      }
    }
  }

```

With the renames, the comments become obvious and could even be removed.
```cpp
  if (isBlockLoaded) {
    if (!isTrajBufferFull) generateTrajectoryPointsFromBlock();  // Caution: Do not consolidate checks on isBlockLoaded/isTrajBufferFull, as they are written by generateTrajectoryPointsFromBlock().
    // When generateTrajectoryPointsFromBlock is finished: either isBlockActive has been set false (because the block is
    // done being processed) or isTrajBufferFull is set true, or both.

    // Check if the block has been completely converted:
    if (!isBlockLoaded) {
      discard_planner_block_protected();
      // Check if the block needs to be runout:
      if (!isBlockLoaded && !planner.has_blocks_queued()) {
        runoutBlock();
        generateTrajectoryPointsFromBlock(); // Do an additional call to guarantee batchRdy set this loop.
      }
    }
  }

```

I hope you consider these :).

Oh a small request: rebase instead of merging. Merges make it really hard to me to pick your changes back into my private branch for my printer where I also have a bunch of other stuff going on.

File: Marlin/src/module/ft_motion.cpp (hunk 1 above)
Comment (dbuezas) [reply Marlin/src/module/ft_motion.cpp:725]: Yes tested.

Ignoring the 1<<10 scaling for clarity:

* the delta (nominator) contains how many steps to do for the whole FTM_TS (or slice, which is 1ms). This is because it is calculated as the distance between trajectory points, which are spaced by 1ms.
* the denominator contains how many microticks (FTM_STEPS_PER_UNIT_TIME) there are in a slice.

For example, say x must do 6 steps in the whole slice (i.e in 1ms), and there are 20 FTM_STEPS in one slice (FTM_STEPS_PER_UNIT_TIME=20)

Then:
```
delta_x = 6
denom = 20
```

step_error would go like this:
```
0 -> 6 -> 12 -> 18 -> 24 [step here!]
```

So both delta and denom come scaled by FTM_STEPS_PER_UNIT_TIME.

The 1<<10 scaling just adds resolution to the delta_x, so delta_x can be for example 6.5, and the error (or remainder) can see that higher resolution.

File: Marlin/src/module/ft_motion.cpp (hunk 2 above)
Comment (dbuezas) [reply Marlin/src/module/ft_motion.cpp:735]: We want to keep track of how error accumulates per stepper command. If we would just accumulate error for the whole slice, then'd accumulate all of it and make all steps together at the beginning of each slice.

File: Marlin/src/module/ft_motion.cpp (hunk 1 above)
Comment (dbuezas) [reply Marlin/src/module/ft_motion.cpp:725]: In a nutshell, error (reminder) per microtick is `delta/FTM_STEPS_PER_UNIT_TIME`, but instead of adding fractional numbers we just add the whole delta, and then instead of stepping when it reaches 1, we step when it reaches FTM_STEPS_PER_UNIT_TIME.

The extra 1<<10 scaling is made because the the delta is computed from trajectory, which is a float in mm.

File: Marlin/src/module/ft_motion.cpp (hunk 2 above)
Comment (dbuezas) [reply Marlin/src/module/ft_motion.cpp:735]: I think I see where the confusion comes from: we accumulate error per microtick as if it was for the whole slice, but the denominator is also the number of microticks per slice, both nominator and denominator come multiplied by  FTM_STEPS_PER_UNIT_TIME

**Comment by dbuezas** [comment]
@thinkyhead I saw you reviewing the PR in the live stream!
The ±1 step was a truncation issue: on direction changes, truncation was biasing a tiny error towards one direction instead of centring it towards zero. Now steps are exact.

File: Marlin/src/module/ft_motion.cpp (hunk 1 above)
Comment (thinkyhead) [reply Marlin/src/module/ft_motion.cpp:725]: I see. That makes perfect sense. It's Bresenhammy, not Thresholdy!

File: Marlin/src/module/ft_motion.cpp (hunk 2 above)
Comment (thinkyhead) [reply Marlin/src/module/ft_motion.cpp:735]: It makes perfect sense now! We are operating in `FTM_STEPS_PER_UNIT_TIME` scale, and the loop is `FTM_STEPS_PER_UNIT_TIME` units long, so by the power of Bresenham it's guaranteed to run `FTM_STEPS_PER_UNIT_TIME` tick events, potentially up to `FTM_STEPS_PER_UNIT_TIME` whole steps.

Now maybe I can help figure out this fractional remainder stuff!

**Comment by thinkyhead** [comment]
Thanks for tuning in… See me roast your PRs on YouTube every week!

I'm glad to hear the "off-by-one" issue is resolved, and it wasn't too difficult.

The flag names I wanted to retain (`batchRdy...`) make more sense to me, because they better reflect how the batch processor uses them. The state of the trajectory buffer being full (`isTrajBufferFull`) would tend to persist until ??, but the flag `batchRdy` is cleared as soon as it's noted by the batch processor. The trajectory buffer being post-processed (`isTrajBufferPostProcessed`) is literally the case, but why does Batchy 9000 care? To the batch processor it is `...RdyForInterp`. The flags being batch-centric means these flag names remain the same even if the logic does not involve "trajectory buffers" _per se_.

So that's my thought about those specific flags.

When working with a PR it is always better to merge rather than rebase, because upon rebase the other participants cannot use Github Desktop to to fetch the changes. They have to delete and re-fetch or use command-line. So I would not myself do a complete _**rebase and force-push**_ to a PR. (I do use force-push to cancel wasteful CI checks for small changes if I think no one will be disrupted at that moment.) That said, since it is your PR initially, you can either rebase and force-push it yourself, or you can ask me to do a rebase and force-push at a specific time. That way I know (hopefully) I won't be stepping on anything.

File: Marlin/src/module/ft_motion.cpp [hunk 3]
```diff
@@ -644,109 +646,101 @@ void FTMotion::makeVector() {
...
-
-    ft_command_t &cmd = stepperCmdBuff[stepperCmdBuff_produceIdx];
-
-    // Init all step/dir bits to 0 (defaulting to reverse/negative motion)
+void FTMotion::generateStepsFromTrajectory(const uint32_t idx) {
+  // Round to nearest (lrintf) to avoid truncation’s sign bias.
+  // Truncating toward zero drops the first small increment after a direction flip,
+  // which shows up as a missing step. Rounding prevents that.
+  #define TOSTEPS_q10(A, B) \
+    lrintf((trajMod.A[idx] - prev_traj_point.A) * \
```
Comment (thinkyhead) [inline Marlin/src/module/ft_motion.cpp]: "Wait, that's not you spell `printf`!"

**Comment by dbuezas** [comment]
Ok, got it.

**Comment by dbuezas** [comment]
The names still make the code harder to follow to me, but it is ofc your call.

File: Marlin/src/module/ft_motion.cpp (hunk 3 above)
Comment (thinkyhead) [reply Marlin/src/module/ft_motion.cpp]: Anyway… We can be more explicit and use the standard `LROUND`. (No guarantee of `FE_TONEAREST`.)

Comment (dbuezas) [reply Marlin/src/module/ft_motion.cpp]: I'm thinking ver deeply about this fix, and I think it just makes ±1 steps less likely, not impossible.
Actually, if one were to engineer a specific sequence of moves, I think one could even force it to drift:
* move forward such that the steps per unit of time have a 0.4 decimal after scaling
* move backwards at a speed that makes integer steps per unit of time
* repeat 

axis drifted.

The steps cannot be made exact on each time unit, because that causes rates that change every ms and unnecessarily so: the steps can easily align in a way such that every second trajectory point causes an extra step, and we don't want to correct for that, it fixes itself in the very next call to generate stepper commands.

We can't ask it to use stable rates and also exactly match step counts ~~at arbitrary places~~ **everywhere ** at the same time.

What we can do though is add a guard on the last generateStepsFromTrajectory of the block. If steps are still off, add a correction to the accumulator (error). The next block will then start by correcting the drift.

This ensures there is no drift, while also keeping silent rates that don't make the steppers  resonate or make noises. WDYT?

File: Marlin/src/module/ft_motion.cpp (hunk 1 above)
Comment (dbuezas) [reply Marlin/src/module/ft_motion.cpp:725]: Exactly, that's the idea. This way we can get stable step rates

**Comment by dbuezas** [comment]
With the latest fix I can't reproduce any off by 1 steps or drift. I declare the potential issue as FIXED!

I went back to comparing against step counts to avoid drift (as original), but with a big twist:
The delta calculation takes into account the accumulated bresenham error.

This (together with the resolution scaling, persistent step_error and modified stepping algorithm), results in phase correct, stable rate step train, which also can't drift since it always compares the target against the actual count of steps that were made. I'm so happy, I really doubted there was a way! (there's always a way :tada: )

I had to rebase to be able to test the version with your changes in my custom machine, so I also had to force push. (@thinkyhead) I discarded the commit that removed the step counter (I'm using it again now).

I'm a lot happier with this solution

**Comment by dbuezas** [comment]
PXL_20250908_215449037

It benchies. ZVD is quite impressive. The print was silent except for gyroid that made the extruder scream, but that's a job for smoothLA (soon).

File: Marlin/src/module/ft_motion.cpp (hunk 3 above)
Comment (dbuezas) [reply Marlin/src/module/ft_motion.cpp]: Solved differently

**Comment by thinkyhead** [comment]
Ok, the changes all seem sensible and well-defined, and the correction in behavior should definitely help with the reputation of this new feature. Will merge this soon!

We are not quite at the level of perfect yet with this big update. Nevertheless, I will aim to tag 2.1.3 for release this weekend for the benefit of our friends attending 3DPrintopia. Then we can address issues discovered by the wider community in future 2.1.3.x updates.

CC: @ulendoalex

**Comment by dbuezas** [comment]
Thanks @thinkyhead , I opened 2 more PRs, and a third is pending for axis smoothing (including smoothLA). All together should make Ftmotion the preferred motion system for 32bit machines.
