### PR TITLE
Fix M23 select long filename for print

### LINKED ISSUE #25497: [BUG] Selecting file for printng with `M23` by it's long filename does not work
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Even with `LONG_FILENAME_HOST_SUPPORT` and `LONG_FILENAME_WRITE_SUPPORT` defines, selecting a file for printing with `M23` by the long file name does not work.

### Bug Timeline

_No response_

### Expected behavior

Selecting a file for printing with `M23` works

### Actual behavior

Selecting a file by it's long filename fails

### Steps to Reproduce

1. Insert SD card with a file that has long filename (non-DOS compatible), e.g. `longfilename.gcode`
2. In Serial console issue `M21` command
3. In Serial console issue `M20 L` command. Verify that the file is there and reported with both DOS filename and Long filename (`LONGFI~1.GCO` and `longfilename.gcode`) 
4. In Serial console issue `M23 longfilename.gcode` to select the file

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

_No response_

### Electronics

_No response_

### Add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I have added a bunch of `DEBUG_ECHO*` calls that mostly duplicate code comments, into `SdBaseFile.cpp`, inside the method with following signature:
```cpp
// open with filename in dname and long filename in dlname
bool SdBaseFile::open(SdBaseFile *dirFile, const uint8_t dname[11]
    OPTARG(LONG_FILENAME_WRITE_SUPPORT, const uint8_t dlname[LONG_FILENAME_LENGTH])
  , uint8_t oflag
)
```
and here's the sample serial console log:
```
ttyACM0 21°> M20 L
SENDING:M20 L
Begin file list
LONGF~1.GCO 758868 LONGF~1.GCO
LONGFI~1.GCO 902501 longfilename-1.gcode
LONGFI~2.GCO 879788 longfilename-2.gcode
SAMPLE~1.GCO 921715 sample_long_name.gcode
TEMP.GCO 444974 TEMP.GCO
End file list
ttyACM0 21°> M23 /longfilename-1.gcode
SENDING:M23 /LONGFILENAME-1.GCODE
Now fresh file: /LONGFILENAME-1.GCODE
>>> diveToFile  X0.00 Y208.00 Z0.00
 path = '/LONGFILENAME-1.GCODE'
 CWD to root: 0x200032D4
 startDirPtr = 0x200032D4
 final workDir = 0x200032D4
 returning string LONGFILENAME-1.GCODE
<<< diveToFile  X0.00 Y208.00 Z0.00
>>> SdBaseFile::open()  X0.00 Y208.00 Z0.00
 dname: LONGF~18GCO
 reqEntriesNum: 3 lfnNameLength: 20
 search for file
/  absolute index position: 0
  p->name: PRINT
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
/  absolute index position: 1
  p->name: LONGF~1 GCO
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
/  absolute index position: 2
  p->name: B1
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
       isDirLFN(p)
       lfnSequenceNumber: 2
        Check checksum for all other entries with the starting checksum fetched before
         Set chunk of LFN from VFAT entry into lfnName
         LFN found?:          lfnFileFound: 0
/  absolute index position: 3
  p->name: l
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
       isDirLFN(p)
       lfnSequenceNumber: 1
        Check checksum for all other entries with the starting checksum fetched before
         Set chunk of LFN from VFAT entry into lfnName
         LFN found?:          lfnFileFound: 0
/  absolute index position: 4
  p->name: LONGFI~1GCO
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
/  absolute index position: 5
  p->name: B2
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
       isDirLFN(p)
       lfnSequenceNumber: 2
        Check checksum for all other entries with the starting checksum fetched before
         Set chunk of LFN from VFAT entry into lfnName
         LFN found?:          lfnFileFound: 0
/  absolute index position: 6
  p->name: l
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
       isDirLFN(p)
       lfnSequenceNumber: 1
        Check checksum for all other entries with the starting checksum fetched before
         Set chunk of LFN from VFAT entry into lfnName
         LFN found?:          lfnFileFound: 0
/  absolute index position: 7
  p->name: LONGFI~2GCO
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
/  absolute index position: 8
  p->name: Ba
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
       isDirLFN(p)
       lfnSequenceNumber: 2
        Check checksum for all other entries with the starting checksum fetched before
         Set chunk of LFN from VFAT entry into lfnName
         LFN found?:          lfnFileFound: 0
/  absolute index position: 9
  p->name: s
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
       isDirLFN(p)
       lfnSequenceNumber: 1
        Check checksum for all other entries with the starting checksum fetched before
         Set chunk of LFN from VFAT entry into lfnName
         LFN found?:          lfnFileFound: 0
/  absolute index position: 10
  p->name: SAMPLE~1GCO
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
/  absolute index position: 11
  p->name: TEMP    GCO
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     useLFN
      !lfnFileFound
/  absolute index position: 12
  p->name:
  Check empty status: Entry empty
<<< SdBaseFile::open()  X0.00 Y208.00 Z0.00
open failed, File: LONGFILENAME-1.GCODE.
ttyACM0 21°> M23 /LONGFI~1.GCO
SENDING:M23 /LONGFI~1.GCO
Now fresh file: /LONGFI~1.GCO
>>> diveToFile  X0.00 Y208.00 Z0.00
 path = '/LONGFI~1.GCO'
 CWD to root: 0x200032D4
 startDirPtr = 0x200032D4
 final workDir = 0x200032D4
 returning string LONGFI~1.GCO
<<< diveToFile  X0.00 Y208.00 Z0.00
>>> SdBaseFile::open()  X0.00 Y208.00 Z0.00
 dname: LONGFI~1GCO
 reqEntriesNum: 1 lfnNameLength: 0
 search for file
/  absolute index position: 0
  p->name: PRINT
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     !useLFN
/  absolute index position: 1
  p->name: LONGF~1 GCO
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     !useLFN
/  absolute index position: 2
  p->name: B1
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     !useLFN
/  absolute index position: 3
  p->name: l
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     !useLFN
/  absolute index position: 4
  p->name: LONGFI~1GCO
  Check empty status: Entry not empty
    Reset empty counter
    Search for SFN or LFN?
     !useLFN
      fileFound: 1
<<< SdBaseFile::open()  X0.00 Y208.00 Z0.00
File opened: LONGFI~1.GCO Size: 902501
File selected
ttyACM0 21°>
```

As can be clearly seen in
```
>>> SdBaseFile::open()  X0.00 Y208.00 Z0.00
 dname: LONGF~18GCO
 ```
the short filename composed to lookup the file by was wrong (and presumably pretty much random), which didn't match the actual short name of a file and thus selecting a file failed.

### PR DESCRIPTION
**Pull request by eduard-sukharev**
### Description

When Marlin scans VFAT sequences to compose a LFN to be compared with provided one, the actual LFN is UTF-16LE, while provided filename is supposedly a UTF-8. This commit extracts existing conversion logic and reuses it when searching for file by its LFN.

### Benefits

It is now possible to select a file for printing via Serial console with M23 by LFN

### Configurations

```cpp
#define UTF_FILENAME_SUPPORT
```

### Related Issues

This should fix #25497

### CODE REVIEW

**Comment by eduard-sukharev** [comment]
Testing shows that it works for `/longfilename.gcode`, but doesn't work for `/longdirectory/F.GCO` - somehow LFNs in dirnames are still broken when selecting file for print

**Comment by eduard-sukharev** [comment]
> Testing shows that it works for `/longfilename.gcode`, but doesn't work for `/longdirectory/F.GCO` - somehow LFNs in dirnames are still broken when selecting file for print

Ok, that's resolved - it was not working because temporary `lfnName` variable was dirty and `/longdirectory` turned into `/longdirectory1.gcode` because of `/longfilename-1.gcode` file that was parsed first.

File: Marlin/src/sd/SdBaseFile.cpp [hunk 1]
```diff
@@ -1506,44 +1512,53 @@ int8_t SdBaseFile::readDir(dir_t *dir, char *longFilename) {
     // Post-process normal file or subdirectory longname, if any
     if (DIR_IS_FILE_OR_SUBDIR(dir)) {
       #if ENABLED(UTF_FILENAME_SUPPORT)
```
Comment (eduard-sukharev) [inline Marlin/src/sd/SdBaseFile.cpp:1512]: Although this is the original behavior, I guess UCS-2 to UTF-8 conversion should be done always, since VFat always stores long names as UCS-2 (UTF-16) in LFN sequences, while we always handle 8bit string names.

File: Marlin/src/sd/SdBaseFile.cpp [hunk 2]
```diff
@@ -703,14 +703,18 @@ bool SdBaseFile::open(SdBaseFile *dirFile, const uint8_t dname[11]
               // Get VFat dir entry
               pvFat = (vfat_t *) p;
               // Get checksum from the last entry of the sequence
-              if (pvFat->sequenceNumber & 0x40) lfnChecksum = pvFat->checksum;
+              if (pvFat->sequenceNumber & 0x40) {
+                lfnChecksum = pvFat->checksum;
+                memset(lfnName, '\0', sizeof(lfnName));
```
Comment (thinkyhead) [inline Marlin/src/sd/SdBaseFile.cpp]: Do we need to clear the whole buffer here to ensure a null terminator later, or can we get away with just `lnfName[0] = '\0'`?

**Comment by thinkyhead** [comment]
Overall it looks good. Thanks for the fix! Long filenames are important going forward. We've had to keep our own implementation of `SDFat` in Marlin for legacy reasons and to keep the code minimal, but at this point maybe there's a good lightweight but thorough Arduino-based FAT library that we should adopt for the future. (One of many things that we've been mulling over but haven't gotten around to yet.)

File: Marlin/src/sd/SdBaseFile.cpp (hunk 2 above)
Comment (eduard-sukharev) [reply Marlin/src/sd/SdBaseFile.cpp]: No, I guess it wouldn't work: `lfnName` is filled from the end of the actual LFN found in VFAT sequences (which appear in reverse order; see method `getLFNName`), which means just using `lfnName[0] = '\0'` wouldn't suffice.
However, the code below 
```cpp
if (!strncasecmp((char*)dlname, (char*)lfnName, lfnNameLength)) lfnFileFound = true;
```
compares these chararrays up until `lfnNameLength`, which is initialized as
```cpp
lfnNameLength = useLFN ? strlen((char*)dlname) : 0,
```
above, which means we should compare these strings up until requested part length. Which means, yes, we probably don't even need this line at all and it should work OK for comparison.

Comment (eduard-sukharev) [reply Marlin/src/sd/SdBaseFile.cpp]: Although, on second thought, If we remove the `memset`, then we're probably prone to error cases.
Let's assume we have files:
```
/my_cool_model.gcode
/important.log
/important.log.gcode
```
then, in certain conditions,  attempting to open `/important.log.gcode` will actually open `/important.log` file.

**Comment by eduard-sukharev** [comment]
This solves the selection of a file by LFN only in root of an SD card. Selecting within LFN directory is still broken and should be addressed separately.

File: Marlin/src/sd/SdBaseFile.cpp (hunk 2 above)
Comment (thinkyhead) [reply Marlin/src/sd/SdBaseFile.cpp]: Generally, when copying strings into buffers we should append a nul after writing the other bytes. This avoids the need to clear the whole buffer before the copy. The `memset` might use some extra electrons, but it's minor thing in practical terms. Only the code size ultimately matters, not the performance, since this is not a bottleneck.
