### PR TITLE
Fix STM32F1 SPI device init, MKS_LCD12864

### LINKED ISSUE #19159: [BUG] MKS GEN L V1.0 + MKS LCS 12864A no display
### Bug Description
I tried several suggestions but still - LCD only lits up, without any display.

### My Configurations
MKS Gen L  + MKS LCD12864A V1.0
compiled in Visual Studio Code

[Settings.zip](https://github.com/MarlinFirmware/Marlin/files/5130131/Settings.zip)

### Steps to Reproduce

1. Change settings to have 
#define MOTHERBOARD BOARD_MKS_GEN_L  
#define MKS_LCD12864
2. Complie
3. Have small blue light lamp instead of printers display

**Expected behavior:** 
Graphical status display

**Actual behavior:**
Modern art installation

#### Additional Information

I tried delays changing, brightness change, different board (SKR 1.3) all with no results. Is it possible that pins are not correctly defined for this one or any other known issue?

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

Some PINs file have `ENABLE_SPI2`, to select the SPI 2 as the main device. But the current code start the SPI object with the SPI 1.
If any code try to use SPI before calling `spiInit` function (that set it according to board pins), the SPI will not work.

And this is the problem with #19269 . The LCD code in u8glib don't call `spiInit`, it rely on the current SPI selected from the global SPI object.

The MKS fix call SD card mount in the init of marlin code. The SD mount code call `spiInit`, putting the SPI to the right device, so its the reason why LCD works after the sd card mount. That SD mount just hide the real problem.

This fix start the SPI object with according with the board definition. It solves the problem in the root cause.

@thisiskeithb tested it and solved the LCD problem.

~But it generate other issue: a very long boot time, that I'm looking for and `SD Init Fail error`~. We check and that issue always happens, even with the old and mks pr. It's a boot loader issue. The delay happens before marlin ever starts.

### Benefits

- Fix STM32F1 HAL SPI default device
- Fix #19159

### Related Issues

#19269 
#19159

### CODE REVIEW

File: Marlin/src/HAL/STM32F1/SPI.cpp [hunk 1]
```diff
@@ -710,6 +710,10 @@ static spi_baud_rate determine_baud_rate(spi_dev *dev, uint32_t freq) {
   return baud_rates[i];
 }
 
-SPIClass SPI(1);
+#if SPI_DEVICE == 1
+  SPIClass SPI(1);
+#else
+  SPIClass SPI(2);
+#endif
```
Comment (sjasonsmith) [inline Marlin/src/HAL/STM32F1/SPI.cpp]:
```suggestion
SPIClass SPI(SPI_DEVICE);
```



Here is the code from `spi_pins.h` that allows for three SPI devices. The SKR Mini V1.1 (NOT the E3 Mini) defines `ENABLE_SPI3`. Might as well just use the constant directly.

```
#if ENABLED(ENABLE_SPI3)
  #define SPI_DEVICE 3
#elif ENABLED(ENABLE_SPI2)
  #define SPI_DEVICE 2
#else
  #define SPI_DEVICE 1
#endif
```

Comment (rhapsodyv) [reply Marlin/src/HAL/STM32F1/SPI.cpp]: HAHAH, for sure. I'm too concentred in the lcd and the code that just made a stupid if :-p

**Comment by thisiskeithb** [comment]
> But it generate other issue: a very long boot time, that I'm looking for and SD Init Fail error

To add to this, it's only an issue if you boot with an SD card inserted and it takes 30 seconds (vs. booting without one which only takes ~3 seconds). After Marlin is done booting, inserting an SD card works fine and I get a `Media Inserted` message instead of `SD Init Fail`.

**Review by sjasonsmith — APPROVED** [review]

**Comment by thisiskeithb** [comment]
To save you from reading all the text below, this is likely a board/bootloader issue causing a 30 second delay when cold booting with an SD card inserted and not a Marlin issue.

---

I tried some additional LCD controllers on the Robin E3 board and still get the 30 second lockup on boot with an SD card inserted:
-`MKS_MINI_12864`
-`MKS_LCD12864`
-`REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`
-`CR10_STOCKDISPLAY` (using onboard slot)*

\* _Note: Onboard SD card pins are shared with the LCD controller pins on this board_

Working with @rhapsodyv on Discord, it's likely the board/bootloader since I don't get serial output from Marlin until right after that 30 seconds and Marlin appears to boot normally (except for the SD Init Fail error):

```log
15:07:58.806 -> echo:[178] HAL_init()
15:07:58.806 -> echo:[178] setup_killpin()
15:07:58.806 -> echo:[178] tmc_serial_begin()
15:07:58.806 -> echo:[181] setup_powerhold()
15:07:58.806 -> echo:[183] esp_wifi_init()
15:07:58.806 -> PowerUp
15:07:58.806 -> Marlin bugfix-2.0.x
15:07:58.840 -> 
15:07:58.840 -> echo: Last Updated: 2020-09-05 | Author: (thisiskeithb, Ender-3)
15:07:58.840 -> echo:Compiled: Sep  5 2020
15:07:58.840 -> echo: Free Memory: 24503  PlannerBufferBytes: 3456
15:07:58.840 -> echo:[201] ui.init()
15:07:58.840 -> echo:[202] ui.show_bootscreen()
15:08:03.059 -> echo:[4427] ui.reset_status()
15:08:03.059 -> echo:[4427] settings.first_load()
15:08:04.228 -> echo:V81 stored settings retrieved (670 bytes; crc 40203)
15:08:04.228 -> echo:[5588] thermalManager.init()
15:08:04.477 -> echo:[5840] print_job_timer.init()
15:08:04.477 -> echo:[5841] endstops.init()
15:08:04.477 -> echo:[5841] stepper.init()
15:08:04.477 -> echo:[5843] watchdog_init()
15:08:04.477 -> echo:[5846] test_tmc_connection(0x1, 0x1, 0x1, 0x1)
15:08:04.477 -> Testing X connection... OK
15:08:04.511 -> Testing Y connection... OK
15:08:04.511 -> Testing Z connection... OK
15:08:04.511 -> Testing E connection... OK
15:08:04.511 -> echo:[5887] setup() completed.
15:08:04.511 -> SD: Status changed from 2 to 1
15:08:07.041 -> echo:No SD card
```

@makerbase-mks / @mks-viva : Why does the board lock up with "boot..." on the LCD for 30 seconds while an SD card is inserted on boot?

**Comment by thisiskeithb** [comment]
After more testing with @rhapsodyv, the Marlin bootscreen can now be enabled on the Nano V2, Robin E3, and Robin Lite3 boards with MKS Mini 12864 & LCD12864 LCDs after adding a delay _and_ the LCD has proper contrast from the start of the boot process.

**Comment by rhapsodyv** [comment]
Thanks to @thisiskeithb dedication to get everything as right as possible, and his tests, we fixed more old issues with the MKS_LCD12864. Now its even show the marlin boot screen correctly!

🚀

**Comment by makerbase-mks** [comment]
@thisiskeithb  @rhapsodyv 
I has test it and this works perfectly! This screen has been fully working on LPC and STM32F1.

**Comment by thisiskeithb** [comment]
> @thisiskeithb @rhapsodyv
> I has test it and this works perfectly! This screen has been fully working on LPC and STM32F1.

The original issue (https://github.com/MarlinFirmware/Marlin/issues/19159) was for a Gen-L (8-bit) and the LCD12864A, but that hasn't been addressed yet since neither @rhapsodyv or I have that LCD. AVR uses software serial, so this fix doesn't apply.

Can you work on getting that LCD/motherboard combo working?

**Comment by ShadowOfTheDamn** [comment]
Hi every body. tried the new bugfix but doesn't help with character LCD.
[BUG] RADDS v1.5 LCD 2004 Initialization problem #18132

**Comment by thisiskeithb** [comment]
> RADDS v1.5 LCD 2004 Initialization problem

That’s completely different hardware than what this PR addresses.

**Comment by sjasonsmith** [comment]
@thisiskeithb i had asked them to re-test, not knowing if the delays from this would impact it at all. Apparently not, so further discussion on it should not occur here.

**Comment by ShadowOfTheDamn** [comment]
ok tnx for the information.
