### PR TITLE
Fix E3 V2 extruder movement when moving other axis

### LINKED ISSUE #19944: [BUG] Ender 3V2 - Moving Z after called print also moves extruder
### Bug Description

Working with ender 3v2, using latest bugfix branch when cancelling a print, moving Z axis will also move the filament (it moved the extruder in the same amount).
Another move of Z axis will not do it again.

This happened in 2.0.7, later i reverted to creality's firmware, but now after installing bltouch i put bugfix 2.0.x and i see this hasn't been solved.
#19644 < Posted here before

### Configuration Files
[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/5458316/Archive.zip)

### Steps to Reproduce

1. Start a print
2. Cancel (I cancelled using octoprint's interface)
3. Using printer interface I tried to move Z axis (I usually do it to clean the bed surface)

**Expected behavior:**

Only the Z axis should move

**Actual behavior:**

Z axis move and extruder moved as well
Very problematic as this can harm printers, the nozzle might not be hot enough, it can also cause jam inside the bowden tube (which it did for me) and it can make a mess of the spooler as it throws out the filament very quickly

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

The E3 DWIN Motion menu resets E to zero each time the menu is entered, so that extruder movement is relative from 0.0.

The code injected a `G92` command and immediately after set `current_position.e` to zero. This caused the `G92` code to optimize out any adjustment, since `current_position` already matched the adjusted position.

I've changed this to call `sync_plan_position_e` instead of injecting `G92`. This code already uses internal calls to perform moves, so it doesn't make sense to use g-code for this when we have an internal call it can easily use.

### Requirements

Ender 3 V2 DWIN display.

### Benefits

No more weird E movement when manually moving other axis.

### Configurations

Ender 3 V2 example.

### Related Issues

#19944

### CODE REVIEW

File: Marlin/src/lcd/dwin/e3v2/dwin.cpp [hunk 1]
```diff
@@ -2321,9 +2321,9 @@ void HMI_Prepare() {
         DWIN_Draw_FloatValue(true, true, 0, font8x16, Color_White, Color_Bg_Black, 3, 1, 216, MBASE(2), current_position.y * MINUNITMULT);
         DWIN_Draw_FloatValue(true, true, 0, font8x16, Color_White, Color_Bg_Black, 3, 1, 216, MBASE(3), current_position.z * MINUNITMULT);
         #if HAS_HOTEND
-          queue.inject_P(PSTR("G92 E0"));
```
Comment (sjasonsmith) [inline Marlin/src/lcd/dwin/e3v2/dwin.cpp:2324]: It bothers me that I cannot explain why this wasn't working. If nobody can reply with a good explanation I will try to debug a little more.

Comment (sjasonsmith) [reply Marlin/src/lcd/dwin/e3v2/dwin.cpp:2324]: I figured out why this didn't work. `G92` only adjust the current position if the needed asjustment is `!NEAR_ZERO`.

This code sets current_position before the injected command runs, which will prevent the planner from ever being updated.

My fix seems appropriate, since this jogging code already manipulates `current_position`. Within one mechanism it probably doesn't make sense to use g-code calls for some position-related tasks and internal calls for others.

**Comment by Bluelinegecko** [comment]
Seems to have resolved the issue on the Ender3V2 I am working on.

**Comment by thinkyhead** [comment]
The real question is: Why is the E coordinate being reset to 0 by the LCD code at that point? Maybe the E position should be left alone, just as it is left untouched by the reference code (MarlinUI manual move).

**Comment by thinkyhead** [comment]
I've posted a followup #20837 to prevent the E position being reset to zero by entering the manual move menu. Instead it just initializes the scaled copy of the E position from the current E position. With that change manual moves should work in the same manner as with the other rotary-knob LCD controllers. Please give it a test to make sure I haven't misplaced any commas….
