### PR TITLE
STM32: rework timer frequency protection

### LINKED ISSUE #23213: STEP_TIMER_NUM and TEMP_TIMER_NUM not declared for STM32 builds
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I receive this error when trying to compile Marlin with attached files.

I see the same issue with the example version config files for Ender-5 Creality V427.

[Marlin-Clean.zip](https://github.com/MarlinFirmware/Marlin/files/7612675/Marlin-Clean.zip)

Marlin\src\HAL\STM32\fast_pwm.cpp: In function 'void set_pwm_frequency(pin_t, int)':
Marlin\src\HAL\STM32\fast_pwm.cpp:74:36: error: 'Instance' was not declared in this scope
   74 |   uint32_t index = get_timer_index(Instance);
      |                                    ^~~~~~~~
Marlin\src\HAL\STM32\fast_pwm.cpp:77:16: error: 'TEMP_TIMER_NUM' was not declared in this scope; did you mean 'TIMER_NUM'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                ^~~~~~~~~~~~~~
      |                TIMER_NUM
Marlin\src\HAL\STM32\fast_pwm.cpp:77:43: error: 'STEP_TIMER_NUM' was not declared in this scope; did you mean 'TIMER_NUM'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                                           ^~~~~~~~~~~~~~
      |                                           TIMER_NUM
Compiling .pio\build\STM32F103RET6_creality\src\src\HAL\STM32\tft\tft_ltdc.cpp.o
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32\fast_pwm.cpp.o] Error 1
=========================================================================== [FAILED] Took 7.65 seconds ===========================================================================

Environment             Status    Duration
----------------------  --------  ------------
STM32F103RET6_creality  FAILED    00:00:07.646
====================================================================== 1 failed, 0 succeeded in 00:00:07.646 ======================================================================The terminal process "C:\Users\Zach\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

### Bug Timeline

This is the first Marlin version I've tried to compile.

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

2.0.x Bugfix

### Printer model

Ender 5

### Electronics

V4.2.7, BLTouch,

### Add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by tpruvot**
STEP_TIMER_NUM, TEMP_TIMER_NUM and PULSE_TIMER_NUM are not the indexes returned by the STM32 framework get_timer_index() function. Same thing now with the recently renamed MF_TIMER_xxx constants

In STM32 HAL these constants are defined by Marlin for its own container of custom timers, timer_instance[] which has only 2 records.

follow up for #23125

### CODE REVIEW

**Comment by descipher** [comment]
Please consider:

https://github.com/MarlinFirmware/Marlin/blob/a7549aac5c5efc7097d6ebe69b2d46b3e7acbfab/Marlin/src/module/stepper.cpp#L2772

and 

https://github.com/MarlinFirmware/Marlin/blob/a7549aac5c5efc7097d6ebe69b2d46b3e7acbfab/Marlin/src/module/temperature.cpp#L2378

These calls use the STEP_TIMER_NUM and TEMP_TIMER_NUM refs.

**Comment by descipher** [comment]
So it is only true for the maple HAL:
```
#ifndef STEP_TIMER_NUM
  #if defined(MCU_STM32F103CB) || defined(MCU_STM32F103C8)
    #define STEP_TIMER_NUM      4  // For C8/CB boards, use timer 4
  #else
    #define STEP_TIMER_NUM      5  // for other boards, five is fine.
  #endif
#endif
#ifndef PULSE_TIMER_NUM
  #define PULSE_TIMER_NUM       STEP_TIMER_NUM
#endif
#ifndef TEMP_TIMER_NUM
  #define TEMP_TIMER_NUM        2  // Timer Index for Temperature
  //#define TEMP_TIMER_NUM      4  // 2->4, Timer 2 for Stepper Current PWM
#endif
```

**Comment by descipher** [comment]
Why would we not keep this consistent? Array Index in one vs actual timer in the other?

**Comment by descipher** [comment]
The same issue exists with the __STM32F1__ HAL the actual timers are not TEMP_TIMER_NUM or STEP_TIMER_NUM.

**Comment by descipher** [comment]
Thanks for the followup.

**Comment by tpruvot** [comment]
> Please consider:https://github.com/MarlinFirmware/Marlin/blob/a7549aac5c5efc7097d6ebe69b2d46b3e7acbfab/Marlin/src/module/stepper.cpp#L2772
> 
> and
> https://github.com/MarlinFirmware/Marlin/blob/a7549aac5c5efc7097d6ebe69b2d46b3e7acbfab/Marlin/src/module/temperature.cpp#L2378
> 
> These calls use the STEP_TIMER_NUM and TEMP_TIMER_NUM refs.

yes... but HAL_timer_start() use the marlin array of HardwareTimer

and yes STEP_TIMER_NUM  5 is only for the F1 HAL, i agree the STM32 code can be confusing (and confused me before) with the same defines constants used diffently... this PR is only for STM32 HAL, not maple/F1 HAL

**Comment by descipher** [comment]
Tested. HAL_STM32 passed 👍 
Maple HAL failed, due to it using different pin mapping to timers, also it sets the wrong frequency .. lol (500Hz)
I am looking at the Maple issue. It's related to the library and of course mappings are a mess.

**Comment by tpruvot** [comment]
Thanks for the report. Indeed my current printer can't use pwm on the maple framework due to the missing alternate function pin mapping, but F1 timer HAL code seems more "simple" to use, at least for the timer numbers...

**Comment by descipher** [comment]
I think AF mapping is not really missing. It just cannot do it based on the method used in the timer_dev structs and other device structs. There is no pointer assignment for the alternate pin in the map table.
e.g.
```
{&gpiod,    NULL, NULL,  11, 0, ADCx} , /* PD11  FSMC_A16 */
{&gpiod,    NULL, NULL,  12, 0, ADCx} , /* PD12  FSMC_A17 */
{&gpiod,    NULL, NULL,  13, 0, ADCx} , /* PD13  FSMC_A18 */	
{&gpiod,    NULL, NULL,  14, 0, ADCx} , /* PD14  FSMC_D0 */
{&gpiod,    NULL, NULL,  15, 0, ADCx} , /* PD15  FSMC_D1 */
```
Could be set as follows:

```
{&gpiod,    NULL, NULL,  11, 0, ADCx} , /* PD11  FSMC_A16 */
{&gpiod, &timer4, NULL,  12, 1, ADCx} , /* PD12  FSMC_A17 */
{&gpiod, &timer4, NULL,  13, 2, ADCx} , /* PD13  FSMC_A18 */	
{&gpiod, &timer4, NULL,  14, 3, ADCx} , /* PD14  FSMC_D0 */
{&gpiod, &timer4, NULL,  15, 4, ADCx} , /* PD15  FSMC_D1 */
```

**Comment by tpruvot** [comment]
i didnt try, but maybe if i remove the standard timer4 pins in the variant, i can then set it on PD12 & 13. May need a afio_remap call then... i bricked the board the last time i tried but didnt touch the variant map, just afio_remap  :p

**Comment by descipher** [comment]
I would not recommend Maple after looking deeper at it.

**Comment by thinkyhead** [comment]
The value returned by `get_timer_index` is not necessarily going to be the timer number minus one, since `timer_index_t` is an `enum` containing only enabled timers, with skips and gaps. So I changed the `index` test to compare the returned `get_timer_index` value against the `enum` for the timer index, rather than the timer index minus one.

**Comment by descipher** [comment]
You should be good using the index value based on the libs methods.
```cpp
/**
  * @brief  HardwareTimer destructor
  * @retval None
  */
HardwareTimer::~HardwareTimer()
{
  uint32_t index = get_timer_index(_timerObj.handle.Instance);
  disableTimerClock(&(_timerObj.handle));
  HardwareTimer_Handle[index] = NULL;
  _timerObj.__this = NULL;
}

/**
  * @brief  return timer index from timer handle
  * @param  htim : one of the defined timer
  * @retval None
  */
timer_index_t get_timer_index(TIM_TypeDef *instance)
{
  timer_index_t index = UNKNOWN_TIMER;

#if defined(TIM1_BASE)
  if (instance == TIM1) {
    index = TIMER1_INDEX;
  }
#endif
```

File: Marlin/src/HAL/STM32/fast_pwm.cpp [hunk 1]
```diff
@@ -25,69 +25,66 @@
...
-  ) return;
-
-  if (HardwareTimer_Handle[index] == nullptr) // If frequency is set before duty we need to create a handle here. 
+  const PinName pin_name = digitalPinToPinName(pin);
+  TIM_TypeDef * const Instance = (TIM_TypeDef *)pinmap_peripheral(pin_name, PinMap_PWM); // Get HAL timer instance
+  const timer_index_t index = get_timer_index(Instance);
+
+  // Protect used timers.
+  #define __TINDEX(T) TIMER##T##_INDEX // Timer indexes from TIMER#_INDEX enum which depends on TIM#_BASE defines.
+  #define _TINDEX(T) __TINDEX(T)
```
Comment (tpruvot) [inline Marlin/src/HAL/STM32/fast_pwm.cpp]: could be useful to have this macro in HAL timers.h, and maybe with a more explicit name like TIMER_INDEX(NUM)

File: Marlin/src/HAL/STM32/fast_pwm.cpp [hunk 2]
```diff
@@ -25,63 +25,59 @@
...
+  // Protect used timers.
+  #ifdef STEP_TIMER
+    if (index == TIMER_INDEX(STEP_TIMER)) return;
+  #endif
+  #ifdef TEMP_TIMER
+    if (index == TIMER_INDEX(TEMP_TIMER)) return;
+  #endif
+  #if defined(PULSE_TIMER) && MF_TIMER_PULSE != MF_TIMER_STEP
+    if (index == TIMER_INDEX(PULSE_TIMER)) return;
+  #endif
```
Comment (tpruvot) [inline Marlin/src/HAL/STM32/fast_pwm.cpp:74]: im not sure this last one is useful here, or correctly coded in STM32 HAL (see timers.h and timers.cpp)

```
#define NUM_HARDWARE_TIMERS 2
```
prevents the use/define of it...

```
#ifndef MF_TIMER_PULSE
  #define MF_TIMER_PULSE        MF_TIMER_STEP
#endif
```

also for the other ones... 
```
#ifndef MF_TIMER_STEP
  #define MF_TIMER_STEP         0  // Timer Index for Stepper
#endif
```

for STM32... there is no meaning of using these ifndef ... because its just offsets in a marlin array, unrelated to timer selection so.

File: Marlin/src/HAL/STM32/fast_pwm.cpp [hunk 3]
```diff
@@ -25,63 +25,59 @@
...
+  const TimerModes_t previousMode = HT->getMode(channel);
 
   if (previousMode != TIMER_OUTPUT_COMPARE_PWM1)
     HT->setMode(channel, TIMER_OUTPUT_COMPARE_PWM1, pin);
 
   if (needs_freq) {
-    if (timer_freq[index] == 0 ) {                    // If the timer is unconfigured and no freq is set then default PWM_FREQUENCY.
+    if (timer_freq[index] == 0) {                     // If the timer is unconfigured and no freq is set then default PWM_FREQUENCY.
       timer_freq[index] = PWM_FREQUENCY;
       set_pwm_frequency(pin_name, timer_freq[index]); // Set the frequency and save the value to the assigned index no.
```
Comment (tpruvot) [inline Marlin/src/HAL/STM32/fast_pwm.cpp]: here: set_pwm_frequency(pin_name, PWM_FREQUENCY); is enough... 
timer_freq[index] = f_desired; is made in set_pwm_frequency()

File: Marlin/src/HAL/STM32/fast_pwm.cpp (hunk 2 above)
Comment (thinkyhead) [reply Marlin/src/HAL/STM32/fast_pwm.cpp:74]: Yes, these timers should always exist, and no overrides have ever been needed or proposed, so the HALs that have these values fixed and not related to platform timer IDs should drop the `#ifdef` wrappers, which give the incorrect impression that they can be overridden in some way.

File: Marlin/src/HAL/STM32/timers.h [hunk 4]
```diff
@@ -41,16 +41,9 @@
...
-#endif
-#ifndef MF_TIMER_PULSE
-  #define MF_TIMER_PULSE        MF_TIMER_STEP
-#endif
-#ifndef MF_TIMER_TEMP
-  #define MF_TIMER_TEMP         1  // Timer Index for Temperature
-#endif
+#define MF_TIMER_STEP         0  // Timer Index for Stepper
+#define MF_TIMER_TEMP         1  // Timer Index for Temperature
+#define MF_TIMER_PULSE        MF_TIMER_STEP
```
Comment (tpruvot) [inline Marlin/src/HAL/STM32/timers.h]: maybe some comment should be added to explain these values are not tunable....

Comment (tpruvot) [reply Marlin/src/HAL/STM32/timers.h]: unlike some other HALs....

**Comment by ellensp** [comment]
The simulator is also broken with error: ‘STEP_TIMER_NUM’ was not declared in this scope

**Comment by tpruvot** [comment]
hmm no, there is no more STEP_TIMER_NUM ref in git... (after this PR at least)

**Comment by descipher** [comment]
> hmm no, there is no more STEP_TIMER_NUM ref in git... (after this PR at least)

Yes, I see Scott has refactored them for all HALs so a merge would be in order for any in progress PRs. Or better yet .. rebase em.

**Comment by tpruvot** [comment]
rebased & squashed as a single commit (easier to cherry pick)

**Comment by descipher** [comment]
> rebased & squashed as a single commit (easier to cherry pick)

Indeed, looks good.
