### PR TITLE
Fix IJK axis references and E stepper indices

### LINKED ISSUE #22143: [BUG] (bugfix-2.0.9.x) 'E_AXIS' was not declared in this scope
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Error while build with  #define EXTRUDERS 0  (CNC config).

```
> Executing task in folder Marlin-bugfix-2.0.9.x: C:\.platformio\penv\Scripts\platformio.exe run <

Processing LPC1768 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.3.zip; board: nxp_lpc1768; framework: arduino)
------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/nxplpc-arduino-lpc176x/nxp_lpc1768.html
PLATFORM: NXP Arduino LPC176x (0.1.3) > NXP LPC1768
HARDWARE: LPC1768 100MHz, 31.97KB RAM, 464KB Flash
DEBUG: Current (cmsis-dap) On-board (cmsis-dap) External (blackmagic, jlink)
PACKAGES:
 - framework-arduino-lpc176x 0.2.7
 - toolchain-gccarmnoneeabi 1.90301.200702 (9.3.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ strict
Found 4 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Servo> 1.0.0
|-- <TMCStepper> 0.7.1
|-- <U8glib-HAL> 0.4.5
Building in release mode
Compiling .pio\build\LPC1768\src\src\HAL\LPC1768\HAL.cpp.o
Compiling .pio\build\LPC1768\src\src\HAL\LPC1768\HAL_MinSerial.cpp.o
Compiling .pio\build\LPC1768\src\src\HAL\LPC1768\HAL_SPI.cpp.o
Compiling .pio\build\LPC1768\src\src\HAL\LPC1768\MarlinSerial.cpp.o
In file included from Marlin\src\HAL\LPC1768\HAL.cpp:26:
Marlin\src\HAL\LPC1768\include/../../../gcode/parser.h: In static member function 'static
float GCodeParser::axis_unit_factor(AxisEnum)':
Marlin\src\HAL\LPC1768\include/../../../gcode/parser.h:314:23: error: 'E_AXIS' was not declared in this scope; did you mean 'C_AXIS'?
  314 |       return (axis >= E_AXIS && volumetric_enabled ? volumetric_unit_factor : linear_unit_factor);
      |                       ^~~~~~
      |                       C_AXIS
*** [.pio\build\LPC1768\src\src\HAL\LPC1768\HAL.cpp.o] Error 1
=============================== [FAILED] Took 8.69 seconds ===============================

Environment    Status    Duration
-------------  --------  ------------
LPC1768        FAILED    00:00:08.687
```

### Steps to Reproduce

Try to build

### Version of Marlin Firmware

Marlin-bugfix-2.0.9.x

### Printer model

CNC

### Electronics

BTT SKR 1.3 board

### Additional information & file uploads

[Configs_n_Diffs.zip](https://github.com/MarlinFirmware/Marlin/files/6658350/Configs_n_Diffs.zip)

### PR DESCRIPTION
**Pull request by slowbro**
### Description

Fixes some references to `E_AXIS` that break compilation with `#define EXTRUDERS 0`, as well as the new linear axes i/j/k.

Also includes some cleanup/standardization for multiple E steppers in M569, M906, and M911-914.

### Requirements

EXTRUDERS 0 for the E_AXIS stuff, LINEAR_AXES < 4.

### Benefits

Fixes some edge cases in compilation.

### Configurations

See #22143

### Related Issues

Fixes #22143

### CODE REVIEW

File: Marlin/src/gcode/feature/L6470/M906.cpp [hunk 1]
```diff
@@ -281,7 +281,7 @@ void GcodeSuite::M906() {
           break;
       #endif
 
-      #if HAS_EXTRUDERS
+      #if E_STEPPERS
```
Comment (thinkyhead) [inline Marlin/src/gcode/feature/L6470/M906.cpp:281]: There should be no case where `HAS_EXTRUDERS` is not set when `E_STEPPERS > 0`. And, this code is using the E index from `get_target_extruder_from_command` which does refer (abstractly) to the 'extruder' or the 'tool index' and not to the E stepper. You can also see that `get_target_extruder_from_command` does this:
```cpp
    if (e < EXTRUDERS) return e;
```
So, if we are going to be referring here to `E_STEPPERS`, which is apparently the real case, this should not be calling `get_target_extruder_from_command` — or it should be passing a flag to limit based on `E_STEPPERS` instead of limiting based on `EXTRUDERS`.

**Comment by slowbro** [comment]
Thanks @thinkyhead!
