### PR TITLE
[2.0.x] fix bltouch homing

### LINKED ISSUE #11378: [bugfix-2.0.x] bltouch stows when homing Z
The probe reacts fine to gcodes but when the printer homes, it does not deploy but stows. The print head crashes into the bed after that.
It worked fine yesterday and stopped working after I flashed 2018-07-26 05:58:28 -0500.

### PR DESCRIPTION
**Pull request by GMagician**
Fix #11378

### CODE REVIEW

**Comment by GMagician** [comment]
@thinkyhead ok, as state in previous PR I not tested G28 with bltouch and.....bug.

I supposed that function DEPLOY_PROBE should do as stated but it forget bltouch. Is it not a probe? is it not used as other probes?

**Comment by tig33r** [comment]
Probably missing ")" before return in 1372 line.

Also head after homing Z is around ~15mm above bed.

**Comment by GMagician** [comment]
@tig33r fixed missing bracket but change should not affect home position

**Comment by tig33r** [comment]
I did not change conf file (exactly same as before your commit), just flash my board (due + ramps-fdv2.1) with newest repo changes. Weird behavior, someone else has to evaluate it.

**Comment by GMagician** [comment]
@tig33r can you explain me what happens? bltouch deploy and stow correctly during home? only final position is wrong? What happens to be labeled as "weird"?

**Comment by tig33r** [comment]
Homing process is going ok (move out pin, first fast bed move until pin reach bed, again move out pin and slow bed move until reach bed, at the end bed is moving down like always) but finally head in position 0 is about ~15 mm above bed. Exactly same configuration.h file with bugfix before your change is giving correctly positioned head above bed.

Tommorow I will record video for both conditions.

**Comment by Stephane-80** [comment]
hello, same problem here i think.
final position is wrong 
it check normally fast and slow but after the slow test ,when it move up the pin get out
and get in after the up move

**Comment by thinkyhead** [comment]
> I supposed that function DEPLOY_PROBE should do as stated but it forget bltouch. Is it not a probe? is it not used as other probes?

The way the BLTouch's code works came out of a bunch of testing and development, and it was useful to keep BLTouch deploy/stow separate from the general probe deploy/stow. We could probably dig up the PRs where the BLTouch was being developed and fixed to read the rationale.

I've added an extra commit suggesting changes to solve the Z position problem for testing (basically just reverting some of the changes from the earlier PR). I look forward to feedback from testers.

File: Marlin/src/module/motion.cpp [hunk 1]
```diff
@@ -1436,6 +1452,16 @@ void homeaxis(const AxisEnum axis) {
...
 
+  // Put away the Z probe
+  #if HOMING_Z_WITH_PROBE
+    if (axis == Z_AXIS) {
+      #if ENABLED(BLTOUCH)
+        if (set_bltouch_deployed(false)) return;
+      #endif
+      if (STOW_PROBE()) return;
+    }
+  #endif
```
Comment (thinkyhead) [inline Marlin/src/module/motion.cpp:1449]: Moved this down to make the revert more complete, but if the other reverts solve the Z position problem then this may turn out to be ok moved back up above.

**Comment by tig33r** [comment]
Looks like it works ok in my setup. Maybe someone else can confirm that fact.

**Comment by vincent-ogury** [comment]
The G28 works.
The G29 failed.

File: Marlin/src/module/motion.cpp (hunk 1 above)
Comment (GMagician) [reply Marlin/src/module/motion.cpp:1449]: Yes this will solve Z. STOW_PROBE move Z

**Comment by thinkyhead** [comment]
How did G29 fail? The pin didn't deploy at some point during the procedure?

**Comment by thinkyhead** [comment]
As this at least partly solves the issue, I will merge it for now, and we can continue to patch following more testing.

**Comment by vincent-ogury** [comment]
Yes. It goes to the position. Then go down without deploying.
Then go up and say: probe failed.

**Comment by vincent-ogury** [comment]
I retry with the last merge and will give a feedback

**Comment by vincent-ogury** [comment]
last merge make it work again !!! excellent

**Comment by GMagician** [comment]
@vincent-ogury, @tig33r, @Stephane-80  I made some minor change to my PR (from my branch) can you test it again, sorry for bothering continuosly

@thinkyhead since stow/deploy_probe functions act with no care of bltouch and since bltouch needs always to deploy and stow. I moved latter calls just before axis move. This should not change any behaviour but will keep deploy just before move call and such calls will be near stow counterpart. It seems following a more correct logic

**Comment by hamster65** [comment]
Thanks! It's working again!

**Comment by GMagician** [comment]
PR is just public now....
