### PR TITLE
reset echo:start back to start and default monitor_speed back to 250000

### LINKED ISSUE #20305: [BUG] start was changed to echo:start
### Bug Description

Standard says that firmware starts with
start

but when I used latest commit I saw it now says
echo:start

which is against standards and can cause hosts to not detect a reset of printer if they watch for a line beginning with "start" and not a line containing "start" which could also be a file in listing or a M118 response or just a word in a message. 

### Configuration Files

Happens for all configs

### Steps to Reproduce

Connect

**Expected behavior:**

Start communication with
start

**Actual behavior:**

Starts communication with
echo:start

#### Additional Information

Violation against many years old standard for communication.

### PR DESCRIPTION
**Pull request by ellensp**
### Requirements

Current Marlin bugfix

### Description

In commit https://github.com/MarlinFirmware/Marlin/commit/5a5be7e287183e633ee3235ee1bcd79a72a1a1f5
"start" was changed to "echo:start"
This seems to be in conflict of being a control words as defined in https://reprap.org/wiki/G-code#Replies_from_the_RepRap_machine_to_the_host_computer
```
When the machine boots up it sends the string
start
```

Secondly platformio's default monitor_speed of 250000 was changed to 115200 in https://github.com/MarlinFirmware/Marlin/commit/b6a32500c401877e3ee1300fa613e81086bb31d3

Since the default BAUDRATE in marlin is still 250000 I believe this is in error and am reverting it.

### Benefits

start works as per the protocol description. 
platformio serial monitor starts in correct baudrate.

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/20305
https://github.com/MarlinFirmware/Marlin/commit/b6a32500c401877e3ee1300fa613e81086bb31d3

### Concerns
Since "start" was changed to "echo:start" back in April 2020 in version 2.0.6 Changing "echo:start" back to "start" may break some clients that have been modified to now expect "echo:start"

One thought was to send both going forward?

### CODE REVIEW

File: Marlin/src/MarlinCore.cpp [hunk 1]
```diff
@@ -982,7 +982,7 @@ void setup() {
     serial_connect_timeout = millis() + 1000UL;
     while (!MYSERIAL1 && PENDING(millis(), serial_connect_timeout)) { /*nada*/ }
   #endif
-  SERIAL_ECHO_MSG("start");
+  SERIAL_ECHOLN("start");
```
Comment (sjasonsmith) [inline Marlin/src/MarlinCore.cpp]: This used to use `SERIAL_ECHOLNPGM`. Is this going to fail on AVR?

Comment (ellensp) [reply Marlin/src/MarlinCore.cpp]: I tested on avr (mega2560) , and retested just now for piece of mind
Enabled both and got the expect results.
21:42:47.658 > echo:start
21:42:47.658 > start
21:42:47.658 >  External Reset
....

Comment (ellensp) [reply Marlin/src/MarlinCore.cpp]: But SERIAL_ECHOLNPGM is cleaner.

**Review by sjasonsmith — APPROVED** [review]
This seems correct to me. It looks like the change was probably accidental.

Given that it has been this way for 8 months, I am going to wait for @thinkyhead to weigh in on it.

**Comment by ellensp** [comment]
Yes, this I why I asked @thinkyhead to review. Didn't want to presume.
