### PR TITLE
TMC2240 Stepper Driver fix and tune

### LINKED ISSUE #27885: [BUG] Sensorless homing does not work with 2240s & potential reboots
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Testing was done on a BIQU BX with 2240s installed on X, Y, Z1, Z2, and E0 with sensorless homing.

Edit: I am also now testing this on a Prusa MK3S/+ Bear with BTT002 & 2240s installed on X & Y

---

I can move each axis around, but sensorless homing does not work and drivers shut down. There are also still compile issues when enabling `TMC_DEBUG`.

### Details

I tried a standard `G28` and there's an slight attempt to home X & Y, but they instantly trigger (or so I thought) and I can no longer command X or Y to move until a power cycle.

I tried enabling `TMC_DEBUG` to collect more info, but it won't compile to due various references to TSTEP. I had to disable the following in `tmc_util.cpp` to get `TMC_DEBUG` to compile:

<details><summary>Click me for the diff!</summary>
<p>

```diff
diff --git a/Marlin/src/feature/tmc_util.cpp b/Marlin/src/feature/tmc_util.cpp
index fb17e56..e7f0414 100644
--- a/Marlin/src/feature/tmc_util.cpp
+++ b/Marlin/src/feature/tmc_util.cpp
@@ -715,13 +715,13 @@
   #endif
 
   template <typename TMC>
-  void print_tstep(TMC &st) {
-    const uint32_t tstep_value = st.TSTEP();
-    if (tstep_value != 0xFFFFF)
-      SERIAL_ECHO(tstep_value);
-    else
-      SERIAL_ECHOPGM("max");
-  }
+  // void print_tstep(TMC &st) {
+  //   const uint32_t tstep_value = st.TSTEP();
+  //   if (tstep_value != 0xFFFFF)
+  //     SERIAL_ECHO(tstep_value);
+  //   else
+  //     SERIAL_ECHOPGM("max");
+  // }
   void print_tstep(TMC2660Stepper &st) { }
 
   template <typename TMC>
@@ -749,7 +749,7 @@
       case TMC_CS_ACTUAL: print_cs_actual(st); break;
       case TMC_VSENSE: print_vsense(st); break;
       case TMC_MICROSTEPS: SERIAL_ECHO(st.microsteps()); break;
-      case TMC_TSTEP: print_tstep(st); break;
+      //case TMC_TSTEP: print_tstep(st); break;
       #if ENABLED(HYBRID_THRESHOLD)
         case TMC_TPWMTHRS: SERIAL_ECHO(uint32_t(st.TPWMTHRS())); break;
         case TMC_TPWMTHRS_MMS: {
@@ -1006,7 +1006,7 @@
         PRINT_TMC_REGISTER(GSTAT);
         PRINT_TMC_REGISTER(IOIN);
         PRINT_TMC_REGISTER(TPOWERDOWN);
-        PRINT_TMC_REGISTER(TSTEP);
+        //PRINT_TMC_REGISTER(TSTEP);
         PRINT_TMC_REGISTER(TPWMTHRS);
         PRINT_TMC_REGISTER(CHOPCONF);
         PRINT_TMC_REGISTER(PWMCONF);
```

</p>
</details>

With `TMC_DEBUG` enabled, I found that the following differences between `M122` reports before & after homing:

Before homing:
```
        X    Y    Z    Z2    E
Enabled        false    false    true    true    false
[...snip...]
Driver registers:
        X    0x81:00:40:00
        Y    0x81:00:40:00
        Z    0x81:0F:40:00
        Z2    0x81:0F:40:00
        E    0x81:00:40:00
```

After homing:
```
        X    Y    Z    Z2    E
Enabled        true    true    true    true    false
[...snip...]
Driver registers:
        X    0x80:0F:50:22
        Y    0x80:0F:50:24
        Z    0x80:1F:40:7C
        Z2    0x80:1F:40:10
        E    0x81:00:40:00
```

@dbuezas found that according to the datasheet, this is a driver shutdown due to overheating. That is not really the case since drivers are cool to the touch and they are triggering instantly while homing, even at the least sensitive StallGuard value.

---

Based on reports in the #trinamic channel on our Discord, you can use 5130 as a substitute for 2240, but I didn't have 100% success with that either. Drivers no longer shutdown, but they do not trigger while homing, even at the most sensitive StallGuard setting (opposite of above since hit state has to be flipped per the sanity checks).

There's also a report of a printer rebooting with fixes from https://github.com/MarlinFirmware/Marlin/pull/27880, but I have not experienced that issue.

Another interesting find is that 2240s are *a lot quieter* when configured as 5130s vs. 2240s.

### Bug Timeline

Since 2240 suppot was added in https://github.com/MarlinFirmware/Marlin/pull/25974

### Expected behavior

Sensorless homing and drivers work

### Actual behavior

Sensorless homing fails and causes drivers to shutdown until a full power cycle

### Steps to Reproduce

1. Install 2240 drivers into BX, including three additional jumpers per driver for SPI mode
2. Update config to support 2240s
3. Build & flash current `bugfix-2.1.x` to BX
4. Attempt to home all via LCD or `G28`

### Version of Marlin Firmware

bugfix-2.1.x (fde0eaf)

### Printer model

BIQU BX

### Electronics

Stock electronics except for 2240 drivers

### LCD/Controller

Stock TFT

### Other add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Stock BX config: https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/BIQU/BX

Change all `*_DRIVER_TYPE`s to `2240` and enable `TMC_USE_SW_SPI` or use the attached modified config: [Configurations-config-examples-BIQU-BX.zip](https://github.com/user-attachments/files/20446655/Configurations-config-examples-BIQU-BX.zip)

Don't forget to install three additional jumpers under each driver for SPI mode.

### PR DESCRIPTION
**Pull request by thinkyhead**
TMC2240 is brand new and there are still a lot of details to sort out with initialization, etc. This PR is for testing and feedback of TMC2240 performance until we can achieve optimum settings.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Can we host `TMC2240_Datasheet.pdf` in the docs repo / link to it instead of hosting it within this one?

I'll get these changes pulled down and try out sensorless homing on the BX again. I've also pinged gonzo in the #trinamic channel on Discord to see if reboots are fixed for them.

**Comment by thisiskeithb** [comment]
Tested with https://github.com/thinkyhead/Marlin/commit/70ca79b7c9fa72c232a662549bfcd4814a8bbfa1

I cleared the `/.pio/build/libdeps/` folder to ensure a fresh copy of TMCStepper 0.8.5 (https://github.com/MarlinFirmware/TMCStepper/commit/0101c8fdb6fef0b05ab8131bdd4c2fd185b6071b) was pulled down and sensorless homing still fails like I describe in https://github.com/MarlinFirmware/Marlin/issues/27885


<details><summary>M122 output after booting (Z1 & Z2 are active):</summary>
<p>

```log
Send: M122
		X	Y	Z	Z2	E
Enabled		false	false	true	true	false
Set current	1050	1150	1050	1050	800
RMS current	1033	1131	1033	1033	513
MAX current	1457	1595	1457	1457	723
Run current	31/31	31/31	31/31	31/31	20/31
Hold current	15/31	15/31	15/31	15/31	10/31
CS actual
PWM scale
vsense
stealthChop	true	true	true	true	true
msteps		16	16	16	16	16
interp		true	true	true	true	true
tstep		max	max	max	max	max
PWM thresh.
[mm/s]
OT prewarn	false	false	false	false	false
off time	3	3	3	3	4
blank time
hysteresis
 -end		-1	-1	-1	-1	2
 -start		5	5	5	5	1
Stallguard thrs
uStep count	16	16	16	16	16
DRVSTATUS	X	Y	Z	Z2	E
sg_result	0	0	0	0	0
stallguard	*	*	*	*	*
fsactive
stst
olb
ola
s2gb
s2ga
otpw
ot
s2vsa
s2vsb
Driver registers:
		X	0x81:00:40:00
		Y	0x81:00:40:00
		Z	0x81:0F:40:00
		Z2	0x81:0F:40:00
		E	0x81:00:40:00


Testing X connection... OK
Testing Y connection... OK
Testing Z connection... OK
Testing Z2 connection... OK
Testing E connection... OK
```

</p>
</details>

<details><summary>M122 report after a G28 and X & Y motors can move freely by hand / drivers are shutdown:</summary>
<p>

```log
Send: M122
		X	Y	Z	Z2	E
Enabled		true	true	true	true	false
Set current	1050	1150	1050	1050	800
RMS current	1033	1131	1033	1033	513
MAX current	1457	1595	1457	1457	723
Run current	31/31	31/31	31/31	31/31	20/31
Hold current	15/31	15/31	15/31	15/31	10/31
CS actual
PWM scale
vsense
stealthChop	true	true	true	true	true
msteps		16	16	16	16	16
interp		true	true	true	true	true
tstep		max	max	max	max	max
PWM thresh.
[mm/s]
OT prewarn	false	false	false	false	false
off time	3	3	3	3	4
blank time
hysteresis
 -end		-1	-1	-1	-1	2
 -start		5	5	5	5	1
Stallguard thrs
uStep count	16	16	16	16	16
DRVSTATUS	X	Y	Z	Z2	E
sg_result	18	16	42	48	0
stallguard					*
fsactive
stst
olb
ola
s2gb
s2ga
otpw
ot
s2vsa		*	*
s2vsb
Driver registers:
		X	0x80:0F:50:12
		Y	0x80:0F:50:10
		Z	0x80:1F:40:2A
		Z2	0x80:1F:40:30
		E	0x81:00:40:00


Testing X connection... OK
Testing Y connection... OK
Testing Z connection... OK
Testing Z2 connection... OK
Testing E connection... OK
```

</p>
</details>

**Comment by thinkyhead** [comment]
> Can we host TMC2240_Datasheet.pdf in the docs repo / link to it instead of hosting it within this one?

I don't have any plan to commit it. It is here in this PR for reference.

**Comment by thinkyhead** [comment]
This PR is for experimentation, so please try various adjustment to the TMC2240 initialization values to see if you can get to a point where it doesn't shut down when attempting to move a stepper by any distance at boot (e.g., `G1 X1`). We don't need to go crazy and jump straight to `G28` until we have this much working. Some non-authoritative sample init values are included in a comment in the init method, but refer to the datasheet to find out what the expected effect should be prior to making any adjustments.

---
The `s2vsa` (Short to VS A) flag on the Trinamic TMC2240 indicates a short circuit from one of the motor outputs to the supply voltage (VS), specifically on channel A. This typically suggests:
- A direct or partial short from the motor coil pin (OA) to the motor power supply (VS).
- A serious hardware fault, not just a mild misconfiguration.

It's not typically triggered by bad settings, but there are edge cases where driver settings might lead to false positives or exacerbate electrical conditions that trigger this:
1. Too-high current limits (configured via IHOLD/IRUN) can cause sharp current spikes that stress the MOSFETs or wires.
2. Improper sense resistor values or incorrect VSENSE configuration could cause the chip to misinterpret normal current levels.
3. Fast decay or improper chopper timing (CHOPCONF) might cause ringing or voltage spikes on the outputs.
4. Floating motor outputs (no motor connected or loose wires) can create unstable conditions that confuse the detection logic.

More likely causes (hardware/wiring):
- Miswiring, e.g. one coil wire shorted to the motor supply line.
- Motor failure or internal shorts in the windings.
- PCB or solder bridge between OA and VS lines.
- Induced spikes or noise from poor PCB layout or inadequate decoupling.

What to check:
1. Inspect the wiring and PCB for shorts between motor outputs and VS.
2. Try a different motor or disconnect the motor entirely.
3. Lower the current limits to the minimum and see if the flag still sets.
4. Use oscilloscope to look at the output waveform if available.
5. Double-check all driver configuration registers, especially current settings and chopper mode.

**Comment by thisiskeithb** [comment]
> see if you can get to a point where it doesn't shut down when attempting to move a stepper by any distance at boot

I can command motors to move after a fresh boot without issue.

The problem is that as soon as I try to home, X & Y drivers shut down.

**Comment by MarathonMAN1** [comment]
I can confirm reboot from leveling bed to event after G29 has been fixed. Drivers also act normal and run like a scalded dog. Name change another long story.

**Comment by thisiskeithb** [comment]
We should remove the `TMC2240_STANDALONE` option since these drivers can only be configured via SPI. There's no potentiometer to set current for a "standalone" mode.

I also verified that `TMC2240_STANDALONE` does not work on real hardware.

**Comment by thisiskeithb** [comment]
The TMC2240 reference should be dropped from the first column since sensitivity values are -64 to 63 based on testing & the datasheet (h/t to @ellensp for confirming):

https://github.com/MarlinFirmware/Marlin/blob/823014868c1a9974f0f1881193a8f042577310f5/Marlin/Configuration_adv.h#L3470-L3472

I moved a couple TMC2240s from my BX to my MK3S Bear and I'm experiencing the same issue with sensorless homing except motors stay engaged and drivers don't shutdown. They just trigger instantly on any value from -64 all the way to 63.  Motors can be commanded to move after a homing attempt, but sometimes they buzz/don't move correctly. If I switch back to 5160s on my Bear, everything works as expected.

**Comment by ellensp** [comment]
Issue is not so simple.

https://github.com/MarlinFirmware/Marlin/blob/823014868c1a9974f0f1881193a8f042577310f5/Marlin/Configuration_adv.h#L3470-L3472

tmc2240 has stallguard2   which is -64 to 64
but it also has stallguard4 which is 0 to 255 

current code does update sgt, which is stallguard2

**Comment by thinkyhead** [comment]
We'll get Stallguard2 sorted out before we get into Stallguard4, which has some extra complexities but also some extra goodies that could be useful in the future.

**Comment by thinkyhead** [comment]
> I moved a couple TMC2240s from my BX to my MK3S Bear and I'm experiencing the same issue with sensorless homing except motors stay engaged and drivers don't shutdown.

Does `M119` show "TRIGGERED" all the time? If so, the `ENDSTOP_HIT_STATE` will need to be updated to require `LOW` instead of `HIGH`. This will match all other drivers except TMC2209.

Note: The opposite DIAG state required for TMC2209 might not apply to TMC2209 modules from every vendor, but currently it seems to be the standard.

**Comment by thisiskeithb** [comment]
> Does `M119` show "TRIGGERED" all the time?

Indeed.

```log
Send: M119
Reporting endstop status
x_min: TRIGGERED
y_min: TRIGGERED
z_min: open
filament: TRIGGERED
```

**Comment by thinkyhead** [comment]
So we have some suggestions provided by ChatGPT. I will boil them down. Let me know how the driver behaves after experimenting with some of these suggestions.

1. **Current range and configuration**
  - You’re setting `DRV_CONF.current_range`, but the TMC2240 supports wider current scaling than the 2208, and an incorrect range may cause overshoot or undervaluation of RMS current.
  -  👉 Double-check that your `TMC2240_CURRENT_RANGE` is appropriate for the selected sense resistor and the current setting (`st.rms_current(mA)`).
2. **Slope control**
  - `DRV_CONF.slope_control` is being set, but TMC2240 has aggressive slope tuning options. Too sharp edges can cause ringing, which might be seen as a short.
  - 👉 Try the default (0) slope control setting to test stability, or explicitly use more gentle rise/fall settings.
3. **`TOFF` and blanking time (`TBL`)**
  - You’ve set `toff = 3`, `tbl = 0b10` (36 tCLK). Compare that to the 2208 where `tbl = 0b01` (24 tCLK).
  - `TOFF` 3 is reasonable, but combined with longer blanking (`tbl = 0b10`) it can delay off-time enough to create undesired current peaks, especially on a fast step edge.
  - 👉 Try `tbl = 0b01` and/or `toff = 4` to see if it improves things.
4. **`PWMCONF` parameters**
  - You’re using: `pwmconf.pwm_ofs = 30; pwmconf.pwm_reg = 4;` compared to the TMC2208 `pwmconf.pwm_ofs = 36;
pwmconf.pwm_reg = 8;`. This means your TMC2240 has a lower PWM offset and regulation strength, which can affect chop stability at low speeds or with light load. If the PWM waveform sags, it might cause an `s2vsa` detection when driving certain motors.
  - 👉 Try matching `pwm_ofs` and `pwm_reg` closer to the 2208 values (e.g. `ofs = 36`, `reg = 8`) and monitor for changes.
5. **Other diagnostic suggestions**
  - Try SpreadCycle mode: Temporarily disable StealthChop to rule out bad PWM behavior at low speed.

---
What about the settings borrowed from Makerbase, you may ask? So I did.
```c
pwmconf.pwm_ofs            = 29;
pwmconf.pwm_grad           = 30;
pwmconf.pwm_freq           = 0b00;
pwmconf.pwm_autoscale      = true;
pwmconf.pwm_autograd       = true;
pwmconf.freewheel          = 0;
pwmconf.pwm_meas_sd_enable = false;
pwmconf.pwm_dis_reg_stst   = false;
pwmconf.pwm_reg            = 4;
pwmconf.pwm_lim            = 12;
```

Field | Your previous | New version | Notes
-- | -- | -- | --
pwm_ofs | 30 | 29 | Very close. 28–36 is a good range. Lower values save power but reduce headroom.
pwm_grad | (missing) | 30 | Important. Higher grad gives faster response to load. 30 is good.
pwm_reg | 4 | 4 | OK. Often 4–8. Affects regulation response strength.
pwm_lim | 12 | 12 | Standard.
pwm_freq | (missing) | 0b00 | 1/1024 fCLK (≈39kHz @ 40MHz). Default and safe.
pwm_autoscale | true | true | Good. Enables adaptive PWM for quietness.
pwm_autograd | true | true | Good. Works with autoscale.
freewheel | (not specified) | 0 | Normal operation.
pwm_meas_sd_enable | (not specified) | false | OK unless you’re measuring sense resistor voltage.
pwm_dis_reg_stst | (not specified) | false | Good. Allows regulation as needed.

### 👍 Why this is better:

- `pwm_grad = 30` and `pwm_ofs = 29` strike a good balance between quietness and responsiveness.
- `pwm_freq = 0b00` gives a low-frequency PWM suitable for 24V operation (avoids high-frequency losses).
- `autoscale` + `autograd` ensure the driver adjusts gracefully to load changes.

These values match what Trinamic shows in application notes for StealthChop-enabled axes (like X, Y, or Z) in 3D printing or CNC.

### 🛠 Suggestion

Try using these PWM settings in your TMC2240 init, especially in combination with:
- stealthChop mode on
- ```
  CHOPCONF.toff = 4
  TBL = 0b01
  ```
- Slightly more conservative `DRV_CONF.slope_control`

Also, log or monitor the `DRV_STATUS` and `GSTAT` periodically during testing to catch any other driver-side warnings before failure.

**Comment by dbuezas** [comment]
Diag0 defaults to open drain, does the endstop pin have a pullup, and is the endstop configured as active low?

Otherwise set the diag0_pushpull bit of the gconf register to 1 which also makes it active high.

**Comment by thinkyhead** [comment]
The TMC2240 drivers I ordered will arrive tomorrow and then I can put them through various tests to find the best defaults for PWM, stealthChop, etc. I will also compare our settings to those of other softwares that support this model of stepper driver. And perhaps I can even get advice from a Trinamic engineer. I hear they are very friendly.

**Comment by thinkyhead** [comment]
Gathering some more reference material…
- https://klipper.discourse.group/t/sensorless-homing-with-the-tmc-2240-drivers/11438/33
- https://www.klipper3d.org/Config_Reference.html?h=tmc2240#tmc2240
- https://mellow.klipper.cn/en/docs/ProductDoc/ModuleDrive/tmc2240/

File: Marlin/Configuration_adv.h [hunk 1]
```diff
@@ -3503,6 +3502,7 @@
     //#define W_STALL_SENSITIVITY  8
     //#define SPI_ENDSTOPS              // TMC2130, TMC2240, and TMC5160
     //#define IMPROVE_HOMING_RELIABILITY
+    //#define PREFER_STALLGUARD4        // TMC2240
```
Comment (thisiskeithb) [inline Marlin/Configuration_adv.h:3505]: Was additional code supposed to be added for this flag?

Edit: Submitted a PR to remove it & the datasheet: https://github.com/MarlinFirmware/Marlin/pull/27919
