### PR TITLE
Better Defaults and Compatibility for SDIO in STM32

### LINKED ISSUE #19274: [BUG] MKS Robin v2.3 issues with HAL/STM32
### Bug Description

During a print, usually early in the print (10+- 5 minutes in roughly) the printer will perform one or two random travels, off the print to one end of an axis and then back to the print (similar to a corrupted SD card line error) and continue printing.  Shorty (minute or so) after this, it stops without any further movement of the printhead or extruders. Then **does the "reset" where the board and screen turn off and then back on as though the power was just cycled off and then on**, or as though the on-board reset button was pushed.  The screen returns to its normal "just after power on" condition, "?" marks flashing in the position indication spots, heaters setting is back to "0" and the temps are dropping to room temperature.

### My Configurations

The board is the MKS Robin v2.3 with MKS TFT v1.1R 
coreXY printer
running on 24volts

files attached

### Steps to Reproduce

1) turn on the printer normally
2) run "SD" in custom commands to enable reading the SD card
3) tap on the SD card icon on the status page
3) browse to the desired g-code to print and start the print 
4) print starts normally prints the first few layers
5) it stops without user input
6) the board restarts on its own

Resets when...
Printing from an SD card in New Marlin GUI mode

Doesn't reset when...
Printing from Pronterface in New Marlin GUI mode
Printing from SD card in classic Marlin UI mode

Build enviro for New GUI is mks_robin_stm32
Build enviro for Classic UI is mks_robin

**Expected behavior:**
Complete the print without stopping.

**Actual behavior:**
Stops mid-print without raising.
If allowed to, the nozzle is stuck in the cooling print.

#### Additional Information
STL is from Fusion 360
G-code created by PrusaSlicer
No issues with hundreds of other prints from these sources.

Note: used the Discord #support channel to attempt a resolution to no avail.  Username Mattdog01.

[Configuration files.zip](https://github.com/MarlinFirmware/Marlin/files/5179723/Configuration.files.zip)

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

SDIO from STM32 have some different defaults and configurable options, from STM32F1. This PR add the compatibility options and match the default parameters.

### Benefits

Make STM32 more compatible with STM32F1, and more stable.

Should fix #19274

### CODE REVIEW

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp [hunk 1]
```diff
@@ -88,18 +88,37 @@
...
+  // SDIO Max Clock (naming from STM Manual, don't change)
+  #define SDIOCLK 48000000
+
+  static uint32_t sdio_set_clock(uint32_t clk) {
+    /*
+     * limit the SDIO master clock to 8/3 of PCLK2. See STM32 Manuals
+     * Also limited to no more than 48Mhz (SDIOCLK).
+     */
+    const uint32_t pclk2 = HAL_RCC_GetPCLK2Freq();
+    clk = min(clk, ((uint32_t)pclk2/3)*8);
```
Comment (sjasonsmith) [inline Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: You should get more accurate results if you multiply before divide.

For example: If `pclk2 = 100`, ideal answer is 266.66667...

`(uint32_t)pclk2 / 3 * 8 == 264`

`(uint32_t)pclk2 * 8 / 3 == 266`

Ideal answer is 266.66

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp [hunk 2]
```diff
@@ -88,18 +88,37 @@
...
+
+  // SDIO retries, configurable. Default is 3, from STM32F1
+  #ifndef SDIO_READ_RETRIES
+    #define SDIO_READ_RETRIES                  3
+  #endif
+
+  // SDIO Max Clock (naming from STM Manual, don't change)
+  #define SDIOCLK 48000000
+
+  static uint32_t sdio_set_clock(uint32_t clk) {
```
Comment (sjasonsmith) [inline Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: This name could be better. It is not easy to tell this returns a clock divider.

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp [hunk 3]
```diff
@@ -88,18 +88,37 @@
...
+    /*
+     * limit the SDIO master clock to 8/3 of PCLK2. See STM32 Manuals
+     * Also limited to no more than 48Mhz (SDIOCLK).
+     */
+    const uint32_t pclk2 = HAL_RCC_GetPCLK2Freq();
+    clk = min(clk, ((uint32_t)pclk2/3)*8);
+    clk = min(clk, (uint32_t)SDIOCLK);
+    // round up divider, so we don't run the card over the speed supported.
+    return pclk2/clk + (pclk2 % clk != 0) - 2;
```
Comment (sjasonsmith) [inline Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: How is this rounding up?

It looks like it _sometimes_ adds one, but _always_ subtracts 2. Without rounding would this already have a `- 2`?

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 2 above)
Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: Perhaps `sdio_calc_clock_divider`?

File: Marlin/src/pins/stm32f1/pins_MKS_ROBIN.h [hunk 4]
```diff
@@ -165,6 +165,8 @@
 #define SPI_DEVICE                             2
 
 #define SDIO_SUPPORT
+#define SDIO_CLOCK                       4500000
+#define SDIO_READ_RETRIES                     16
```
Comment (sjasonsmith) [inline Marlin/src/pins/stm32f1/pins_MKS_ROBIN.h:169]: Why is this set in both the pins file and also `build_flags`?

Comment (sjasonsmith) [reply Marlin/src/pins/stm32f1/pins_MKS_ROBIN.h:169]: Is it used by framework libraries, that cannot see defines from the Marlin pins file?

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 1 above)
Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: I'm following the STM32 manual... I know that the order don't make too much diference, but I'm following the order of stm32 manual...

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 2 above)
Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: I agree that the name is bad. I thought in changing it too.. But in the end I kept it, because si the same name as maple.

Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: I don't care about Maple.

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 1 above)
Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: Where in the manual? I would like to look at it.

I would consider this a math bug, right now.

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 3 above)
Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: The comment explains why it's round up, in the case of remainder, it's better to get a higher divider to avoid pass the asked speed.

The `-2` it's because stm32duino will add `+ 2` to the divider we pass, as documented in their documentation.

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 1 above)
Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: My point is that the order _does_ make a difference. When doing integer math operations need to be ordered to minimize rounding errors.

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 2 above)
Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: By which I mean that we should not allow badly named Maple code to force bad names on us here.

File: Marlin/src/pins/stm32f1/pins_MKS_ROBIN.h (hunk 4 above)
Comment (rhapsodyv) [reply Marlin/src/pins/stm32f1/pins_MKS_ROBIN.h:169]: > Why is this set in both the pins file and also `build_flags`?

I migrate the build_flags from TRANSFER_CLOCK_DIV to SDIO_CLOCK. Them I added in the Matt board the value that should work for him (the same value of other mks boards)

Comment (rhapsodyv) [reply Marlin/src/pins/stm32f1/pins_MKS_ROBIN.h:169]: > Is it used by framework libraries, that cannot see defines from the Marlin pins file?

It's used only by marlin.

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 1 above)
Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: Screen Shot 2020-12-26 at 18 01 20

Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: If / 3 * 8 gives a lower value, I think we should keep it.

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 3 above)
Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: `SDIO clock frequency is 48MHz / (TRANSFER_CLOCK_DIV + 2)`

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 1 above)
Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: Which manual does this come from? I would like to look at it in context.

The image you show is not code. It does not necessarily assume integer rounding will occur.

File: Marlin/src/pins/stm32f1/pins_MKS_ROBIN.h (hunk 4 above)
Comment (sjasonsmith) [reply Marlin/src/pins/stm32f1/pins_MKS_ROBIN.h:169]: I think we should be consistent and either always set it in pins files or always set in platformio.ini.

If it is only used by Marlin the pins file is the better place for it.

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 1 above)
Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: F4, page 1022: https://www.st.com/resource/en/reference_manual/dm00031020-stm32f405-415-stm32f407-417-stm32f427-437-and-stm32f429-439-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf

F1, page 569: https://www.st.com/resource/en/reference_manual/cd00171190-stm32f101xx-stm32f102xx-stm32f103xx-stm32f105xx-and-stm32f107xx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf

Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: I found the manual. Reviewing now.

Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: So, if you treated their formula as integer math:

`Frequency(PCLK2) >= 0 * Frequency(SDIO_CK)`

This would always evaluate to true!
`Frequency(PCLK2) >= 0`

That is clearly nonsense, meaning they are not providing an integer math formula. I am sure their intention is more like:
`Frequency(PCLK2) >= 0.375 * Frequency(SDIO_CK)`

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 3 above)
Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: Could you add a comment reflecting that? I find it best if you don't have to look up reference manuals for something like this. From the reference manual:

`// SDIO_CK frequency = SDIOCLK / [CLKDIV + 2]`

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 1 above)
Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: what is the verdict?

Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: For me, SDIO_CK must be less than 3/8 of PCLK2.

Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: Or, SDIO_CK must be less than 0.375 of PCLK2, if we don't like fractions :-)

Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: Well, that is backwards. 

SDIO_CK must be less than 8/3 of PCLK2.

The integer math copied from Maple is wrong. The fix is simple.

Change:

` clk = min(clk, ((uint32_t)pclk2/3)*8);`

to

` clk = min(clk, ((uint32_t)pclk2 * 8 / 3);`

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp [hunk 5]
```diff
@@ -128,7 +128,7 @@
     Init.ClockPowerSave      = hsd.Init.ClockPowerSave;
     Init.BusWide             = hsd.Init.BusWide;
     Init.HardwareFlowControl = hsd.Init.HardwareFlowControl;
-    Init.ClockDiv            = sdio_set_clock(SDIO_CLOCK);
+    Init.ClockDiv            = clock2divider(SDIO_CLOCK);
```
Comment (sjasonsmith) [inline Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: Is this referring to "clock2", or "clock to divider"?

If the second, please use words and not numbers. `clock_to_divider`

File: Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp (hunk 1 above)
Comment (rhapsodyv) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: `clk = min(clk, (uint32_t)(pclk2 * 8 / 3));`?

Comment (sjasonsmith) [reply Marlin/src/HAL/STM32/Sd2Card_sdio_stm32duino.cpp]: `pclk2` is already a `uint32_t`, so the cast and parenthesis aren't needed at all. I didn't notice that before.

`clk = min(clk, pclk2 * 8 / 3);

**Review by sjasonsmith — APPROVED** [review]
I assume @rhapsodyv has tested on the Robin boards and the changes make sense to me.

I don't have much background in SDIO. It would be great if @Bob-the-Kuhn (as the original author of this file) or @xC0000005 (since it was mostly used with Lerdge boards) could review as well.

**Comment by rhapsodyv** [comment]
> I assume @rhapsodyv has tested on the Robin boards and the changes make sense to me.
> 
> I don't have much background in SDIO. It would be great if @Bob-the-Kuhn (as the original author of this file) or @xC0000005 (since it was mostly used with Lerdge boards) could review as well.

I tested in a robin nano v2 (F1) and v3 (F4), and @mattdog01 has been testing it for a few weeks on his mks robin. He says that it fixed all his issues with STM32.
