### PR TITLE
Only setup SPI pins if needed

### LINKED ISSUE #19370: Recent LPC176x SPI causes cause pin conflicts on MKS SGEN_L with FYSETC Mini display
### Bug Description

Recent changes to LPC176x SPI code in commit 1a4b82a5d663ab7f68199bf77183047c1133e479 configures pins for all SPI controllers, even if they are not used.

This causes problems for boards which do not use all SPI controllers, and repurpose those pins for something else. If they are only used as GPIO, they will likely not reconfigure their pin function, and the pin will remain connected to the SPI controller.

I discovered this on an MKS SGEN_L when using a FYSETC Mini display. It looks like there is potential for additional conflicts when other displays are used.

The problem occurs due to this initialization code in `SPIClass::SpiClass`, because the same pin (`P0_15`) is both `BOARD_SPI1_SCK_PIN`, and the `LCD_RESET_PIN` pin for the FYSETC Mini display.

```
  PINSEL_CFG_Type PinCfg;  // data structure to hold init values
  #if BOARD_NR_SPI >= 1
    _settings[0].spi_d = LPC_SSP0;
    _settings[0].dataMode = SPI_MODE0;
    _settings[0].dataSize = DATA_SIZE_8BIT;
    _settings[0].clock = SPI_CLOCK_MAX;
    // _settings[0].clockDivider = determine_baud_rate(_settings[0].spi_d, _settings[0].clock);
    PinCfg.Funcnum = 2;
    PinCfg.OpenDrain = 0;
    PinCfg.Pinmode = 0;
    PinCfg.Pinnum = LPC176x::pin_bit(BOARD_SPI1_SCK_PIN);
    PinCfg.Portnum = LPC176x::pin_port(BOARD_SPI1_SCK_PIN);
    PINSEL_ConfigPin(&PinCfg);
    SET_OUTPUT(BOARD_SPI1_SCK_PIN);
```
### My Configurations

This is a minimal configuration for an MKS SGEN_L 1.0 with a FYSETC Mini 1.2 display.
If it has not already been merged, you will need to include the change from #19369 to fix an issue in the MKS_SGen_L pins file.
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5213445/Configuration.zip)

### Steps to Reproduce

1. Power on board

**Expected behavior:**
    Marlin splash screen, followed by normal menus.

**Actual behavior:**
    Screen visibly powers on, but never displays anything.

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

It fixes #19370. Now, the SPI pins are only initialised once and just if used. The pin setup is done in the first use.

### Benefits

Fixes #19370.

### CODE REVIEW

**Comment by sjasonsmith** [comment]
This fixed the issue with the FYSETC Mini display, but I'm having some trouble with the ONBOARD SD card.

I don't know whether that is due to this change or not. I'll have to do some more testing with this in the morning.

**Comment by rhapsodyv** [comment]
I will try in my SRK too.

**Comment by rhapsodyv** [comment]
Tested in my SKR 1.4 Turbo + ` SDCARD_CONNECTION ONBOARD` + FYSETC_MINI_12864_1_2 or REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER.

I didn't find any problem accessing the SD card, neither get any error.

File: Marlin/src/HAL/LPC1768/HAL_SPI.cpp [hunk 1]
```diff
@@ -233,6 +202,42 @@ SPIClass::SPIClass(uint8_t device) {
...
+  if ((_currentSetting->spi_d == LPC_SSP0 && spiInitialised[0] == false) ||
+      (_currentSetting->spi_d == LPC_SSP1 && spiInitialised[1] == false)) {
+    pin_t sck, miso, mosi;
+    if (_currentSetting->spi_d == LPC_SSP0) {
+      sck = BOARD_SPI1_SCK_PIN;
+      miso = BOARD_SPI1_MISO_PIN;
+      mosi = BOARD_SPI1_MOSI_PIN;
+      spiInitialised[0] = true;
+    }
+    else if (_currentSetting->spi_d == LPC_SSP0) {
```
Comment (sjasonsmith) [inline Marlin/src/HAL/LPC1768/HAL_SPI.cpp]:
```suggestion
    else if (_currentSetting->spi_d == LPC_SSP1) {
```

**Comment by sjasonsmith** [comment]
The the most recent change, this works fine with the SGEN_L. It differs from the SKR because the SKR uses SPI0 for everything, and the SGEN_L uses SPI1.

**Comment by sjasonsmith** [comment]
I guess I didn't describe the problem I was seeing. When I switched to a RepRapDiscount Full Graphics display on the SGEN_L, I could not enable both SD and LCD, or the LCD would freeze up. With the most recent change to this branch it now works with both enabled, with SPI set to both ONBOARD and LCD.
