### PR TITLE
FT_MOTION: Fix shaper buffer size & planner

### LINKED ISSUE #27535: [BUG] FT_MOTION causes violent Y movement
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When I enable FT_MOTION travel moves on the Y axis end violently, causing layer shifts.

My settings:
```
Send: M503
Recv: echo:; Linear Units:
Recv: echo:  G21 ; (mm)
Recv: echo:; Temperature Units:
Recv: echo:  M149 C ; Units in Celsius
Recv: echo:; Filament settings (Disabled):
Recv: echo:  M200 S0 D1.75
Recv: echo:; Steps per unit:
Recv: echo:  M92 X79.52 Y80.00 Z400.00 E424.83
Recv: echo:; Max feedrates (units/s):
Recv: echo:  M203 X500.00 Y500.00 Z10.00 E60.00
Recv: echo:; Max Acceleration (units/s2):
Recv: echo:  M201 X3000.00 Y3000.00 Z100.00 E5000.00
Recv: echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
Recv: echo:  M204 P500.00 R3000.00 T3000.00
Recv: echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>):
Recv: echo:  M205 B20000.00 S0.00 T0.00 J0.03
Recv: echo:; Home offset:
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:; Auto Bed Leveling:
Recv: echo:  M420 S1 Z10.00 ; Leveling ON
[G29 commands removed for brevity]
Recv: echo:; Material heatup parameters:
Recv: echo:  M145 S0 H205.00 B60.00 F0
Recv: echo:  M145 S1 H240.00 B80.00 F0
Recv: echo:  M145 S2 H220.00 B70.00 F0
Recv: echo:  M145 S3 H230.00 B50.00 F0
Recv: echo:; Power-loss recovery:
Recv: echo:  M413 S0 ; OFF
Recv: echo:; Z-Probe Offset:
Recv: echo:  M851 X-28.50 Y22.00 Z-2.04 ; (mm)
Recv: echo:; Skew Factor:
Recv: echo:  M852 I0.000000 J0.000000 K0.000000 ; XY, XZ, YZ
Recv: echo:; Fixed-Time Motion:
Recv: echo:  M493 S1 A36.00 B29.50 D0 F0.00 H0.00 P1 K26.10
Recv: echo:; Nonlinear Extrusion:
Recv:   M592 A0.00 B0.00 C1.00
Recv: echo:; Input Shaping:
Recv: echo:  M593 X F0.00 D0.15
Recv: echo:  M593 Y F0.00 D0.20
Recv: echo:; Linear Advance:
Recv: echo:  M900 K0.10
Recv: echo:; Filament load/unload:
Recv: echo:  M603 L0.00 U100.00 ; (mm)
Recv: echo:; Filament runout sensor:
Recv: echo:  M412 S1 ; Sensor ON
Recv: echo:; Model predictive control:
Recv: echo:  M306 E0 P40.00 C14.54 R0.2053 A0.1187 F0.1686 H0.0056
Recv: ok
```

Executing the GCODE
```
M493 S0
G0 F21000
G0 Y50
G0 Y150
```
Gives this (expected) result:

https://github.com/user-attachments/assets/d9dd3240-b129-4e2c-8e5f-61d482297cf0

Executing the GCODE
```
M493 S1 X0 Y0
G0 F21000
G0 Y50
G0 Y150
```
Gives this result:

https://github.com/user-attachments/assets/8ad083f3-194f-4c32-9839-585870ed5461

I'm using the latest bugfix-2.1.x (2024/11/16)

### Bug Timeline

_No response_

### Expected behavior

Smooth movement both with FT_MOTION enabled and disabled

### Actual behavior

Violent movement with FT_MOTION enabled

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

bugfix-2.1.x 2024/11/16

### Printer model

Neptune 3 Plus

### Electronics

stock

### LCD/Controller

stock elegoo LCD

### Other add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

None

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/user-attachments/files/17802692/Configuration.zip)

```
Send: M115
Recv: echo:M115
Recv: FIRMWARE_NAME:Marlin bugfix-2.1.x (Nov 18 2024 14:24:38) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:3D Printer KINEMATICS:Cartesian EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Recv: Cap:SERIAL_XON_XOFF:0
Recv: Cap:BINARY_FILE_TRANSFER:0
Recv: Cap:EEPROM:1
Recv: Cap:VOLUMETRIC:1
Recv: Cap:AUTOREPORT_POS:0
Recv: Cap:AUTOREPORT_TEMP:1
Recv: Cap:PROGRESS:0
Recv: Cap:PRINT_JOB:1
Recv: Cap:AUTOLEVEL:1
Recv: Cap:RUNOUT:1
Recv: Cap:Z_PROBE:1
Recv: Cap:LEVELING_DATA:1
Recv: Cap:BUILD_PERCENT:1
Recv: Cap:SOFTWARE_POWER:0
Recv: Cap:TOGGLE_LIGHTS:1
Recv: Cap:CASE_LIGHT_BRIGHTNESS:1
Recv: Cap:EMERGENCY_PARSER:1
Recv: Cap:HOST_ACTION_COMMANDS:1
Recv: Cap:PROMPT_SUPPORT:1
Recv: Cap:SDCARD:1
Recv: Cap:MULTI_VOLUME:0
Recv: Cap:REPEAT:0
Recv: Cap:SD_WRITE:1
Recv: Cap:AUTOREPORT_SD_STATUS:0
Recv: Cap:LONG_FILENAME:1
Recv: Cap:LFN_WRITE:1
Recv: Cap:CUSTOM_FIRMWARE_UPLOAD:0
Recv: Cap:EXTENDED_M20:1
Recv: Cap:THERMAL_PROTECTION:1
Recv: Cap:MOTION_MODES:0
Recv: Cap:ARCS:1
Recv: Cap:BABYSTEPPING:1
Recv: Cap:EP_BABYSTEP:0
Recv: Cap:CHAMBER_TEMPERATURE:0
Recv: Cap:COOLER_TEMPERATURE:0
Recv: Cap:MEATPACK:0
Recv: Cap:CONFIG_EXPORT:0
```

### PR DESCRIPTION
**Pull request by dbuezas**
#28217 handling of buffer sizes was unfortunately not correct. And the old calculation was also missing the damping factor.

The calculation comes from shaping.cpp:
It's the max possible value of Ni[max_i] before subtracting the centroid (inside `set_axis_shaping_N`)

Also guarded more usages of the shapers to further reduce flash & ram consumption.
Saves an extra kb with all but one shaper disabled 

Also fixes shaky ftmotion caused by a mistake of mine a couple days back

### CODE REVIEW

File: Marlin/src/module/ft_motion/shaping.h [hunk 1]
```diff
@@ -91,14 +91,24 @@ typedef FTShapedAxes<float>            ft_shaped_float_t;
...
 typedef struct AxisShaping {
-  bool ena = false;                 // Enabled indication
-  float d_zi[FTM_ZMAX] = { 0.0f };  // Data point delay vector
-  float Ai[5];                      // Shaping gain vector
-  int32_t Ni[5];                    // Shaping time index vector
-  uint32_t max_i;                   // Vector length for the selected shaper
+  bool ena = false;                         // Enabled indication
+  float d_zi[FTM_ZMAX] = { 0.0f };          // Data point delay vector
+  float Ai[FTM_SHAPING_Ni_SIZE];            // Shaping gain vector
+  int32_t Ni[FTM_SHAPING_Ni_SIZE] = { 0 };  // Shaping time index vector
```
Comment (dbuezas) [inline Marlin/src/module/ft_motion/shaping.h]: the `= { 0 }` could be removed, if structs are initialised to zero anyway. I just set this for the case where all shapers are disabled, in which case even more code can be stripped out

Comment (thinkyhead) [reply Marlin/src/module/ft_motion/shaping.h]: It's fine to do this in a `struct` when there are other default values.

File: Marlin/src/gcode/feature/ft_motion/M493.cpp [hunk 2]
```diff
@@ -296,7 +296,7 @@ void GcodeSuite::M493() {
   const float zetaVal = seenI ? parser.value_float() : 0.0f;
   const bool goodZeta = seenI && c.goodZeta(zetaVal);
   if (seenI && !goodZeta)
-    SERIAL_ECHOLN(F("?Invalid "), F("(I) Zeta value. (0.01-1.0)")); // Zeta out of range
+    SERIAL_ECHOLN(F("?Invalid "), F("(I) Zeta value. (0.01-0.25)")); // Zeta out of range
```
Comment (thinkyhead) [inline Marlin/src/gcode/feature/ft_motion/M493.cpp]: This should probably be `STRINGIFY(FTM_MAX_DAMPENING)` (or just `, FTM_MAX_DAMPENING`) instead of `0.25`.

Comment (dbuezas) [reply Marlin/src/gcode/feature/ft_motion/M493.cpp]: Oh yes, good idea

File: Marlin/src/gcode/feature/ft_motion/M493.cpp [hunk 3]
```diff
@@ -33,14 +33,14 @@ void say_shaper_type(const AxisEnum a, bool &sep, const char axis_name) {
...
-    case ftMotionShaper_3HEI:  SERIAL_ECHOPGM("3 Hump EI"); break;
-    case ftMotionShaper_MZV:   SERIAL_ECHOPGM("MZV");       break;
+    TERN_(FTM_SHAPER_ZV,    case ftMotionShaper_ZV:    SERIAL_ECHOPGM("ZV");        break);
+    TERN_(FTM_SHAPER_ZVD,   case ftMotionShaper_ZVD:   SERIAL_ECHOPGM("ZVD");       break);
+    TERN_(FTM_SHAPER_ZVDD,  case ftMotionShaper_ZVDD:  SERIAL_ECHOPGM("ZVDD");      break);
+    TERN_(FTM_SHAPER_ZVDDD, case ftMotionShaper_ZVDDD: SERIAL_ECHOPGM("ZVDDD");     break);
+    TERN_(FTM_SHAPER_EI,    case ftMotionShaper_EI:    SERIAL_ECHOPGM("EI");        break);
+    TERN_(FTM_SHAPER_2HEI,  case ftMotionShaper_2HEI:  SERIAL_ECHOPGM("2 Hump EI"); break);
+    TERN_(FTM_SHAPER_3HEI,  case ftMotionShaper_3HEI:  SERIAL_ECHOPGM("3 Hump EI"); break);
+    TERN_(FTM_SHAPER_MZV,   case ftMotionShaper_MZV:   SERIAL_ECHOPGM("MZV");       break);
```
Comment (thinkyhead) [inline Marlin/src/gcode/feature/ft_motion/M493.cpp:43]: If you disable `FTM_SHAPER_ZV` does this still compile with a spurious `;` in the middle of a `switch` block?

Comment (dbuezas) [reply Marlin/src/gcode/feature/ft_motion/M493.cpp:43]: Looks like it, but isn't it inconsequential?

Comment (thinkyhead) [reply Marlin/src/gcode/feature/ft_motion/M493.cpp:43]: test added.
