### PR TITLE
FYSETC S6: Allow redefine pin functions, enable eeprom

### LINKED ISSUE #18434: [FR] Proper EEPROM support on Fysetc S6
### Description

Add support for the onboard EEPROM for Fysetc S6

### Feature Workflow

According to the documentation for Fysetc S6 there is an onboard 24LC16 EEPROM
When compiling with PRINTCOUNTER enabled, an error is issued:
```
Marlin\src\HAL\STM32\../../inc/../HAL/STM32/inc/SanityCheck.h:44:4: warning: #warning "FLASH_EEPROM_EMULATION may cause long delays when writing and should not be used while printing." [-Wcpp]
   44 |   #warning "FLASH_EEPROM_EMULATION may cause long delays when writing and should not be used while printing."
      |    ^~~~~~~
Marlin\src\HAL\STM32\../../inc/../HAL/STM32/inc/SanityCheck.h:45:4: error: #error "Disable PRINTCOUNTER or choose another EEPROM emulation."

This is a bit wierd, as the controller has on-board EEPROM.

Also, a warning is issued on:
Marlin\src\HAL\STM32\../../inc/../HAL/STM32/inc/SanityCheck.h:44:4: warning: #warning "FLASH_EEPROM_EMULATION may cause long delays when writing and should not be used while printing." [-Wcpp]
   44 |   #warning "FLASH_EEPROM_EMULATION may cause long delays when writing and should not be used while printing."
```
But no FLASH_EEPROM_EMULATION definitions exist on configuration.h or configuration_adv.h

#### Additional Information

Schematics for Fysetc S6 can be found on https://github.com/FYSETC/FYSETC-S6

Tested with a pull of the current bugfix on June 26th, 2020

### PR DESCRIPTION
**Pull request by LinFor**
### Description

FYSETC S6 pin file enhancements

### Benefits

- Allow override endstops, heaters and fans socket function in Configuration.h without redefinition warning
- S6 has i2c eeprom soldered onboard, enables it's support. Maybe not all boards have it soldered (board images on fysetc site shows not-soldered placeholder), but it present in schematic and my v1.2 have it soldered.

### Configurations

None special

### Related Issues

#18434 - Proper EEPROM support on Fysetc S6 _(added by sjasonsmith)_

### CODE REVIEW

**Comment by sjasonsmith** [comment]
Can you describe your use-case which makes overriding every basic pin necessary? We don't normally do it for every pin on other boards.

File: Marlin/src/pins/stm32f4/pins_FYSETC_S6.h [hunk 1]
```diff
@@ -41,17 +41,17 @@
...
+  #define I2C_EEPROM
 #endif
 
 #if ENABLED(FLASH_EEPROM_EMULATION)
   // Decrease delays and flash wear by spreading writes across the
   // 128 kB sector allocated for EEPROM emulation.
   #define FLASH_EEPROM_LEVELING
 #elif ENABLED(I2C_EEPROM)
-  #define MARLIN_EEPROM_SIZE              0x1000  // 4KB
+  #define MARLIN_EEPROM_SIZE              0x0700  // 2KB
```
Comment (sjasonsmith) [inline Marlin/src/pins/stm32f4/pins_FYSETC_S6.h]: 2kb is 0x0800. Which is correct?

File: Marlin/src/pins/stm32f4/pins_FYSETC_S6.h [hunk 2]
```diff
@@ -41,17 +41,17 @@
 // EEPROM Emulation
 //
 #if NO_EEPROM_SELECTED
-  #define FLASH_EEPROM_EMULATION
+  //#define FLASH_EEPROM_EMULATION
   //#define SRAM_EEPROM_EMULATION
-  //#define I2C_EEPROM
+  #define I2C_EEPROM
```
Comment (sjasonsmith) [inline Marlin/src/pins/stm32f4/pins_FYSETC_S6.h]: Is this really all that was needed? I assume you have tested this and it works?

I am asking because I was under the impression that some addition pin definitions would be needed. Have you done anything like that in your configuration files?

Comment (sjasonsmith) [reply Marlin/src/pins/stm32f4/pins_FYSETC_S6.h]: Perhaps that is all defined in the board's variant file.

Comment (sjasonsmith) [reply Marlin/src/pins/stm32f4/pins_FYSETC_S6.h]: Probably these from `variant.h`. I was confused because people in the FR were referring to a different EEPROM type used on the Ender 3 V2.

```
// I2C Definitions
#define PIN_WIRE_SDA            PB9
#define PIN_WIRE_SCL            PB8
```

File: Marlin/src/pins/stm32f4/pins_FYSETC_S6.h [hunk 3]
```diff
@@ -41,17 +41,17 @@
 // EEPROM Emulation
 //
 #if NO_EEPROM_SELECTED
-  #define FLASH_EEPROM_EMULATION
+  //#define FLASH_EEPROM_EMULATION
```
Comment (sjasonsmith) [inline Marlin/src/pins/stm32f4/pins_FYSETC_S6.h]: I wonder how many people changing the default will inconvenience...

I have a board without an EEPROM, but it is damaged. If only the first batch is missing them, perhaps it is fine to change it.

**Review by sjasonsmith — CHANGES_REQUESTED** [review]

File: Marlin/src/pins/stm32f4/pins_FYSETC_S6.h (hunk 1 above)
Comment (LinFor) [reply Marlin/src/pins/stm32f4/pins_FYSETC_S6.h]: Sorry, this is typo. Of course 0x0800.

File: Marlin/src/pins/stm32f4/pins_FYSETC_S6.h (hunk 2 above)
Comment (LinFor) [reply Marlin/src/pins/stm32f4/pins_FYSETC_S6.h]: Yes, it works with only I2C_EEPROM.

**Comment by LinFor** [comment]
> Can you describe your use-case which makes overriding every basic pin necessary? We don't normally do it for every pin on other boards.

My case is as follows:

- I am using 4-pin coolers with PWM signal speed control. Because the power ports are switched by mosfets, I cannot control the coolers through the standard fan ports (there is, of course, a variant with a voltage divider, but it is very redundant in my opinion). For the purpose of controlling the speed of the coolers, I use endstop ports, which give out positive PWM.
- I am using a 220v table heater connected via a solid state relay. Because to control the relay does not require a lot of current, I use one of the free fan ports to control the heating of the bed - the xh 2.54 connector is more convenient to use (than screw terminals) and provides a reliable contact, at the same time freeing up the power port for future use.
- The backlighting of the case and the blowing of the extruder radiator also use fan ports due to their convenience.

Perhaps I'm going the wrong way, but I used a similar redefinition method on the Gen L board (variant of RAMPS) and found it very convenient.

File: Marlin/src/pins/stm32f4/pins_FYSETC_S6.h (hunk 3 above)
Comment (LinFor) [reply Marlin/src/pins/stm32f4/pins_FYSETC_S6.h]: It may be necessary to allow to choose the way of storing the state ("eeprom") in the configuration.
Ok, I really don't know how many people have boards with an unsoldered chip, I thought it was not in the photo simply because they photographed an engineering sample. It is present on my board (it is in the fall of 2019).

**Comment by sjasonsmith** [comment]
To summarize, we have two decisions to make:

1. Do we change the default EEPROM to IIC, even though the first batch does not have it populated?
My recommendation: Change it and risk inconveniencing the few people who don't have the EEPROM. It is an easy workaround to switch back. If it comes up we can consider forcing users to select in their config file, with no default.

2. Do we want to make all these pins conditional? I want @thinkyhead's input on this. Some consistency to our strategy across boards would be good.
I personally feel that when you are straying wildly from the configs (as you are), you should just edit the pins file directly. Making every pin conditional clutters the file and makes it harder to read/maintain.

**Review by sjasonsmith — APPROVED** [review]

**Comment by sjasonsmith** [comment]
I am having some errors between my chair and keyboard with regard to using GitHub's review tooling. Please disregard my approval, as it is really contingent on the previous comment.

**Comment by thisiskeithb** [comment]
> I personally feel that when you are straying wildly from the configs (as you are), you should just edit the pins file directly. Making every pin conditional clutters the file and makes it harder to read/maintain.

Ditto.

**Comment by sjasonsmith** [comment]
I have decided to roll most of this back, keeping only the fix to the EEPROM size.

My reasoning is as follows:

1. For pin overrides, this is inconsistent with other boards. When completely redefining pin meanings users should just edit the pins file. If we wish to allow overriding every pin we should do it in a way that is consistent across boards.

2. For default EEPROM mechanism, I decided it should not change. This contradicts my earlier statement, but the following are my reasons:
    - V2.0 boards already use I2C by default, and are probably most new users
    - Even for boards with I2C, this will cause users to lose their existing values, such as UBL meshes. The upset people when we first added the `FLASH_EEPROM_LEVELING` behavior, and I would like to avoid that if possible.
    - I didn't have a great way to communicate to early V1.2 users that their EEPROM may not work. I tried doing it to warnings, but this causes hundreds of warnings during an otherwise normal build.

Flash EEPROM emulation should be fine for most users, and they likely will not care or notice which mechanism they use. For those users (such as you) which want to use I2C, you can simply add `#define I2C_EEPROM` to your `Configuration.h` file, or edit the default in the pins file.
