### PR TITLE
🩹 Fix MKS Gen-L V1 pins, allow more RAMPS overrides

### LINKED ISSUE #26971: [BUG] MKS_GEN_L extruder fan not working
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The extruder fan would not turn on when reaching or exceeding 50 degrees C. Tried old stable firmware I had (1.1.9), and it worked. After trying multiple configurations for 2.1.x and making sure all settings are correct, I compared the pins file for MKS_GEN_L and found that the wrong MOSFET was assigned to pin 7. Currently it sais #define MOSFET_B_PIN, but this should be #define MOSFET_D_PIN.
Changing to #define MOSFET_D_PIN and building the firmware again has fixed the issue for me! 
I suppose everyone using this board will face the same issues, so could you update this please?

### Bug Timeline

Around a year ago (same issue with old bugfix 2.1.x firmware I downloaded around a year ago)

### Expected behavior

Extruder fan to start spinning above 50 degrees C

### Actual behavior

Extruder fan never started spinning

### Steps to Reproduce

- Build firmware for MKS_GEN_L board.
- Use Artillery Genius BL touch configuration file
- Flash firmware
- Set extruder temperature to 60 degrees C 

### Version of Marlin Firmware

bugfix 2.1.x 13-4-2024

### Printer model

Artillery Genius

### Electronics

Stock + BL touch

### LCD/Controller

MKS TFT28 V1.0

### Other add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration bugfix 2.1.x 14-4-2024.zip](https://github.com/MarlinFirmware/Marlin/files/14972277/Configuration.bugfix.2.1.x.14-4-2024.zip)

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

MKS Gen-L V1.0 moseft pins keep getting changed, with the latest being in #25717 since they assumed MKS' schematic was correct & the pins diagram wrong. I physically traced the pins on my MKS Gen-L V1.0 board and the pins diagram is correct, not the schematic.

They are:
```
     HEATER_BED = 8
       HEATER_0 = 10
HEATER_1 / FAN1 = 7 (FAN1 when used in a single hotend config / frequently used for E0_AUTO_FAN_PIN)
           FAN0 = 9
```

I fully defined the pins as they are on the board itself and added silkscreen labels & Marlin's custom `MOSFET_*_PIN` naming scheme as comments and disabled them for documentation purposes. Some `#ifndefs` were required in `pins_RAMPS.h` to prevent a wall of warnings due to pins being redefined.

Also, this board only ships with an ATmega2560, so I updated the board environment to reflect that.

### Requirements

MKS Gen-L V1.0

### Benefits

This will hopefully be the last MKS Gen-L V1.0 change since I physically traced pins in question to the MCU pins.

### Configurations

[Configs from #26971](https://github.com/MarlinFirmware/Marlin/files/14972277/Configuration.bugfix.2.1.x.14-4-2024.zip) or [Artillery Genius BLTouch configs](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Artillery/Genius/BLTouch) from our Configurations repo.

### Related Issues

- #26971
- #25717

### CODE REVIEW

**Comment by thisiskeithb** [comment]
After chatting with @ellensp, I reverted to using the default `MOSFET_*_PIN`s as defined in `pins_RAMPS.h`, but left the correct pins (commented out) in `pins_MKS_GEN_L.h` for documentation purposes so there's no confusion as to what they should be in the future.

**Comment by thisiskeithb** [comment]
Merge conflicts caused by https://github.com/MarlinFirmware/Marlin/commit/9342dae8f04cc0e775515ec903dad1357bd7c344 have been resolved.

**Comment by sjasonsmith** [comment]
@ellensp would you mind reviewing and commenting on this? I'm a bit confused by the back and forth regarding which incorrect pins to use versus comment out. It sounds like you know what's going on and will be better able to assess whether this is ready to go in than I am.

**Comment by thisiskeithb** [comment]
The commented out pins are there for documentation purposes. I physically traced out the connectors/mosfets to the MCU pins on my MKS Gen-L V1 and verified they are correct.

This PR is ready to merge.

**Comment by sjasonsmith** [comment]
I just still don't understand what they mean. They are just commented out pins "for documentation purposes", but do they represent pins that are wrong? Are they from the schematic, from the board? I'm left guessing what a commented out pin names.

Perhaps more explanation is warranted in the comments to describe the errors in the schematic, rather than just the single line saying "there are errors on the schematic". I'm not sure how to interpret that information as I look at the rest of the file.

File: Marlin/src/pins/ramps/pins_MKS_GEN_L.h [hunk 1]
```diff
@@ -37,10 +38,15 @@
 // Heaters / Fans
 //
 
-#define MOSFET_A_PIN                          10  // HE0
-#define MOSFET_B_PIN                           7  // HE1 or FAN Hotend Cooling
-#define MOSFET_C_PIN                           8  // HBED
-#define FAN0_PIN                               9  // FAN Part Cooling
+//#define HEATER_BED_PIN                       8  // H-BED / "MOSFET_C_PIN"
```
Comment (thisiskeithb) [inline Marlin/src/pins/ramps/pins_MKS_GEN_L.h]: `// H-BED / "MOSFET_C_PIN"`

The label on the PCB is "H-BED". The `MOSFET_C_PIN` comment means that this board uses Marlin's custom "`MOSFET_C_PIN`" naming from the `pins_RAMPS.h` include. The entire line can be removed, but I left it here because this particular board's pins file keeps getting changed incorrectly.

File: Marlin/src/pins/ramps/pins_MKS_GEN_L.h [hunk 2]
```diff
@@ -37,10 +38,15 @@
...
+//#define HEATER_0_PIN                        10  // HE0   / "MOSFET_A_PIN"
```
Comment (thisiskeithb) [inline Marlin/src/pins/ramps/pins_MKS_GEN_L.h]: `// HE0   / "MOSFET_A_PIN"`

The label on the PCB is "HE0". The `MOSFET_A_PIN` comment means that this board uses Marlin's custom "`MOSFET_A_PIN`" naming from the `pins_RAMPS.h` include. The entire line can be removed, but I left it here because this particular board's pins file keeps getting changed incorrectly.

File: Marlin/src/pins/ramps/pins_MKS_GEN_L.h [hunk 3]
```diff
@@ -37,10 +38,15 @@
...
+#if ANY(HAS_MULTI_HOTEND, HEATERS_PARALLEL)
+  #define HEATER_1_PIN                         7  // HE1
+#else
+  #define FAN1_PIN                             7  // HE1
+#endif
+
+//#define FAN0_PIN                             9  // FAN / "MOSFET_B_PIN"
```
Comment (thisiskeithb) [inline Marlin/src/pins/ramps/pins_MKS_GEN_L.h]: `// FAN / "MOSFET_B_PIN"`

The label on the PCB is "FAN". The `MOSFET_B_PIN` comment means that this board uses Marlin's custom "`MOSFET_B_PIN`" naming from the `pins_RAMPS.h` include. The entire line can be removed, but I left it here because this particular board's pins file keeps getting changed incorrectly.

**Comment by thisiskeithb** [comment]
> I just still don't understand what they mean. They are just commented out pins "for documentation purposes", but do they represent pins that are wrong? Are they from the schematic, from the board? I'm left guessing what a commented out pin names.
> 

I left some review comments, so hopefully that clears things up.

> Perhaps more explanation is warranted in the comments to describe the errors in the schematic, rather than just the single line saying "there are errors on the schematic". I'm not sure how to interpret that information as I look at the rest of the file.

I'm not able to review MKS' schematic for all the pin & connector errors, but [their pins diagram PDF](https://github.com/makerbase-mks/MKS-GEN_L/blob/master/hardware/MKS%20Gen_L%20V1.0_008/MKS%20Gen_L%20V1.0_008%20PIN.pdf) is correct.

`<sarcasm>`Maybe there needs to be a `STOP CHANGING THESE PINS` warning at the top instead?`</sarcasm>` 😄

File: Marlin/src/pins/ramps/pins_MKS_GEN_L.h [hunk 4]
```diff
@@ -24,7 +24,8 @@
 /**
  * MKS GEN L – Arduino Mega2560 with RAMPS v1.4 pin assignments
  * Schematic: https://github.com/makerbase-mks/MKS-GEN_L/blob/master/hardware/MKS%20Gen_L%20V1.0_008/MKS%20Gen_L%20V1.0_008%20SCH.pdf
```
Comment (sjasonsmith) [inline Marlin/src/pins/ramps/pins_MKS_GEN_L.h:26]:
```suggestion
 * Schematic: https://github.com/makerbase-mks/MKS-GEN_L/blob/master/hardware/MKS%20Gen_L%20V1.0_008/MKS%20Gen_L%20V1.0_008%20SCH.pdf
 * Pin Diagram: https://github.com/makerbase-mks/MKS-GEN_L/blob/master/hardware/MKS%20Gen_L%20V1.0_008/MKS%20Gen_L%20V1.0_008%20PIN.pdf
```

File: Marlin/src/pins/ramps/pins_MKS_GEN_L.h [hunk 5]
```diff
@@ -24,7 +24,8 @@
...
- * ATmega2560, ATmega1280
+ * Note: Schematic contains pin & connector errors
```
Comment (sjasonsmith) [inline Marlin/src/pins/ramps/pins_MKS_GEN_L.h]:
```suggestion
 * Note: Schematic contains pin & connector errors, correct pin mappings are found on the pin diagram
```

File: Marlin/src/pins/ramps/pins_MKS_GEN_L.h (hunk 3 above)
Comment (sjasonsmith) [inline Marlin/src/pins/ramps/pins_MKS_GEN_L.h]:
```suggestion
// The following is included for documentation purposes only. Is is actually defined in pins_RAMPS.h.
//#define FAN0_PIN                             9  // FAN / "MOSFET_B_PIN"
```

File: Marlin/src/pins/ramps/pins_MKS_GEN_L.h (hunk 2 above)
Comment (sjasonsmith) [inline Marlin/src/pins/ramps/pins_MKS_GEN_L.h]:
```suggestion
// The following are included for documentation purposes only. They are actually defined in pins_RAMPS.h.
//#define HEATER_BED_PIN                       8  // H-BED / "MOSFET_C_PIN"
//#define HEATER_0_PIN                        10  // HE0   / "MOSFET_A_PIN"
```

**Review by sjasonsmith — COMMENTED** [review]
What do you think of the more explicit documentation of these that I suggest in this review?

**Comment by thisiskeithb** [comment]
> What do you think of the more explicit documentation of these that I suggest in this review?

All suggested changes accepted/merged. Should be good to go once CI is done.

File: Marlin/src/pins/ramps/pins_MKS_GEN_L.h [hunk 6]
```diff
@@ -37,10 +39,17 @@
 // Heaters / Fans
 //
 
-#define MOSFET_A_PIN                          10  // HE0
-#define MOSFET_B_PIN                           7  // HE1 or FAN Hotend Cooling
-#define MOSFET_C_PIN                           8  // HBED
-#define FAN0_PIN                               9  // FAN Part Cooling
```
Comment (thinkyhead) [inline Marlin/src/pins/ramps/pins_MKS_GEN_L.h:43]: Either the MOSFET pin scheme needs to be retained, or this file needs to do the handling of the flags `*_EFB`, `*_EEB`, etc., for cases where the Extruder, Fan, Bed arrangement may change. These flags may already be set for the `HAS_MULTI_HOTEND` and/or `HEATERS_PARALLEL` and should be preferred over referring to these settings flags directly.

Comment (thinkyhead) [reply Marlin/src/pins/ramps/pins_MKS_GEN_L.h:43]: Reminder that the rule for Extruder, Fan, Bed pins is not to always define them according to their silkscreen label, but according to the configuration requirements. The board may say something like "H1, Fan, Bed" which would correspond to the common default `FET_ORDER_EFB`. But when two extruders are defined, the `FET_ORDER_EEB` flag gets set, so the pins should then be defined as "H1, H2, Bed" with no fan.

If the `FET_ORDER_*` flags aren't coming out right for this board according to those flags, either these FETs are just not defined in the correct sequence, or the general FET assignment in `pins_RAMPS.h` is wonky.

Comment (thinkyhead) [reply Marlin/src/pins/ramps/pins_MKS_GEN_L.h:43]: Hmm, I wonder if it work just using the order 10, 9, 8, 7… But we have to look at the machines these ship in also and see if they are using non-standard ordering on shipping units.

Comment (thisiskeithb) [reply Marlin/src/pins/ramps/pins_MKS_GEN_L.h:43]: > Either the MOSFET pin scheme needs to be retained, or this file needs to do the handling of the flags *_EFB, *_EEB, etc.,

I really don't follow all that `FET_ORDER` stuff since we don't do that on non-AVR boards, but I have physically traced the pins on the MCU and verified that they now match real hardware.

Comment (thisiskeithb) [reply Marlin/src/pins/ramps/pins_MKS_GEN_L.h:43]: > Hmm, I wonder if it work just using the order 10, 9, 8, 7… But we have to look at the machines these ship in also and see if they are using non-standard ordering on shipping units.

We host several Artillery configs and the older/non-32-bit printers use a standard Gen-L: https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/examples/Artillery

File: Marlin/src/pins/ramps/pins_MKS_GEN_L.h [hunk 7]
```diff
@@ -37,10 +39,30 @@
...
+#define HEATER_0_PIN                MOSFET_A_PIN
+#if ANY(FET_ORDER_EEF, FET_ORDER_EEB)
+  #define HEATER_1_PIN              MOSFET_B_PIN
+#endif
+#define HEATER_BED_PIN              MOSFET_C_PIN
+
+#define FAN0_PIN                    MOSFET_D_PIN
+#if ENABLED(FET_ORDER_EFF)
+  #define FAN1_PIN                  MOSFET_B_PIN
+#endif
```
Comment (thinkyhead) [inline Marlin/src/pins/ramps/pins_MKS_GEN_L.h:65]: This should do better, and is more complete. Boards like this one that include `pins_RAMPS.h` and have a preferred plug ordering should all follow this sort of approach and override the standard RAMPS assignments.

While many boards do not implement assignment of the PWM pins based on the `FET_ORDER_*` flags, all pins files are free to do so to handle standard rearrangements and fit them to their preferred usage.
