### PR TITLE
🩹 Add unmeasured ADC reference warning for MKS_TINYBEE board (#27434)

### LINKED ISSUE #27434: [BUG] Wrong temperature readings on MKS TinyBee boards (reference diode varies between boards)
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I got an MKS TinyBee a couple of days ago and I ran into this issue (#24142) when setting up the temperature sensors. 
There is a related fix (#24432), but it doesn't fix it for every board. 

In the tinybee there is a zener diode that along with a resistor and a couple capacitor provides the analog reference for the ESP32's ADC. For what I have tested, it seems that the quality of the zener diode varies quite a bit between boards. The nominal value is 2.5V, the fix changed it in the config to 2.565V. 
I measured the reference with no load (no thermistors connected) and in my board it is 2.642V. Although it is a small difference it throws completely off the temperature measurements (by around 30C). 

There's no easy fix, as changing it to my read value would throw it off for other users. The actual solution would be to change the zener in the board for a better part, or just hack together a better voltage reference (as it also seems to vary quite a bit throughout time). That is likely out of what most users would do, so I think I think it would be good to document it somewhere. Maybe a warning to suggest `BOARD_MKS_TINYBEE`'s users to measure the reference adjust `ADC_REFERENCE_VOLTAGE` appropiately? It feels like this is something that should be in `Configuration_adv.h`, though. 

I'm willing to make the appropiate patches, but I think it deserves some though.
Kind regards, and thanks for all the work put in this awesome project :)

### Bug Timeline

It is an old issue with a known cause

### Expected behavior

I expect the temperature readings to be accurate.

### Actual behavior

The readings are thrown off by around 30C.

### Steps to Reproduce

1. Use the `bugfix-2.1.x` branch. 
2. Measure the pins of any temperature sensor with NO sensors connected. Negative probe to ground. One pin should be ground and the other should be around 2.5V. 
3. If the reading for the second pin is `2.565V` or similar, the issue will not appear. If it is off by >0.1V, the issue will appear as a distorted temperature reading. 
4. Change `ADC_REFERENCE_VOLTAGE` to the measured voltage in `pins_MKS_TINYBEE.h`. The issue should be gone.  

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Anet A6

### Electronics

MKS TinyBee, 4x TMC2209 drivers

### LCD/Controller

None

### Other add-ons

None

### Bed Leveling

None

### Your Slicer

None

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by fermino**
### Description

MKS_TINYBEE uses a voltage reference based on a resistor-zener circuit. In some boards the zener is of dubious quality and it leads to a poor voltage reference, which in turn throws the voltage readings off (in my case, 30°C). This PR lets the user know of that with a compiler warning, so that it can be dealt with accordingly. 

This follows up on #24142 and #24432, and closes #27434.

The reference circuit, out of the [manufacturer's schematic](https://github.com/makerbase-mks/MKS-TinyBee/blob/main/hardware/MKS%20TinyBee%20V1.0_003/MKS%20TinyBee%20V1.0_003%20SCH.pdf): 
image

### Requirements

MKS_TINYBEE with a different voltage reference. 

### Benefits

It lets the user know of a common case, which can be slightly hard to track down. It allows for the related constant to be defined easily. 

### Configurations

Default MKS_TINYBEE.

### Related Issues

#24142 
#27434

### CODE REVIEW

File: Marlin/src/pins/esp32/pins_MKS_TINYBEE.h [hunk 1]
```diff
@@ -115,10 +115,21 @@
...
+ * In some boards the voltage reference is a bit off due to low quality
+ * components. That is enough to throw off the ADC readings and thus the
+ * temperatures by more than 10°C in some cases. If you experience that
+ * problem, measure the reference voltage (VDDA) at the 2nd pin of
+ * TH1/TH2 (with the sensors disconnected) and set ADC_REFERENCE_VOLTAGE
+ * in your config.
+ */
+
+#ifndef ADC_REFERENCE_VOLTAGE
+  #warning "If you experience odd temperature readings make sure to measure the analog reference voltage. See pins_MKS_TINYBEE.h for details"
```
Comment (thisiskeithb) [inline Marlin/src/pins/esp32/pins_MKS_TINYBEE.h]: I think this is a good idea, but you get a wall of warnings due to the many (re)includes of board pin files: https://github.com/MarlinFirmware/Marlin/actions/runs/14003259323/job/39213443240?pr=27755#step:8:49

There are a couple options:
- Add this warning via `warnings.cpp` if this motherobard is enabled
- Implement something like what was done for the `CONTROLLER_WARNING` macro if you want to halt compilation and force the user to measure their board / set the voltage / disable the warning: https://github.com/MarlinFirmware/Marlin/blob/14fa7057718acbed8d0e4238f2eba9b9f645db64/Marlin/src/pins/pins.h#L126-L130

It kind of depends on just how dodgy that part is.

Comment (fermino) [reply Marlin/src/pins/esp32/pins_MKS_TINYBEE.h]: Thanks for the feedback!

I don't have any other sample besides my own experience and the linked issues, so maybe it's not that common? I don't really know... Could it pose a security hazard? If no temperature safeguards are enabled it could be...? I might be splitting hairs here... 

I think having one warning would be enough to make users aware of the problem. In the end, having a 30C difference is quite noticeable :laughing:

Comment (fermino) [reply Marlin/src/pins/esp32/pins_MKS_TINYBEE.h]: I just move the warning, but I don't know what the proper/expected way to do it in this codebase because something that defines `ADC_REFERENCE_VOLTAGE` that is being included in Warnings.cpp so the warning is not triggered properly.

Comment (thisiskeithb) [reply Marlin/src/pins/esp32/pins_MKS_TINYBEE.h]: `ADC_REFERENCE_VOLTAGE` is defined in the pins file / via an #ifndef, so you can simplify the `#if` check in the warning:`#if MB(MKS_TINYBEE)`

I'd change the warning too.

Combined changes look something like:
```c
/**
 * MKS_TINYBEE Analog Reference
 */
#if MB(MKS_TINYBEE)
  #warning "If you experience odd temperature readings make sure to measure the analog reference voltage and add '#define ADC_REFERENCE_VOLTAGE <value>' to your config. See pins_MKS_TINYBEE.h for details."
#endif
```
