### PR TITLE
Fix AutoReporter not building and not working

### LINKED ISSUE #20921: [BUG] Temperature no longer reported to OctoPrint
### Bug Description

Somewhere between yesterday morning and the most recent merges within 24 hours, OctoPrint can no longer read temperatures from my SKR Pro 1.0. It worked when I used Bugfix 2.0 from yesterday morning sometime (-8 PST) but when I used the latest bugfix this morning the issue cropped up. It causes OctoPrint to disconnect due to multiple timeouts.

### Configuration Files
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5895797/Configs.zip)

### Steps to Reproduce

Use the current bugfix 2.0 and connect to SKR 1.0 with Octoprint. It appears to connect OK but no temperature data is reported. This causes OctoPrint to throw an error about multiple timeout retires exceeded.

**Expected behavior:**

Temperatures would display

**Actual behavior:**

No temperature is displayed and the host disconnects.

#### Additional Information

I will do my best to provide any additional details as needed. I am not a developer so please be gentle. Thanks for your wonderful work and contributions to 3D printing and Open Source!

### LINKED ISSUE #20946: [BUG] ADVANCED_OK returns additional info
Board is a SKR Mini E3 v2.0

Configs:
https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20Pro/BigTreeTech%20SKR%20Mini%20E3%202.0

Enable ADVANCED_OK and compile.

Build is from bugfix-2.0.x on Jan 28 2021.

Output from USB Serial:
```
Send: N609 G1 X81.579 Y150.534 E0.02365*91
Recv: ok WN\x856m0g9p P0 B1
Send: N610 G1 X81.579 Y153.156 E0.08224*94
Recv: ok WN\x856m1h0g P0 B3
Send: N611 G1 X82.334 Y153.156 E0.02365*93
Recv: ok WN\x856m1h1h P0 B3
Send: N612 G1 X82.334 Y147.117 E0.18936*89
Recv: ok WN\x856m1h2i P0 B3
Send: N613 G1 X83.088 Y146.469 E0.03118*94
Recv: ok WN\x856m1h3j P0 B3
Send: N614 G1 X83.088 Y153.156 E0.20968*90
Recv: ok WN\x856m1h4k P0 B3
```

I'm not sure what the `WN\x856m1h3j` etc parts are.... Probably a bug...

### LINKED ISSUE #20960: error: the value of 'CardReader::auto_report_port' is not usable in a constant expression
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5901122/Configuration.zip)

### Bug Description

Latest version of bugfix-2.0.x branch fails to build if AUTO_REPORT_SD_STATUS and more than one serial port is defined (HAS_MULTI_SERIAL is true).

### Steps to Reproduce

1. Drop config files into place.
2. Build with platformio & Auto Build Marlin

**Expected behavior:**

Successful compile

**Actual behavior:**

d:\src\marlin\marlin\src\sd\cardreader.h:187:62: error: the value of 'CardReader::auto_report_port' is not usable in a constant expression

### PR DESCRIPTION
**Pull request by X-Ryl669**
### Description

Newly added AutoReporter class does not build correctly when MULTI_SERIAL is enabled. 
Also, it does not work since it the base class is not using a virtual auto_report method.
This PR fix both issue (I hope, I don't have any printer with those)
I'm not using a virtual table for the cost it has, but CRTP again, so it should be optimal.

Fix #20921 and #20913.

### Requirements

Board from #20921

### Configurations

Don't have

### Related Issues

#20921

### CODE REVIEW

File: Marlin/src/libs/autoreport.h [hunk 1]
```diff
@@ -23,14 +23,17 @@
...
   millis_t next_report_ms;
   uint8_t report_interval;
+  #if HAS_MULTI_SERIAL
+    serial_index_t report_port_mask;
+    AutoReporter() : report_port_mask(SERIAL_ALL) {}
+  #endif
 
   // Override this method
-  inline void auto_report() { }
+  inline void auto_report() { static_cast<Child*>(this)->report(); }
```
Comment (thinkyhead) [inline Marlin/src/libs/autoreport.h]: Thanks! I had meant to apply the "Curiously Recursive Template Pattern" but totally forgot this aspect. https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern

File: Marlin/src/module/temperature.h [hunk 2]
```diff
@@ -798,7 +798,7 @@ class Temperature {
         #endif
       );
       #if ENABLED(AUTO_REPORT_TEMPERATURES)
-        class AutoReportTemp : public AutoReporter<SERIAL_ALL> { void auto_report(); };
+        struct AutoReportTemp : public AutoReporter<AutoReportTemp> { void report(); };
```
Comment (rhapsodyv) [inline Marlin/src/module/temperature.h]: why inherit if you are using `child->report()`?

File: Marlin/src/libs/autoreport.h (hunk 1 above)
Comment (X-Ryl669) [reply Marlin/src/libs/autoreport.h]: I knew it! Now it's done ;-)

File: Marlin/src/module/temperature.h (hunk 2 above)
Comment (thinkyhead) [reply Marlin/src/module/temperature.h]: Indeed. I think I can refactor this to just use a helper function / struct / class / lambda for the report function, no need for inclusion in the child class.

Comment (X-Ryl669) [reply Marlin/src/module/temperature.h]: Good question. It could be done with a static function too if you only needed one, but the code need 2 different methods (temperature report and SDcard report are different).

The CRTP works this way: 
1. base class calls something it does not know until the template is specialized.
2. The child class specialize the template, so the base class is `base<child>`, now the base class can static_cast to Child safely, it's known so `static_cast<Child*>(this)->` will call the child class's method
3. There is no need the child method is called the same as the base class, it's not a virtual table. If it's called the same, it'll work as well (since you explicitly call the child's method) but it's confusing to the reader that'll think it's a virtual table (IMHO). So unless it's absolutely required, I'm not naming the child method the same.

From the compiler point of view, auto_report from base is just a method that's calling another method of itself. There is no runtime dispatch, it's a compile-time dispatch. The main advantage is that you've a single interface in the base and the "child" is only implementing the feature you need (just like a pure virtual method without the cost).

Comment (rhapsodyv) [reply Marlin/src/module/temperature.h]: Yes, we can have 
```
struct AutoReportTemp { void report(); };
AutoReporter<AutoReportTemp> auto_reporter;


void Temperature::AutoReportTemp::report() {
       print_heater_states(active_extruder);
       SERIAL_EOL();
     }
```

And don't use inheritance at all... but I thought you wanted to keep the pattern, so I "got it"....

Comment (rhapsodyv) [reply Marlin/src/module/temperature.h]: CRTP is only need when we have a base and derived depending on each other interface. But in the current code, only Base need to call one method from child... So the child don't need share any special interface with parent, at all... I wonder... Just thinking loud...

Comment (X-Ryl669) [reply Marlin/src/module/temperature.h]: Yep that would work if the report method was static and/or does not need anything from AutoReporter (like in both usage here, you're 100% right).

Comment (X-Ryl669) [reply Marlin/src/module/temperature.h]: I've not checked what's in actual report method, sorry.

Comment (X-Ryl669) [reply Marlin/src/module/temperature.h]: Indeed, the child class does not need anything from the base class, I'll remove the inheritance.

Comment (rhapsodyv) [reply Marlin/src/module/temperature.h]: CRTP is cute. We can leave it. Now @thinkyhead should decide what he like most: a cute CRTP or avoid inheritance when not needed... 🤓

Comment (rhapsodyv) [reply Marlin/src/module/temperature.h]: the report method can be static too.

**Comment by X-Ryl669** [comment]
Here it is, no inheritance, plain old static method calling.

**Comment by thinkyhead** [comment]
Thanks! Looks like we arrived at about the exact same code.
