### PR TITLE
Probe behaviour correction

### LINKED ISSUE #25515: [BUG] G29 P1 Retracts Probe at Point 38
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After issuing a G29 P1, it will probe normally (CRTouch) all the way to point 37. At point 38 it retracts the probe and attempts to probe. At best, it causes a failed probe point, at worst it causes a bed crash.

Terminal Output:
`[...]
Recv: //action:notification Probing Failed
Recv: Error:Probing Failed
Recv: Probing mesh point 38/100.
Recv: //action:notification Probing Point 38/100
[...]`

At point 39, it extends the probe and continues to point. From then it continues normally to 58/100 and stops.

Any assistance is appreciated.

Thanks!

### Bug Timeline

New printer/first time flash

### Expected behavior

It should not retract the probe during probing.

### Actual behavior

It retracts the probe, leading to a bed crash.

### Steps to Reproduce

Issue G29 P1 from terminal.
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/10962728/configs.zip)

### Version of Marlin Firmware

Marlin bugfix-2.1.x

### Printer model

Ender 3 Neo

### Electronics

Stock 4.2.7 board

### Add-ons

Stock

### Bed Leveling

No Bed Leveling

### Your Slicer

None

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

_No response_

### LINKED ISSUE #25560: [BUG] G34 not working properly
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When running G34 on any bugfix branch after the 14th when the bed levels itself it then does not move down again to deploy the probe properly. 

The leveling works as expected, bed moves out of the way, probe deploys, it probes properly, does all three points, and on the third point it adjusts but immediately probes again without moving down enough causing errors. I forced it to clear and each time after they adjust it does the same thing and does not move to deploy the probe fully.

The 13th of this month works, 18th and 23rd do not.

### Bug Timeline

between 3/14 and 3/18

### Expected behavior

It should move to deploy the probe after adjusting the leveling.

### Actual behavior

It adjusts the tram, then does not move to deploy the probe and tries to take the next reading.

### Steps to Reproduce

G28
G34

### Version of Marlin Firmware

bugfix 2.1.x

### Printer model

MP3DP

### Electronics

SKR Pro

### Add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

_No response_

### LINKED ISSUE #25565: [BUG] Additional bed move while G29 probing
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I run the latest version of trhe bugfix-2.1.x branch and recently the printer started to additionally lower the bed when running a G29. Is that a new configuration option or abug? 

I configured `MULTIPLE_PROBING 2` and `BLTOUCH_HS_MODE true`

A video showing the problem: https://youtu.be/SN9cbFaW7ks

### Bug Timeline

new

### Expected behavior

In previous versions it did the two probes and then lowered to `Z_CLEARANCE_BETWEEN_PROBES` (I think) and then moved to the next point.

### Actual behavior

After the two probes it lowers the bed to `Z_CLEARANCE_BETWEEN_PROBES` and an additional ammount which I cannot tell where it comes from.

### Steps to Reproduce

Simply run a G29

### Version of Marlin Firmware

Bugfix-2.1.x 2023-03-24

### Printer model

Ender 5 plus

### Electronics

Bigtreetech SKR MINI E3 V3.0

### Add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/11069036/Configurations.zip)

### LINKED ISSUE #25658: tool head crashes into the bed trying to deploy mag mounted Z probe
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

tool head crashes into the bed trying to deploy/stow mag mounted Z probe during G34 and bed leveling. deploying and sowing the probe works fine from the LCD and During Z Calibration via Z Probe offset wizard, but once I try to Z auto align or bed level, the tool head to the X & Y Coordinates  correctly but in z it Goes further down and crashes into the bed and the probe holder while showing z=1 at the LCD, for more info I have a separate z end stop at max. the machine is an IDEX with dual Y and Z, running on a BBT octopus v1.1 f407 chip board.

### Bug Timeline

since I installed the 2.1.2 firmware it is a new custom build machine

### Expected behavior

deploying and stowing the probe normally during G34 Z AUTO ALIGNING AND BED LEVELING  

### Actual behavior

It crashes into the bed

### Steps to Reproduce

Call G34

### Version of Marlin Firmware

2.1.x bugfix

### Printer model

I3 style Idex

### Electronics

BBT Octopus v1.1 F407 Chip

### Add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11185291/Configuration.zip)

### LINKED ISSUE #25737: [BUG] G29 command fails to make probe reach the bed
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Trying to generate a mesh with G29 fails when trying to probe the first point. It seems like the probe is unable to reach the bed, and this causes an emergency shutdown.

Any other usage of the probe (G28, G34...) doesn't seem to be affected by this issue. It only happens during G29 probing specifically.

### Bug Timeline

Started when I updated to `2.1.X` version. 

### Expected behavior

I expect the probe to be able to reach the bed without issuing an emergency shutdown

### Actual behavior

The probe fails to reach the bed, and issues an M114 command. See below for further logs.

### Steps to Reproduce

1. Issue a `G28` command to home the axis
2. Issue a `G29 P1` command to start probing the bed
3. Watch how it fails to do so at the first point 

### Version of Marlin Firmware

Marlin bugfix-2.1.x (Apr 23 2023 18:51:04)

### Printer model

Custom Prusa i3

### Electronics

BTT SKR 2.0 Rev B

### Add-ons

BLTouch 3.1

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

Output of the "Steps to reproduce" section with `M111 S247`: https://pastebin.com/tRZNjZWW

[Configuration files (bugfix-2.1.x)](https://github.com/MarlinFirmware/Marlin/files/11304342/Marlin.zip)
[Configuration files (2.1.x)](https://github.com/MarlinFirmware/Marlin/files/11304344/Marlin.zip)

Video showcasing the issue following the "Steps to reproduce" section:
https://user-images.githubusercontent.com/13695988/233854869-f124306d-b42d-4619-99f9-8360c51957d8.mp4

### LINKED ISSUE #25751: [BUG] Delta calibration not possible
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I use a removable probe under the nozzle and when starting delta calibration, the head takes a 1st measurement but does not come up and moves to take the 2nd measurement, then the 3rd measurement and the head lifts diagonally to reach the 4th point. The head lowers to take the measurement but does not reach the bed. It ends up at an undefined height with a "probing failed" message.

### Bug Timeline

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

bugfix 2.1.3 bump 20230427

### Printer model

Delta

### Electronics

Nanov3.1

### Add-ons

removable probe

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

`Send: G33 V3
Recv: G33 Auto Calibrate
Recv: Checking... AC at radius:117.0000
Recv: .Height:330.0000  Ex:0.0000  Ey:0.0000  Ez:0.0000  Radius:151.6700
Recv: .               Tx:0.0000  Ty:0.0000  Tz:0.0000
[...]
Printer seems to support the busy protocol, will adjust timeouts and set busy interval accordingly
[...]
Recv: Deploy Z-Probe
Recv: //action:prompt_end
Recv: //action:prompt_begin Deploy Z-Probe
Recv: //action:prompt_button Continue
Recv: //action:prompt_show
[...]
Send: M876 S0
Recv: Wait for bed heating...
[...]
Recv:  T:-1.00 /0.00 (4089.1875) B:59.63 /60.00 (3431.5000) M:26.23 (3894.1875) @:0 B@:91
Recv:  T:-1.00 /0.00 (4088.0625) B:59.84 /60.00 (3427.1875) M:26.41 (3892.7500) @:0 B@:76
[...]
Recv: Stow Z-Probe
Recv: //action:prompt_end
Recv: //action:prompt_begin Stow Z-Probe
Recv: //action:prompt_button Continue
Recv: //action:prompt_show
[...]
Send: M876 S0
Recv: Error:Probing Failed
Recv: Correct delta settings with M665 and M666`

### PR DESCRIPTION
**Pull request by jamespearson04**
### Description
Fix for #25560. In `G34` with `Z_STEPPER_AUTO_ALIGN`, the current z height is altered as part of the leveling process. This results in the printer thinking it has more clearance available than it actually does, so after probing it does not lift sufficiently.

This adds a blocking move to a safe height above probe trigger height, if the printer doesn't end up there after performing a probe. This commit should probably be left in even if the probing changes that illuminated this issue are altered, as a safeguard due to the "dirty trick" included in G34_M422.cpp.

### Update
Also includes corrections to after probe lift behaviour - the addition of the triggered height had been removed, so clearances such as `Z_CLEARANCE_BETWEEN_PROBES` were not being fully applied. (The clearance should apply to the probe, so the move should be relative to the triggered height)

`bltouch.z_extra_clearance()` has been changed to ~~return the Z nozzle to probe offset, instead of a fixed value of 7, as the probe will only extend below the nozzle by the offset amount - certainly never a full 7mm.~~ a define in config.h.

This solves #25565, as moves now align as they should in procedures that require multiple probes at different points.

### Requirements
Testing requires independent dual (or more) Z axes and bed probe for G34 related testing, or just some kind of bed probe for G29 testing.

### Benefits
Fixes broken G34 and extra lifts on G29

### Configurations
None - unable to test as I don't have dual Z. Testing in #25560 has demonstrated this to be the source of the issue however.
Tested G29 with UBL, and it works as it should.

### Related Issues
#25560 #25565

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I haven't tested a BLTouch-based config yet, but this PR solves the issue with the nozzle dragging across the bed after the final iteration of `G34`/`Z_STEPPER_AUTO_ALIGN` on a Biqu B1 SE Plus with dual+independent Z drivers & motors (stock only has a single Z motor/leadscrew) that has a strain gauge hotend (`NOZZLE_AS_PROBE`).

For reference, I'm using the following `Z_CLEARANCE_*` settings:

```cpp
#define Z_CLEARANCE_DEPLOY_PROBE    2 // Z Clearance for Deploy/Stow
#define Z_CLEARANCE_BETWEEN_PROBES  2 // Z Clearance between probe points
#define Z_CLEARANCE_MULTI_PROBE     2 // Z Clearance between multiple probes
//#define Z_AFTER_PROBING           5 // Z position after probing is done
```
Full config: [Biqu_B1_SE_Plus_Dual_Independent_Z.zip](https://github.com/MarlinFirmware/Marlin/files/11152323/Biqu_B1_SE_Plus_Dual_Independent_Z.zip)

**Comment by jamespearson04** [comment]
@thisiskeithb Good, though the latest changes should make the previous solution redundant. I suggest it be left in anyway as a safeguard because of the way G34 works (re: changing the z height mid operation), in case of any future changes to probing behaviour.

With reference to the other probing behaviour issues, I'm not sure if @thinkyhead was planning on moving the `current_position.z + ` inside the `do_z_clearance()` function, or if it was to make the addition obsolete by using `Z_SAFE_PROBE_CLEARANCE`.

If it was the former, lots of uses of `do_z_clearance()` elsewhere need to be swapped to `blocking_move_to_z()` with an if greater than current height check. If the latter, there also need to be equivalent variants for `Z_CLEARANCE_MULTI_PROBE` and `Z_CLEARANCE_DEPLOY_PROBE`.

It may be fine as is with the `current_position.z  + `, but thinkyhead removed them a few days ago so I'd like his input regarding putting them back.

ETA: The probe type shouldn't matter for the G34 fix, so I'd consider that validated

**Comment by V1EngineeringInc** [comment]
This fixes my issues with G34.

**Review by SRCGremlin — APPROVED** [review]
Confirm, this fixes issue #25515, all 2.1.2 probing issues corrected. Ender 5 Plus SKR 1.4 Turbo Hemera build

**Comment by SRCGremlin** [comment]
One more comment, I've been printing all day so far with this fix. 

There does seem to be some outstanding issue with a missing Z raise move on G28. Maybe related to Z_SAFE_HOMING (but could be a separate operation that is missing the move) that might need some more testing/ looking into. 

On my Ender 5 Plus I found that the bed would not raise on a G28 in some situations. If I pinpoint it exactly I'll let you know.

**Comment by jamespearson04** [comment]
Is it not raising in a problematic manner? Because if your printer has homed already, and the bed is far enough away, no lifts should be performed as they shouldn't be necessary.

For example, if you send `G28`, allow it to home all axes, and then send `G28 Z`, it will just deploy and probe, as it will already be at a safe height.

This does highlight a different minor issue, if the nozzle is lower than both the clearance height, and the clearance height - probe offset, two z lifts will be performed to reach a safe clearance.

**Comment by jamespearson04** [comment]
The aforementioned double lift has been fixed with the above commit. Also behaviour of `G28 Rx` has been fixed. It was moving to height xmm, as opposed to lifting a distance of xmm, as documentation describes.

**Comment by Farva42** [comment]
> One more comment, I've been printing all day so far with this fix.
> 
> There does seem to be some outstanding issue with a missing Z raise move on G28. Maybe related to Z_SAFE_HOMING (but could be a separate operation that is missing the move) that might need some more testing/ looking into.
> 
> On my Ender 5 Plus I found that the bed would not raise on a G28 in some situations. If I pinpoint it exactly I'll let you know.

I've been trying to figure out what's causing the missing z clearance moves and it looks like it's an issue somewhere in the stepper disable process. 

If you can try something for me. 
Turn your printer off and on. 
Home all axis. You should see it do a Z clearance move
Send an M84 command or if you don't have a host connected disable steppers. 
Home all axis again and I'm expecting that you won't see a Z clearance move.

**Comment by SRCGremlin** [comment]
> > One more comment, I've been printing all day so far with this fix.
> > There does seem to be some outstanding issue with a missing Z raise move on G28. Maybe related to Z_SAFE_HOMING (but could be a separate operation that is missing the move) that might need some more testing/ looking into.
> > On my Ender 5 Plus I found that the bed would not raise on a G28 in some situations. If I pinpoint it exactly I'll let you know.
> 
> I've been trying to figure out what's causing the missing z clearance moves and it looks like it's an issue somewhere in the stepper disable process.
> 
> If you can try something for me. Turn your printer off and on. Home all axis. You should see it do a Z clearance move Send an M84 command or if you don't have a host connected disable steppers. Home all axis again and I'm expecting that you won't see a Z clearance move.

@Farva42 I can confirm that I am seeing exactly what you are describing. The issue doesn't present itself as a problem unless the nozzle has moved into a position where the probe cannot trigger EG. cancel a print without a follow up move or something along those lines. Still haven't tested the latest commit with the G28 change in this PR though.

**Comment by jamespearson04** [comment]
@Farva42, the stepper disable process doesn't really come into things, unless you're suggesting the `current_position` should be invalidated on M84, but that's not really a matter for this PR. Whether or not it does a lift will depend on the position of the nozzle/bed: if it's below the clearance height, it lifts to the clearance height, if it already exceeds the clearance height then it performs no lift.

Just tested with M84, and it behaves as expected, only lifting if there's not enough clearance. (Below the clearance height `Z_HOMING_HEIGHT - probe.offset.z`, where probe offset is negative, so a typical value is around 7mm.)

For clarity - it does no lifting move, because no lifting move is required. 

You can see this by performing commands: `G28; G0 Z1; M84; G28` - it lifts when it needs to.

**Comment by Farva42** [comment]
> @Farva42, the stepper disable process doesn't really come into things, unless you're suggesting the `current_position` should be invalidated on M84, but that's not really a matter for this PR. Whether or not it does a lift will depend on the position of the nozzle/bed: if it's below the clearance height, it lifts to the clearance height, if it already exceeds the clearance height then it performs no lift.
> 
> Just tested with M84, and it behaves as expected, only lifting if there's not enough clearance. (Below the clearance height `Z_HOMING_HEIGHT - probe.offset.z`, where probe offset is negative, so a typical value is around 7mm.)
> 
> For clarity - it does no lifting move, because no lifting move is required.
> 
> You can see this by performing commands: `G28; G0 Z1; M84; G28` - it lifts when it needs to.

M84 should invalidate current position as when you disable steppers you can manually move the Z axis down. 

If you say home the printer. Command the printer to move to Z100 then M84 to disable steppers and move the Z axis to touch the print bed current position cannot be used as you are no where near it. With a BL touch probe or inductive this is not an issue but with a probe like a mag mounted where you need clearance to safely attach the probe it can cause it to crash. 

I think you are correct that it needs to be dealt with as a seperate issue. As there is more going on with m84 beyond just the lack of clearance raise. 

This issue goes into it a little more. https://github.com/MarlinFirmware/Marlin/issues/23095

**Comment by jamespearson04** [comment]
It seems that his fix for that was selectively implemented:
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/module/stepper.cpp#L524

I'll do some testing with it enabled, I may include the changes here if they're small.

**Comment by Farva42** [comment]
> It seems that his fix for that was selectively implemented: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/module/stepper.cpp#L524
> 
> I'll do some testing with it enabled, I may include the changes here if they're small.

I've tested that without the condition of using ProUI and it does not correct the trusted flags. I did find however that if you call m84 twice in a row the second time it will correctly set all axis as untrusted.

**Comment by jamespearson04** [comment]
@Farva42 do you have `#define HOME_AFTER_DEACTIVATE` uncommented in configuration.h? That solves half the problem, I'm looking to resolve the missing lift now.

**Comment by Farva42** [comment]
> @Farva42 do you have `#define HOME_AFTER_DEACTIVATE` uncommented in configuration.h? That solves half the problem, I'm looking to resolve the missing lift now.

No I do not have it uncommented. Regardless it should still be doing the clearance as the z axis should be untrusted after disabling the steppers.

**Comment by jamespearson04** [comment]
That's what that define is for - not every firmware build has to worry about the axes moving unexpectedly.
Without that define, `set_axis_untrusted()` essentially has no effect, so it'll need to be uncommented to behave as you want.

Working on sorting out the two versions of the clearance lift now.

**Comment by jamespearson04** [comment]
The latest commit corrects `M84;G28` behaviour to lift relative to the current height depending on whether `HOME_AFTER_DEACTIVATE` is defined. @Farva42 This should work as you expect if you have that define uncommented.

File: Marlin/src/feature/bltouch.h [hunk 1]
```diff
@@ -76,7 +77,7 @@ class BLTouch {
     static constexpr bool high_speed_mode = false;
   #endif
 
-  static float z_extra_clearance() { return high_speed_mode ? 7 : 0; }
+  static float z_extra_clearance() { return high_speed_mode ? -probe.offset.z : 0; }
```
Comment (thinkyhead) [inline Marlin/src/feature/bltouch.h]: The extra 7mm is to account for the length of the BLTouch pin (extending below the point where it triggers). The point where the probe triggers is at the exact height defined by `probe.offset.z`.

In "high speed mode" the pin is expected to automatically re-extend as soon as the probe is triggered, and so extra clearance is needed compared to the case where the probe pin remains in the unextended position.

So this change is inappropriate. The value of `probe.offset.z` may be extremely small, as little as 1-2mm, and does not account for the extra length of the extended probe pin.

File: Marlin/src/gcode/calibrate/G28.cpp [hunk 2]
```diff
@@ -411,11 +411,18 @@ void GcodeSuite::G28() {
...
     const bool seenR = parser.seenval('R');
-    const float z_homing_height = seenR ? parser.value_linear_units() : Z_HOMING_HEIGHT;
+    float z_homing_height;
+    if (seenR)
+      z_homing_height = current_position.z + parser.value_linear_units();
+    else {
+      z_homing_height = (Z_HOMING_HEIGHT) - _MIN(probe.offset.z, 0);
+      if (!TERN(HOME_AFTER_DEACTIVATE, axis_is_trusted, axis_was_homed)(Z_AXIS))
+        z_homing_height += current_position.z;
+    }
```
Comment (thinkyhead) [inline Marlin/src/gcode/calibrate/G28.cpp]: Note that `Z_HOMING_HEIGHT` used to be called `MIN_Z_HEIGHT_FOR_HOMING` and does not just apply to "Z homing," in case that is a point of any confusion. It actually applies to the minimum height that is safe for any XY movement during homing.

The `HOME_Z_FIRST` case above would typically be used when Z is homing to the top (or the bed moves down). In such a case, XY could then home right away, so on such a setup, `Z_HOMING_HEIGHT` might even be set to `Z_HOME_POS`.

At this point we don't know the true Z height unless Z is "trusted" so we want to move to (at minimum) the `Z_HOMING_HEIGHT`. If there is a setup where the bed falls down, we can trust Z is higher than expected. If the case was a `DELTA` where the nozzle could fall down, then we would want to always raise Z over the current position.

In practice, however, `DELTA` and other machines that have a Z carriage vulnerable to gravity are not allowed to sleep the steppers that keep Z in place.

File: Marlin/src/gcode/calibrate/G28.cpp [hunk 3]
```diff
@@ -411,11 +411,18 @@ void GcodeSuite::G28() {
     TERN_(HOME_Z_FIRST, if (doZ) homeaxis(Z_AXIS));
 
     const bool seenR = parser.seenval('R');
-    const float z_homing_height = seenR ? parser.value_linear_units() : Z_HOMING_HEIGHT;
+    float z_homing_height;
+    if (seenR)
```
Comment (thinkyhead) [inline Marlin/src/gcode/calibrate/G28.cpp]: Originally the `R` parameter was meant to simply be 0 for cases where a raise was not wanted, and was not really designed for the case used by some LCD implementations where it has been set to "5." The implementers of the code for those LCDs were not aware of this, and may have expected `R5` to raise 5mm above the current position after modifying Z (for something like a power-loss recovery). So we need to look at their custom handling, if they are not simply using the standard `recovery.resume` behavior.

In general, when first homing a machine after it has been booted, the initial raise always works because the current Z position is reset to `Z_IDLE_HEIGHT`, which is 0 for most machines, but may be a large value for machines whose beds are susceptible to gravity.

File: Marlin/src/module/stepper.cpp [hunk 4]
```diff
@@ -521,7 +521,7 @@ void Stepper::enable_axis(const AxisEnum axis) {
 bool Stepper::disable_axis(const AxisEnum axis) {
   mark_axis_disabled(axis);
 
-  TERN_(DWIN_LCD_PROUI, set_axis_untrusted(axis)); // MRISCOC workaround: https://github.com/MarlinFirmware/Marlin/issues/23095
+  TERN_(HOME_AFTER_DEACTIVATE, set_axis_untrusted(axis)); // MRISCOC workaround: https://github.com/MarlinFirmware/Marlin/issues/23095
```
Comment (thinkyhead) [inline Marlin/src/module/stepper.cpp]: Axes are always marked as "untrusted" when they are disabled (below) by `DISABLE_AXIS_##N()`. The workaround added here for the benefit or ProUI is unclear. The `can_axis_disable` used below is meant to check whether a stepper may be in use by more than one axis, as with the case of CoreXZ, for example. This workaround may be intended to force behavior that would not otherwise apply in a shared stepper situation. Maybe it can be removed.

File: Marlin/src/module/probe.cpp [hunk 5]
```diff
@@ -966,7 +959,7 @@ float Probe::probe_at_point(const_float_t rx, const_float_t ry, const ProbePtRai
     switch (raise_type) {
       default: break;
       case PROBE_PT_RAISE:
-        do_z_clearance(Z_CLEARANCE_BETWEEN_PROBES);
+        do_z_clearance_by(Z_CLEARANCE_BETWEEN_PROBES); // Always raise over the current Z position when the probe triggers
```
Comment (thinkyhead) [inline Marlin/src/module/probe.cpp]: Consider the case where the probe triggers at a lower point (for some reason). That will actually lead to less of a raise.

File: Marlin/src/module/stepper.cpp (hunk 4 above)
Comment (Farva42) [reply Marlin/src/module/stepper.cpp]: This looks like an attempt to ensure the axis get marked as untrusted as the disable function is not always correctly setting the untrusted flag.

**Comment by V1EngineeringInc** [comment]
I just ran the latest set of changes and G28, G34, and G29(bilinear) worked for me. I was using BlTouch HS mode and it all seemed great.

File: Marlin/src/module/probe.cpp (hunk 5 above)
Comment (jamespearson04) [reply Marlin/src/module/probe.cpp]: ~~What about where the probe triggers at a higher point? This change leads to no raise. And a bunch of additional raises during G29 variants.~~

~~so something like `_MAX(Z_CLEARANCE_BETWEEN_PROBES, Z_CLEARANCE_BETWEEN_PROBES + current_position.z)` then.~~

My bad, mornings, sorry. This should be `do_z_clearance_by(Z_PROBE_SAFE_CLEARANCE + _MIN(probe.offset.z, 0));`, to put us at Z_PROBE_SAFE_CLEARANCE after probing. ~~Same should maybe be done for G28.~~ G28 Should lift by `do_z_clearance_by(Z_CLEARANCE_BETWEEN_PROBES + _MIN(probe.offset.z, 0));`

File: Marlin/src/module/stepper.cpp (hunk 4 above)
Comment (jamespearson04) [reply Marlin/src/module/stepper.cpp]: Yeah, this should really be removed then.

File: Marlin/src/feature/bltouch.h (hunk 1 above)
Comment (jamespearson04) [reply Marlin/src/feature/bltouch.h]: So in reality it needs to be slightly larger than `-probe.offset.z`. 7mm is far too high, and kind of defeats the purpose of HS mode. Surely the extra distance required should actually come from `Z_CLEARANCE_AFTER_PROBING`/ `Z_CLEARANCE_MULTI_PROBE`.

Have you tested my version? works a treat

Comment (jamespearson04) [reply Marlin/src/feature/bltouch.h]: Perhaps a define for the `PROBE_TRIGGER_DISTANCE`?

It would be the distance between the probe touching the bed and the probe triggering, could be added to the -probe offset above.

File: Marlin/src/gcode/calibrate/G28.cpp (hunk 2 above)
Comment (jamespearson04) [reply Marlin/src/gcode/calibrate/G28.cpp]: Yes, that's fine, I see the two heights are typically defaulted together:
https://github.com/MarlinFirmware/Marlin/blob/7e700c13948506ab0fc57719c7c1bd35f0cb33c4/Marlin/src/inc/Conditionals_post.h#L3182-L3196

The intention is to standardise the lift distance after probing, so that when a chain of commands like `G28;G29` are sent, so long as they're defined to the same height, the printer doesn't have to perform any vertical moves to tranisition between each them. So this should actually be `+ bltouch.z_extra_clearance()`, not `- _MIN(probe.offset.z, 0)` now I think about it.

But I see what you mean, the `_MIN()` is necessary, ~~however I think this should actually be reworked to use `do_z_clearance_by()` instead now.~~

**Comment by jamespearson04** [comment]
There are some extra lifts with HS mode during G29 due to lifting by `Z_CLEARANCE_BETWEEN_PROBES` after probing, but lifting to `Z_PROBE_SAFE_CLEARANCE` before probing. This is because of the reverted change in `bltouch.z_extra_clearance()`. Before the change `Z_PROBE_SAFE_CLEARANCE == Z_CLEARANCE_BETWEEN_PROBES + probe.offset.z == Z_CLEARANCE_BETWEEN_PROBES + current_position.z` after probe trigger. 

If this relationship is broken (as it currently is), we get an extra lift. In order to fix this we should lift by `Z_PROBE_SAFE_CLEARANCE + _MIN(probe.offset.z, 0)` after probing, not by `Z_CLEARANCE_BETWEEN_PROBES`.

**Comment by jamespearson04** [comment]
~~Another thing to note is the probe deploying before lifting to a safe height in G29 P1.~~ Was above deploy probe clearance.

File: Marlin/src/module/stepper.cpp (hunk 4 above)
Comment (jamespearson04) [reply Marlin/src/module/stepper.cpp]: This has been set back as it was, as it's not related to this PR. (It already worked as expected as long as `HOME_AFTER_DEACTIVATE` was defined) - 14e463a

File: Marlin/src/module/probe.cpp (hunk 5 above)
Comment (jamespearson04) [reply Marlin/src/module/probe.cpp]: e19a6d4 implements the above mentioned change, which results in the elimination of extra lifts during G29 w/ HS mode as a result of 98ec0be. Future changes to `Z_PROBE_SAFE_CLEARANCE` shouldn't cause the extra lifts to reoccur now.
(extra lifts in this case meaning performing two z lifts instead of a single one to the same height)

File: Marlin/src/gcode/calibrate/G28.cpp (hunk 2 above)
Comment (jamespearson04) [reply Marlin/src/gcode/calibrate/G28.cpp]: Thinking about it further, it may make sense for it to be either `Z_CLEARANCE_BETWEEN_PROBES + _MIN(probe.offset.z, 0)` or `Z_PROBE_SAFE_CLEARANCE + _MIN(probe.offset.z, 0)`, as with `probe_at_point()`.

Comment (jamespearson04) [reply Marlin/src/gcode/calibrate/G28.cpp]: The former will result in a lift between G28 and G29 with HS mode enabled, but that seems correct.

Comment (jamespearson04) [reply Marlin/src/gcode/calibrate/G28.cpp]: Implemented in cdc9973

Comment (thinkyhead) [reply Marlin/src/gcode/calibrate/G28.cpp]: Using the `probe.offset.z` makes some sense, as a positive value would have the nozzle pressed against the bed when it triggers, so raising by that amount brings the nozzle to Z0, and raising more brings the nozzle the appropriate height above the bed.

Of course, if the user has their `probe.offset.z` correctly set, simply raising to the `Z…CLEARANCE` position already does the trick, but we have no guarantee of that. If the user has a messed up `probe.offset.z` all bets are off, but we should try to do the safe thing, so raising above the current position does always seem sensible. A weird `probe.offset.z` like +20 might cause an excessive raise, but at least it can't harm the bed.

We are so far only looking at the situation with the bed, of course, and not at situations where a probe might be used with a workpiece that is above 0. That kind of case will need more thought, as we have the choice to set Z to 0 in response to a probe, or just probe to get the height, so most of the time, again, it's preferable for the probe to raise above the current Z position.

File: Marlin/src/gcode/calibrate/G28.cpp [hunk 6]
```diff
@@ -411,11 +411,18 @@ void GcodeSuite::G28() {
...
+      z_homing_height = current_position.z + parser.value_linear_units();
+    else {
+      z_homing_height = (Z_CLEARANCE_BETWEEN_PROBES ) + _MIN(probe.offset.z, 0);
```
Comment (thinkyhead) [inline Marlin/src/gcode/calibrate/G28.cpp]: It's better to use `Z_HOMING_HEIGHT` here within `G28`. It will be automatically set to `Z_CLEARANCE_BETWEEN_PROBES` if it is not provided. Considering the case where the BLTouch in HS mode is deployed while an XY move is being done, there should only be extra clearance after the probe has been deployed, and it may not be needed for the initial move to home X and/or Y, unless there is some logic to deploy the Z probe at the very start of `G28` after the initial Z raise. AFAIK the BLTouch doesn't ever deploy until it actually reaches the safe homing position, regardless of its HS mode.

**Comment by thinkyhead** [comment]
> This is because of the reverted change in `bltouch.z_extra_clearance()`

…Or misuse of `bltouch.z_extra_clearance()` which is meant to provide an extra 7mm of clearance when we know the probe will be moving laterally while it is deployed. If there is an inappropriate extra or compounding raise in some situation, it may be due to relative raise `do_z_clearance_by` being applied more than once. This is the kind of thing we have tried to avoid by using `do_z_clearance` with a specific Z position provided by the user as "known to be safe."

The times when we don't know the true Z position are rare. When a machine starts up, we can be relatively certain that the nozzle is not below the bed. If a machine is set up in such a way that the nozzle can fall below the bed, then the user needs to account for that in their configuration by providing a larger Z height for probe deployment and lateral motion during the initial homing. Machines that home Z first (e.g., to max) or whose beds fall down can worry less about this.

File: Marlin/src/module/probe.cpp [hunk 7]
```diff
@@ -966,7 +959,7 @@ float Probe::probe_at_point(const_float_t rx, const_float_t ry, const ProbePtRai
     switch (raise_type) {
       default: break;
       case PROBE_PT_RAISE:
-        do_z_clearance(Z_CLEARANCE_BETWEEN_PROBES);
+        do_z_clearance_by((Z_PROBE_SAFE_CLEARANCE) + _MIN(probe.offset.z, 0));
```
Comment (thinkyhead) [inline Marlin/src/module/probe.cpp]: With a BLTouch probe, the `probe.offset.z` can be anything between - let's say -0.5mm and -5mm, since the deployed probe and the stowed probe can have that much difference. This is one of the advantages of BLTouch is that it has such a versatile working range, simplifying its mounting.

The `Z_PROBE_SAFE_CLEARANCE` is meant to give adequate clearance for lateral motion, and to be the least amount of clearance required for the current probe mode. BLTouch HS mode has the advantage that the probe re-deploys on its own before arriving at the next probe point. But since it requires more of a raise, it may actually lead to an increase in the overall probing time on machines with a slow Z axis.

The `raise_after` parameter tells `run_z_probe` what to do in preparation for the next probe, or if it is the last probe it tells `run_z_probe` to stow the probe. The change I made above to override `raise_after` and do a "hard stow" on the BLTouch when it's not in HS mode is meant to invoke the raise in `probe.stow`, which may be larger or smaller than `Z_CLEARANCE_BETWEEN_PROBES`. From a scan of the code it looks like BLTouch is happy to stow without any raise at all, so it may not raise at all outside of HS mode.

If this "trick" is problematic then we can get rid of the extra `raise_type` finagling above and just use `raise_after`.

In general, it might be cool to just make these methods receive exact Z values for their various raises and generalize probing, so a command like `G30` can be given overrides, and higher-level methods can pass in the user-configured values when doing pre-configured probing procedures. Something to contemplate for a future revision.

File: Marlin/src/module/probe.cpp [hunk 8]
```diff
@@ -823,7 +816,7 @@ float Probe::run_z_probe(const bool sanity_check/*=true*/) {
           #if EXTRA_PROBING > 0
             < TOTAL_PROBING - 1
           #endif
-        ) do_z_clearance(Z_CLEARANCE_MULTI_PROBE);
+        ) do_z_clearance(z + (Z_CLEARANCE_MULTI_PROBE));
```
Comment (thinkyhead) [inline Marlin/src/module/probe.cpp]: I brought `z` back here because it includes `largest_sensorless_adj` and that used to be a part of the raise here. If we want to use `do_z_clearance_by(Z_CLEARANCE_MULTI_PROBE)` as a relative raise, then we should also add `largest_sensorless_adj`, but `z` already includes that.

File: Marlin/src/gcode/calibrate/G28.cpp [hunk 9]
```diff
@@ -408,17 +408,37 @@ void GcodeSuite::G28() {
...
     const bool seenR = parser.seenval('R');
-    const float z_homing_height = seenR ? parser.value_linear_units() : Z_HOMING_HEIGHT;
 
-    if (z_homing_height && (seenR || NUM_AXIS_GANG(doX, || doY, || TERN0(Z_SAFE_HOMING, doZ), || doI, || doJ, || doK, || doU, || doV, || doW))) {
-      // Raise Z before homing any other axes and z is not already high enough (never lower z)
-      if (DEBUGGING(LEVELING)) DEBUG_ECHOLNPGM("Raise Z (before homing) by ", z_homing_height);
-      do_z_clearance(z_homing_height);
-      TERN_(BLTOUCH, bltouch.init());
+    // Use raise given by 'R' or Z_HOMING_HEIGHT (above the probe trigger point)
+    float z_homing_height = seenR ? parser.value_linear_units() : DIFF_TERN(HOMING_Z_WITH_PROBE, Z_HOMING_HEIGHT, _MIN(probe.offset.z, 0));
```
Comment (thinkyhead) [inline Marlin/src/gcode/calibrate/G28.cpp]: I changed this to `DIFF_TERN` rather than `SUM_TERN` because it makes more sense (to me) that we would do more of a raise in the case where `probe.offset.z` is farther from the bed. But again, the inclusion of `probe.offset.z` here is somewhat dubious, since the configured `Z_HOMING_HEIGHT` is already supposed to be accounting for that. That is, it should be defined by the user as larger than the largest `-probe.offset.z` they expect to have.

**Comment by thinkyhead** [comment]
One of the likely complicating factors for `G34` is that it wants to modify the `current_position.z` while operating. If that could be modified it might simplify the issue with using relative raise versus raising to certain (known) Z positions.

In general, we don't modify the current Z position until after probing (for homing) has been completed, and then it is generally only set to `Z_HOME_POS` (i.e., 0) minus the `probe.offset.z` at the moment when the probe triggers. It would be also be possible to set it after raising the probe. In that situation we would have to have done a relative raise, and then it must be known and within the control of `G28`.

When doing `G29` we presume that homing has already been done, and Z is known, and that is why we can be confident in doing our Z raises to specific Z positions rather than doing relative raises out of an overabundance of caution. Very tilted beds are of course possible, but we cannot go out of our way too much to accommodate messed up hardware. Users should take special care to get their machines as level as possible before invoking automatic calibration. `G34` is a special case, since it is meant to deal with an out-of-whack gantry, but there may be other ways to deal with that rather than imposing relative Z raises on the entire suite of probing procedures.

**Comment by jamespearson04** [comment]
> One of the likely complicating factors for `G34` is that it wants to modify the `current_position.z` while operating. If that could be modified it might simplify the issue with using relative raise versus raising to certain (known) Z positions.

Absolutely, though it should be made safe by the lift added in this PR. I figured that would be a suitable solution until someone with the equipment to test it could get to reworking it.


> When doing `G29` we presume that homing has already been done, and Z is known, and that is why we can be confident in doing our Z raises to specific Z positions rather than doing relative raises out of an overabundance of caution.

And that seems reasonable. The multiple lift issue introduced by swapping from relative to absolute lifts was due to the move to `safe_z` in `probe_at_point()` and the post probe lift lifting to different values; Post probe lift moving to `Z_PROBE_SAFE_CLEARANCE` should sort that.

**Comment by jamespearson04** [comment]
> …Or misuse of `bltouch.z_extra_clearance()` which is meant to provide an extra 7mm of clearance when we know the probe will be moving laterally while it is deployed.

If you need 7mm of extra clearance, your probe is catching on your prints whilst stowed. It shouldn't be a fixed value of 7mm, it should be the distance between the tip of the nozzle and the tip of the deployed probe. Adding a blanket 7mm defeats the purpose of HS mode, because the time it takes to lift an extra 7mm can be longer than it takes to deploy/stow the probe.

I can understand not wanting to use `probe.offset.z`, as the user could set this badly, but it's value should be approximately the same (+ the actuation distance of whatever probe is in use).

It should probably be a define, that way you can default it to 7mm unless the user specifies a height.

File: Marlin/src/gcode/calibrate/G28.cpp (hunk 9 above)
Comment (jamespearson04) [reply Marlin/src/gcode/calibrate/G28.cpp]: Yeah, swapping to absolute moves is fine, so `probe.offset.z` will be uneccesary in many places.

File: Marlin/src/module/probe.cpp (hunk 8 above)
Comment (jamespearson04) [reply Marlin/src/module/probe.cpp]: This makes `Z_CLEARANCE_MULTI_PROBE` a relative move, whilst others will be absolute. Worth bearing in mind, but I don't think it would be problematic at all. Perhaps renaming to `Z_LIFT_MULTI_PROBE` would be appropriate.

File: Marlin/src/module/probe.cpp (hunk 7 above)
Comment (jamespearson04) [reply Marlin/src/module/probe.cpp]: In the mentioned case, if stow provides no lift, the lift will come from `do_blocking_move_to()`, when `probe_at_point()` is next called. It works, but doesn't seem ideal.

That said, stow does do a raise, but only if the following statement is false: `#if EITHER(FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE) && DISABLED(PAUSE_BEFORE_DEPLOY_STOW)` (which is the case for BLTOUCH, so a lift is included)

https://github.com/MarlinFirmware/Marlin/blob/3cb855c7d21efbe85030add1234d8d3b1fb209a7/Marlin/src/module/probe.cpp#L508-L519

`zdest` should be reworked a little, as the switch to absolute height means the `- zoffs` should be unnecessary.

**Comment by dfries** [comment]
I've also "discovered" BLTouch high speed mode probing.
G29 5x5 with two touches at each point on Ender 6 times in MM:SS
2.0.9.3 took 3:19.75
bugfix-2.1.x took 4:34.13,
much optimization later and high speed mode I'm down to 1:07.00

I'll have to decide personally if I want some higher clearances to not destroy the probe if I forget to clear small parts (it happens).

> it should be the distance between the tip of the nozzle and the tip of the deployed probe.

I've concluded the probe offset is the base value and an additional marginal clearance is required on top of that.  The probe offset is the offset between the "trigger height" of BLTouch and the nozzle, not the BLTouch probe tip and the nozzle since it will extend a little more when hanging.  The difference for me (I tried to measure), is roughly 0.9 mm, meaning Z needs to increase by about 0.9mm beyond the probe offset before the probe tip is just barely touching the print bed.  If you only raise by the probe offset the tip will most definitely be dragging on the bed with an XY movement and have the opportunity to catch on anything.

The other reason to have some extra clearance in there is not everyone will have the correct probe offset initially.  It needs to account for some amount of having a bad value in there.

I've moved the logic to the source file in my branch and require the user to define Z_CLEARANCE_BLTOUCH_HS, which is how much extra clearance do you want beyond the probe offset.  If the probe offset is 0 or positive, they get 7mm.

Marlin/src/feature/bltouch.cpp
```cpp
#ifdef BLTOUCH_HS_MODE
float BLTouch::z_extra_clearance() {
  // In BLTOUCH HS mode, the probe travels in a deployed state, set the
  // clearance to raise Z to accommodate the deployed state.  Use probe
  // offset + margin or if not available, the length of the deployed pin
  // (BLTOUCH stroke < 7mm).
  if(high_speed_mode)
  {
    // Only use probe offset option if a margin value is available.  Otherwise
    // raising by the offset would give 0 clearance.
    #if defined(Z_CLEARANCE_BLTOUCH_HS) && Z_CLEARANCE_BLTOUCH_HS > 0
    // negative is expected and means probe is lower
    if(probe.offset.z < 0)
      return -probe.offset.z + Z_CLEARANCE_BLTOUCH_HS;
    #endif
    // offset not set or positive (invalid), use BLTOUCH stroke
    return 7;
  }
  return 0;
}
#endif
```

I see probe.cpp has removed using BLTouch::z_extra_clearance(), still I made the changes.  See pull request #25655 "BLTouch::z_extra_clearance() use probe offset instead of full travel"

I have a speed improvement to avoid back to back deploy() or stow() commands incurring a delay per command, now only the first delays. The change is is in pull request #25656, "BLTouch::command Avoid write for duplicate probe commands"

**Comment by roirh** [comment]
Hi,
I have a printer with strain gauge on the nozzle.
Recent changes to this repository broke the G34 command, as the Z_CLEARANCE_MULTI_PROBE wasn't applied correclty due to "dirty trick" mentioned.
I tested this PR and and it fixes my G34.
G28, G29 and G34 are working as intended.

This are my related settings on my machine:
#define Z_CLEARANCE_BETWEEN_PROBES  4 // Z Clearance between probe points
#define Z_CLEARANCE_MULTI_PROBE     2 // Z Clearance between multiple probes

**Comment by thinkyhead** [comment]
> It should probably be a define, that way you can default it to 7mm unless the user specifies a height.

It is defined by `NOZZLE_TO_PROBE_OFFSET` and it is not overridden in the configuration by enabling `BLTOUCH`. The user still has to explicitly define a default value for it. In situ it uses the last value retrieved from the EEPROM or subsequently set by the user. There is no way to guarantee its reliability. The solution proposed by @dfries is better, but is still not without its caveats. We should try some solutions and then try to intentionally thwart those solutions to see what kind of mayhem we can cause.

**Comment by thinkyhead** [comment]
Alrighty then… The configurations are clear that the probe clearance settings should be applied above the trigger point of the probe (`probe.offset.z`) so I've modified the raise function to use the probe Z offset and adjusted some code to compensate for this change. Please review.

**Comment by thisiskeithb** [comment]
### How I tested this
I created a [test branch](https://github.com/thisiskeithb/EnderAIO/tree/probe_testing) in my Ender-3 AIO fork & rebased it to current `bugfix-2.1.x` (182497f) and added a squashed version of this PR.

The test machine is an Ender-3 with an SKR 3, TMC2209s on X/Y/Z1/Z2/E0, BLTouch in HS mode, dual+independent Z drivers+motors.

### Collected logs for review

- [G28-G30.log.zip](https://github.com/MarlinFirmware/Marlin/files/11195065/G28-G30.log.zip)
- [G28-G29.log.zip](https://github.com/MarlinFirmware/Marlin/files/11195066/G28-G29.log.zip)
- [G34.log.zip](https://github.com/MarlinFirmware/Marlin/files/11195067/G34.log.zip)
- [G35.log.zip](https://github.com/MarlinFirmware/Marlin/files/11195131/G35.log.zip)

### Notes
Each of the referenced commands appear to work correctly again, even though there's still an extra Z height raise when `BLTOUCH_HS_MODE` = `true`.

Probing issues started ~a month ago, and going back to previous bugfix code within that timeframe has been problematic on this machine (and others with various probe options) for testing since it causes head crashes / nozzle dragging / probing to not work as expected (single probes despite having multi-probing enabled, or no probing would occur), but this PR is a vast improvement over the current bugfix since none of those issues exist with this PR.

File: Marlin/src/module/motion.cpp [hunk 10]
```diff
@@ -792,15 +792,18 @@ void do_blocking_move_to_x(const_float_t rx, const_feedRate_t fr_mm_s/*=0.0*/) {
...
     );
   }
-  void do_z_clearance(const_float_t zclear, const bool lower_allowed/*=false*/) {
-    if (DEBUGGING(LEVELING)) DEBUG_ECHOLNPGM("do_z_clearance(", zclear, ", ", lower_allowed, ")");
-    const float zdest = _MIN(zclear, Z_MAX_POS);
-    if (zdest == current_position.z || (!lower_allowed && zdest < current_position.z)) return;
+  void do_z_clearance(const_float_t zclear, const bool with_probe/*=true*/, const bool lower_allowed/*=false*/) {
+    UNUSED(with_probe);
+    float zdest = zclear;
+    TERN_(HAS_BED_PROBE, if (with_probe && probe.offset.z < 0) zdest -= probe.offset.z);
```
Comment (dfries) [inline Marlin/src/module/motion.cpp]: This is changing the offset from Probe::do_z_raise HOTEND offset to probe.offset, is that going to cause any issues?
```
const float zoffs = DIFF_TERN(HAS_HOTEND_OFFSET, offset.z, hotend_offset[active_extruder].z);
```
There's also a now unused `UNUSED(with_probe);` two lines up.

Comment (thinkyhead) [reply Marlin/src/module/motion.cpp]: - I removed the `do_z_raise` method and just inlined the code, and it no longer refers to `probe.offset.z` there since it calls `do_z_clearance`.
- If `HAS_BED_PROBE` is not set then `with_probe` is stripped out in the precompiler by `TERN_`. Hence `UNUSED` is added to suppress the "unused" warning.

Comment (thinkyhead) [reply Marlin/src/module/motion.cpp]: So far in my testing there's nothing weird happening in `G28` or `G29`, though it does raise a little more than I would prefer. I've not tested `G29` with UBL, only ABL, but its clearance moves are very similar. I've also not tested `G35` yet, but that is next!

Comment (dfries) [reply Marlin/src/module/motion.cpp]: > it does raise a little more than I would prefer.

Is that adding probe offset to clearance giving a higher Z?

Comment (thinkyhead) [reply Marlin/src/module/motion.cpp]: It is intended to consistently apply the behavior described in `Configuration.h`:
```cpp
/**
 * Z probes require clearance when deploying, stowing, and moving between
 * probe points to avoid hitting the bed and other hardware.
 * Servo-mounted probes require extra space for the arm to rotate.
 * Inductive probes need space to keep from triggering early.
 *
 * Use these settings to specify the distance (mm) to raise the probe (or
 * lower the bed). The values set here apply over and above any (negative)
 * probe Z Offset set with NOZZLE_TO_PROBE_OFFSET, M851, or the LCD.
 * Only integer values >= 1 are valid here.
 *
 * Example: `M851 Z-5` with a CLEARANCE of 4  =>  9mm from bed to nozzle.
 *     But: `M851 Z+1` with a CLEARANCE of 2  =>  2mm from bed to nozzle.
 */
```

Comment (thinkyhead) [reply Marlin/src/module/motion.cpp]: > Is that adding probe offset to clearance giving a higher Z?

Is that causing more of a raise than I would prefer? When the BLTouch probe is in HS mode it's not bad. And when it's not in HS mode, it's still not bad, since the probe will need to deploy fully at the next point. I was trying to get a tiny raise, just 1mm clearance for the tip of the deployed probe, but I (so far) didn't get it quite that low.

Comment (dfries) [reply Marlin/src/module/motion.cpp]: This is what I have in my Core-XY Configuration.h
Complete with negative numbers for Z_CLEARANCE_MULTI_PROBE + probe offset to be roughly 1mm.

```
#if ENABLED(BLTOUCH)
// once deployed the probe goes down by the probe offset.  Deploy only
// needs to be a little more.
#define Z_CLEARANCE_DEPLOY_PROBE    4 // Z Clearance for Deploy/Stow
// This is in case I failed to clear any really small prints.
#define Z_CLEARANCE_BETWEEN_PROBES  3 // Z Clearance between probe points
// The BLTouch probe seems to need to travel up about 0.9mm before the pin
// clears what it touched, using 1mm.  Take the probe offset into account as
// it gets added to this number.
// For Ender 6 probe offset is about -2.52
// 1 - 2.52 = -1.52
#define Z_CLEARANCE_MULTI_PROBE     -1.52 // Z Clearance between multiple probes
// extra Z Clearance for high speed mode, probe offset + this margin
#define Z_CLEARANCE_BLTOUCH_HS      2
#else
#define Z_CLEARANCE_DEPLOY_PROBE   10 // Z Clearance for Deploy/Stow
#define Z_CLEARANCE_BETWEEN_PROBES  5 // Z Clearance between probe points
#define Z_CLEARANCE_MULTI_PROBE     5 // Z Clearance between multiple probes
//#define Z_AFTER_PROBING           5 // Z position after probing is done
#define Z_CLEARANCE_BLTOUCH_HS      7 // default length of BLTOUCH stroke
#endif

```

Comment (thinkyhead) [reply Marlin/src/module/motion.cpp]: Everything seems to be working well with this PR plus the (modified) changes that remain in your extra-clearance PR, but I will give it another round of testing later today. If you have a chance to try that combination also I would value your feedback. Pass it on!

**Comment by thinkyhead** [comment]
> Each of the referenced commands appear to work correctly again, even though there's still an extra Z height raise when BLTOUCH_HS_MODE = true.

Try this PR in combination with #25655 using a smaller clearance. The recommended raise over the trigger-height is 3 and you can also reduce your other clearance settings, thanks to the BLTouch being so out of the way when stowed. I had to increase my probing margin a little (13) to avoid the binder clips on my test machine, but otherwise everything was going pretty smooth.

**Comment by izzymoren0** [comment]
@thinkyhead i dont know if this is exactly the issue i have with the current marlin build, as my bltouch hs mode is broken.

it was working very well in the past with HS mode and just a small amount of z clearance and a -0.8 z-offset with following parameters:
#define Z_CLEARANCE_DEPLOY_PROBE   2 // Z Clearance for Deploy/Stow
#define Z_CLEARANCE_BETWEEN_PROBES  2 // Z Clearance between probe points
#define Z_CLEARANCE_MULTI_PROBE     2 // Z Clearance between multiple probes
//#define Z_AFTER_PROBING           4 // Z position after probing is done

currently, i have the issue that probing is way slower because the bltouch seems to do a doubled clearance move between leveling points and in my display i can see, it shows Z9 for that. So it raises the Z-Axis way more then before.

after changing
#define Z_PROBE_SAFE_CLEARANCE SUM_TERN(BLTOUCH, Z_CLEARANCE_BETWEEN_PROBES, bltouch.z_extra_clearance())
to
#define Z_PROBE_SAFE_CLEARANCE SUM_TERN(BLTOUCH, Z_CLEARANCE_BETWEEN_PROBES, 0)

it seems to working again, but, i dont know if im supposed to do that :D

**Comment by thinkyhead** [comment]
> it seems to working again, but, i dont know if im supposed to do that :D

The new option `BLTOUCH_HS_EXTRA_CLEARANCE` is meant to be added before we should expect to get reasonable behavior for BLTouch HS mode. You might find that your basic `Z_CLEARANCE_BETWEEN_PROBES` is sufficient, but I would recommend tuning the probe clearances in concert with `BLTOUCH_HS_EXTRA_CLEARANCE` to get enough raise on the probe between points both in HS mode and in "slow" mode. I can bring the `BLTOUCH_HS_EXTRA_CLEARANCE` PR option over to this PR to help make that easier.

**Comment by jamespearson04** [comment]
> The solution proposed by @dfries is better, but is still not without its caveats. We should try some solutions and then try to intentionally thwart those solutions to see what kind of mayhem we can cause.

His solution was essentially what I meant, thanks to @dfries for sorting that out :) I'll test the latest changes tomorrow, but just from looking, all should be good. Many thanks to @thinkyhead

**Comment by roirh** [comment]
Lates changes to this PR broke the G34 command again (working 2 days ago). I had no time yet to test what change it was.

Now it wont rebounce by Z_CLEARANCE_MULTI_PROBE in the second probe.

My config:
#define NOZZLE_AS_PROBE
(...)
#define MULTIPLE_PROBING 2
(...)
#define Z_CLEARANCE_DEPLOY_PROBE    0 // Z Clearance for Deploy/Stow
#define Z_CLEARANCE_BETWEEN_PROBES  4 // Z Clearance between probe points
#define Z_CLEARANCE_MULTI_PROBE     2 // Z Clearance between multiple probes
//#define Z_AFTER_PROBING           5 // Z position after probing is done

G34 log after G28.
[g34 log.txt](https://github.com/MarlinFirmware/Marlin/files/11205221/g34.log.txt)

**Comment by thinkyhead** [comment]
> Now it wont rebounce by `Z_CLEARANCE_MULTI_PROBE` in the second probe

Maybe it has something to do with the way `G34` messes with the `current_position.z`. I haven't dived into `G34` yet in my testing, so I'm sure things will become clearer once I start my analysis.

**Comment by jamespearson04** [comment]
That's exactly it @thinkyhead. They're "above" `Z_CLEARANCE_MULTI_PROBE` when the probe triggers, so no clearance lift is done.
G34 is essentially incompatible with doing clearances to absolute heights, as opposed to adding to the current height.

**Comment by Farva42** [comment]
> > Now it wont rebounce by `Z_CLEARANCE_MULTI_PROBE` in the second probe
> 
> Maybe it has something to do with the way `G34` messes with the `current_position.z`. I haven't dived into `G34` yet in my testing, so I'm sure things will become clearer once I start my analysis.

With LCD bed tramming trying to modify 'current_position' to account for the probe offset was not working. I had to use a different variable instead of trying to modify 'current_position'. To allow it to account for the probe offset. I'm wondering if this might be the same issue.

**Comment by thinkyhead** [comment]
> incompatible with doing clearances to absolute heights 

Well these are _supposed_ to be equivalent…

The original proposal was also a move to an _absolute_ height:
```cpp
if (current_position.z < z_probed_height + (Z_PROBE_SAFE_CLEARANCE))
  do_blocking_move_to_z(z_probed_height + (Z_PROBE_SAFE_CLEARANCE));
```

The updated code also moves to an _absolute_ height, with `false` to indicate the probe offset should not be applied:
```cpp
do_z_clearance(z_probed_height + (Z_PROBE_SAFE_CLEARANCE), false);
```

Does the original `do_blocking_move_to_z` still work, while the updated `do_z_clearance` does not?

**Comment by jamespearson04** [comment]
The fix doesn't work with multiple probing, because it needs to lift inside the `probe.probe_at_point()` function to perform the second probe - it doesn't reach the "dirty fix" before the repeat probing. - it was an oversight on my part

**Comment by jamespearson04** [comment]
Altering `do_z_clearance()` to offset by the current position instead of the probe offset would fix the issue, and shouldn't have any other effects since the probe offset should be the same as the current position when the probe triggers.

**Comment by jamespearson04** [comment]
Those commits should fix G34 for multiple probing. The lift after probing has been changed back to `do_z_clearance_by()` instead of `do_z_clearance()`, this should work fine after the recent changes.

**Comment by thinkyhead** [comment]
I think the problem is with the conception of `G34` and not with our reform of `probe_at_point`. I really want these configuration settings to mean what they say they mean, and for these raises to go to the specific Z position which is set for them (over a negative trigger height). Imposing a relative raise over the happenstance height of the actual trigger makes the raises inconsistent and dependent on the bed topography. It would make more sense for `G34` to take the returned `measured_z` and use it to make whatever correction is needed, rather than modify `probe_at_point` and affect every other procedure that uses it.
```cpp
/**
 * Z probes require clearance when deploying, stowing, and moving between
 * probe points to avoid hitting the bed and other hardware.
 * Servo-mounted probes require extra space for the arm to rotate.
 * Inductive probes need space to keep from triggering early.
 *
 * Use these settings to specify the distance (mm) to raise the probe (or
 * lower the bed). The values set here apply over and above any (negative)
 * probe Z Offset set with NOZZLE_TO_PROBE_OFFSET, M851, or the LCD.
 * Only integer values >= 1 are valid here.
 *
 * Example: `M851 Z-5` with a CLEARANCE of 4  =>  9mm from bed to nozzle.
 *     But: `M851 Z+1` with a CLEARANCE of 2  =>  2mm from bed to nozzle.
 */
```

**Comment by jamespearson04** [comment]
I agree that G34 is problematic, but I think we actually do want the raise to depend on topography. If something triggers the probe higher than the bed, we should still lift to provide the defined clearance above whatever has triggered the probe. 

Otherwise, in the event of an obstacle greater in height than the defined clearance, the probe would remain on said obstacle, and would catch on it during moves to the next point.

**Comment by jamespearson04** [comment]
I'd argue that this way actually better matches the described behaviour. Edit: and they wouldn't be inconsistent, the distance between the probe and bed will actually be more consistent, as now we're moving relative to a bed that we know is there, not where we think the bed should be.

**Comment by V1EngineeringInc** [comment]
Isn't the idea behind G34 all the same as G29, with an added maximum tilt offset added to the deploy height?

**Comment by jamespearson04** [comment]
G34 actually shifts the whole coordinate system, so it thinks the bed is further away. This means if the probe is set to move to a fixed height after probing, it thinks that fixed height is below the bed, so if it weren't restricted from moving downwards after probing, it would try and crash into the bed

**Comment by thinkyhead** [comment]
I suspect that if we do an absolute raise, that simply means this…
```cpp
do_z_clearance(z_probed_height + (Z_PROBE_SAFE_CLEARANCE), false);
```
…probably just need to change to this…
```cpp
do_z_clearance(Z_PROBE_SAFE_CLEARANCE);
```
But, as I mentioned, I haven't yet started on actual testing of `G34` against the updated `probe_at_point`, so we'll see if my suspicion is correct very soon.

**Comment by jamespearson04** [comment]
Multiple probing is handled in `probe.probe_at_point()`, so it wouldn't lift between multiple probes without commit c944425 / 043212a.
With that commit, the "dirty fix" portion should be unneccessary. Edit: To clarify, this is in reference to G34

**Comment by thinkyhead** [comment]
> in the event of an obstacle greater in height than the defined clearance, the probe would remain on said obstacle

I understand that concern. In the event that the probe triggers more than ~2mm early there is now a failure condition. (See the added `error_tolerance` in `run_z_probe`.) Meanwhile, the probe will definitely lift by *some* amount on any probe downward, because it always starts above its trigger point. If it were able to clear the obstacle on the way over to probing it, then it should also clear that obstacle after probing it.

**Comment by thinkyhead** [comment]
> With that commit, the "dirty fix" portion should be unneccessary. … in reference to `G34`

We can discuss the potentials all day, but I need to get to actual testing and experimenting. I'm sure that will produce some answers and maybe more questions. Unfortunately, the only machine I have with independent Z motors is the AnyCubic Chiron, and I'll probably give myself a hernia carrying it over to the workbench!

**Comment by jamespearson04** [comment]
Yeah, I see what you mean, the only case it should be triggering high is under some kind of error condition, aside from `G34`, which is just its own issue, so absolute moves should be fine. I'll revert the commits changing it. 

This does mean that `G34` won't work with multiple probing until its dirty trick is removed, or it could be reworked to include its own version of `probe_at_point()` using relative moves.

**Comment by thinkyhead** [comment]
> it could be reworked to include its own version of probe_at_point() using relative moves.

If needed, we can add another parameter to `probe_at_point` that helps out `G34`, but it may be unnecessary depending on how much data is available both before and after probing. We can perhaps do something using the stepper counts (converted to mm) before and after `sync_plan_position`, for example.

**Comment by thinkyhead** [comment]
I pushed all the "innocuous" changes to `bugfix-2.1.x` that mainly affected `G28` and `G29`, so this PR is now just down to figuring out `G34`. To sync your own branch, GitHub Desktop might give the option to do a "reset," but if not you can use the CLI and enter the command:
```
git reset --hard origin/bugfix-2.1.x
```
Testing begins shortly!

**Comment by jamespearson04** [comment]
On further investigation, if we set the axis as untrusted, we can probe down to -10mm instead of -2mm + zoffs, so that might let us get rid of the dirty trick.

**Comment by thinkyhead** [comment]
> On further investigation, if we set the axis as untrusted, we can probe down to -10mm

If the only reason for that trick is to be able to probe farther down, there may be other solutions to that. The important thing is that the position is generally "known" and this isn't changed by probing. So is all one needs is a hack to probe past the safety margin then you can –for example– remember the current position, then modify it by +10, then after probing you can modify it again by -10. Another thing that can be done is to add a flag to the probing function to ignore the safety margin. Or, the safety margin can be changed into a variable with a corresponding G-code (which could also set the "too soon" margin) and that can be modified before and after the probing call.

Anyway, I got distracted because I converted my Chiron to use the standard graphical display, and the kit that I used didn't provide a connection for the Z probe. So I had to mess with the Chiron for a day and a half to get that sorted out. But I have a working probe now so if no other distractions come up I can get down with all the `G34` experiments tonight.

**Comment by jamespearson04** [comment]
I agree, I think the only reason the dirty trick is there is to defeat the safety margin, so a parameter to ignore or override that in `probe.probe_at_point()` would probably be the best way to do it. But yeah, having it as a variable would accomplish the same, it just comes down to how user facing you want the safety margin to be I guess. It would add utility being able to set them with gcode, but it seems like it might be one of those nice features that's never ever needed.

Also, changing the "too soon" margin above any of the z clearances would mean if the probe did trigger, it wouldn't lift, and wouldn't return an error - basically there'd be a lot to consider if the margins became variable.

And having thought about it some more, setting the axis untrusted would probably just end up invoking G28 first anyway, so doubt that's the way to go.

Good luck with the testing! Don't break anything!

**Comment by jamespearson04** [comment]
So I've added a parameter to the probing functions to override the minimum probe height, and attempted to use this to remove the dirty trick from G34. 

**I have no way of testing G34, so test that commit with caution**

I expect to it to work correctly with `#define HOME_AFTER_G34` enabled, but testing with this disabled is very much needed. I need to know if the Z height is correct after a G34 whilst the above is disabled, and if not, I need to know in which way it's incorrect (how far off is it? Does this match the probe offset or clearance values?). Multiple probing should behave the same as regular probing now, so testing with that disabled should cover the changes in these commits. Any help testing this would be much appreciated :)

**Comment by jamespearson04** [comment]
@thinkyhead i think commit 2c2b5ca / bbd0186 might want pushing to the main branch, can't compile without it

**Comment by jamespearson04** [comment]
Having looked into it some more, I still don't think the above G34 fix will work reliably with multiple probing. This is because the probe could still trigger above `Z_CLEARANCE_MULTI_PROBE`, in which case no lift will be performed between the multiple probes. I will note that it should work, depending on the tilt severity, as opposed to just not working at all previously.

The only way I can think of solving this is to parameterize the clearance heights. At this point it might be worth implementing a probe settings object, so that probe_at_point doesn't have a million parameters. 

**EDIT:** I think the above might be wrong actually for `TOTAL_PROBING` >2 , as multiple probing lifts are relative to the trigger position as of b5899a9, hopefully everything works now.

**Comment by jamespearson04** [comment]
The above commit should make it so that `TOTAL_PROBING` == 2 also works.

**Comment by Cooldog1099** [comment]
I attempted to compile this but receive many errors such as `#error "DISABLE_INACTIVE_EXTRUDER is now DISABLE_OTHER_EXTRUDERS."`.

Previous version compiles fine, and I'm sure I don't know what I'm doing. Suggestions?

**Comment by dfries** [comment]
> I attempted to compile this but receive many errors such as `#error "DISABLE_INACTIVE_EXTRUDER is now DISABLE_OTHER_EXTRUDERS."`.

Commit 
61f22f34d32ca33d99233eb5b242e52c23aabb23 changed the name.  You'll need to update your Marlin/Configuration.h to use DISABLE_OTHER_EXTRUDERS, see https://github.com/MarlinFirmware/Marlin/pull/25571

**Comment by GMagician** [comment]
With new bugfix I got bad behaviours with G34, redirected here by @thisiskeithb I tested this PR. It works but it adds some weird behaviours.
1) On G34 start Z lowers a bit, move to first detection point and raises a bit.
2) On G34 End it does a double raise just before homing

**Comment by PendulumPit** [comment]
I tested this PR with a klackender mag mounted probe. It solved the one issue with G34 of dive bombing the unloader by going below zero to undock itself. 
    Now it does a G28 and then goes back and checks the X endstop and then moves to 0,0 and dive bombs that corner by going below zero and then continues with its normal routine and undocks itself with no issue but it then checks the Y endstop and then goes back to perform its final G28.
    I also tried it with FTM turned on but it would not power the 2nd Z stepper for dual Z so I shut that part off.

**Comment by jamespearson04** [comment]
@PendulumPit That sounds like some intriguing behaviour, I have some minor changes to make to tidy up the G34 code, but I can't really see how anything in there would cause that. Does G28 behave properly by itself? 

The homing in G34 checks if the axes are trusted before doing anything else, and if they aren't it homes all axes. Then, at the end it does the command "G28Z" which will home Z, unless X or Y is set untrusted, in which case they'll be homed. Basically it would appear this behaviour must be originating somewhere else, either likely G28 or probe related code. Something may be setting the axes as untrusted?

I'd suggest a clean build of the firmware just in case, and posting your configs might help track down the source of the bug.

**Comment by jamespearson04** [comment]
@GMagician The past couple of commits should hopefully fix point 1. Please test with caution, as I can't test it myself.
I might have a fix for point 2, but I need to investigate G28 a little more first.

**Comment by jamespearson04** [comment]
@PendulumPit have you commented out any extra deploy moves? `#define MAG_MOUNTED_DEPLOY_5 { PROBE_DEPLOY_FEEDRATE, {   0,   0,  0 } }  // Extra move if needed` etc? 

Having them uncommented and set to 0s seems as though it might cause the behaviour described.

**Comment by PendulumPit** [comment]
> @PendulumPit have you commented out any extra deploy moves? `#define MAG_MOUNTED_DEPLOY_5 { PROBE_DEPLOY_FEEDRATE, { 0, 0, 0 } } // Extra move if needed` etc?
> 
> Having them uncommented and set to 0s seems as though it might cause the behaviour described.

I set the klackender probe with the directions provided on their github page for use in Marlin.  No extra moves.
  Through all my testing of this probe in Marlin in 2.1.2 and the current bugfix and this PR the one issue I hate and will stop using this with Marlin is that it won't concurrently do the task initiated. For example a G34 does the G28 and then undocks itself to only go back to dock the probe again to do the rest of G34 and the goes for any task that requires a G28 first.
    G28 on its own works perfect.
    I no longer have the files as I deleted everything and have moved on to my current project at hand.
      Thank you for your efforts!
        Persistence will prevail!

**Comment by GMagician** [comment]
> @GMagician The past couple of commits should hopefully fix point 1. Please test with caution, as I can't test it myself. I might have a fix for point 2, but I need to investigate G28 a little more first.

Not sure I cherry picked code correctly (manually done, non real cherry pick) but ooint 1 is not fixed.ù
Point 2 I'm not so sure it's a news, maybe already present before

**Comment by Cooldog1099** [comment]
> > I attempted to compile this but receive many errors such as `#error "DISABLE_INACTIVE_EXTRUDER is now DISABLE_OTHER_EXTRUDERS."`.
> 
> Commit [61f22f3](https://github.com/MarlinFirmware/Marlin/commit/61f22f34d32ca33d99233eb5b242e52c23aabb23) changed the name. You'll need to update your Marlin/Configuration.h to use DISABLE_OTHER_EXTRUDERS, see #25571

Thank you. Got the new configs and made my changes and it compiled fine. 

I'm having another issue. I know its a config issue, but I forgot how I solved it before and haven't been able to locate the setting to change yet.

When the nozzle is touching, the display reads +15. 

Stock Ender 3 Neo (CRtouch).  

Thanks.

**Comment by jamespearson04** [comment]
What's your `NOZZLE_TO_PROBE_OFFSET` in configuration.h? it should be around about - 1 to -3mm.

15mm is pretty far off, so I'd check the firmware value first, but it can be set via printer UI, it's something along the lines of "Probe offset", or with the command `M851 Z-2.2` where -2.2 would mean the probe triggers 2.2mm below the nozzle. Sending `M851` will also get the printer to send the current offset values to the host, so you can check it that way if you can send serial commands.

Make sure to save your settings after changing it, either using M500 or via printer UI.

The marlin discord is a better place to find support for this sort of thing btw :)

**Comment by Cooldog1099** [comment]
> What's your `NOZZLE_TO_PROBE_OFFSET` in configuration.h? it should be around about - 1 to -3mm.
> 
> 15mm is pretty far off, so I'd check the firmware value first, but it can be set via printer UI, it's something along the lines of "Probe offset", or with the command `M851 Z-2.2` where -2.2 would mean the probe triggers 2.2mm below the nozzle. Sending `M851` will also get the printer to send the current offset values to the host, so you can check it that way if you can send serial commands.
> 
> Make sure to save your settings after changing it, either using M500 or via printer UI.
> 
> The marlin discord is a better place to find support for this sort of thing btw :)

Ya, I'll head over. I know it's something simple, and I also failed to accurately describe the issue. I didn't notice it'd failing to actually auto home when it tries, it stops because the floor is out of range.

Thanks again. I'll post back here after I test my original problem.

**Comment by jamespearson04** [comment]
> > @GMagician The past couple of commits should hopefully fix point 1. Please test with caution, as I can't test it myself. I might have a fix for point 2, but I need to investigate G28 a little more first.
> 
> Not sure I cherry picked code correctly (manually done, non real cherry pick) but ooint 1 is not fixed.ù Point 2 I'm not so sure it's a news, maybe already present before

You'll need both of those commits, it would be better to use a fresh copy of this branch or use `git pull` to bring it up to date. Then a clean build of the firmware - G34 is basically incapable of moving downwards outside of probing moves now, so it should be fixed.

ETA: And yeah, point 2 was almost certainly there before, but there might be a way around it. In theory, the bed should only ever move further away from the nozzle as it's aligned, so we can consider the Z axis trusted in that regard, but it all depends how low G28 is allowed to probe when the axis is trusted. Is it configured to throw an error if the probe doesn't trigger by -2mm? If so, we can either keep the lift, and set it untrusted, or add a parameter that allows G28 to probe lower than normal, as has been done for `probe_at_point()`

**Comment by GMagician** [comment]
@jamespearson04 I got your PR + git pull +my cnf and point 1 works as expected. Point 2 still present but it's still valid my previous doubt

**Comment by jamespearson04** [comment]
> @jamespearson04 I got your PR + git pull +my cnf and point 1 works as expected. Point 2 still present but it's still valid my previous doubt

Yeah, point 2 was definitely preexisting. Still waiting to verify some things before implementing my solution

**Comment by Cooldog1099** [comment]
Alright, back on track. 

I compiled and tested the new firmware. It now has collisions at points 24 & 46 during the UBL mesh build `G29 P1` 

It retracts the probe, then continues the probe movement. If it survives the crash, it extends the probe and starts to probe point 25 in the same place as it attempted 24.

I got sent from [here](https://github.com/MarlinFirmware/Marlin/issues/25515#event-8937292149)

**Comment by jamespearson04** [comment]
@Cooldog1099 I think yours must be a hardware or configuration issue, I don't think the recent changes could be responsible for that behaviour - at no point has anything been changed that should make the probe triggering less reliable (so as to lead to collisions). Does it stop working on the same point consistently? That would be the only thing that would make me think it might be a FW bug, but it's still not a smoking gun, as wires could have issues that only show up when they bend a certain way. Maybe you have a faulty probe/wiring?

The only recommendation I have is to clean and then rebuild the firmware, and make sure that your probe wiring is seated properly, and maybe give it a little wiggle in case it's got slightly intermittent contact. M502 to reset EEPROM might be a good idea too.

**Comment by Cooldog1099** [comment]
Its not that the probe is failing to trigger, it is that it actively stows the probe before it attempts the probe. It then deploys the probe again on the next point. It exhibits this behavior only at those 2 specific points. I am almost 100% sure its a FW issue, because it makes an action (stow probe) that it should not. 

I will wipe and recompile the FW and try again.

**Comment by jamespearson04** [comment]
I'm afraid the code doesn't account for that behaviour, the only times a stow are to commence are:
A: Immediately after the probe has triggered, (happens on the final probe)
B: If the UI button is pressed, cancelling the probing. (At which point it will not go on to probe more points)

**Comment by Cooldog1099** [comment]
This is why I'm not a programmer. This stuff wouldn't make any sense.

Anyway, after multiple flashes and more testing, it still occurs at the same points.

However, since I am now an expert at compiling firmware and a few hours of messing with it, I narrowed it down to `#define MULTIPLE_PROBING 3`

`#define MULTIPLE_PROBING 2` seems to work fine.

Guess I'll just leave it at 2.

**Comment by jamespearson04** [comment]
That's really quite strange, the variations between `MULTIPLE_PROBING 3` and `MULTIPLE_PROBING 2` don't come anywhere near any calls to stow the probe. Whatever is breaking would appear to be happening at a lower level.

Have you made sure you're using the correct environment version for your board? (STM32F103RE vs STM32F103RC etc)  The Creality 427 has a few different build options, this seems like the sort of issue that _might_ appear if the wrong one is used. Failing that, I'd update your original issue with the info you shared here, as the issue doesn't appear to be related to this PR.

**Comment by jamespearson04** [comment]
4e94aa0 should remove the additional lift before homing at the end of G34, with `HOME_AFTER_G34` enabled. 

I should note that this depends on `G28Z` probing "indefinitely" (as the bed can move further from the nozzle after a G34) whilst in a homed and trusted state. If there are plans to introduce a limit to the homing depth whilst trusted, that commit would need to be removed. 

Other than that, I think everything should work correctly now, just need to go through and make sure the right heights are being used, and double check the calculations.

**Comment by thinkyhead** [comment]
> I think everything should work correctly now

Good to see we're getting there! I got pulled into other PRs and tasks for a couple days, so still haven't tested too much. I'm not sure the removal of `set_axis_never_homed(Z_AXIS)` from `G34` is safe for all configuration options. Under some configurations Z homing might just be skipped altogether if homing was already done. But now that I think of it… that might only apply to `G28` with the `O` parameter that indicates homing can be skipped if an axis is trusted.

So, I'll give it a full run tomorrow as well and we'll see where we're at with this set of changes.

**Comment by jamespearson04** [comment]
> Under some configurations Z homing might just be skipped altogether if homing was already done.

Yeah, it should just be with the `0` parameter as you say. Can't imagine there should be a config that doesn't behave this way, as it would make rehoming after bed adjustments and similar a pain.

I'll try to have a look through G34 tonight and update the comments to reflect the changes.

I think there might be some more to be done to optimize it, for example: `z_probe = (Z_TWEEN_SAFE_CLEARANCE + zoffs) + z_measured_max + z_maxdiff;`
I think zoffs can be removed, and some other things done to cut down on operations that aren't actually necessary, but it needs to be consistent throughout, so I wanted to make sure it was working properly before tweaking that and making it harder to track down issues. I'll see about doing that after the comments are sorted.

**Comment by carlosg-gh** [comment]
Not sure if it's the same issue, reading the description of the PR it seems like it. But this PR didn't fix the issue described here: https://github.com/MarlinFirmware/Marlin/issues/25737

**Comment by jamespearson04** [comment]
@Kurolox could you try it with a smaller `Z_CLEARANCE_DEPLOY_PROBE` if that works for your setup? Your logs suggest a value of 8 or maybe 9 should work. I suspect it will work then, and it should help me narrow down the source.

**Comment by jamespearson04** [comment]
Actually looks like this is happening in G28: In your video, after G28 it lifts to 12.45mm, but then the coordinates adjust down to 7.45, so G29 thinks it's lower than it is, hence the additional lift when you start G29.

**Comment by jamespearson04** [comment]
@thinkyhead I think you'll want de09495 for the main branch, enabling `Z_AFTER_PROBING` was breaking G28 as it was moving before handling the endstops.

**Comment by jamespearson04** [comment]
@Kurolox that commit should fix the issue you've encountered, let me know if it does.

**Comment by carlosg-gh** [comment]
@jamespearson04 I can confirm that your commit fixed my issue. Sorry if it wasn't related to the original issue!

**Comment by jamespearson04** [comment]
Nah, you're in the right place, glad I could help :)

File: Marlin/src/gcode/calibrate/G28.cpp [hunk 11]
```diff
@@ -626,6 +625,8 @@ void GcodeSuite::G28() {
       safe_delay(SENSORLESS_STALLGUARD_DELAY); // Short delay needed to settle
     #endif
   #endif // HAS_HOMING_CURRENT
+  
+  if (doZ) do_move_after_z_homing();
```
Comment (thinkyhead) [inline Marlin/src/gcode/calibrate/G28.cpp]: The move after homing is certainly intended for any situation where `G28` / `G28 Z` is happening, but is it universally appropriate for situations where Z homes first, and for the Foam Cutter?

I'd like to do a quick review of the code history to understand why it was limited to doing the final move where it was.

e.g., Is it safe to assume that setups that home Z to max and have`G28 Z` as the slicer profile End G-code, the final move to a lower position is disabled in the configuration.

If needed, we can clear `doZ` before we get here for any situations determined inappropriate.

Comment (thinkyhead) [reply Marlin/src/gcode/calibrate/G28.cpp]: So, one thing I see is that in July 2020 (#18576) `probe.move_z_after_homing` replaced a block of code that dealt with Z clearance after homing Z to min.
```cpp
        #if HOMING_Z_WITH_PROBE && defined(Z_AFTER_PROBING)
          #if Z_AFTER_HOMING > Z_AFTER_PROBING
            do_blocking_move_to_z(Z_AFTER_HOMING);
          #else
            probe.move_z_after_probing();
          #endif
        #elif defined(Z_AFTER_HOMING)
          do_blocking_move_to_z(Z_AFTER_HOMING);
        #endif
```
And this block was added as part of #16755 in Feb 2020, replacing the simple raise for homing with the probe `probe.move_z_after_probing()`.

Presumably we don't need to be specifically concerned about the probe clearance now that it's been moved to the probing method. Also, at that time Z would only home first if it was homing to max, but we've since relaxed that requirement.

Anyway, my major concern is that some users may have chosen `G28 Z` as their End G-code in the slicer, on DELTA, machines with a Z bed, and others that home to max. Even if the user hasn't set `Z_AFTER_HOMING` there is a special case for `DWIN_LCD_PROUI` — which should probably be removed, or at least moved to the ProUI code and not applied for all `G28 Z` commands.

So, if this is best done at the end of `G28`, we should use a different flag for this final move and only set it for the appropriate situation… namely, we should not apply it after homing Z to max. I may also add a comment to the configuration about this.

**Comment by GMagician** [comment]
Not sure I'm the only one having issues with G28/G34 but without this PR I get my nozzle drop into the bed...literally. Is not too dangerous to leave marlin without this patch?

File: Marlin/src/gcode/calibrate/G28.cpp [hunk 12]
```diff
@@ -383,7 +385,6 @@ void GcodeSuite::G28() {
                NUM_AXIS_LIST(              // Home each axis if needed or flagged
                  homeX = needX || parser.seen_test('X'),
                  homeY = needY || parser.seen_test('Y'),
-                 homeZZ = homeZ,
```
Comment (jamespearson04) [inline Marlin/src/gcode/calibrate/G28.cpp]: This removal causes a compilation error, as the number of valid arguments in NUM_AXIS_LIST is one fewer than the number of axes, it's been reintroduced in 9ccb8c4.

**Comment by jamespearson04** [comment]
The following is from `Probe::set_deployed()`, I think the `_MAX()` statement is unnecessary, as the entire purpose of `Z_CLEARANCE_DEPLOY_PROBE` is to specify the height for this action, so it shouldn't be overridden. It also defaults to `Z_CLEARANCE_BETWEEN_PROBES` if unset. This is changed in the latest commit, 0e62852.

https://github.com/MarlinFirmware/Marlin/blob/aaf63b24547f59ca628f51113ac262aad4c4f57a/Marlin/src/module/probe.cpp#L514-L518

**Comment by jamespearson04** [comment]
Issue #25751 is a similar story to G34, the G33 function uses `probe.probe_at_point()` before properly setting the delta height, as a result the change to absolute clearance moves result in no lifts after probing in many cases, dragging the probe on the bed. The most recent commits (a1cf215 through 2069bb4) add an argument to `probe.probe_at_point()`  that allows it to be operated with relative lifts. (maybe lift_relative and sanity_check could be rolled in to one, as they will both tend to be required together)

Using `probe.probe_at_point()` in this manner can render `safe_z` and its assosciated pre probing z move inert, however this was likely the case prior to the changes that broke G33 and G34 anyway. It just means that the first call to `probe_at_point(lift_relative=true)` must be from a known safe height, the post probe lift will ensure it is at the correct height for subsequent probes. Any functions likely to require this version are almost certainly going to be moving to a height before calling probe anyway, so this shouldn't be an issue.

 This argument should allow any other functions that require a relative version of `probe_at_point()` to be easily amended by setting `lift_relative = true`, when we have no means of determining alternate clearance height and min point values. (For instance, we don't know how far off delta height could be, so we can't increase our margins to account for it.)

**Comment by jamespearson04** [comment]
still yes homeZZ ;)

**Comment by daniel-walker** [comment]
This commit breaks my build inside Marlin/src/lcd/e3v2/jyersui/dwin.cpp usage of constexpr which throws errors, and some issue with the case statement.

Marlin/src/lcd/e3v2/jyersui/dwin.cpp:1573:12: error: jump to case label
