### PR TITLE
Fix G-code preview for LVGL_UI

### LINKED ISSUE #19914: [BUG] MKS UI does not show gcode preview image
Board MKS robin nano v2
Marlin 2.0.x - last bugfix

### Bug Description

In the generated gcode through the plugin "mks wifi", the model preview on the memory card is not displayed (displayed "no data")
Software - Cura v. 4.7.1, mks wifi plugin v. 1.0.2 (from cura store).

### My Configurations

[Conf.zip](https://github.com/MarlinFirmware/Marlin/files/5440936/Conf.zip)

### Steps to Reproduce

1. Install Cura slicer, install mks wifi plugin from cura store;
2. Slice any model and save on sd card with option "save as tft file";

3. Insert sd card into printer and click "printing"
4. "No data"

#### Additional Information

1. My test gcode file with the preview of the model:
[simple cube.zip](https://github.com/MarlinFirmware/Marlin/files/5440987/simple.cube.zip)
2. The preview is displayed normally during printing

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

Fix #19914 

It was broken by recent changes on MKS Cura plugin and the watchdog enabled by default.

### CODE REVIEW

File: Marlin/src/lcd/extui/lib/mks_ui/draw_print_file.cpp [hunk 1]
```diff
@@ -358,7 +358,7 @@ void disp_gcode_icon(uint8_t file_num) {
 uint32_t lv_open_gcode_file(char *path) {
   #if ENABLED(SDSUPPORT)
     uint32_t *ps4;
-    uint32_t pre_sread_cnt = 0;
+    uint32_t pre_sread_cnt = (uint32_t)-1;
```
Comment (sjasonsmith) [inline Marlin/src/lcd/extui/lib/mks_ui/draw_print_file.cpp]: I always prefer to use `UINT32_MAX` rather than casting a `-1`.

**Comment by X-Ryl669** [comment]
This does not work for me (see attached issue #19914) for an example "crashing" file. The changes here does fix the same icon appearing multiple time, but the bug is about the icon not being decoded correctly and crashing the printer. 
On my printer (Robin Nano35), the expected icon size is 100x100, and the stored icon in the file is 50x50. Since the code does not handle different dimension, it ends up reading too much from the file as it does not find the "end of image" marker.
The buffer and the stack is overwritten in consequence and the printer crash. The parse must be more robust to this.

I've proposed a fix that do work for me [here](https://github.com/makerbase-mks/Marlin-2.x.x/pull/31).
