### PR TITLE
Test probe points at build time

### LINKED ISSUE #19454: [BUG] Comment for assisted tramming does not match points that need to be set
### Bug Description

The comment in Configuration_adv.h how to set up the tramming points seems not to be correct.
" // Define positions for probing points, use the hotend as reference not the sensor."
When setting up the points as commented, the tramming does not complete (fails at point 1 (counting from 0).
I took the assumption, that the probe position needs to be the set-point, contrary to the comment and that #define PROBING_MARGIN , from bed leveling needs to be obeyed, too. Also the extruder must not leave the min and max bed size, taking the probe to nozzle offset into consideration. To simplify things I defined the printer as a one extruder type instead of two.

Working configuration: 
The extruder now goes to x=189  and y=187 maximum when tramming (as expected if my assumptions is correct)
#define X_BED_SIZE 195
#define Y_BED_SIZE 194
NOZZLE_TO_PROBE_OFFSET { -64, -16, 0 }
PROBING_MARGIN 6
// Define positions for probing points, use the hotend as reference not the sensor.
  #define TRAMMING_POINT_XY { {  6, 7 }, { 125,  7 }, { 125, 171   }, { 6, 171 } }

I also suspect that the number of screw turns might not be calculated correctly, as the screw position needs to be known on the bed and relative to the tramming points to calculate correctly.

### My Configurations
[Configuration Tramming.zip](https://github.com/MarlinFirmware/Marlin/files/5252026/Configuration.Tramming.zip)

**Expected behavior:** setup beeing succesfull when beeing set up as commented
**Actual behavior:** setup is successfull when set up opposite to the comment

#### Additional Information
#Error compiling in 2.0.6 due to G35.cpp and ASSISTED_TRAMMING with BLTouch present #19402

### LINKED ISSUE #20412: G35/ASSISTED_TRAMMING always fails on point 1
### Bug Description

`G35`/`ASSISTED_TRAMMING` always fails on point 1. Additionally, if I uncomment and try to use `ASSISTED_TRAMMING_WIZARD`, it can only probe `TRAMMING_POINT_NAME_1`. If I try probe any of the other points, it will report the last measurements as gibberish on my LCD, and not move. Even if I try to measure the other points as my first operation from entering the wizard, it will just move to the default Z height and sit there.

### Configuration Files

[MarlinConfig.zip](https://github.com/MarlinFirmware/Marlin/files/5664215/MarlinConfig.zip)

### Steps to Reproduce

1. Send `G35` via serial, or select "Assisted Tramming" from the LCD.

**Expected behavior:**

Honestly, I don't know. I'm just trying to use a new feature.

**Actual behavior:**

(see Bug Description)

#### Additional Information

BTW, I'm really just trying to improve my overall hot bed replacement and UBL probing process. I figure if I can get the corners level quickly with auto-tramming, then `G29 P1` is more likely to be in the ballpark on the first try. Yes, my 12x12 grid +  `MULTIPLE_PROBING 3` is probably unnecessary, but damnit... it makes printing on clean glass so great, even if building the mesh takes about 30 minutes. (Seriously, if someone could add an M-code to control `GRID_MAX_POINTS`, that would solve my terrible workflow problems too 😅).

Here's the G-code output from `G35` and my EEPROM settings.
```
M503
23:33:37.780 > echo:  G21    ; Units in mm (mm)  
23:33:37.780 > echo:  M149 C ; Units in Celsius  
23:33:37.780 >
23:33:37.780 > echo:; Filament settings: Disabled
23:33:37.780 > echo:  M200 S0 D1.75
23:33:37.780 > echo:; Steps per unit:
23:33:37.780 > echo: M92 X80.00 Y80.00 Z400.00 E415.00
23:33:37.780 > echo:; Maximum feedrates (units/s):
23:33:37.780 > echo:  M203 X300.00 Y300.00 Z5.00 E25.00
23:33:37.780 > echo:; Maximum Acceleration (units/s2):
23:33:37.780 > echo:  M201 X3000.00 Y3000.00 Z100.00 E10000.00
23:33:37.780 > echo:; Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
23:33:37.780 > echo:  M204 P3000.00 R3000.00 T3000.00
23:33:37.780 > echo:; Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>
23:33:37.780 > echo:  M205 B20000.00 S0.00 T0.00 J0.03
23:33:37.780 > echo:; Home offset:
23:33:37.780 > echo:  M206 X0.00 Y0.00 Z0.00
23:33:37.780 > echo:; Unified Bed Leveling:
23:33:37.780 > echo:  M420 S1 Z10.00
23:33:37.780 >
23:33:37.780 > Unified Bed Leveling System v1.01 active
23:33:37.842 > 
23:33:37.843 > echo:; Active Mesh Slot: 3
23:33:37.843 > echo:; EEPROM can hold 5 meshes.
23:33:37.843 >
23:33:37.843 > echo:; Material heatup parameters:
23:33:37.843 > echo:  M145 S0 H180 B65 F0
23:33:37.843 > echo:  M145 S1 H200 B85 F0
23:33:37.843 > echo:; PID settings:
23:33:37.843 > echo:  M301 P40.70 I3.00 D69.20
23:33:37.843 > echo:; Z-Probe Offset (mm):
23:33:37.843 > echo:  M851 X-23.42 Y-48.30 Z-0.94
23:33:37.843 > echo:; Linear Advance:
23:33:37.843 > echo:  M900 K0.08
23:33:37.843 > ok
G35
23:33:49.257 > echo:busy: processing
23:33:51.911 > echo:busy: processing
23:33:53.910 > echo:busy: processing
23:33:57.219 > echo:busy: processing
23:33:59.218 > echo:busy: processing
23:34:01.216 > echo:busy: processing
23:34:03.214 > echo:busy: processing
23:34:05.292 > echo:busy: processing
23:34:07.290 > echo:busy: processing
23:34:09.290 > echo:busy: processing
23:34:11.288 > echo:busy: processing
23:34:12.150 > X:173.42 Y:198.30 Z:10.94 E:0.00 Count X:13874 Y:15864 Z:4378
23:34:13.286 > echo:busy: processing
23:34:15.284 > echo:busy: processing
23:34:18.497 > echo:busy: processing
23:34:20.496 > echo:busy: processing
23:34:22.494 > echo:busy: processing
23:34:24.556 > echo:busy: processing
23:34:26.747 > echo:busy: processing
23:34:28.745 > echo:busy: processing
23:34:30.743 > echo:busy: processing
23:34:32.742 > echo:busy: processing
23:34:34.741 > echo:busy: processing
23:34:36.738 > echo:busy: processing
23:34:37.453 > G35 failed at point 1 (Rear-Left) X280.00 Y20.00
23:34:37.453 > G35 aborted.
```

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

Users frequently experience G35 failures because their selected probe points are outside the area reachable by the bed probe. It would benefit from build-time tests to make sure probe points can be reached, as is done for G34.

This is not a perfect solution, since probe offsets can be modified and stored to the EEPROM at runtime. This will at least identify misconfigurations with default settings.

This changes several things:

1. Update configuration_adv.h sample tramming points so they will work with the default bed size and probe offset.
2. Slight wording change in Configuration_adv, to remove "relative to probe" that confused some users.
3. Extract the portion of probe.h min/max functions relevant to build-time checks. Make these constexpr, and add Probe::build_time helpers for use in static_asserts.
4. Remove `inline` and `FORCE_INLINE` attributes from all probe.h functions. These should not be performance critical, and reduce flash usage.
5. Refactors G34 build-time checks to use these helpers.
6. Adds build-time checks for G35 tramming points.
7. Adds build-time checks for custom 3-point PROBE_PT values.
8. Adds build-time checks for LEVEL_CORNERS_USE_PROBE insets

### Benefits

- More users detect issues at build-time, reducing support burden.
- Reduced flash usage by 336 bytes on my AVR test config.

### Configurations

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5742834/Configuration_adv.zip)

### Related Issues

#20412

### CODE REVIEW

**Comment by sjasonsmith** [comment]
I marked this as a draft because I have not tested it on a printer yet. So far I have only tested the build-time portion of this. I would like to do a sanity check which uses this at runtime.

I also need to do a careful review of my own changes to make sure nothing seems out of place. I will do this tomorrow.

File: Marlin/Configuration_adv.h [hunk 1]
```diff
@@ -801,10 +801,10 @@
 //#define ASSISTED_TRAMMING
 #if ENABLED(ASSISTED_TRAMMING)
 
-  // Define positions for probing points, use the hotend as reference not the sensor.
-  #define TRAMMING_POINT_XY { {  20, 20 }, { 200,  20 }, { 200, 200 }, { 20, 200 } }
+  // Define positions for probe points.
+  #define TRAMMING_POINT_XY { {  20, 20 }, { 180,  20 }, { 180, 180 }, { 20, 180 } }
```
Comment (rhapsodyv) [inline Marlin/Configuration_adv.h:805]: instead of 180, this should not be a offset from BED_SIZE, like `X_BED_SIZE - 20`?

Comment (thisiskeithb) [reply Marlin/Configuration_adv.h:805]: Or better yet, use `PROBING_MARGIN` (or `PROBING_MARGIN_LEFT/RIGHT/FRONT/BACK` if defined) instead of an arbitrary number.

Comment (sjasonsmith) [reply Marlin/Configuration_adv.h:805]: I’m not trying to make these auto-select. The original values simply could not work with other defaults.

These really need to factor the probe offset (not just the margin), but the offset is not accessible in a macro, only in a constexpr or at runtime.

**Comment by sjasonsmith** [comment]
In think I broke something. Investigating now. G29 is not probing the correct area on my bed.

**Comment by sjasonsmith** [comment]
I had an obvious copy/paste error which prevented G29 from probing the correct region, it is fine now after my "Fix incorrect function calls" commit above.

I'm still observing some weirdness in the assisted tramming wizard, but I see no way it is caused by this change. After probing a point sometimes it just returns to the Info screen without me doing anything. I will double-check that the problem existed prior to these changes.

**Comment by sjasonsmith** [comment]
I have verified that the problem with `ASSISTED_TRAMMING_WIZARD` returning to the Info screen is pre-existing, and not related to this change.

**Comment by sjasonsmith** [comment]
@thinkyhead once this change goes in I will revisit #20298 to resolve conflicts between them.
