### PR TITLE
Prevent watchdog reset in setup()

### LINKED ISSUE #21764: [BUG] MKS Robin Nano v3 Freezes with 2.0.8
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

No more serial port :  
No usb connexion
No tft serial port active

### Bug Timeline

_No response_

### Expected behavior

Connexion with PC or Octoprint
Connexion with MKS TFT 28

### Actual behavior

No connexion with PC or Octoprint and no connexion with the screen

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

2.0.8

### Printer model

Artillery Genius

### Electronics

MKS Robin Nano V3

### Add-ons

_No response_

### Your Slicer

_No response_

### Host Software

OctoPrint

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

BOOTSCREEN_TIMEOUT will trigger watchdog if it's a big value.

### Related Issues

#21665

### CODE REVIEW

**Comment by thinkyhead** [comment]
Have you actually seen this? Because the only thing `bootscreen_completion` does is call `safe_delay`, which is already supposed to be resetting the watchdog timer. If this single call to the reset the watchdog is somehow preventing a reboot, then it is only hiding another issue, and we need to look at something earlier in the boot process that is going on for more than 4 seconds without resetting the watchdog.

**Comment by rhapsodyv** [comment]
safe_delay will only refresh watchdog if EARLY_WATCHDOG is enabled, or if there're some raw temperatures to process... if not, it will just return doing nothing...

**Comment by thinkyhead** [comment]
Since we are dependent on `safe_delay` in the boot process, let us consider modifying these aspects of `safe_delay`.

**Comment by rhapsodyv** [comment]
Do you think safe_delay should refresh watchdog?

For me, the correct fix is bootloader_completion ensure that the watchdog is "refreshed". 

If we change safe_delay, it will prevent the watchdog trigger when someone do a very bad use of safe_delay (very long timeouts), that is something that we may want to avoid...

**Comment by thinkyhead** [comment]
If you enable `MARLIN_DEV_MODE` the `setup()` function will show the millisecond timing of each step in the setup. From these we can see which steps are taking a long time, and we can look closer at those steps. We may insert `watchdog_reset` calls into `setup` itself between steps that individually only take a small amount of time, but which would add up to more than 4s. But, we'll need to add watchdog resets into those steps which might themselves take more than 4s.

**Comment by thinkyhead** [comment]
> Do you think `safe_delay` should refresh watchdog?

That is why it exists. If it's now calling temperature check and expecting the watchdog to be reset by that, but the temperature ISR is not yet running by design, then it should instead reset the watchdog.

**Comment by rhapsodyv** [comment]
> > Do you think `safe_delay` should refresh watchdog?
> 
> That is why it exists. If it's now calling temperature check and expecting the watchdog to be reset by that, but the temperature ISR is not yet running by design, then it should instead reset the watchdog.

But temperature ISR is not all... very long delays will break usb serial (CDC) and usb flash drive, only to name a few that comes to my head.

**Comment by thinkyhead** [comment]
Since `safe_delay` is just a loop calling `idle()` are you implying that all our loops calling `idle()` are bad?

**Comment by rhapsodyv** [comment]
If someone needs a delay > then watchdog timeout, I think he should change the code to use some sort of state machine, or rethink the code.

I think the only place that we have such big timeout is for bootscreen.

And before the bootscreen optimization, it runs before the watchdog init, so it wasn't an issue until now.

**Comment by thinkyhead** [comment]
Every time there is a pause waiting for a click, we are sitting in a loop calling `idle`.

**Comment by thinkyhead** [comment]
If course, "`idle`" is a bit of a misnomer. Everything happens from `idle` except for churning through the G-code queue.

**Comment by rhapsodyv** [comment]
Or we just add a sanity check to force bootscreen timeout to be less than 4s :-)
But today, the default is 4s

**Comment by thinkyhead** [comment]
What I am trying to point out through evidence is that there is not an issue with a "long delay" because it is already used everywhere, and it keeps everything running, and it is supposed to reset the watchdog on condition. The main condition is that there is a temperature reading ready. But, we could also add the condition that is now only applied to DUE and allow it to apply everywhere: to _always_ reset the watchdog if we haven't reached the end of `setup`.

**Comment by rhapsodyv** [comment]
> Since `safe_delay` is just a loop calling `idle()` are you implying that all our loops calling `idle()` are bad?

If safe_delay call idle, it will not break any peripheral. But could lead to a infinite call stack loop (because can potentially exists a lot of paths to test safe_delay) and it may add a lot of overhead where safe_delay is called (as it will run all idle code, even executing gcode commands!!)

So, in my view, it's a really dangerous step to add idle call in safe_delay...

**Comment by thinkyhead** [comment]
Alternatively, we could disable the watchdog interrupt entirely until the end of `setup` is reached, and only enable it then.

**Comment by rhapsodyv** [comment]
For me, it's an issue unique and exclusive to the bootscreen timeout.

**Comment by thinkyhead** [comment]
The way that Marlin works via the `idle` loop, yes it is possible to blow up the stack, but in practice this is easily prevented with re-entry guards where needed. And that is only in the MarlinUI …… maybe a few other places.

But that is Marlin's architecture, though. The entire machine runs out of `idle` in a loop, by design, whenever something needs to do a delay or wait for a click, etc.

**Comment by rhapsodyv** [comment]
> Alternatively, we could disable the watchdog interrupt entirely until the end of `setup` is reached, and only enable it then.

Sure. That makes a lot of sense. But, I really don't know the what all init calls are doing. Tmc, serial, and a lot of random stuff. So I'm not confident to move the watchdog start to the end...

But, it will work and probably is a safe to do.

**Comment by thinkyhead** [comment]
However. Sometimes the watchdog is already activated by platform variant code or bootloader.

**Comment by thinkyhead** [comment]
> it may add a lot of overhead where safe_delay is called (as it will run all idle code, even executing gcode commands!!)

That is exactly what is wanted. That is the design pattern of Marlin. But, it won't be running any G-code commands out of the queue. A "G-code" could be run with one of the "parse-now" methods, but that's just a fancy function call.

**Comment by thinkyhead** [comment]
image

Note that `idle` does not advance the G-code queue. That is by design. It does however read new items from serial inputs and SD into the queue until it is full.

**Comment by rhapsodyv** [comment]
Maybe add only HAL_Idle_Task + watchdog refresh to safe_delay...

Yet I think that adding watchdog refresh to safe_delay "breaks" the meaning of watchdog refresh as "prefix" for a task.

And a very dangerous change. 

But: is there another place that has issue calling safe_delay?

**Comment by thinkyhead** [comment]
There is no problem related to `safe_delay` calling `idle`. We can drop that topic.

The watchdog refresh is, by design, tied to the temperature ISR setting the "readings ready" flag. It is not meaningful elsewhere, so the watchdog can be disabled or it can be refreshed unconditionally until the end of `setup`.

**Comment by rhapsodyv** [comment]
Hum... as long as the "unconditional" call to watchdog refresh make sure that temp manager is called, things will be fine.

Maybe we need to take a look in how many safe_delay calls are out there... I bet some will hang in a infinite loop if we call idle (re executing the calling code that calls safe_delay again).

We need to measure the impact in the safe delay overhead too.

For me doesn't looks like a simple/safe change.

**Comment by rhapsodyv** [comment]
Ahh... if we call idle inside safe delay we will call idle before setup finishes too... that probably is not wanted... 

I think my fix or moving watchdog start to the end of setup is the way to go.

**Comment by thinkyhead** [comment]
> Hum... as long as the "unconditional" call to watchdog refresh

I misspoke in referring to `safe_delay` calling `idle`. It calls `manage_heater` and it is up to `manage_heater` to handle the watchdog. If it called `idle` then it would be doing more than we need. Loops that call `idle` are expecting the planner to be handling blocks, and all that stuff.

Anyway, let's try this change: Moving `thermalManager.init` to the very end of `setup`, and see how that works!

**Comment by rhapsodyv** [comment]
This should work.

The issue was that the bootscreen was "consuming" all watchdog time (4s) and the watchdog get triggered before the next call for the refresh.

With the last changes, it looks good. 

But, only a question: if temp init is only called in setup, why temperature class need a flag and a `if` to check if it is already initiated?
If we just call watchdog refresh in setup before calling temp.init, we can get rid of the temperature init flag and can remove that runtime `if`.

Isn't? Or I'm missing something?

**Comment by thinkyhead** [comment]
> The issue was that the bootscreen was "consuming" all watchdog time (4s) and the watchdog get triggered before the next call for the refresh.

Well, more succinctly, the problem is that calls to `safe_delay` were failing to reset the watchdog. We cannot do much if some external library was failing to return for 4s, except to disable the watchdog reset, but within Marlin all lengthy delays are supposed to be doing that, even in `setup`. Hence the `early_safe_delay` which I included speculatively.

**Comment by thinkyhead** [comment]
> But, only a question: if temp init is only called in setup, why temperature class need a flag and a if to check if it is already initiated?

That was the author's choice, coming from a school of programming that likes init-guards. You are correct, and I removed it.

File: Marlin/src/module/temperature.cpp [hunk 1]
```diff
@@ -1203,11 +1199,7 @@ void Temperature::min_temp_error(const heater_id_t heater_id) {
  *  - Update the heated bed PID output value
  */
 void Temperature::manage_heater() {
-
-  #if EARLY_WATCHDOG
-    // If thermal manager is still not running, make sure to at least reset the watchdog!
-    if (!inited) return watchdog_refresh();
-  #endif
+  if (marlin_state == MF_INITIALIZING) return watchdog_refresh(); // If Marlin isn't started, at least reset the watchdog!
```
Comment (rhapsodyv) [inline Marlin/src/module/temperature.cpp:1204]: We need this at all?

If we are initializing, we can call watchdog refresh once in setup. Or just init watchdog after all setup. If initialization takes more than watchdog timeout, we probably have a bigger problem.

Anyway, I'm ok with this version!

Comment (thinkyhead) [reply Marlin/src/module/temperature.cpp:1204]: The `setup()` is allowed to take as long as it takes, including users setting a very long boot-screen pause. For testing try setting a 5 second bootscreen timeout, and as always use dev mode to observe the `setup()` logging. If the watchdog resets, it will be clear where in the `setup` it happened.
